### ISSUE TITLE
Printing issue

### ISSUE THREAD

**Issue by dadooie** [sumatrapdfreader/sumatrapdf#1081] opened 2018-10-04 18:15 UTC
Hi!
I want to report a printing issue which sometimes happens when printing from Sumatra. It only happens with some documents. When it happens the printout has horizontal bands missing. Most of my prints are in portrait mode. The system is windows 8.1 Enterprise with latest updates. The printer is Xerox WorkCentre 7845i with PS driver 5433.1600.0.0.

**Comment by GitHubRulesOK** [comment] 2018-10-04 19:15
@dadooie there are several known issues with Xerox WorkCentres (especially the 7545 series) do the pdf files processed by Xerox that fail include jpegs ? 
@kjk although its different models this is effectively a duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/975 which is effectively duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/685 which is effectively duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/417 and related to https://github.com/sumatrapdfreader/sumatrapdf/issues/1058  https://github.com/sumatrapdfreader/sumatrapdf/issues/992 https://github.com/sumatrapdfreader/sumatrapdf/issues/919 possibly some linking/closures

**Comment by GitHubRulesOK** [comment] 2018-10-04 20:34
@dadooie as suggested in one of the other threads with files that fail can you try setting. Printing Preferences -> Advanced tab -> Driver: disable "Print optimization" and report if that helps.

**Comment by dadooie** [comment] 2018-10-05 14:29
I don't see this particular option. Would it be one of these options? I don't think they include jpegs but how can I tell? They are some invoices I needed to print.

![xerox driver options](https://user-images.githubusercontent.com/42794069/46541228-65469780-c889-11e8-885e-4584da3cf4a2.png)

**Comment by GitHubRulesOK** [comment] 2018-10-05 16:09
Not having used a Xerox this century :-) I can only surmise it is the PS Output currently set to "Optimize for Speed" however there are others there that may be relevant such as Pass through, PS level 3, Image Enhancement so if I was there I would be checking one by one and possibly some mixes. Without seeing other tab contents I can only guess if Image Options might also have a bearing ?

**Comment by svaningelgem** [comment] 2018-12-16 20:51
I am facing this issue with a newly bought Canon MF635Cx. When printing via Chrome and/or FoxIT, I don't have the issues.
Double checked with latest pre-release version from today (build date: 2018-11-07). Both 64bit and 32bit have this issue.

**Comment by GitHubRulesOK** [comment] 2019-11-27 17:57
@kjk dupe / consolidate with https://github.com/sumatrapdfreader/sumatrapdf/issues/919

**Closed** 2019-11-27 22:00 UTC
