### ISSUE TITLE
Icons in low resolution

### ISSUE THREAD

**Issue by Baxtex** [sumatrapdfreader/sumatrapdf#908] opened 2017-10-11 11:52 UTC
So I was using Sumatra the other day and noticed that the button icons for the top bar is in ridiculously low resolution.  Don't know if this is something that is already place on the todo list?
![pixels](https://user-images.githubusercontent.com/8721113/31439133-5538f82e-ae8b-11e7-9f24-c32a470c5961.PNG)

**Comment by dasebasto** [comment] 2017-10-11 13:58
Just installed Sumatra and love the performance (especially in Windows 10 preview pane).

But the icons look horrible indeed. This looks like a dupe of https://github.com/sumatrapdfreader/sumatrapdf/issues/734 though

**Comment by kjk** [comment] 2017-10-11 20:07
Closing as duplicate of #734

**Closed by kjk** 2017-10-11 20:07 UTC
