### ISSUE TITLE
Close CHM fullscreen view without keyboard (crash in various view modes)

### ISSUE THREAD

**Issue by Hubel** [sumatrapdfreader/sumatrapdf#198] opened 2015-05-19 08:45 UTC
I use SumatraPDF as a CHM viewer on a Windows 7 touchscreen device that does not usually have a keyboard attached.
On clicking the help button, the help should be displayed in fullscreen mode (or maximized at least). Unfortunately it cannot be closed by just using the touchscreen because there is no close button.

**Is there a way to display a _close button_ or the _file menu_ in fullscreen mode?**
The _view mode_ command line parameter seems to suit my needs the closest. But this is probably not the intended use case with CHM files since they do not consist of single pages. On top of that it does not properly cooperate with the _fullscreen_ option. In the best case the application displays a junk tab that causes a crash when clicked:
![image](https://cloud.githubusercontent.com/assets/10436633/7698533/609cb1c4-fe11-11e4-8e64-b10c2835e7ff.png)

Command line:
_"SumatraPDF.exe" -esc-to-exit -fullscreen -view book view -nameddest 2000 "\Help\MagnatestDSGPENG.chm"_

**Comment by GitHubRulesOK** [comment] 2019-12-11 02:44
Crashes ares caused by sumatraPDF interpreting Command line as bad calls it should have been a quoted string -view "book view" and 2 hyphens in -named-dest

Apart from using A 3rd party key trapper such as AutoHotKey to see a touch as meaning exit (esc) then the best option is to maximise with no menu or toolbar like this
![image](https://user-images.githubusercontent.com/12754913/70586746-ebfab100-1bbf-11ea-8411-8e7c6e09f031.png)

**Comment by GitHubRulesOK** [comment] 2020-01-11 21:32
@kjk this is related to some of my past problems where poor command line structures can sometimes open unexpected files / hang / crash etc

I cannot emulate a second non exting file tab opening in current build only receiving at worst so far an "error loading ####\view" on occasion

Latest builds are now considered more robust ?

**Comment by GitHubRulesOK** [comment] 2020-04-03 23:34
Without further example commands
I am closing on the basis that the command shown needs to follow the current manual at https://www.sumatrapdfreader.org/docs/Command-line-arguments.html where -view commands `"are quoted"`

**Closed by GitHubRulesOK** 2020-04-03 23:34 UTC
