### ISSUE TITLE
[windows]incorrect default installation path

### ISSUE THREAD

**Issue by krisden** [sumatrapdfreader/sumatrapdf#1727] opened 2020-08-11 13:04 UTC
Hi, when setup a computer, I create an admin session first and one or more user.
Since I install software in the admin session, default path in SumatraPDF installer point on the admin user "app data" folder.
Then, when I use a "standard" session type, Sumatra doesn't exists for this user.
The path "C:\Windows\Program" is to correct manually (x64 version)

**Comment by GitHubRulesOK** [comment] 2020-08-11 14:22
duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1641
related to policy changes after https://github.com/sumatrapdfreader/sumatrapdf/issues/115
discussed in many issues i.e. 
https://github.com/sumatrapdfreader/sumatrapdf/issues/1504
and much discussion on forum

**Closed by GitHubRulesOK** 2020-08-11 14:22 UTC
