### ISSUE TITLE
/ToUnicode mapping issue

### ISSUE THREAD

**Issue by willus** [sumatrapdfreader/sumatrapdf#471] opened 2016-03-19 21:10 UTC
Text selected from [this file](http://willus.com/sumatra_temp/polish_tounicode_example.pdf) with Polish characters does not correctly get translated because the /ToUnicode map for the fonts is apparently ignored by Sumatra.  Compare Sumatra with Adobe Reader in copying and pasting the text from [this file](http://willus.com/sumatra_temp/polish_tounicode_example.pdf).

[I couldn't figure out how to attach a file--if somebody else can attach the linked file, that would be better.]

**Comment by kjk** [comment] 2016-03-19 21:31
[polish_tounicode_example.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/181037/polish_tounicode_example.pdf)

**Comment by willus** [comment] 2016-03-19 22:06
Thank you Krzysztof!  L-O-V-E Sumatra.  It is the best.  Thank you, thank you.
P.S. I had tried drag-and-drop but it complained that it didn't understand the file type.  Strange.

**Comment by sschuberth** [comment] 2016-11-08 20:42
Maybe caused by the fix for https://github.com/sumatrapdfreader/sumatrapdf/issues/184?

**Comment by GitHubRulesOK** [comment] 2019-11-15 19:04
@kjk I had hoped this was closed see the correct unicode for first word pasted in the search box.

However this issue is still open since ONLY the first word is available to paste BUT it may give clues to other related selection issues since the height of the selection is broken by the unicode character and spaces

![Untitled471](https://user-images.githubusercontent.com/12754913/68968525-acb48c80-07da-11ea-981a-4b4e91f9c667.png)

**Comment by GitHubRulesOK** [comment] 2020-07-10 08:46
@kjk 
There were 2/3 issues in one here
1) Unicode, closed
2) different behaviour to Acrobat when you copy the first line of text, the excessive justifying spaces are converted to newlines just as if they were paragraphs.

```
    Zapowiadał
    się
    przyj
    emny
    dzień
```

Acrobat will show almost the same gaps (why the slight difference on third line!)
![image](https://user-images.githubusercontent.com/12754913/87135133-8d023500-c291-11ea-9843-dc7eb0f7fca3.png)

but paste the first line as
```
      Zapowiadał się przyj emny dzień
```

This exhibits the basic issue of many other (but not all) complaints related to copy and paste adding excessive newlines

**Comment by GitHubRulesOK** [comment] 2023-10-28 00:48
OK now I see a different selection problem reminiscent of OCR behaviours and thus have to say the file should be classed as out of working spec in that respect
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/04ffa523-096b-4c6f-bd6d-6c08e15f885f)
we can see why in the disjointed storage shown here
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/d795dcc2-e4ed-4e6b-82cb-7ed821003b34)


Sticking with OP complaint that tounicode was not working 
that part NOW with recent updates seems OK

**so closing this one as fixed as reported !** 

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/e4f848cf-a111-4234-ab7f-a96daebeca1b)

**Closed by GitHubRulesOK** 2023-10-28 00:48 UTC
