### ISSUE TITLE
Toolbar icons pixelated in Windows 10

### ISSUE THREAD

**Issue by rubenvb** [sumatrapdfreader/sumatrapdf#326] opened 2015-10-25 12:06 UTC
The toolbar icons are pixelated in Windows 10 (see screenshot). Perhaps the proper ones aren't being selected or the icons are just too small to be displayed on modern hi-res screens. Note this happens regardless of the DPI setting (I tried 100, 125, and 150%). Obviously the problem gets worse with a higher DPI setting.

![screenshot](https://cloud.githubusercontent.com/assets/308670/10715505/0659007a-7b19-11e5-9fa9-bb38609c7d4e.PNG)

**Comment by abhinavk** [comment] 2015-10-25 13:32
I can confirm. I am running the latest build on Windows 10. (1920x1080 @ 125%)

**Comment by altplusf4** [comment] 2015-10-25 22:26
I can confirm this, too. 

Windows 7, DPI scaling 125%.

**Comment by kjk** [comment] 2017-06-09 19:16
Closing as duplicate of #734

**Closed by kjk** 2017-06-09 19:16 UTC
