### ISSUE TITLE
sumatra crashes when zooming in/out on document

### ISSUE THREAD

**Issue by J-Angeles** [sumatrapdfreader/sumatrapdf#1642] opened 2020-06-26 17:53 UTC
[https://gist.github.com/J-Angeles/51602599f9090ce4362a9c973fefdddc](https://gist.github.com/J-Angeles/51602599f9090ce4362a9c973fefdddc)

**Comment by kjk** [comment] 2020-06-26 19:05
Looks like a crash inside `update_ctm_for_subarea`, same as https://github.com/sumatrapdfreader/sumatrapdf/issues/1640

Can you see if it still happens in latest daily build: https://www.sumatrapdfreader.org/dailybuilds.html ?

It looks like the file is https://files.engineering.com/download.aspx?folder=1b6fbaf2-275e-4b94-a304-99b413c5492e&file=sip-trunking-with-elastix-configuration-guide-for-matrix-setu-vtep.pdf

I tried to reproduce it in 3.2 by zomming in and out to extremes but it didn't crash from me.

Can you provide more detailed steps to reproduce it?

**Comment by J-Angeles** [comment] 2020-06-26 21:55
Yes, i installed daily build and it stills crashes. But I just noticed if I use the toolbar buttons to zoom in and out it doesn't crash, only when I use my touchpad on the laptop. I'll try to connect a mouse and see if it does the same with ctrl + wheelbar. 

The way you can reproduce it easier is by zooming in and out very fast.

**Comment by kjk** [comment] 2020-06-27 02:56
I tried using touchpad (on a thinkpad), still no luck getting the crash.

**Comment by GitHubRulesOK** [comment] 2020-06-27 10:11
@kjk Possibly no help to confirm using two slow machines with different touchpads I dont get a crash with that file

@J-Angeles  Is it just one or two files, or does sumatrapdf crash on many files using your machines touchpad ?

**Comment by J-Angeles** [comment] 2020-06-27 21:31
Ok, so I tried the same file on different computer and it didn't crash, I also noticed the pdf file was much clearer and now I'm noticing that the sumatra toolbar and font on the laptop is really faded, but I think that's has to do with the laptop's display driver. I'll try to update or re-install the driver to see if that fixes the problem.

**Comment by kjk** [comment] 2021-05-27 07:39
This could be fixed by updates to mupdf.

If you still get crashes, please re-open and provide the file that crashes and detailed steps to reproduce the crash.

**Closed by kjk** 2021-05-27 07:39 UTC
