### ISSUE TITLE
lines are thinner when compared to other PDF readers

### ISSUE THREAD

**Issue by JSR-GitHub** [sumatrapdfreader/sumatrapdf#1732] opened 2020-08-17 09:58 UTC
I attached two files here.

When opening these files with SumatraPDF the lines are thinner when compared to other PDF readers.
With Adobe Acrobat Reader DC the lines are thicker.
With Foxit Reader the lines are thicker.

[2_PDF_exprot_from_Writer.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5083489/2_PDF_exprot_from_Writer.pdf)
[4_PDF-export_from_Impress.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5083491/4_PDF-export_from_Impress.pdf)

**Comment by GitHubRulesOK** [comment] 2020-08-17 10:16
look the same to me (on same screen when Acrobat is not distorting it)
![Untitled](https://user-images.githubusercontent.com/12754913/90385224-b7a69100-e07a-11ea-99cb-ec780ce15941.png)

**Comment by SumatraPeter** [comment] 2020-08-17 22:19
Duplicate of #624?

**Comment by GitHubRulesOK** [comment] 2020-08-17 22:54
@SumatraPeter thanks I was in work mode when replied so did not have time to search
agreed its similar to many other complaints that other readers make the lines look thicker.

**Closed by GitHubRulesOK** 2020-08-17 22:54 UTC
