### ISSUE TITLE
Prevent misinterpretation of slide left as gesture 'next page'

### ISSUE THREAD

**Issue by wuebbel** [sumatrapdfreader/sumatrapdf#251] opened 2015-08-05 13:01 UTC
I use sumatra v3.0 in full screen mode on a Windows tablet. The gesture for entering/leaving full screen with two finger tap is very handy. However, moving screen content, for a page larger than the screen, by sliding left is very often misinterpreted as gesture 'next page' and 'previous page' for sliding right. 

Is it possible to disable just these two? Or alternatively and even better, interpret a slide left only as 'next page' when the viewport was already on the rightmost position of the page when the slide started? That seems to be the way Chrome does it. 

Best wishes, Frank

**Comment by GitHubRulesOK** [comment] 2020-01-31 21:04
@kjk duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/9 suggest consolidate with that

**Comment by kjk** [comment] 2020-02-01 02:36
Consolidate under #9

**Closed by kjk** 2020-02-01 02:36 UTC
