### ISSUE TITLE
Mimic Firefox tabs - Don't load until clicked on the tab

### ISSUE THREAD

**Issue by AntonioCS** [sumatrapdfreader/sumatrapdf#3009] opened 2022-10-06 16:08 UTC
Hey,

I sometimes open a quite a few pdfs and don't really close them in Sumatra.
The issue is, that every time Sumatra opens it loads every PDF.

Would it be possible to do something similar to what Firefox does when I open it and it has 30+ tabs.
It will only load the tab when I click on it, it won't load them all at start.

**Comment by GitHubRulesOK** [comment] 2022-10-06 18:49
Lazy Loading has already been raised as an issue and added at least once,
https://github.com/sumatrapdfreader/sumatrapdf/commit/8826a6314f6d125fc34e8b45182ec8b142cb793f https://github.com/sumatrapdfreader/sumatrapdf/commit/2e5f670eecd004c2709d31110d27a12008d080ec
https://github.com/sumatrapdfreader/sumatrapdf/pull/2153
https://github.com/sumatrapdfreader/sumatrapdf/pull/2590 https://github.com/sumatrapdfreader/sumatrapdf/pull/2591

closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1497

**Closed by GitHubRulesOK** 2022-10-06 18:49 UTC

**Comment by GitHubRulesOK** [comment] 2022-10-06 20:18
There may be some residual reasons files load slow, most often polling or receiving a remote file, takes ages to load a remote one on https drive. Fastest way to load a file in such cases is as a mapped drive since a lot of the 2way comms is pre-processed.

using 3.5.15244 (see crash reports for 3.5.15249) I can load a stack of files from s:\  drive which is a home **S**hare drive
