### ISSUE TITLE
The road to 3.5

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#3672] opened 2023-09-17 15:00 UTC
Time to release 3.5 which means: finalize things, outside of finalization only small changes and bugfixes. Other stuff can be developed on a branch

Specifically:
* [x] in dark themes, tree view is not colored properly and document colors are inverter. The notion of GetDocumentColors() is not great
* [x] https://github.com/sumatrapdfreader/sumatrapdf/issues/3732
* [x] don't invert colors by default in dark themes. it's probably too confusing for users
* [ ] there's a crash in SaveAs (probably when saving a file that doesn't have an engine i.e. .chm
* [x] fix crash from https://github.com/sumatrapdfreader/sumatrapdf/issues/3729#issuecomment-1733471063
* [ ] look at IsDocLoaded() usage - with lazy loading in now returns false where it used to return true

Done:
* [x] add theme selection to menu
* [x] add a setting to remember themes
* [x] fix https://github.com/sumatrapdfreader/sumatrapdf/issues/3448
* [x] fix https://github.com/sumatrapdfreader/sumatrapdf/issues/3551
* [x] fix: on lazy loading the files do not restore TabState. Not sure if will keep lazy loading but should fix it
* [x] minimize logging that we've added to track misc stuff
* [x] fix https://github.com/sumatrapdfreader/sumatrapdf/issues/3675
* [x] disable / ignore auto-refresh during Ctrl + Shift + S. Not sure how best do it. Set a flag on WindowTab to tell it to ignore one auto-refresh?
* [x] fix https://github.com/sumatrapdfreader/sumatrapdf/issues/3685
* [x] a notion of selected annotation
* [x] list on `Annotation*` should be in  `EngineMupdf` with lifetimes tied to it. Currently we have a confusing mix of lifetimes tied to `EditAnnotationsWindow` and new objects (returned by `GetAnnotationAtPos()`). It'll be faster and easier to manage lifetimes
* [x] fix https://github.com/sumatrapdfreader/sumatrapdf/issues/3615
* [x] https://github.com/sumatrapdfreader/sumatrapdf/issues/3691
* [x] menu radio check is not painted in dark theme (custom draw), see `Settings / Theme` menu
* [x] tab colors in dark themes are pretty random
* [x] trim down what goes into a theme as much as possible
* [x] after switching theme should redraw all tabs in all windows
* [x] apply theme colors to `LabelWithCloseWnd`
* [x] when edit annotations window is shown, creating circle annotation doesn't add it to listbox
* [x] `e` or `Edit Annotations` command from palette doesn't show annot edit window unless mouse over an annotation. With context menu it always shows
* [x] change  CmdEditAnnotations keybinding from 'e' to Ctrl + E
* [x] look into https://github.com/sumatrapdfreader/sumatrapdf/issues/3683
* [x] look into https://github.com/sumatrapdfreader/sumatrapdf/issues/3473
* [x] fix https://github.com/sumatrapdfreader/sumatrapdf/issues/3679
* [x] fix https://github.com/sumatrapdfreader/sumatrapdf/issues/3692
* [x] settled on: `e` to select annotation without opening edit annotations window, `Ctrl + E` to select with opening. This is to avoid conflicts with existing mouse functionality i.e. ctrl + click is for rectangular selection. was: a way to select annotation. double-click conflicts with "select word" so maybe ctrl + click? ctrl + double-click? alt + click?
* [x] when mouse over an annotation, show a notification message `e to select, ctrl + E to edit` to inform about this functionality. Not sure if will keep it
* [x] when mouse move over selected movable annotation, change the cursor to hand to indicate it can be moved
* [x] in edit annotation window, Del should delete currently selected annotation
* [x] change Del to delete currently selected annotation, not the under the curso
* [x] can only move selected annotation (no more ctrl - drag for moving)
* [x] when cursor over annotation, cannot start text selection
* [x] creating 'a' annotation when edit window not open creates bogus bounds
* [x] when `Ctrl + E` ensure listbox is synced with `selectedAnnotation`
* [x] https://github.com/sumatrapdfreader/sumatrapdf/issues/3706
* [x] annotation under cursor notification persists when switching tabs
* [x] don't include translations that have > 100 untranslated strings
* [x] look into https://github.com/sumatrapdfreader/sumatrapdf/issues/3304
* [x] translate annotation notification
* [x] see if can do `Ctrl + click` to select an annotation and `Ctrl + double click` to edit
* [x] see if invert colors should be decoupled from themes. maybe on switching to dark theme sets invertColors to true but allows changing it afterwards. for light theme sets to false and also allows changing afterwards
* [x] don't require uninstaller to be run as admin if doesn't need to
* [x] fix cppcheck issues
* [x] remove hidden conversion to .txt or .pdf as part of `Save As`
* [x] when doing `Save As` and file has unsaved annotations, do `CmdSaveAnnotations`

**Comment by kerryland** [comment] 2023-09-19 04:31
How about adding [this one](https://github.com/sumatrapdfreader/sumatrapdf/issues/3473) about search highlighting being lost when switching between tabs. It seems like regression, and would be annoying if you are using multiple tabs.

Now, I really have to stop poking my nose into your project!

**Comment by kerryland** [comment] 2023-09-21 00:53
@kjk let me know when you are happy with the reworked annotations -- I'm keen to give them a try.

**Comment by GitHubRulesOK** [comment] 2023-09-21 01:24
@kerryland 
I am unclear about your question ?
the above commits will be released in a very short while as part of daily run
and will if not a fail be publicly available from pre-release binaries.

**Comment by kerryland** [comment] 2023-09-21 01:28
The last build I made was rather crash-tastic, but I don't want to complain about it if it's still a WIP.

**Comment by GitHubRulesOK** [comment] 2023-09-21 01:29
@kerryland always good to try recent changes in official binary but beware there are so many recent :-) may need a day or two to test them all

**Comment by GitHubRulesOK** [comment] 2023-09-21 02:14
@kerryland Latest run went well so pre-release should be available
BEWARE browser cache may attempt 15578,
DAILY should be 15601
Testing the reported CVE
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/e9079bda-7b03-42fa-82ff-daea3a13670c)

**Comment by kerryland** [comment] 2023-09-21 02:49
OK, just in case there aren't known problems with annotations, here's how it died for me. Again, just FYI, the sky isn't falling :-)

Start 15601
Open "Emma"
goto page 2
create an annotation via "a"
(jumps to first page)?
press ctrl-e to view annotations
goto page 2
create another annotation via "a"
wait for the crash

**Comment by GitHubRulesOK** [comment] 2023-09-21 03:36
Ha Ha ! That crashes win10 32bit portable version better than the slower CVE way, I would not have thought to use such a mix :-)

**Comment by kjk** [comment] 2023-09-21 06:18
@kerryland please do try annotations and report all problems, especially crashes.

I've bee lightly testing it and I don't get crashes anymore so consistent crash repro steps are valuable.

**Comment by kjk** [comment] 2023-09-21 14:45
> Start 15601 Open "Emma" goto page 2 create an annotation via "a" (jumps to first page)? press ctrl-e to view annotations goto page 2 create another annotation via "a" wait for the crash

@kerryland for what it's worth, I can't repro that in latest build (I'm talking in github, the pre-release build only happens once a day so it might be delayed).

I fixed a bunch of annotation crashes today.

**Comment by GitHubRulesOK** [comment] 2023-09-21 16:02
@kjk I followed @kerryland instructions and instantly got crash I did not submitt as they had raised the alarm , let me see If I can emulate again.

**Comment by GitHubRulesOK** [comment] 2023-09-21 16:15
@kjk Clean run instant crash as per above instructions?
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/12687514/sumatrapdfcrash.zip)
[Emma - Jane Austen - Copy.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/12687559/Emma.-.Jane.Austen.-.Copy.pdf)

**Comment by kjk** [comment] 2023-09-21 16:27
Yeah, I believe I've fixed it, it just didn't propagate yet to pre-release build.

**Comment by kjk** [comment] 2023-09-21 21:04
So the final (?) design for annotations:
* when cursor over annotation we show notification with type of annotation and help text
* `e` selects annotation under cursor; `Ctrl + E` selects and opens annotations editor
* selected (and moveable) annotation can be moved
* `Delete` deletes selected annotation when focus is in main window or annotations editor

**Comment by GitHubRulesOK** [comment] 2023-09-21 21:30
sounds OK ish  :-)
 so side issues you maybe highlight and both sidebare and users preference is ALL black OR whitish plus contrast
 Thus a UI sidebar etc. highlight of #7f7f7f should with luck suit both camps ? also for topbar icons the prime problem is the scale when grey so a colour setting of forground all black all white and mid grey should help heep the number of colours to 3

**Comment by kerryland** [comment] 2023-09-22 02:50
# 15623 feedback:

## Isn't putting focus in 'Contents' field
- ctrl-e
- a to add
- put focus in text entry field. (also, I vote against defaulting it to the selection text!)

## Tooltip timeout is too short
- Personally, I wouldn't have a timeout at all. Remove it when the mouse is moved.
- It's also in a funny location. It should be near the annotation I think.

## Can't save annotations from within annotation editor
- This is a mild irritation. ctrl-shift-s should work from inside the annotation editor too

## Saving annotations shouldn't close the annotation editor
I'm saving because I'm paranoid, not because I'm finished editing annotations :-)
I do understand *why* you're closing it, but that's a technical problem, not mine as an end user :-)

## Crashes if ctrl-e after saving
- 'a' add an annotation
- ctrl-shift-s to save
- ctrl-e
- crash

## Annotations are lost if you decide not to save as a new file
- 'a' to add an annotation
- 'q' to quit (I hit this accidentally, btw. I'm not sure a single keypress should close the document, but anyway...)
- Choose 'Save to new PDF', but then click 'Cancel' because you have changed your mind
- Cry out in pain because document has closed, and your hard work lost. 

PS: The latest commit (305f2039acafd3610d5cfb02084d158fa3318b90, `when opening edit annotations window, sync with selectedAnnotation`) crashes the moment you press `a` :-(

**Comment by kerryland** [comment] 2023-09-22 06:12
Let me know if you agree with the above and I'll happily move each of them into individual tickets. A massive comment is not the best place to track bug reports -- sorry about that!

**Comment by kjk** [comment] 2023-09-22 12:55
I've added comments inline, mostly agree, please open issues.

As to `e` vs. `Ctrl + E` this is kind of cascading logic i.e. one thing leads to another:
* I don't want an easy to press by accident key (i.e. `e`) to invoke a potentially confusing annotations window hence `Ctrl + E` which is still easy to press but not accidentally
* but I still want an easy way to select annotation so that it can be moved with mouse. Initially I planned `Ctrl + click` but that also starts rectangular selection so I went with `e` as kind-of-related to `Ctr-E`
* I might have been wrong about `Ctrl + click` in that it might be possible to do both `select annotation` on `Ctrl + click` and still support rectangular selection. In which case I would remove `e` key binding (but leave `CmdSelectAnnotation` command so that users can bind it themselves)

**Comment by kerryland** [comment] 2023-09-23 07:37
@kjk 
I just noticed this in the "maybe" list:
> move selectedAnnotation from WindowTab to MainWindow?

What benefit would that bring? Wouldn't it mean that you would lose the "selected annotation" when you flip between tabs?
Isn't that also the problem behind https://github.com/sumatrapdfreader/sumatrapdf/issues/3473, because `findThread` is on `MainWindow` rather than `WindowTab`?

**Comment by kjk** [comment] 2023-09-23 11:34
Yeah, good points, hence "maybe".

**Closed** 2023-10-23 21:11 UTC
