### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by taooceros** [sumatrapdfreader/sumatrapdf#2886] opened 2022-08-21 22:00 UTC
https://gist.github.com/taooceros/3afedb9163c8ebdf26cd7e10d8577098

**Comment by taooceros** [comment] 2022-08-21 22:01
happens when opening this file
[RL Theory Book.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9390016/RL.Theory.Book.pdf)

**Comment by taooceros** [comment] 2022-08-21 22:04
I guess it's because of previously stored location. After deleting the session information, it works.

**Comment by GitHubRulesOK** [comment] 2022-08-21 23:34
@kjk using current pre-rel file crashed under win11 sandbox too
[sumatrapdfcrash (2).zip](https://github.com/sumatrapdfreader/sumatrapdf/files/9390186/sumatrapdfcrash.2.zip)

**Comment by GitHubRulesOK** [comment] 2022-09-13 18:35
possibly the issue with annotated files

**Comment by GitHubRulesOK** [comment] 2022-09-27 03:33
Should be fixed in 3.5.15244+ (see note)
likely caused by annotation instability

Note:- current pre-release is 3.5.15249 and on first run MAY crash for a different reason see https://github.com/sumatrapdfreader/sumatrapdf/issues/2984

**Closed** 2022-10-08 02:20 UTC
