### ISSUE TITLE
Problem in searching Farsi words

### ISSUE THREAD

**Issue by najafice** [sumatrapdfreader/sumatrapdf#2631] opened 2022-05-30 08:18 UTC
Hi,
First, I would like to say thank you for developing this lovely app.

Second, SumatraPDF seems to have problem when searching any word in **Farsi**. The program fails to find any word matching with the search box! You can see an example in the picture below:
![Capture](https://user-images.githubusercontent.com/46795285/170948917-4777d5e8-0de1-4ff8-8f0e-86485f01bf9e.PNG)

And Third, please add auto Right to Left (RTL) feature in the annotation content text box when the user switch the language of it's keyboard to Farsi/Arabic.

**Comment by GitHubRulesOK** [comment] 2022-05-30 11:56
Unfortunately PDF when designed did not allow well for non latin text extraction /serching, simply getting characters in printer left to right order. Thus when the single characters are considered as a string there can be any seemingly random matching.

One problem is not all glyphs may be well defined as a text character thus defaults to a ? or box
also depending how reader considers the order a word may be correct but the words in wrong order !

SumatraPDF depends on MuPDF being able to glean enough info from the PDF as to which line characters are to be treated as backwards, and over time that can be wrong and wrong again here ONLY One PDF are two poor examples of interpreting PDF definition of character order. Sadly both horribly wrong.

![image](https://user-images.githubusercontent.com/12754913/170987304-d73626be-fde5-4bd9-87ae-55318b61d4a8.png)

**Comment by najafice** [comment] 2022-05-30 13:15
Anyway, I would be very happy if the problem with non-Latin languages getting resolved in the future versions. There are other PDF readers like Foxit reader that are completely support non-Latin words.

Here is an example for what I mean by RTL in annotation text box. English sentences start from left, and Persian sentences starts from right
![Capture](https://user-images.githubusercontent.com/46795285/170999890-a33acd69-4471-40a2-b1a4-53518246ba89.PNG)
.

**Comment by GitHubRulesOK** [comment] 2023-02-11 21:02
keeping open for the annotation comment otherwise for copy and paste see https://github.com/sumatrapdfreader/sumatrapdf/issues/1870

**Comment by GitHubRulesOK** [comment] 2023-02-11 21:44
closing as duplicate of both #2655 and now #3271

**Closed by GitHubRulesOK** 2023-02-11 21:44 UTC
Labels: mupdf
