### ISSUE TITLE
Parts of UI take color value from FixedPageUI's TextColor

### ISSUE THREAD

**Issue by sdasda7777** [sumatrapdfreader/sumatrapdf#2175] opened 2021-10-03 08:26 UTC
Hope this screenshot explains everything, I would hope the red text in the top bar would either stay black or take a separate parameter. Note that the color of it only gets reloaded when program restarts, which makes it less obvious.
I hope this is a bug, not a feature, because the text now red is unreadable with white TextColor, because I couldn't find a way to change the color of the bar itself.

![image](https://user-images.githubusercontent.com/17746796/135745808-0a7f3b7b-7842-42e0-ac2f-04d0e02abcfa.png)

**Comment by echedey-luis-alvarez** [comment] 2021-10-13 20:43
Duplicate of #1553 .
Please close this issue.

**Closed** 2021-10-13 20:58 UTC

**Comment by echedey-luis-alvarez** [comment] 2021-10-13 20:59
(thx, that was fast btw)
