### ISSUE TITLE
Slovak and Czech languages do not work in 3.5 and 3.6 versions

### ISSUE THREAD

**Issue by SatelitDM** [sumatrapdfreader/sumatrapdf#3960] opened 2023-12-16 11:16 UTC
Slovak and Czech languages do not work in version 3.5.2 and the same is valid also in the latest 6.4 prerelease version. Even when selected, all menu items remain in English.
When looking at translations, Slovak and Czech languages are both fully translated - at least GitHub says 0 untranslated.

**Comment by GitHubRulesOK** [comment] 2023-12-16 12:43
closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/3867

**Closed by GitHubRulesOK** 2023-12-16 12:43 UTC
