### ISSUE TITLE
Comments could not be saved.

### ISSUE THREAD

**Issue by Jack-InGitHub** [sumatrapdfreader/sumatrapdf#3304] opened 2023-02-26 11:57 UTC
# environment 
SumatraPDF 3.4.6 x64
*.pdf >= 100M

# describe
When the pdf file is larger than a certain value, SumatraPDF will not be able to save comments.

**Comment by GJoe2** [comment] 2023-03-03 02:34
I tried a large pdf (120 Mb and mainly images) and I could save the comments but I had issues doing it, SumatraPDF would freeze for a couple of seconds to unexpectedly close it self. 

![image](https://user-images.githubusercontent.com/71229258/222616994-db50149c-664e-4a70-ad8a-a45a14df6c12.png)

**Comment by GitHubRulesOK** [comment] 2023-03-03 04:16
Adding comments/annotation are usually stored in the tail of the PDF HOWEVER to do so the whole file would need scanning for the positions and copy page headers to be adjusted often needs more than one full pass of the file, it is better to do all appendages at once, not one at a time, but the overheads of running back and forwards through thousands of object references, cannot usually be avoided. Here is just one comment added to an image file. You can see the highlighted addition (remember it is just one item) starts with the FORMER EOF (end of file) and has had to per adobe methods add much meta data from the original so as to position that very short binary stream.
![image](https://user-images.githubusercontent.com/12754913/222630005-911c14a8-e187-418a-bfcc-0126615db2d8.png)

**Comment by GitHubRulesOK** [comment] 2023-09-19 01:11
@kjk 

unsure if much can be done for this, version 3.5.15545
source file had no reported errors nor sluggish before annotation

250 MB one highlight annotation mid file as a test, takes over 30 seconds to parse the file during save
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/0d514c56-9225-4315-b1ff-747d86a8e1d0)

then reports file still needs saving on exit
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/f531ea2e-ce78-4585-ac71-2617f2c87443)

open fle in another application is now slow to load and reports errors
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/508c5abc-4850-4bbc-b35e-9acfe8e7dd06)

**Comment by kjk** [comment] 2023-09-23 19:27
Using latest pre-release (https://www.sumatrapdfreader.org/prerelease) I tried saving 70 MB file on a slow network drive and couldn't reproduce.

If it still happens for you in pre-release please provide a test document and more information of what happens exactly when you try to save annotations.

**Closed by kjk** 2023-09-23 19:27 UTC
Labels: annotations
