### ISSUE TITLE
Request for the hightlighter feature in sumatraPdf.

### ISSUE THREAD

**Issue by Ne-vermind** [sumatrapdfreader/sumatrapdf#747] opened 2017-03-12 13:15 UTC
Sir I am a regular user of sumatraPdf i.e 24X7 user. If you can add features such as highlighter and read-out-text option then it may help others as well. When I need to hightlight some text inside a pdf file then I have to move myself for adobe reader as adobe reader does the work perfectly and it also comes with colour variation features. Please try to incorporate these features in the coming versions of sumatraPdf, thank you.

**Comment by zklhp** [comment] 2017-03-13 06:00
Please download the pre-release version here:

http://www.sumatrapdfreader.org/prerelease.html

It has the highlight feature.

Select some text, press H key, the content will be highlighted. Select **the same** text, press H, the highlight disappears.

**Comment by SumatraPeter** [comment] 2017-04-09 08:50
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/185

**Comment by jlanza** [comment] 2017-09-13 14:44
It is not working for me on 3.1.2, should it be working? I have the colors change TextColor = #dddddd BackgroundColor = #333333 and I don't know if this is the issue.

**Comment by jlanza** [comment] 2017-09-14 08:16
I'm testing this feature now and it is not working properly. If I select the exact same text I manage to remove the hightlighting, but if I select just part of it, it includes another hightlight layer on it. And from them on is a complete mess to remove the highlight.

**Comment by SumatraPeter** [comment] 2017-09-17 12:07
@jlanza: Yes, the highlight feature is indeed (quite buggy](https://forum.sumatrapdfreader.org/t/annotation-support/67/4?u=sumatrapeter). Unfortunately the dev who was working on it seems to have left the project.

**Comment by GitHubRulesOK** [comment] 2019-08-15 14:20
Just an upatory comment that Audio Reading and Highlighting are both considered experimental in SumatraPDF. 

There are well supported and good comparable (lighter weight than acrobat) Audio pdf readers such as NVDA [(initial Binary File =23.3 MB)](https://www.nvaccess.org/download/) 

For annotation (e.g. highlighting) SumatraPDF uses some limited features from the MuPDF engine and thus more recent copies of [MuPDF-GL](https://mupdf.com/downloads/) are most useful for producing and editing annotation that is highly compatible with SumatraPDF reader

**Comment by misrarmm** [comment] 2019-10-12 14:21
highlighting feature not working in SumatraPDF
SHIFT+h   is for previous page.

**Comment by GitHubRulesOK** [comment] 2019-10-12 15:14
@misrarmm  As stated above highlight was ONLY available in the pre-release version from https://www.sumatrapdfreader.org/prerelease.html and that should still be the case
Also be aware there are the shortfalls mentioned above and elsewhere so I highly recommend using the lightweight MuPDF GL version as a companion editor highly compatible with SumatraPDF which can add and remove highlights. the two can be linked in SumatraPDF such that reading a page in SumatraPDF via the menu it can then be called in MuPDF for editing.

**Comment by StevenLi-DS** [comment] 2019-12-11 04:59
For some reasons, it doesn't work on my end. Am I missing something?

![demo](https://user-images.githubusercontent.com/33796896/70592820-fe1d2500-1ba8-11ea-932f-aa11b0a94336.gif)

**Comment by GitHubRulesOK** [comment] 2019-12-11 11:15
@StevenLi-DS  Please read issue #1304 it is working but invisible also see https://forum.sumatrapdfreader.org/t/highlighting-problem-in-prerelease-version/2496

**Comment by GitHubRulesOK** [comment] 2020-01-03 20:14
Ok just a heads up that Audio Reading a PDF, highlighting it and adding Notes (comments) are **all features of Windows 10** via Edge
I am not a fan of using Edge for browsing (Firefox is my default browser) but it provides all these functions in a dual user  working fashion **(as long as the file is under 32MB)**
This not too different to way a 1GB Latex Editor is combined with SumatraPDF as the fast light previewer (but with a zero GB installation overhead)

![image](https://user-images.githubusercontent.com/12754913/71746560-1fe69080-2e65-11ea-83d5-68a675a45489.png)

**Comment by SumatraPeter** [comment] 2020-01-03 23:07
> Ok just a heads up that Audio Reading a PDF, highlighting it and adding Notes (comments) are all features of Windows 10 via Edge
I am not a fan of using Edge for browsing (Firefox is my default browser) but it provides all these functions in a dual user working fashion (as long as the file is under 32MB)

@GitHubRulesOK: The new Edge-Chromium (which I like) is officially scheduled to replace the old Edge via Windows Update a few days from now, so guess we need to start testing with it instead. Note that it may not (yet) offer all the PDF-related functions of the old version.

**Comment by GitHubRulesOK** [comment] 2020-01-03 23:30
@SumatraPeter I had heard the engine could change but was not aware its imminent thanks for the heads up on that 
PS any idea how to reliably pass a file:///name to edge, I tried several ways to call alias exe and protocol:// without any joy but since I knobled http(s) protocol from opening edge that may be part of the cause

**Comment by SumatraPeter** [comment] 2020-01-03 23:49
Haven't looked into it, but given that legacy Edge is a UWP app I'm not at all surprised it causes such issues. 🙄 Thankfully Edge-Chromium is a standard Win32 EXE!

**Comment by GitHubRulesOK** [comment] 2020-01-04 00:24
@SumatraPeter that sounds promising if they keep it as a standard.exe but edge  using an alias looks like MicrosoftEdge.exe however when I call it it just flashes on and then closes without visible feedback,. One of the many reasons I use Firefox.exe

**Comment by SumatraPeter** [comment] 2020-01-05 02:50
@GitHubRulesOK: I guess you can try downloading the [latest binary for Edge Launcher from MS](https://github.com/MicrosoftEdge/edge-launcher/releases), then invoke it with something like `MicrosoftEdgeLauncher.exe file:///C:/path/to/file.pdf`.

**Comment by GitHubRulesOK** [comment] 2020-01-16 13:16
@SumatraPeter 
**Thanks** that hint lead me eventually to https://github.com/rt-2pm2/edge-launcher/commit/86a39cab2d46dba6c032d0f0ae6c97fc954d3372

**Comment by GitHubRulesOK** [comment] 2020-05-01 03:21
**Just an update to the comments above about edge which is now chromium based and easier to access**

The command to open the current html or pdf page in edGe for highlighting / read aloud is now

```
ExternalViewers [
	[
		CommandLine = "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" file://"%1#page=%p"
		Name = Ed&ge
		Filter = *.htm;*.html;*.pdf
	]
]
```
in this case I have set the shortcut to <kbd>Alt</kbd>+<kbd>F</kbd>+<kbd>G</kbd>

**Comment by SumatraPeter** [comment] 2020-05-02 01:31
What I find really idiotic is why MS is so slavishly following everything Chrome/Chromium does. I would have expected them to correct some of the more egregious errors at least, but no, [just as](https://support.google.com/chrome/forum/AAAAP1KN0B0Pv-JKE_qS-I/) 64-bit Chrome dating back to half a decade or more ended up in Program Files (x86), so does 64-bit ChrEdge in 2020. 🙄

>The command to open the current html or pdf page in edGe for highlighting / read aloud is now

Unfortunately they removed Read Aloud for PDFs from ChrEdge quite a few months ago and there's still no sign of it as far as I can see. 😞

**Comment by GitHubRulesOK** [comment] 2020-05-02 09:59
@SumatraPeter 
Agreed the location is odd, but at least it is accessible, which as you rightly point out, is not the case for read / aloud, for which I still keep portable acrobat reader since nothing else can equal its display of Adobe modified PDFs (3D, XFA and to some extent tagging)
Highlighting is also degraded in several ways (especially cant see the previous comments feature) and generally inferior to any other solution. 
I now only tend to send htm and html from SumatraPDF to edge for rendering.

**Comment by SumatraPeter** [comment] 2020-05-18 04:09
Read Aloud for PDFs is finally [returning to ChrEdge](https://techdows.com/2020/05/microsoft-edge-84-adds-read-aloud-support-for-pdfs.html)!

**Comment by GitHubRulesOK** [comment] 2020-05-28 18:36
Closing as the core issue of adding highlights is covered by pre-release annotation ability and the prime historic complaint of changing or removing (deleting) is now also addressed by a different method in recent build.
Fresh issues should be raised individually against the new broader pre-release annotations functionality.

**Closed by GitHubRulesOK** 2020-05-28 18:36 UTC
