### ISSUE TITLE
Java run print command is wrong

### ISSUE THREAD

**Issue by leven0106** [sumatrapdfreader/sumatrapdf#136] opened 2015-03-18 02:12 UTC
I use sumatrapdf print pdf file on command.but it has error.

! pdf-fontfile.c:377: fonterror : unsupported encoding (3/3)

pdf-fontfile.c:528: ignoring face name decoding fonterror ! pdf-fontfile.c:377: fonterror : unsupported encoding (3/3)
pdf-fontfile.c:528: ignoring face name decoding fonterror ! pdf-fontfile.c:813: couldn't find system font 'STSong-Light'
pdf-fontfile.c:815: loading non-embedded font 'SimSun' from 'C:\Windows\Fonts\ simsun.ttc'
font.c:63: not building glyph bbox table for font 'SimSun' with 28762 glyphs
My environment:win 7 SP1 x64

**Comment by kjk** [comment] 2015-03-18 02:23
Those are debug messages. Does it print the way it's supposed to? If yes, there is no problem.

If no, then please provide the PDF document that has this problem (see https://github.com/sumatrapdfreader/sumatrapdf/wiki/Submitting-bug-reports).

Those messages usually indicate that PDF itself is malformed, not a bug in the code.

**Comment by kjk** [comment] 2015-04-01 17:58
Closing as needed information not provided.

**Closed by kjk** 2015-04-01 17:58 UTC
