### ISSUE TITLE
pls allow choose local fonts

### ISSUE THREAD

**Issue by WangYH195** [sumatrapdfreader/sumatrapdf#3887] opened 2023-11-17 07:55 UTC
i want to insert some chinese characters as free text, but some words cant display by the defaut font(only 3 choices in V3.5.2 today).
i tried in acrobat to save those words in local font and open the pdf by sumatra. They come back again! So, if i can choose my local font when i insert a free text, everything will be fine.

### Discussed in https://github.com/sumatrapdfreader/sumatrapdf/discussions/2433

<div type='discussions-op-text'>

<sup>Originally posted by **viper73** March 24, 2022</sup>
Hello,

i really like this epub reader (3.4 preRelease). But i dont like the font of the epub books. I like it better when i can choose the font which is more easy to read for me. In other readers i can change the font to my favourite one. Will this be available in one future release? This would be an huge upgrade of this program.

Or is it possible to change the font somewhere in the program myself?

Greets, Viper73</div>

**Comment by GitHubRulesOK** [comment] 2023-11-17 14:46
closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1671 and [#244](https://github.com/sumatrapdfreader/sumatrapdf/issues/2255)

**Closed by GitHubRulesOK** 2023-11-17 14:46 UTC
