### ISSUE TITLE
Is it possible to make the toolbar color black?

### ISSUE THREAD

**Issue by kody180** [sumatrapdfreader/sumatrapdf#2536] opened 2022-05-06 05:14 UTC
I know there is an option to make the background black, but is it possible for the toolbar?
![Untitled-1](https://user-images.githubusercontent.com/72715647/167071119-f9481f7e-1298-4c74-96ba-65a640f72fea.png)

**Comment by GitHubRulesOK** [comment] 2022-05-06 09:34
Yes but that with scrollbars is windows control currently default is common but could be changed by set system colors
It is used by 3rd party skinners such as WindowsBlinds see other related Q&A https://github.com/sumatrapdfreader/sumatrapdf/discussions/2441, it could be changed like tabs via some theming but whilst experiments were tried there currently are no means to theme SumatraPDF as very complex with so many controls. 

Anm closing as this is effect a duplicate of that issue https://github.com/sumatrapdfreader/sumatrapdf/issues/898 and https://github.com/sumatrapdfreader/sumatrapdf/issues/743

**Closed by GitHubRulesOK** 2022-05-06 09:34 UTC
