### ISSUE TITLE
Searching in Right to Left languages 

### ISSUE THREAD

**Issue by quartzbear** [sumatrapdfreader/sumatrapdf#2655] opened 2022-06-02 12:40 UTC
Hi
When searching a PDF with text in a right to left language (Hebrew, in this case) , the program searches for the search query in reverse (looks for the letters showing up left to right). So the only way to search is type in the query in reverse, which is a hassle.
![Screenshot 2022-06-02 153946](https://user-images.githubusercontent.com/33700415/171631151-57c69760-aa94-455e-9190-e46e52888e39.jpg)

Any way to fix the search function?

thanks

**Comment by GitHubRulesOK** [comment] 2022-06-02 13:37
duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/2631 closing as covered by https://github.com/sumatrapdfreader/sumatrapdf/issues/1870

**Comment by kjk** [comment] 2022-06-02 16:36
Please provide a sample document (https://www.sumatrapdfreader.org/docs/How-to-submit-bug-reports) and a few queries in the bug report so that I can copy & paste them into search box (I can't type hebrew).

Right now I don't have anything files to test such scenarios.

**Comment by GitHubRulesOK** [comment] 2022-06-03 02:05
Hmm

MuPDF 1.19.0 sees them RTL
![image](https://user-images.githubusercontent.com/12754913/171772001-8065e1ca-0db9-4d1a-90f3-f3aeefad5492.png)

Older 3.1.2 (not perfect) but was reasonable
![image](https://user-images.githubusercontent.com/12754913/171772567-64d94448-7460-4565-8e22-9b1416229079.png)

**Comment by quartzbear** [comment] 2022-06-06 10:41
Hi, sorry about the delay

I'm using the latest version of Sumatra and it doesn't seem to work unfortunately 

![Screenshot 2022-06-06 133942](https://user-images.githubusercontent.com/33700415/172145685-0fdd7f88-530f-4ddb-87f6-8752217075ea.jpg)
![Screenshot 2022-06-06 133823](https://user-images.githubusercontent.com/33700415/172145693-93ef6c28-e9a8-4a8a-b8a1-579c3e7dcee7.jpg)

**Comment by justlog** [comment] 2023-04-03 21:54
Hey, I'd like to try and fix this (or at least point to where the issue might be), but I would like to know if there is work already being done on this in order to avoid duplicating work.

If not, as @GitHubRulesOK pointed out, the search seem to sort of work on 3.1.2 but stopped working on 3.2.
After some digging, I've noticed that there are commits related to MuPDF api changes (e.g. https://github.com/sumatrapdfreader/sumatrapdf/commit/5985e0e7be2de5c613947d01d04a98d363750843) which seem to be around the time the RTL search stopped working.
Assuming I'm not just talking nonsense (since this is the first time I'm looking at this codebase) and that I can actually help, if there's any more information that could help point me in the direction of a solution, I'd like that very much.

**Comment by kjk** [comment] 2023-04-03 22:23
No one is working on that, as far as I know.

I think you're on the right track: changes related to mupdf api changes are most likely a culprit.

I assume it's something relatively simple, I just don't know any rtl language, I don't know what the expectations are.

I would look into 2 places:
* see if fz_text_page_to_str for rtl text returns something that you would expect (you can see the values in the debugger)
* see if the text we get from text box control to use for search is in the right format
* look into copy & paste because users can copy text from a document and paste into search box and there might be a mismatch

Most likely it's a mismatch between the text we get from search box and text extracted.

Also what I'm unclear on is: is rtl a global UI setting or is it per document / per text setting.

I.e. what happens if you run on arabic UI and search for english text in english document vs. you enter arabic text and search arabic document. Or if the document is part arabic and part english and you enter english text vs. arabic text.

I don't know much about handling rtl text in Windows.

I think text can be categorized to be rtl vs. non-rtl by looking at Unicode code points and categorizing parts as rtl vs non-rtl, but I might be wrong.

Also, it's possible that some parts of the UI are not handling rtl properly. We have a framework and we do switch layout based on rtl (look for `isRtl`) but it's possible we missed some parts.

Rtl work was done by another person who no longer contributes and I don't have knowledge of this area.

**Comment by GitHubRulesOK** [comment] 2023-04-03 22:41
sadly RTL is a global problem in PDF as it was really an afterthought as not a printer nor screen requirement just which order letters are written and extracted and neither needs to be the same then clouded by cursive languages that struggle with mixing  easter with western and the icing on the cake is variable ligature type constructs where order of letters can be 2 1 4 3 and thats without considering vertical placements too.

A string of text may be daclared as opposing to the documents tags  however the bible or koran for all intents and purposes up to version 2.0 is https://ia801003.us.archive.org/5/items/pdf320002008/PDF32000_2008.pdf

**Comment by justlog** [comment] 2023-04-03 22:53
![devenv_fuT83PRbDt](https://user-images.githubusercontent.com/23499125/229642030-ee6dbab9-9a96-485c-b001-9348a2c63f2d.png)
In this picture the findText is giving the right string while pageText isn't (this is not the exact same string mind you, but it contains the same word). 
The text box search is giving out the right value, so something goes wrong when extracting the text from the PDF.
I'm assuming you meant to look into FzTextPageToStr inside of EngineMupdf.cpp which I did. At first glance it seems that indeed the loop of appending the content string is appending the characters in reverse.
I'll try to take a deeper look into this sometime this week.

**Comment by kjk** [comment] 2023-04-03 23:41
Re UI: I mean that in rtl Windows the UI sometimes the placement of widgets should be different e.g. reversed. But if the UI looks good to you, then it's good.

**Comment by GitHubRulesOK** [comment] 2023-04-04 00:40
@justlog 
you may get some hints from last time MuPDF tried to resolve a poor file , but beware all poor samples in lab are not all poor samples in the wild
https://bugs.ghostscript.com/show_bug.cgi?id=706426

**Comment by GitHubRulesOK** [comment] 2023-04-04 02:06
If we analyse why Arabic sample works we see it was written carefully character by character from right to left
![image](https://user-images.githubusercontent.com/12754913/229667884-6aab3484-eddf-4718-bb41-598e0a3f9e5a.png)

If we analyse with a GUI editor the first string from OP sample we see its Hebrew but MS have seemingly written it back to front

![image](https://user-images.githubusercontent.com/12754913/229667498-a31a6aa1-06eb-4470-be38-c875d47eb145.png)

**Comment by sedeek1234** [comment] 2023-09-30 00:05
any updates on resolving this issue ?

**Comment by justlog** [comment] 2023-10-04 09:34
> any updates on resolving this issue ?

Unfortunately no (at least from my end). Life stuff happened so I couldn't get around to it.
If I happen to get some off time sometime soon I can give this another shot but I can't make promises. If there's somebody else who would like to try, go ahead.

**Comment by kjk** [comment] 2023-10-24 15:49
In 3.6 I've updated to latest mupdf, which was quite some changes.

We should change text search to use mupdf API directly.

Long time ago mupdf search wasn't great so we changed the search to extract page text from mupdf and implemented our more advanced search logic on top of that extracted text.

As a bonus it was also easier to add search this way to other document types.

But mupdf search improved and it would probably be better to ditch our search and go back to using mupdf APIs directly. Could fix this issue.

**Comment by GitHubRulesOK** [comment] 2023-10-26 02:21
@kjk 
I note that there was lots of Hebrew Arabic changes in latest MuPDF update

@quartzbear 
I think latest daily 3.6.15800 (if not before) has addressed this issue ? 
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/563d8c16-6ed0-43e6-b754-3fd439fbdb2d)

**Comment by quartzbear** [comment] 2023-10-27 08:46
@GitHubRulesOK 
I didn't try the daily, the recent [3.5.2 ](https://www.sumatrapdfreader.org/download-free-pdf-viewer) still has the problem

**Comment by GitHubRulesOK** [comment] 2023-10-27 13:05
@quartzbear 
agreed it was not fixed in the  3.5.# series so will be 3.6.# before its in a recent release, howeve for now unless you find a specific file which 3.6.##### cant handle the regression issue seems resolved by MuPDF updates.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/941cafac-ece4-4de9-a832-59acf7fb4e84)

**Comment by GitHubRulesOK** [comment] 2023-11-28 01:40
Both Arabic and Hebrew samples appear functional so closing all these legacy discussions 

If you have fresh samples that dont work in current pre-release (do compare with other readers too) please raise as a fresh issue
بيروت
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/c823d559-7e0f-4459-bfa1-c3353160ac3e)
מבוא
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/7b5bb38d-ed63-41b5-9d5d-30dc13119141)

**Closed by GitHubRulesOK** 2023-11-28 01:40 UTC
