### ISSUE TITLE
Bug in pre-release builds

### ISSUE THREAD

**Issue by givemeatip** [sumatrapdfreader/sumatrapdf#2036] opened 2021-07-18 06:02 UTC
Sumatra PDF stops answering at first run after installing the bugged builds but answers after some time. At second run, it is slow to load some PDF files already opened.

These versions I tested and they have the bug:
SumatraPDF-prerel-13718-64-install
SumatraPDF-prerel-13717-64-install

The most recent pre-release version that doesn't have this bug that I could download: SumatraPDF-prerel-13709-64-install

Another question, I notice that new pre release versions are getting released very quickly. This is weird, the pre-release channel was updated less frequently some time ago. What happened?

**Comment by kjk** [comment] 2021-07-20 10:26
can you re-check with latest build. I'm making lots of changes so things might break temporarily

to simplify, there are no more daily builds. pre-release builds are now daily

In the past, before GitHub CI, it wasn't feasible for me to publish every build, so pre-release builds had to be occasionally made manually

with GitHub CI I've added daily builds but daily vs. pre-release is just redundant so no more daily

I've just made updates easier (click a button vs. go to website / download / run) so that should help with frequent updates

**Comment by GitHubRulesOK** [comment] 2021-07-20 13:20
"stops answering at first run after installing" **could be windows adjusting** to the new application
So is it only after new install and NOT slower on shutdown and restart ?

"At second run, it is slow to load some PDF files already opened." unclear if that could be due to a large number of files needing to be re-loaded into memory especially if many require heavy decompression.
Is it noticeable for some files and not others ?

**Comment by GitHubRulesOK** [comment] 2021-07-21 02:44
@kjk 
As you know I had to reinstall a few in a row :-)
It **naturally** takes some while on re-install for system to rebuild icon cache for the new handlers ?
Cant be avoided ?
**Appears to be repeated when SumatraPDF asks** to become default pdf handler
This persists on every opening of SumatraPDF when it attempts to try it again even after dont ask me again is selected.

**removing**
AssociatedExtensions = .pdf

seems to stop that recurring problem

**Comment by kjk** [comment] 2021-07-21 02:54
The way Sumatra registers for .pdf extension is obsolete and shouldn't be done in Win 10.

So yes, this should be improved.

**Comment by GitHubRulesOK** [comment] 2021-07-21 02:57
simplest seems to be remove that line on win 10 where edge rules the roost

**Comment by kjk** [comment] 2021-07-24 19:32
I can't reproduce this so let's assume it has been fixed in recent builds.

**Closed by kjk** 2021-07-24 19:32 UTC
