### ISSUE TITLE
Bug with printing a PDF file

### ISSUE THREAD

**Issue by fblais** [sumatrapdfreader/sumatrapdf#3363] opened 2023-03-20 17:03 UTC
Hi.
I get some strange white bands in the printed document.
Have tried most of the betas since a few weeks, and the bug is still there.
I'm attaching the document.
[bq2031.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/11021002/bq2031.pdf)

Thanks in advance!

**Comment by avorobey** [comment] 2023-03-20 17:22
What's your printer model? Is it a Xerox by any chance?

There are two similar bugs: #3349 and #919, do yours look similar?

(I've no clue how to solve it either way, but may help to gather more evidence)

**Comment by fblais** [comment] 2023-03-20 17:58
My pleasure to help!

**Comment by GitHubRulesOK** [comment] 2023-03-20 18:12
My advice is sadly consider using a PDF to Vector Printer application as it will always fare better

Good candidates are Acrobat Reader (unlicensed for such abuse) GhostScript (licensed of course) many other free(miums) designed for PDF Printing via Command Line are available (some with dubious re/abuse of those two Brand leaders)

**Comment by GitHubRulesOK** [comment] 2023-03-20 18:38
Not so much heavier as even less stable printing outputs there were so many issues with vector printing it was dropped in favour of sending images only to the printer driver, Hence its odd that there are bands of white in the image output but the drivers often split images into horizontal chunks during spooling so my lightweight inkjet gets an image PDFm made up of lots of smaller image bands in the PDF

**Comment by GitHubRulesOK** [comment] 2023-10-25 03:55
Closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/919

**Closed by GitHubRulesOK** 2023-10-25 03:55 UTC
Labels: printing
