### ISSUE TITLE
Toolbar icons with dark themes

### ISSUE THREAD

**Issue by username116** [sumatrapdfreader/sumatrapdf#3738] opened 2023-09-30 14:03 UTC
The toolbar icons in both dark themes appear pixelated, or they display poorly.

Screenshots with the latest pre-release v3.5.15699 64-bit:

![light](https://github.com/sumatrapdfreader/sumatrapdf/assets/108369600/b6b81ba4-5fab-4e68-ad17-4bf593d10c9e)
![dark](https://github.com/sumatrapdfreader/sumatrapdf/assets/108369600/eee4507b-5f2e-4c3e-bade-679eaf44fb7b)
![darker](https://github.com/sumatrapdfreader/sumatrapdf/assets/108369600/2ebf3465-b753-465f-8ca5-e900309b8ab6)

**Comment by GitHubRulesOK** [comment] 2023-09-30 18:02
closing as effectively duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/3669
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/61daeae9-ef55-40c7-bdda-c9a53b1ec13e)

**Closed by GitHubRulesOK** 2023-09-30 18:02 UTC
