### ISSUE TITLE
Sumatra 3.2.11669++ Prerelease crash if trying to open multiple pdf files

### ISSUE THREAD

**Issue by Penaus** [sumatrapdfreader/sumatrapdf#1340] opened 2019-12-20 14:58 UTC
Hello;
Everytime i try to open more than one pdf at once trough "rightclick -> open with -> sumatra" the main windows shows up empty, a few seconds pause and crashes.
Opening the files one-after-one is working flawless.
Tried this behavior with prerelease and the normal.
I'll attach the crashlog + removed my Name in it

[sumatrapdfcrash.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/3988776/sumatrapdfcrash.txt)

EDIT: 
Tried different strategys and found the following strange thing.
Sumatra only crashes if the programm wasnt running before.
If sumatra is already running (doesnt matter if pdf open or not) the new pdf's load flawless

**Comment by GitHubRulesOK** [comment] 2019-12-20 15:36
@kjk Agreed this method of loading seems to crash current pre-releases **3 or more** files
However I have no problem with official 3.1.2  with / without tabs on same machine

**Comment by Penaus** [comment] 2019-12-20 16:05
After reinstalling 3.1.2 loading 3 or more at once works fine. Huh ^^"
On the prerelase (tested 3.2.11731 x64 a few moments ago) the crash still happens.

**Comment by GitHubRulesOK** [comment] 2019-12-20 21:20
@kjk still a problem with 3 basic pdf files
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/3990338/sumatrapdfcrash.zip)

**Comment by GitHubRulesOK** [comment] 2019-12-20 21:33
@kjk dont know if this helps
if thje 3 files are in the same folder as Sumatrapdf.exe there is no crash
If they are in user\documents they do crash ??

**Comment by GitHubRulesOK** [comment] 2019-12-20 21:45
@kjk correction the placement does not seem to be an issue 
**I can open** those same 3 files sometimes **without a crash** even if on a different drive !!

**Comment by GitHubRulesOK** [comment] 2019-12-20 22:35
@kjk after update
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/3990532/sumatrapdfcrash.zip)
crashed with fresh prerelease-11744

**Comment by kjk** [comment] 2019-12-20 23:26
Should be fixed by 11746 and later.

**Closed by kjk** 2019-12-20 23:26 UTC

**Comment by GitHubRulesOK** [comment] 2019-12-21 00:06
@kjk yes a dozen files is now possible but some users throw larger sets than I am testing and seems to crash on overloaded **without a crashdump**
![image](https://user-images.githubusercontent.com/12754913/71299546-c02cb780-2385-11ea-9f11-1f0dcdf7eeef.png)

**Comment by kjk** [comment] 2019-12-21 00:38
I tried a couple of times with 15 files (seems to be a max allowed by explorer) and couldn't reproduce the crash. Will keep an eye on that.

**Comment by GitHubRulesOK** [comment] 2019-12-21 00:42
@kjk could it possibly be aggregated length of args gets truncated ?

**Comment by GitHubRulesOK** [comment] 2019-12-21 00:45
@kjk also note the last file in my series included non a-z characters

**Comment by kjk** [comment] 2019-12-21 00:45
I don't want to speculate. Without a crash report it's just guess work.

**Comment by GitHubRulesOK** [comment] 2019-12-21 01:19
@kjk 
I tried simple names drives C:\... and D:\shortpath\1.pdf etc any 3 or more can still cause crash without a crashreport
Tried downloading symbols (creates 3 files in crash folder) but still no crashreports
