### ISSUE TITLE
add magniiffing if posible

### ISSUE THREAD

**Issue by czert2** [sumatrapdfreader/sumatrapdf#214] opened 2015-06-02 21:09 UTC
it is simple, when you read some books, and it happen to have pictures sometimes they are unreadable, so posibility to increase size for better look at pictures willl be great help.

using bigger screen doesnt allways work :)

**Comment by Tmplt** [comment] 2015-06-02 21:29
Magnifying as in zooming or something else?

CTRL + [+/scoll up] works, and these buttons zoom too:
![zoom buttons](http://i.imgur.com/15oIKNe.png)

**Comment by kjk** [comment] 2019-01-01 22:20
closing as duplicate of #929

**Closed by kjk** 2019-01-01 22:20 UTC
