### ISSUE TITLE
errors when copying text from PDF file.

### ISSUE THREAD

**Issue by NewTrixxx** [sumatrapdfreader/sumatrapdf#3198] opened 2022-12-26 21:12 UTC
Hello all!
When I open a pdf file in SumatraPdfReader and copy text from it, for example, into a Google Translator input form (or elsewhere), some characters are missing. Why does this happen? I'm attaching the pdf page for an example.
[page 11.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/10304791/page.11.pdf)
Thank you in advance.

**Comment by GitHubRulesOK** [comment] 2022-12-26 22:08
The missing characters (ligatures) can be seen in other pdf editors such as Tracker Exchange or Edge viewer, this is a common extraction problem in most viewers where the written text is not simple.

![image](https://user-images.githubusercontent.com/12754913/209585727-a324e64c-f3e8-47f0-984a-0f9fa6970d71.png)
![image](https://user-images.githubusercontent.com/12754913/209585776-15d72d75-e121-446d-8e8f-a47eb9b5dce1.png)

**Comment by GitHubRulesOK** [comment] 2023-10-31 03:35
duplicate of #2422

**Closed by GitHubRulesOK** 2023-10-31 03:35 UTC
