### ISSUE TITLE
Overview mode (3 pages or more) 

### ISSUE THREAD

**Issue by quesada** [sumatrapdfreader/sumatrapdf#3807] opened 2023-10-25 21:09 UTC
Right now we have book mode (2-page view). I have a big screen and like to see as many pages as possible. Okular does this (and llpp), but one is a memory hog and the other is linux-only and protestware.

The only missing thing for sumatra to be perfect is this arbitrary number of pages on screen.

Firefox does display pdfs like this in what they call 'wrapped scroll.' It's amazing, but only for pdf, not epub.

**Comment by GitHubRulesOK** [comment] 2023-10-26 00:45
closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/246

**Closed by GitHubRulesOK** 2023-10-26 00:45 UTC
