### ISSUE TITLE
Vietnamese character support needed (epub)

### ISSUE THREAD

**Issue by komawoyo** [sumatrapdfreader/sumatrapdf#1896] opened 2021-03-01 02:16 UTC
![image](https://user-images.githubusercontent.com/18315233/109443858-9262ea00-79f0-11eb-9cb0-1f998d097443.png)

This is what it looks like on google ebook reader
![image](https://user-images.githubusercontent.com/18315233/109444010-fdacbc00-79f0-11eb-9a11-fe24c7f021f4.png)

**Comment by GitHubRulesOK** [comment] 2021-03-01 03:06
SumatraPDF (like this comment and older hardware readers) uses only one font for all ePub display (Normal **or Bold**, _sometimes Italic_)
The font you are using (if you have not changed it is by default "Georgia" which often has many characters missing)
![image](https://user-images.githubusercontent.com/12754913/109447088-d2e75580-7a3a-11eb-86c4-bdd2d8a8fa2d.png)

Try a font such as Arial or Times Roman in advanced settings
EbookUI [
	FontName = Times Roman
	FontSize = 12
![image](https://user-images.githubusercontent.com/12754913/109447188-088c3e80-7a3b-11eb-9868-80daaea74983.png)

**Comment by GitHubRulesOK** [comment] 2021-03-01 13:54
Closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/442

**Closed by GitHubRulesOK** 2021-03-01 13:54 UTC
