### ISSUE TITLE
Unable to select/copy text in epub files

### ISSUE THREAD

**Issue by taseikyo** [sumatrapdfreader/sumatrapdf#1731] opened 2020-08-17 07:12 UTC
Windows 10, SumatraPDF 3.2 64-bit

The shortcut `<Ctrl> + Left Mouse` doesn't work in epub files :(
![select](https://user-images.githubusercontent.com/23132915/90367926-e08b4e00-e09b-11ea-9b0d-290534494aff.png)

**Comment by SumatraPeter** [comment] 2020-08-17 22:15
Wish people would search a bit before opening issues...

Duplicate of #284 via #1456.

**Comment by GitHubRulesOK** [comment] 2020-08-17 22:51
@SumatraPeter  agreed duplicate of many similar

**Closed by GitHubRulesOK** 2020-08-17 22:51 UTC
