### ISSUE TITLE
Sumatra not fitting text in to a box, clipping it

### ISSUE THREAD

**Issue by waregen** [sumatrapdfreader/sumatrapdf#1048] opened 2018-07-27 09:34 UTC
![text_clipping](https://user-images.githubusercontent.com/15924001/43313301-f44379e8-918f-11e8-9dfe-e0ef503d7696.png)

* [here is the file on ge.tt](http://ge.tt/2JxvEmq2)
* [here is the file on github](https://github.com/sumatrapdfreader/sumatrapdf/files/2235297/sumatra_issue_example.pdf)

I tested with SumatraPDF-prerelease-10766-64, but its the same.

The pdf file is output of an accounting software called Pohoda, they might be in the wrong too, but since sumatra is the only one showing it wrongly I thought its worth to report.

**Comment by GitHubRulesOK** [comment] 2018-07-27 18:03
I am always impressed at how many ways there are NOT to build a pdf
Apart from the use of fonts that are non standard Aral7 & Aral7p this file has not been changed by the editor to identify itself.

If you want to SEE what I mean open this file in Win10 with edge then ask it to read aloud EVEN WITH SOUND OFF it jumps all over the place sometimes even right to left

The file is stupidly restricted WHICH EDGE IGNORES but does show it well 

The information that appears wrong has been overlaid by a very poor forms editor
A good editor should allow the reader to read out the statements and replies in order


Botom line is recent MuPDF 1.13 can also read this file as intended (probably due to recent improvements in Unicode support


@kjk another example where MuPDF lib update  (Tag ?) would solve rendering issues

**Comment by GitHubRulesOK** [comment] 2019-11-18 20:58
@kjk recent commits suggest this is addressed to now be same visual rendering as acrobat.
![Untitled](https://user-images.githubusercontent.com/12754913/69093362-30be7c80-0a46-11ea-9c63-b7744b11bb07.png)

**Comment by kjk** [comment] 2019-11-18 21:04
Yep, is fixed in latest build https://www.sumatrapdfreader.org/dailybuilds.html

**Closed by kjk** 2019-11-18 21:04 UTC
Labels: mupdf
