### ISSUE TITLE
Pdf search doesn't work in Hebrew (and I'm assuming all right-to-left languages)

### ISSUE THREAD

**Issue by natapov** [sumatrapdfreader/sumatrapdf#1870] opened 2021-01-27 17:26 UTC
This is an issue the pre release and current daily build. (The release build doesn't support search in hebrew at all).

When I type a hebrew word into the search bar it reads the word backwards and searches for that instead.
In the attached picture I typed the letters in reverse to illustrate the problem
<img width="386" alt="Screenshot_6" src="https://user-images.githubusercontent.com/73648320/106028962-44975100-60d5-11eb-9266-e15f771e4306.png">

**Comment by GitHubRulesOK** [comment] 2021-01-27 21:57
Uncertain without opening the file, but the way I understand it is the characters are placed in the file in what is in effect computerised first to last (L2R) order, you could argue that should be R2L in another part of the universe but since the First "!dlroW olleH" thats the way programmers work.
What should happen is when the glyphs are seen to be a R2L character they should be extracted in reverse order, there are some flags to help that happen and MuPDF are aware of this issue as there is at least one open bug for when arabic pdf objects are compared with html objects (which have a different methodology).

I will tag as MuPDF and link this issue to https://bugs.ghostscript.com/show_bug.cgi?id=701798 in the hope there is somefuture enhancement

**Comment by GitHubRulesOK** [comment] 2021-01-27 23:18
@rigulel 
Can I suggest you try a portable version 3.1.2 see https://www.sumatrapdfreader.org/download-prev.html

@kjk 
took me a while to find a typical example where different versions could be compared
However there seems to have again been another regression in font/type handling between 3.1.2 and 3.2X

Here we can see 3.1.2 can search Hebrew in correct order whilst latest version is incorrectly in reverse, so now am uncertain if it is only MuPDF at fault or if its up or downstream differences 
![image](https://user-images.githubusercontent.com/12754913/106067015-b2ec0b80-60f5-11eb-80cc-2525029989b9.png)

**Comment by MrTaylab** [comment] 2023-06-23 05:51
A temporary solution could be this python code written by ChatGPT
def reverse_words(input_string):
    words = input_string.split()
    reversed_words = [word[::-1] for word in words]
    return ' '.join(reversed_words)

So you copy text from the pdf and put it in the python code and it does the job for you. 
An example would be:
a="نيمدقتملاب"
print(reverse_words(a))# Output: بالمتقدمين

But the copying is still showing some other unexpected errors.

**Comment by sedeek1234** [comment] 2023-09-30 00:01
I tried the portable version 3.1.2 and it seems to be working just fine .. The question is if it was fine in a much earlier version it can't be that hard to fix it for the newer versions can it ? 
It's a major issue for half of the earths population to not be able to search, copy or paste in R2L languages .. 
Please help fixing this asap

**Comment by GitHubRulesOK** [comment] 2023-11-28 01:43
Both Arabic and Hebrew samples appear functional in 3.6.15909 so closing all these legacy discussions 

If you have fresh samples that dont work in current pre-release (do compare with other readers too) please raise as a fresh issue
بيروت
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/c823d559-7e0f-4459-bfa1-c3353160ac3e)
מבוא
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/7b5bb38d-ed63-41b5-9d5d-30dc13119141)

**Closed by GitHubRulesOK** 2023-11-28 01:43 UTC
Labels: mupdf
