### ISSUE TITLE
Pictures intact while color theming.

### ISSUE THREAD

**Issue by ThomasLeigh** [sumatrapdfreader/sumatrapdf#1759] opened 2020-09-14 14:06 UTC
II’ve noticed that if I change colors (within advanced settings), it influences pictures. I’ve set colors to end up with a kind of a preferred dark theme, but unfortunately it has also affected pictures. I’ve learned that it is hard to distinguish pictures from all the rest (background, text color...) within pdf files. I’d like to ask whether it could be possible today, perhaps? :) It would be fantastic to have dark-themed Sumatra with pictures remaining intact.

**Comment by GitHubRulesOK** [comment] 2020-09-14 21:04
This is a duplicate of several issues but there are two seperate reqirements
1) a wish by users to change the colours of the interface ( some can be but others are defaulted by windows)
2) a need to invert negative colours which has always been available via -invert-colors
3) a need to dim colours for night time reading, possible by reducing blue light levels and reducing contrast. Thus not a problem use the given settings to reduce blue levels and colour range.
so am closing as duplicated by
1.) https://github.com/sumatrapdfreader/sumatrapdf/issues/898 https://github.com/sumatrapdfreader/sumatrapdf/issues/778
2.) no problem
3.) https://github.com/sumatrapdfreader/sumatrapdf/issues/770 https://github.com/sumatrapdfreader/sumatrapdf/issues/437#
4.) https://github.com/sumatrapdfreader/sumatrapdf/issues/1275

**Closed by GitHubRulesOK** 2020-09-14 21:04 UTC
