### ISSUE TITLE
Remember single opened tab

### ISSUE THREAD

**Issue by michaelkolber** [sumatrapdfreader/sumatrapdf#1753] opened 2020-09-09 15:16 UTC
This is in a way of continuation of #28. I think it would make sense for Sumatra to remember even a single tab. The way common programs such as Chrome, Notepad++, and VS Code handle remembering tabs is that Alt+F4 / X button remembers a single tab, while Ctrl+W does not.

In the case of Chrome, Ctrl+W on the last tab closes the entire window.  
In the case of Notepad++ and VS Code, they behave like Sumatra, where they show a landing/blank screen.

It seems somewhat inconsistent that a single tab isn't remembered, but more than 1 tab is. I would be ok with this being togglable.

**Comment by GitHubRulesOK** [comment] 2020-09-09 23:31
Duplicate of Session not saved/restored if only one tab was open #1055

**Closed by GitHubRulesOK** 2020-09-09 23:31 UTC
