### ISSUE TITLE
Possible regression with odd image pdf

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#2283] opened 2022-01-11 23:39 UTC
The attached PDF was a batch translation of image to PDF
[Growing_1024x1024.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/7850483/Growing_1024x1024.pdf)

 Which shows well in Edge and older MuPDF 1..18 (not tested with 1.19) and official 3.3.3
 but shows a black screen in win7 32bit 3.4.14242 others in the batch from heic files also are black so it seems not to be one file but the method of insert & thus render
[sample1.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/7850502/sample1.pdf)
.

**Comment by kjk** [comment] 2022-01-20 23:01
Both files show for me with latest on win 11. Maybe a windows codec issue?

**Comment by GitHubRulesOK** [comment] 2022-01-20 23:10
I am using different system heic codec since its windows 7 32bit
but would have expected it not to affect PDF image render especially as MuPDfF shows colour PDF

**Comment by kjk** [comment] 2022-02-04 21:34
Agree that HEIC codec should not have effect on PDF.

Closing as I can't reproduce so no progress possible.

**Closed by kjk** 2022-02-04 21:34 UTC

**Comment by GitHubRulesOK** [comment] 2022-02-04 21:52
I will accept as bad file due to my poor chooice of methodology, but there are similar mupdf quirks in bugzilla where masks behave different, and you recently closed one out recently.
