### ISSUE TITLE
Second file will not open if Sumatra was opened from Everything

### ISSUE THREAD

**Issue by diethylether** [sumatrapdfreader/sumatrapdf#999] opened 2018-03-24 14:07 UTC
If I open a PDF in Sumatra from Everything (http://voidtools.com) and I try to open another into a new tab, from Windows Explorer, it does not work. Opening a second PDF from Everything is fine.

If I start Sumatra from Windows Explorer, then open a second PDF from Everything, and then a third from Windows Explorer, that works too.

So, it seems that opening a PDF from Everything stops Sumatra from opening further PDFs from Windows Explorer. I can't imagine why this could be.

This was not a problem in a previous version (cannot remember which... I use Ninite to update Sumatra) and I don't know if this is Everything's fault or Sumatra's. I'm using v3.1.2 x64 on a standard Windows 10 installation.

**Comment by SumatraPeter** [comment] 2018-03-24 17:42
Does the [latest pre-release build](https://www.sumatrapdfreader.org/prerelease.html) behave the same way too? Also, have you reported this to Everything's dev as well?

**Comment by diethylether** [comment] 2018-03-24 18:55
Yes, the same behaviour occurrs in the pre-release build. And yes, I have
filed a bug report with Everything's dev too.

Also, I installed it over v3.1 and I lost file associations with .pdf. When
Sumatra asks me if I'd like to make it the default app for .pdf that
doesn't work. I've had to set it manually.

**Comment by SumatraPeter** [comment] 2018-03-24 19:49
Yeah, it's a [known issue](https://www.sumatrapdfreader.org/docs/Setting-Sumatra-as-default-PDF-reader.html) with Win10.

**Comment by diethylether** [comment] 2018-03-24 20:12
Thanks. And I forgot to mention that yes, I am running Everything as admin. I just checked and the behaviour is the same whether I run it as admin or not.

**Comment by GitHubRulesOK** [comment] 2020-07-05 02:08
@kjk 
from above description can you confirm this is in effect a duplicate of #1609

**Comment by kjk** [comment] 2020-07-06 10:47
Closing as almost certainly it was admin => non-admin communication.

**Closed by kjk** 2020-07-06 10:47 UTC
