### ISSUE TITLE
funny printing with crop marks

### ISSUE THREAD

**Issue by v-python** [sumatrapdfreader/sumatrapdf#374] opened 2015-12-02 03:55 UTC
[0_HN2015-crop and mark 2.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/49371/0_HN2015-crop.and.mark.2.pdf)

Above file started life as a Word Perfect document, was printed to a TIFF printer, run through Acrobat to add crop and trim boxes, and trim marks, and this is the result.

But to print it?  SumatraPDF, either portable version 3.0 or installed version 3.2.10488 64-bit, on my Win10 box (new box, not an upgrade) with any of 3 printer drivers, produces a "scrunched" version... that is, for my HP LJ3015, it causes it to ask for 4.89×5.3" paper... but the image size is 5.91×8.66"!

I tell the LJ to use letter size, but the image still comes out scaled down to fit the smaller paper.

On the other printers, they don't ask for different paper size, but they produce the same size image.

Curiously, when I print from installed SumatraPDF 3.0 from my wife's upgraded-from-win8-to-win10 laptop, it prints fine to the same networked HP LJ3015 printer, centering the 5.91×8.66" image on the letter-size paper, without prompting regarding the page size.

Also uploaded document to http://ge.tt/5di3StS2/v/0 per instructions found somewhere on the forums.

I don't know if it is something about my computer, network, or the file.

**Comment by GitHubRulesOK** [comment] 2020-06-19 03:46
@kjk 
Old unanswered Issue, I guess this is no longer a "problem", However there are several factors involved that are known to potentially cause such disparity. so for others looking here:-
Cropping can have an effect on determining print area but the printing area in this case appears unaffected as shown in acrobat
![image](https://user-images.githubusercontent.com/12754913/85094092-cccf8280-b1e5-11ea-871f-ab3cd2dc757b.png)

The print driver default settings of letter print paper combined with SumatraPDF defaults should produce the expected result as described on "the wifes" printer so no issue there.

The "new box" had presumably had an altered default setting in it's print driver for a different paper size. Thus not a network or file problem, simply the new driver (or print settings) on the "new box"  was modified away from the standard default setting. (most likely for envelopes or photo prints)

@v-python 
Sorry no-one was able to follow this through at the time.
I am closing as "too old" a historic issue but can be re-opened if you still confirm a problem when system default is set to letter.

**Closed by GitHubRulesOK** 2020-06-19 03:46 UTC

**Comment by v-python** [comment] 2020-06-19 05:26
Well, several revisions of Windows 10 later, and maybe a revised printer driver too, this file still doesn't print right. But the symptoms changed.  So attempting to print it first it told the printer to ask me for legal size paper, even though the image area is smaller than letter size.  I gave it letter size anyway, and then the printer told me "clearing paper path" a bunch of times, feeding a sheet through without actually printing on it.  When I tried a second time, after a power cycle on the printer, it printed it, printed a blank sheet after, and then started the clearing paper path routine again.

I don't recall how I got past this issue 4 years ago: I did somehow get the file printed (my guess is that I probably did it via loading it in IrfanView and printing it as graphics), but obviously there is still something wrong somewhere, because Sumatra still can't print it properly.

**Comment by GitHubRulesOK** [comment] 2020-06-19 11:31
@v-python 
Thanks for the feedback
You mention using Irfanview and if you look inside the file description you will see that was the "creator" of the PDF, so it possibly would work well when reloaded back into it as originator.

As to the difference between PC behaviour it is governed by the "default" print driver settings per PC so different PC's attached to the same physical printer will behave differently.
Windows revision, print driver version, application version will then compound the difference.
"Windows System" printer driver defaults, "Print" Driver default settings, user settings either in the dialog or using command line can all be affected by the one and only SumatraPDF default setting which can have one of three/four values.
In effect there is much outside SumatraPDF control other than ONLY that one setting stored in advanced settings.

> PrinterDefaults [
> 	PrintScale = shrink
> ]

**Comment by v-python** [comment] 2020-06-19 18:46
Yeah, IrfanView is my favorite graphics program, and SumatraPDF is my favorite PDF viewer (because it doesn't take all day to start up, like Adobe Viewer does... well, it seems like all day when waiting for it.. maybe it is trying to be like Adobe Photoshop in that way).

I kept feeding same page through the printer.  When it did print, it was nicely centered, but one of the other prints during its "clearing paper path" produced "PCL XL error" and then indented a couple lines later "Warning:          IllegalMediaSize".  In every print attempt, it wound up with the "clearing paper path" on the printer LCD status display.

I think I have the first of those printer drivers, except my printer is actually connected via Ethernet, not USB.

The page size before printing is different than after printing to PDF printer on a different paper size.

Testing with a postscript printer driver doesn't test the actual printer driver, of course.

It seems to print fine to Universal Document Converter printer driver.

So when I try printing to the FoxIt PDF printer driver, SumatraPDF crashed!  I hit cancel because it said to do that to help diagnose, but then my browser went to your web site.  Not clear whether I was supposed to do something there, it wasn't obvious, if so, so I didn't.

**Comment by GitHubRulesOK** [comment] 2020-06-19 22:38
Agreed capturing print driver output before sending over ethernet does not detect comms, memory or printer file or paper handling, but does help to check position and intended page size.
Checking the default printer settings both on the printer and in windows printer properties may show any mismatch.
So as to reduce some printer handling variations SumatraPDF printing was "dumbed down" after version 3.0 to simply hand over an image to windows printing at the required size and rotation (not always as a user may expect) Any downstream issues are now most usually caused by the enlarged volumns of image bytes.
