### ISSUE TITLE
Copy-paste fails on certains PDF on 3.2 and not on 3.1.2

### ISSUE THREAD

**Issue by msnbcorp** [sumatrapdfreader/sumatrapdf#1505] opened 2020-03-19 14:33 UTC
3.2 seems to have introduced a new bug.
On certain pdf, notably some of the pdf generated by latex (lot of scientific article etc...) sumatra pdf 3.2 fails to copy-paste properly some text **BUT sumatra 3.1.2 succeed**.

An example :

**Selection of the text on a test file with sumatra pdf 3.1.2 :** 
![312](https://tof.cx/images/2020/03/19/535b2431a9e315b5188a7e7a37a53b94.jpg)

**Selection of the text on a test file with sumatra pdf 3.2 :** 
![32](https://tof.cx/images/2020/03/19/45a3615e01ef1f42517d327d53bd0bb4.jpg)

**Original text :** 
>ÉÉÉÉÉÉÉÉÉÉÉÉÉÉÉÉÉ EEEEEEEEEEEEEEEEE
>EEEEEEEEEEEEEEEEE EEEEEEEEEEEEEEEEE

**3.1.2 copy-paste text :** 
>ÉÉÉÉÉÉÉÉÉÉÉÉÉÉÉÉÉ EEEEEEEEEEEEEEEEE
>EEEEEEEEEEEEEEEEE EEEEEEEEEEEEEEEEE

**3.2 copy-paste text :** 

>É É É É É É É É É É É É É É É É É
>E E E E E E E E E E E E E E E E E
>E E E E E E E E E E E E E E E E E
>E E E E E E E E E E E E E E E E E

An example file : 
[test4.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4355094/test4.pdf)

**Comment by GitHubRulesOK** [comment] 2020-03-19 16:21
@kjk 
as you are aware there are several related issue to this one where words in many cases are wraped to seperate lines and some examples are raised in Copying text without (any) line-breaks #1427 

However this sample also illustrates another raised issue in that the word **I n t r od u c t i on** is not searchable

**Comment by msnbcorp** [comment] 2020-03-19 16:51
> 
> 
> @kjk
> as you are aware there are several related issue to this one where words in many cases are spaced out and often wrapped to separate lines
> Some examples are raised in Copying text without (any) line-breaks #1427 and
> /ToUnicode mapping issue #471
> 
> However, this sample also illustrates another raised issue in that the word **I n t r od u c t i on** is not searchable and thus similar to Problem copying text from PDFs #544

Hi, i am aware of the fact that this issue is general in viewer software BUT in the other issue the problems are shown for situation where they happen on ALL versions of sumatra (at least, all the last one). 

The problem shown here is of the same nature but only appear on the last version and work perfectly on the version before. So it's a newly introduced bug and not a conception problem of sumatrapdf.

**Comment by u-fischer** [comment] 2020-03-19 18:39
I can reproduce the problem with the lmodern and the ec-fonts. It works again with the old cmr font and with otf fonts. I don't think that the problem is from spaces in the page stream. I have there for example `(TEST)` or `(EEEEEEEEEEEEEEEEE)`. It looks more as if the copy&paste code inserts a spurious space almost everywhere. Actually the one place where the space is not inserted is where in the stream there is a negative kern: `(Intro)-32(duction)`.

**Comment by GitHubRulesOK** [comment] 2020-03-19 18:52
Hi Ulrike (how's bear coping with all this social distancing ?)
Using conventional sources we see no problem
![image](https://user-images.githubusercontent.com/12754913/77103423-481c6f00-6a12-11ea-9d21-68f16cb2dfaf.png)
It less conventional Tesseract OCR and pdfLaTeX rooted documents that tend to cause issues
is there something in the way their glyphs are defined that you think causes a difference?

**Comment by u-fischer** [comment] 2020-03-19 19:08
The problematic documents uses type1 fonts. I doubt that the glyph definitions are the problem - it worked fine with sumatra 3.1.2.  Imho there is simply an error in the code somewhere that inserts a space.

**Comment by GitHubRulesOK** [comment] 2020-03-19 20:04
@kjk 
if I recollect correctly there were some significant changes made to interpret "foreign" word spacing behaviours. Certainly if a line has been justified with larger word spacing it sometimes seems they are treated as either EOL or paragraph endings.

**Comment by msnbcorp** [comment] 2020-03-19 20:23
Note that there is no need of anything "foreign" to achieve the same bug. 
A minimal (and standard) latex code like : 

> \documentclass{book}
>\usepackage{lmodern}
>\usepackage[utf8]{inputenc}
>\usepackage[T1]{fontenc}

%%%%%% begin %%%%%%%
>\begin{document}
>\frontmatter
%%%%%% TEST %%%%%%

>\chapter{TEST}
>\section{Introduction}

>EEEEEEEEEEEEEEEEE
>EEEEEEEEEEEEEEEEE

>\end{document}

produce the same bug. With no special spacing etc... (no babel, no koma-script ...) it's all standard scientific international document/article/report.

**Comment by GitHubRulesOK** [comment] 2020-03-19 20:31
@msnbcorp 
my reference was not to your sample but to code introduced for Cyrillic/CJK handling some time ago
P.S. Ulrike would not see SumatraPDF application **update** signal until 3.2 goes on full release usually a week or so after forum users are given the chance to get bitten :-).

**Comment by GitHubRulesOK** [comment] 2020-03-28 22:09
@kjk 
unsure where the root is but in checking a decompressed copy of above sample it exhibits the same problem however if I resave in notepad (without any changes) but with Unix LF the problem disappears
![image](https://user-images.githubusercontent.com/12754913/77834949-9df2c480-7140-11ea-816e-e5b40bd9873a.png)
[decompressed.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4397977/decompressed.pdf)
[decompressed-resave.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4397978/decompressed-resave.pdf)

**Comment by msnbcorp** [comment] 2020-03-28 23:05
@GitHubRulesOK  : A quick difference between the two file show that the char " " in decompressed-resave are writen as NULL character in the decompressed.pdf, this seems to be the only difference.
As it's a replacement char to char it is logical that the size is the same ;)

**Comment by GitHubRulesOK** [comment] 2020-03-28 23:11
@msnbcorp 
I stuble on the cause without any analysis tools so ran comp (a very poor tool ) which shows first 10 changes as # 20 (decimal 32 is replaced somewhere !! as 0 (null) but since you got a better handle on it I guess that is the root cause
somewhere SumatraPDF is potentially interpreting one like the other ?

**Comment by NicolBolas** [comment] 2020-03-28 23:22
It should also be noted that this affects searching, since it's based on the same mechanism that gets the text string for copy&paste.

**Comment by SumatraPeter** [comment] 2020-03-29 20:00
@NicolBolas: Yes, that's already been noted in issue #1526 which has been marked as a duplicate of this one.

**Comment by GitHubRulesOK** [comment] 2020-03-29 20:19
@NicolBolas it was mentioned above in this thread too https://github.com/sumatrapdfreader/sumatrapdf/issues/1505#issuecomment-601274154 and also later illustrated in one of the images even if not repeated

**Comment by kjk** [comment] 2020-07-06 17:59
Fixed  by https://github.com/sumatrapdfreader/sumatrapdf/commit/59ee85e40bed1a94a16ef3cfa801fe4e0face3f1

**Closed by kjk** 2020-07-06 17:59 UTC

**Comment by msnbcorp** [comment] 2020-09-14 12:05
I have tested the last dev-build, it is still not fixed properly as GitHubRulesOK mentionned in [59ee85e](https://github.com/sumatrapdfreader/sumatrapdf/commit/59ee85e40bed1a94a16ef3cfa801fe4e0face3f1). This issues should be re-open.

**Comment by GitHubRulesOK** [comment] 2020-09-14 20:06
@msnbcorp 
there are several freetype related issues and although some similar ones are still open in theory **this one issue** is fixed. perhaps check which problems you have and see if they match those still open.
![image](https://user-images.githubusercontent.com/12754913/93132578-d32ea700-f6cd-11ea-86d5-f388afb83b37.png)

**Comment by msnbcorp** [comment] 2020-09-15 07:40
Hi, on this specific file it's OK, but on other files it's not ... 

I guess this had solved a part of the problem, but the copy-paste is still messy on certain files...

**Comment by GitHubRulesOK** [comment] 2020-09-15 08:50
yes copy and past fails on OCR files and LaTeX because of the way the fonts are interpreted by freetype

Many intercharacter spacing issues, but not all, were resolved, as here, by this fix
there are still issues over font height, word spacing, line returns,  and Unicode that remain unresolved by this fix thus open elsewhere.

**Comment by msnbcorp** [comment] 2020-09-15 14:21
Ok, if they are open elsewhere no problem ;) 

I hope this will be fixed soon, it's sad that none of these problems appears on 3.1.2 ...
