### ISSUE TITLE
Crash in template_affine_N_near_fb0

### ISSUE THREAD

**Issue by williamgriffiths** [sumatrapdfreader/sumatrapdf#1775] opened 2020-10-10 16:38 UTC
https://gist.github.com/williamgriffiths/835c1f811fb08e1147b9ff366eb66a86

**Comment by GitHubRulesOK** [comment] 2020-10-10 17:14
Potentially a dupe of Crash in template_affine_N_near_fb0 during zoom #1660
Can you confirm your actions just prior to crash ?

**Comment by kjk** [comment] 2020-11-17 22:47
Crash:
```
00007FFF7C78D9F7 01:000000000004C9F7 libmupdf.dll!template_affine_N_near_fb0+0x127 C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\draw-affine.c+703
00007FFF7C7979B1 01:00000000000569B1 libmupdf.dll!fz_paint_image_imp+0x1011 C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\draw-affine.c+4081
00007FFF7C7A99DF 01:00000000000689DF libmupdf.dll!fz_draw_fill_image+0xa8f C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\draw-device.c+1803
00007FFF7C764B37 01:0000000000023B37 libmupdf.dll!fz_fill_image+0x97 C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\device.c+337
00007FFF7C783B5E 01:0000000000042B5E libmupdf.dll!fz_run_display_list+0xdee C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\list-device.c+1800
00007FF7DAFA8149 01:0000000000187149 sumatrapdf.exe!EnginePdf::RenderPage+0x439 C:\Users\kjk\src\sumatrapdf\src\EnginePdf.cpp+1191
00007FF7DAF15ABC 01:00000000000F4ABC sumatrapdf.exe!RenderCache::RenderCacheThread+0x28c C:\Users\kjk\src\sumatrapdf\src\RenderCache.cpp+634

```

**Comment by kjk** [comment] 2020-11-17 22:47
Most likely a duplicate of #1514

**Closed by kjk** 2020-11-17 22:47 UTC
