### ISSUE TITLE
Windows 10 does not allow Sumatra PDF as default app

### ISSUE THREAD

**Issue by IanJermyn** [sumatrapdfreader/sumatrapdf#438] opened 2016-02-13 15:31 UTC
This problem started recently, within the last few days. Sumatra PDF has been replaced as the default pdf app by Microsoft Edge. When I try to reset Sumatra as the default app, there is an error message saying that "An app caused a problem with the default app setting for .pdf files, so it was reset to Microsoft Edge". 64-bit versions of Windows 10 and Sumatra 3.1.1.

**Comment by macpo** [comment] 2016-02-16 20:07
This worked for me to solve the problem...

[https://social.technet.microsoft.com/Forums/en-US/2dc8c9e0-324d-422d-ba0d-fac5d5c4aee0/an-app-default-was-reset?forum=win10itprogeneral](url)
> I resolved the problem for myself by using the Search bar to open "Choose a default app for each type of file", scrolling down to PDF, clicking Microsoft Edge and selecting SumatraPDF. It didn't immediately switch back, and double-clicking a PDF opened the correct program.

**Comment by KrasnayaPloshchad** [comment] 2016-02-23 17:25
Currently, you have to go Start → Settings → Default apps, click/touch Select default app by file type to set Sumatra PDF as default app. See what I have done.
![Set default app by file type via Windows 10 Setting](http://chuantu.biz/t2/28/1456248096x3340468352.png)
@kjk I think you can try to adding a special support to let users allow Sumatra PDF as default app via Control Panel, as following screenshot shows:
![Set default app via Windows 10 Control Panel](http://chuantu.biz/t2/28/1456248168x3340468352.png)

**Comment by chantisnake** [comment] 2016-02-29 00:53
this is a commonly known bug in latest windows 10.

**Comment by JohnOnGitHub** [comment] 2016-12-13 23:04
Done it:
Run Sumatra, 
go via the menu (top left) to options,
 at the bottom there is the option "make SumatraPDF my default pdf reader" or something like that.
Click it.
Having confirm/picked in a Windows window (!), it should change to say "SumatraPDF is your default reader. 
Voila et merci.

**Comment by julianlopezv** [comment] 2018-10-19 17:11
I did this:
1) Right click on pdf file and properties
2) Opens with -> change
3) SumatraPDF is in the list (don't use it)
4) Goto more apps -> look for another app on this pc
5) Search SumatraPDF on install path (C:\Program Files\SumatraPDF)
6) Set SumatraPDF.exe

**Comment by GitHubRulesOK** [comment] 2018-10-20 10:47
@kjk this is directly related to several open issues such as https://github.com/sumatrapdfreader/sumatrapdf/issues/589 (edge steals focus, win10 default setting ignored etc.) perhaps they could be linked here and closed as related duplicates?

**Comment by HermesPasser** [comment] 2018-11-01 01:10
"Properties/Opens with" and "Start/Settings/Default apps" are not working here, i even tried delete the registers related with open files as pdf but still the default app changes back to edge.

**Comment by Alacritous** [comment] 2018-12-02 00:17
To force windows to use a particular program, the most effective way is as follows. 

Open a command prompt with administrator privileges. 

type 

**assoc .pdf**

That will show you the program currently associated with PDF files. 

to set it to SumatraPDF type the following. 

**assoc .pdf=SumatraPDF**

I used this to associate .epub, .cbr, .pdf with Sumatra and it worked when all the other methods failed. 

You can use this method to associate any file with any program

To see ALL associations

**assoc|more**

**Comment by derpyherp** [comment] 2019-01-02 13:04
I'm not sure this is right. Didn't work for me, and the documentation claims it's for associating file _type_ with file extension, not a program for opening it.

As described here:
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/assoc

> assoc [<.ext>[=[<FileType>]]]
> 
> <.ext> | Specifies the file name extension.
> <FileType> | Specifies the file type to associate with the specified file name extension.

As a side note, I can change the default app to something like Sigil, or Calibre ebook viewer, or Adobe Reader, but not SumatraPDF using _any_ method mentioned here.

**Comment by Alacritous** [comment] 2019-03-18 19:05
One more thing to add. I just discovered this powershell script that has an option to prevent Edge from stealing back PDF association. Which others might find useful.   It can also be used to remove other bloatware from windows. But the PDF file association thing is what I thought would be useful here. 

https://github.com/Sycnex/Windows10Debloater

**Comment by GitHubRulesOK** [comment] 2019-11-16 11:30
@kjk there should be two open issues with file association
1) range of file types supported during install and
2) inability to force default association
 this one is a duplicate of the later https://github.com/sumatrapdfreader/sumatrapdf/issues/615#

**Comment by kjk** [comment] 2019-11-18 00:36
This is now tracked by #1248

**Closed by kjk** 2019-11-18 00:36 UTC
