### ISSUE TITLE
Crash when zoom is 0

### ISSUE THREAD

**Issue by finn-cz** [sumatrapdfreader/sumatrapdf#1770] opened 2020-10-01 19:31 UTC
[https://gist.github.com/finn-cz/1967e63e30cf6dce5ff38104cfd1c333](https://gist.github.com/finn-cz/1967e63e30cf6dce5ff38104cfd1c333)

**Comment by kjk** [comment] 2020-11-16 08:05
The crash is because zoom on some page is 0:
```
doc: D:\home\jan.narovec\datasheety\procesory\Texas\tms570\EAI_ARM_PLATFORM_DOCUMENTS\ARM\CortexR\DDI0406C_C_arm_architecture_reference_manual.pdf, pageNo: 172, zoom: 0.00
```
```
00007FF7BC2F2AF9 01:0000000000191AF9 sumatrapdf.exe!EnginePdf::Transform+0xa9 D:\a\sumatrapdf\sumatrapdf\src\EnginePdf.cpp+1279
00007FF7BC23222A 01:00000000000D122A sumatrapdf.exe!DisplayModel::CvtToScreen+0xca D:\a\sumatrapdf\sumatrapdf\src\DisplayModel.cpp+974
00007FF7BC234B8E 01:00000000000D3B8E sumatrapdf.exe!DisplayModel::SetScrollState+0x8e D:\a\sumatrapdf\sumatrapdf\src\DisplayModel.cpp+1755
00007FF7BC232AF9 01:00000000000D1AF9 sumatrapdf.exe!DisplayModel::SetViewPortSize+0xf9 D:\a\sumatrapdf\sumatrapdf\src\DisplayModel.cpp+1134
00007FF7BC29820B 01:000000000013720B sumatrapdf.exe!WindowInfo::UpdateCanvasSize+0x20b D:\a\sumatrapdf\sumatrapdf\src\WindowInfo.cpp+162
00007FF7BC227D2E 01:00000000000C6D2E sumatrapdf.exe!WndProcCanvas+0x3be D:\a\sumatrapdf\sumatrapdf\src\Canvas.cpp+1602
```

I've seen this before. Is this because the size of the canvas is so small?
Is it the page?

**Comment by kjk** [comment] 2020-11-16 08:13
I think I found the document https://www.macs.hw.ac.uk/~hwloidl/Courses/F28HS/Docu/DDI0406C_C_arm_architecture_reference_manual.pdf

But I can't reproduce the crash. 
@finn-cz do you remember what did you do to trigger the crash?

**Comment by GitHubRulesOK** [comment] 2021-05-28 17:42
@kjk 
from your description seems to be a potential duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1475#

**Comment by kjk** [comment] 2021-05-28 20:16
Yes, looks like dup of #1475

**Closed by kjk** 2021-05-28 20:16 UTC
