### ISSUE TITLE
Sumatra lock folders after closing the file.

### ISSUE THREAD

**Issue by AC130USpectre** [sumatrapdfreader/sumatrapdf#774] opened 2017-04-08 06:55 UTC
Hello, I discovered the following issue. Suppose I have a file in _folder1/folder2/file.pdf_. I open this file, close it (but Sumatra is still running), move _file.pdf_ from _folder2_ to some other place and then I try to delete _folder2_. But until Sumatra is running, my OS (Windows 10 64-bit) alert me that _folder2_ is in use and cannot be deleted. Seems like Sumatra hold _folder2_ even when no file inside this folder is opened.

**Comment by SumatraPeter** [comment] 2017-04-09 12:55
Duplicate of a bug I reported last year (and which unfortunately remains unfixed): https://github.com/sumatrapdfreader/sumatrapdf/issues/536

**Comment by AC130USpectre** [comment] 2017-04-09 13:36
Nice! I hope it will encourage developers to fix the original issue

**Comment by kjk** [comment] 2017-04-27 18:48
Closing as dup of #536

**Comment by kjk** [comment] 2017-05-02 20:56
Should be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/c863232e153ca3ba62f91853ee4c0631a51ac37b

**Closed by kjk** 2017-05-02 20:56 UTC
