### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [sumatrapdfreader/sumatrapdf#1153] opened 2019-04-05 12:13 UTC
Hi,
It's been so long since the last update.
Sumtra pdf works good like always but
 there are some features missing in sumtra like:
1. Support for e-forms
2. Morden look and feel
3.Some customization options etc.

So I just want to know is the project dead, should I move on to some other software?

**Comment by GitHubRulesOK** [comment] 2019-04-05 15:39
1) Unknown if anyone would do such a thing, however I personally don't want automatic 3rd party phone home actions imbedded in this lightweight viewer that could then be used to monitor my usage . 
2) Can't get more modern than windows 10  imposed system colours and your choice of alternative icons  here are mine what else is there to change ?

Not dead see recent commits just no one offering to add more features at present

![Untitled](https://user-images.githubusercontent.com/12754913/55639412-391cbc80-57c1-11e9-95a9-ec24a66e66e8.png)

**Comment by Ashutosh-Kukreti** [comment] 2019-04-06 04:00
1. Ok
2. Ok

Your reader looks a bit different from mine ,how?

**Comment by GitHubRulesOK** [comment] 2019-04-06 11:15
The Windows system colours and fonts control the top two lines you can switch the settings to use sys colours but I usually end up switching it off as it can confuse me.

The Icons are inbuilt in toolbar_11.bmp which can be overridden by an external one in the same folder as SumatraPDF-settings.txt the default one is https://github.com/sumatrapdfreader/sumatrapdf/blob/master/src/toolbar_11.bmp

R,G,B (FF, 0, FF) in the .bmp image (are transparent in the toolbar) more details here https://github.com/sumatrapdfreader/sumatrapdf/issues/16 first old link is dead but the last example one is here https://gist.githubusercontent.com/gl-bars/7842c590e884dae8f17c/raw/6ac21f49ba83b454b9ff85fd8a2a5c6da0c19805/toolbar_11.bmp

Draw your own BMP icons at a size to suit your age (I am old my icons are big)

Although the file MUST be called toolbar_11.bmp there are 13 icons numbered 0-12 (confusing :-)

NOTE the Open button is replaced with a "Save As" icon for Plugin mode: 
0 OPEN ICON and this position is ALSO used for number 12 (SAVE COPY)
1 PRINT DIALOG
icon bar will split here for GOTO_PAGE box
2 GOTO_PREV_PAGE
3 GOTO_NEXT_PAGE
4 VIEW_FIT_WIDTH/Continuous
5 VIEW_FIT_PAGE/Single Page
6 VIEW_ZOOMOUT
7 VIEW_ZOOMIN
icon bar will split here for find box
8 FIND_PREV
9 FIND_NEXT
10 FIND_MATCH
11 reserved for a blanking icon
12 see note above this is the SAVE_AS icon for imbedded mode

**Comment by Ashutosh-Kukreti** [comment] 2019-04-06 13:23
Thank You :)

**Comment by silenceleaf** [comment] 2019-04-21 19:04
Since, last release is 2016, do you have any plan to issue a new version?

**Comment by mooms06** [comment] 2019-04-22 16:15
https://www.sumatrapdfreader.org/prerelease.html

**Comment by GitHubRulesOK** [comment] 2019-04-22 20:43
@silenceleaf there is never a plan to issue a new version [(see wiki)](https://github.com/sumatrapdfreader/sumatrapdf/wiki/Release-process) it is continuous minor updates (e.g. 3 fresh languages this week) until a significant improvement is added by others. So until that happens the current release is 3.1.2 or pre-release towards next.

**Comment by Arty2** [comment] 2019-08-17 18:43
Perhaps one option would be to embrace the pixelated toolbar icons until someone will be able to add SVG support (which in itself would cause blurry icons in low DPI displays).

One example here of a custom toolbar I made for my own use:
![toolbar_11](https://user-images.githubusercontent.com/3519269/63216047-f6d49600-c137-11e9-90a2-2b45688bcd02.png)

**Comment by GitHubRulesOK** [comment] 2019-11-16 20:43
@kjk similare to other "are you still alive" queries the initial question here was about xfa support which I see is MuPDF status "wontfix" the other options about cosmetic updates I think are covered by several other "feature requests" thus I would say this thread is basically a duplicate of other issues.

**Comment by kjk** [comment] 2019-11-17 23:52
Also, each issue should be about a single thing.

**Closed by kjk** 2019-11-17 23:52 UTC
