### ISSUE TITLE
White bar at the bottom of the application when using a dark theme in a maximized window

### ISSUE THREAD

**Issue by MathisP75** [sumatrapdfreader/sumatrapdf#4621] opened 2024-11-05 15:50 UTC
**SumatraPDF version**
- Version 3.6.16779 Pre-release

**Describe the bug**
When using a dark theme in a maximized window, there is a white bar at the bottom of the window. It does not happen when the window is not maximized.

**Screenshots**
![image](https://github.com/user-attachments/assets/af6c43d1-7bd4-4623-9c75-610d36103125)
![image](https://github.com/user-attachments/assets/805434b8-fa5d-4c88-90d5-c5fbb2ae0b7c)

**Comment by MathisP75** [comment] 2024-11-05 15:56
This also applies to the bookmarks sidebar 
![image](https://github.com/user-attachments/assets/f4ddcca2-9b35-4d23-9010-3ff28da31d64)

**Comment by GitHubRulesOK** [comment] 2024-11-05 16:10
Duplicate of

**Closed** 2024-11-05 16:18 UTC
