### ISSUE TITLE
Future Request: thumbnail view for photo folders and CBR/CBZ files

### ISSUE THREAD

**Issue by yurix4** [sumatrapdfreader/sumatrapdf#540] opened 2016-05-29 14:54 UTC
Sumatra is good as viewer for CBR/CBZ images. Thumbnail view will make it better!

**Comment by SumatraPeter** [comment] 2018-12-08 14:09
@kjk: Duplicate of #146.

**Comment by kjk** [comment] 2018-12-08 20:42
Closing as duplicate

**Closed by kjk** 2018-12-08 20:42 UTC
