### ISSUE TITLE
Enhancement: Right-Click Open PDF Link in New Tab/Window Browser Style Actions

### ISSUE THREAD

**Issue by bradkrane** [sumatrapdfreader/sumatrapdf#1186] opened 2019-07-26 14:56 UTC
Forgive me if this is a duplicate, but if so in my defense, I used both the related issues beta search and because you know it's in beta googled the issue all the way to page 2! 

Anyway, I was reading a document and right-clicked on a PDF document link and was surprised for the first time, that there was no open in new tab or open in new window option in the context menu like in web browsers.

**Comment by SumatraPeter** [comment] 2019-07-27 00:49
> right-clicked on a PDF document link

You're right that no such feature exists currently, but just out of curiosity, the link in the PDF pointed to what exactly? Another location in the same PDF? Another PDF entirely? A website? An email address?

**Comment by bradkrane** [comment] 2019-07-28 14:33
The PDF link pointed to another location within itself.

**Comment by SumatraPeter** [comment] 2019-07-28 22:54
Looks to be similar to #46 which seems to have been erroneously closed (there is no option yet for opening the linked page in a new tab).

**Comment by GitHubRulesOK** [comment] 2020-02-04 20:06
Closing as duplicate of reopened #46

**Closed by GitHubRulesOK** 2020-02-04 20:06 UTC
