### ISSUE TITLE
Easier way to Invert color

### ISSUE THREAD

**Issue by lollita** [sumatrapdfreader/sumatrapdf#674] opened 2016-11-27 09:24 UTC
I would a button or option to invert pdf colors.

**Comment by Jeff-Relf** [comment] 2017-06-12 08:13
I love how bitmap colors are inverted but, when viewing a person's face,
I want to see it normally ( sans inversion ).
I'd like to hit an icon|key to toggle the inversion.

**Comment by kjk** [comment] 2017-06-12 09:27
Closing as duplicate of #275

**Closed by kjk** 2017-06-12 09:27 UTC

**Comment by lollita** [comment] 2017-06-12 09:29
In browser is possible to invert text only with css.
Do it is possible in pdf?

**Comment by kjk** [comment] 2017-06-12 09:30
No, PDF doesn't work that way.

**Comment by JJenkx** [comment] 2017-08-31 02:19
My setup is all black boarders and black start-up screen and total black in full-screen with white text.

Setting/Advanced Options, add line **GradientColors** to **FixedPageUI** then choose your hex color. Here is mine setup for all black and white.

```
MainWindowBackground = #000000
EscToExit = false
ReuseInstance = false
UseSysColors = false
RestoreSession = true

FixedPageUI [
	TextColor = #ffffff
	BackgroundColor = #000000
	SelectionColor = #f5fc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
	GradientColors = #000000
]
```

https://i.stack.imgur.com/vMHOQ.png
