### ISSUE TITLE
Dictionary Support

### ISSUE THREAD

**Issue by Aphexus** [sumatrapdfreader/sumatrapdf#947] opened 2017-12-25 07:23 UTC
Life is complex and lots to do. Having support for looking up word definitions is crucial in the modern world. Having support for this in Sumatra would be awesome and not too much work to do?

Basically when one, say, clicks on a word(shift RMB?), the definition is shown. One can customize the definitions using any of the standard dictionary formats such as

http://wordnet.princeton.edu/

(it's just a matter of looking up the word in the text file and then displaying the definition)

**Comment by iamthepanda** [comment] 2017-12-29 03:57
love the idea, but in the meantime hopefully this will suffice https://autohotkey.com/boards/viewtopic.php?f=6&t=7373

**Comment by Aphexus** [comment] 2017-12-29 04:09
Unfortunately, not everyone can install new software nor want to. Usually there are only two places I need to look up words, when viewing pages on the internet(which I can use a browser plugin to solve the problem) or reading PDF's such as technical books which have a lot of uncommon words.  Also, the script you link to pops up a browser, which can be slow and requires switching back and forth. It would be far more optimal for sumatra to implement this with a small popup and local dictionary. Shouldn't be that much work.

**Comment by iamthepanda** [comment] 2017-12-29 07:39
> The results are trimmed down and displayed in a Gui using an ActiveX control
not sure where you're getting that it opens up a browser

sure it's not perfect, but for those who are using windows and are willing to compromise, this could be a very powerful solution which is pretty close to the experience of the browser plugins

**Comment by GitHubRulesOK** [comment] 2019-12-01 01:03
@kjk effectively part of the extended uses for discussion in #1280

**Comment by GitHubRulesOK** [comment] 2020-02-24 22:56
@Aphexus 
Every dictionary has its own method of searching so I have only based this issue answer on your Original Post request namely WordNet which comes in 3 variants usable with Windows (there is different better support for unix)

WordNet for Windows Desktop has not progressed past v 2.1 which runs as CLI (WN) or GUI (WNB)

The CLI version can be run in a console but due to the hundreds of permutations would need to be tailored to each indiviuals preferences thus not easy to provide a generic solution.
The GUI version has no means to specify a search word when called. So your best option is to either double click the word of choice, right click to copy and use CTRL+V to add the search term or use a dedicated script via AHK or Windows scripting to automate that action.

The 3rd Option is to use the more up to date version 3.1 Web browser look-up and if you wish to use that with WebSearch.VBS as described in https://forum.sumatrapdfreader.org/t/advanced-tips-pass-selection-to-another-app-e-g-web-search/2700/3 then for WordNet the  MySearch command needs to be similar to 

```
MySearch="http://wordnetweb.princeton.edu/perl/webwn?c=8&sub=Change&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&i=-1&h=0000000000000&s="
```

After repeatedly making any preference changes to your optimal start-up options you should note the search address probably changes to a much shorter form. If that shorter form is your preferred setting then replace the one above.

It is the lack of Windows GUI command line support that inclines me to say WordNet needs to be treated just like any other Web based search (dictionary / thesaurus / translation thus this issue is a duplicate of #1280 and I am consolidating as such

**Closed by GitHubRulesOK** 2020-02-24 22:56 UTC
