### ISSUE TITLE
Color key masking broken

### ISSUE THREAD

**Issue by DLTech21** [sumatrapdfreader/sumatrapdf#3627] opened 2023-08-28 08:57 UTC
The attached [sample file](https://github.com/DLTech21/mupdf/blob/23/111.pdf) contains an image  over on the text

the wrong preview is

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/2238211/c9fa43ff-f634-46fc-a6b1-a89908287172)

the correct preview is

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/2238211/2d04ac7c-2b8f-4871-9885-9980b4fec922)

**Comment by GitHubRulesOK** [comment] 2023-08-28 10:45
@DLTech21 
Adobe Reader says the signatures are broken and another editor agrees they need removal and replace.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/57ad44eb-21e9-4e1a-a1ea-d7d5401b78c6)


@kjk 
Not withstanding the Above errors MuPDF does seem to show the stamps correctly.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/954d764f-5c13-4a26-b958-fdb7226d06b7)  

 whereas SumatraPDF does not  

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/d82fb3c4-b247-418a-bc1b-c99e6268c31e)

If I over stamp the two versions we can see it is the over stamp itself that carries a transparency masking problem similar to the QRcode.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/70dfebdf-5c08-48db-9d0f-f75b43dafe01)

**Comment by DLTech21** [comment] 2023-08-29 01:19
you said "Not withstanding the Above errors MuPDF does seem to show the stamps correctly." Can tell MuPDF version or branch?
while using the MuPDF master branch does seem to show the stamps incorrectly.

**Comment by GitHubRulesOK** [comment] 2023-08-29 01:40
@DLTech21 I THOUGHT my default was more recent variant but on checking its 1.18 is my current default whilst 1.20 (my most recent as on win 32 at present) DOES have the problem thus a MuPDF regression ?

**Comment by GitHubRulesOK** [comment] 2023-08-29 02:43
@DLTech21  hmmm way beyond me as not a c coder but 17 seems a reasonable scalar for the factors in that area but then I do not understand the changes anyway, so here is the commit where it was described why it was that way https://github.com/ArtifexSoftware/mupdf/commit/8e8384412535046dd8a2a4b753b3d6e962c628b1

**Comment by sebras** [comment] 2023-08-30 23:52
The problem is that the scaling and shifting done in `fz_mask_color_key()` is necessary for normal images, but not indexed images (this is what Adobe calls palettized images). A patch is being prepared upstream.

**Comment by GitHubRulesOK** [comment] 2023-10-24 02:47
closing as 3.6 does not have this issue 
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/e66648ec-d771-45b0-b93b-9c5c7aeeb564)

**Closed by GitHubRulesOK** 2023-10-24 02:47 UTC
Labels: mupdf
