### ISSUE TITLE
when open too many tab pages, the left and right button will block the 'X' button of the rightmost tab page

### ISSUE THREAD

**Issue by Huangmp1996** [sumatrapdfreader/sumatrapdf#2128] opened 2021-08-17 08:52 UTC
![sumatra_screen](https://user-images.githubusercontent.com/50688803/129694470-7f57d94a-a3a0-419c-934a-8f86581acf47.jpg)

How can I close the left and right button in the tab pages? For example here I can't close the 'taxize' tab page.

**Comment by GitHubRulesOK** [comment] 2021-08-17 11:40
The issue is due to a dpi scaling mis match between 2 parts of header usually reported around 200%/225% (I cant replicate at 125%/150%)

To close the rightmost tab you have several options
"middle mouse click" the visible part **once with a 3 button mouse**
with a 2 button mouse drag tab one space left and click now visible tab X 
use Ctrl+W
or File > close

Closing as Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/447

**Closed by GitHubRulesOK** 2021-08-17 11:40 UTC
