### ISSUE TITLE
TextColor = #E0E0E0 + BackgroundColor = #181818 inverts pictures and not only the text

### ISSUE THREAD

**Issue by Joachim-Otahal** [sumatrapdfreader/sumatrapdf#3066] opened 2022-10-31 18:02 UTC
My setting to habe white text on dark background:
FixedPageUI [
	TextColor = #E0E0E0
	BackgroundColor = #181818
	SelectionColor = #b5bc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
	GradientColors = #000000 #101010 #000000
	HideScrollbars = false
]
Result is an inverted picture: 
![image](https://user-images.githubusercontent.com/10100281/199076828-ea7cc615-b5d5-4c71-a549-cdadd6f06bd5.png)

When using this the PICTURE looks as it should:
FixedPageUI [
	TextColor = #000000
	BackgroundColor = #ffffff
	SelectionColor = #b5bc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
	GradientColors = #000000 #101010 #000000
	HideScrollbars = false
]
![image](https://user-images.githubusercontent.com/10100281/199077006-014ac3a1-a0c5-440f-b8e8-9faacd500179.png)

Source PDF for this: https://b-ok.cc/book/23252516/dd867b - but you can use any PDF EPUB etc.
Those Textcolor-Backgroundcolor settings should never invert the pictures, it should only apply to the text.

**Comment by GitHubRulesOK** [comment] 2022-10-31 23:56
closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/3061

**Closed by GitHubRulesOK** 2022-10-31 23:56 UTC
