### ISSUE TITLE
SumatraPDF and editable fields

### ISSUE THREAD

**Issue by angelog0** [sumatrapdfreader/sumatrapdf#1863] opened 2021-01-19 15:00 UTC
It seems that one cannot edit fields in PDF files which have them.

For example, I have built [this ](http://mirrors.ctan.org/info/pdf-forms-tutorial/en/examples/ex0001.tex) document with LaTeX (TeXLive):

```
latexmk -pdf ex0001.tex
```

but in SumatraPDF its not editable. It does in PDF-XChange viewer.

Maybe you have some suggestions.

Thanks

**Comment by GitHubRulesOK** [comment] 2021-01-19 16:42
SumatraPDF is not an editor (Read Only)

There is the possibility to use the Pre-release version "annotation" to overwrite the fields with "free text" which you would need to set boundary colour "none" it is a limited method as it then requires saving the piecemeal annotations into the source pdf.

An alternative is to try MuPDF-GL the compatible "Viewer" from the same library which will allow field entries but is less intuitive than PDF-XChange viewer.

I would favour adding an entry in SumatraPDF ExternalViewers to call PDF-XChange viewer with the page number that needs editing then save/close in PDF-XChange viewer should show the text in SumatraPDF Reader.

**Comment by GitHubRulesOK** [comment] 2021-01-19 16:52
Closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1249

also related 
https://github.com/sumatrapdfreader/sumatrapdf/issues/551
https://github.com/sumatrapdfreader/sumatrapdf/issues/1743
https://github.com/sumatrapdfreader/sumatrapdf/issues/1649

**Closed by GitHubRulesOK** 2021-01-19 16:52 UTC
