### ISSUE TITLE
Sumatra show some images inverted in certain .cbx files

### ISSUE THREAD

**Issue by Shideravan** [sumatrapdfreader/sumatrapdf#2702] opened 2022-06-09 00:07 UTC
![image](https://user-images.githubusercontent.com/12163923/172737164-6a8975eb-5017-4ea2-b14c-a4c039a8a68e.png)

The same files outside of the file extracted
![image](https://user-images.githubusercontent.com/12163923/172737469-092ead1c-257d-4ae8-a144-4a885eefe5f5.png)

In Calibri ebook reader:
![image](https://user-images.githubusercontent.com/12163923/172737536-fe3d9205-b187-4fb0-9770-f3ecfa161d2c.png)

Version: Pre-release 6adbae8
My Sumatra settings are in the following file
[SumatraPDF-settings.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/8865687/SumatraPDF-settings.txt)

**Comment by GitHubRulesOK** [comment] 2022-06-09 00:30
Potential duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1544#

**Comment by kjk** [comment] 2022-06-09 01:02
Please provide a cbx archive or a file that shows this issue as per https://www.sumatrapdfreader.org/docs/How-to-submit-bug-reports

**Comment by Shideravan** [comment] 2022-06-10 00:59
Here it is
https://datassette.nyc3.cdn.digitaloceanspaces.com/revistas/club_nintendo_cl_033_ano_04_no_05.cbz

**Closed** 2022-06-10 06:59 UTC

**Comment by Shideravan** [comment] 2022-06-10 17:33
Thank you!
