### ISSUE TITLE
Crash upon highlighting

### ISSUE THREAD

**Issue by vipatel10** [sumatrapdfreader/sumatrapdf#2948] opened 2022-09-10 12:54 UTC
Steps to reproduce:  Open pdf, highlight any text on the first page, then press a.

Gist: https://gist.github.com/vipatel10/3ffa463718049f7ef773d3c53b3c305f
[Nietzsche by Internet Encyclopedia of Philosophy.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9540385/Nietzsche.by.Internet.Encyclopedia.of.Philosophy.pdf)

**Comment by GitHubRulesOK** [comment] 2022-09-27 03:26
Should be fixed in 3.5.15244+ (see note)
likely caused by annotation instability

Note:- current pre-release is 3.5.15249 and on first run MAY crash for a different reason see https://github.com/sumatrapdfreader/sumatrapdf/issues/2984

**Closed** 2022-10-08 02:19 UTC

**Comment by vipatel10** [comment] 2022-10-08 03:10
I'm curious, what caused the crash and how did you fix it?
