### ISSUE TITLE
Dark mode icons look terribly aliased

### ISSUE THREAD

**Issue by expikr** [sumatrapdfreader/sumatrapdf#3785] opened 2023-10-24 06:09 UTC
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/77922942/505f91d5-7993-45f7-a220-8a01c4698511)

**Comment by GitHubRulesOK** [comment] 2023-10-24 10:16
Duplicate of (https://github.com/sumatrapdfreader/sumatrapdf/issues/3738)

**Closed by GitHubRulesOK** 2023-10-24 10:16 UTC
