### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by grimes2** [sumatrapdfreader/sumatrapdf#1561] opened 2020-04-19 15:28 UTC
The search in following document is not working. The document was created by Lyx. (3.2 and 3.3 prerelease,) (3.1.2 is working)
[Pettersson_Discography.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4499495/Pettersson_Discography.pdf)

**Comment by GitHubRulesOK** [comment] 2020-04-19 19:16
@kjk For reference looks like it uses Fonts: known as  **C**omputer **M**odern-**S**uper **F**onts
SFBX1440 (Type1; embedded)
SFRM1000 (Type1; embedded)
SFRM1200 (Type1; embedded)
SFRM1728 (Type1; embedded)
SFTI1000 (Type1; embedded)

Appears to be a duplicate of  Copy-paste fails on certains PDF on 3.2 and not on 3.1.2 #1505

**Comment by kjk** [comment] 2020-07-06 18:00
Fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/59ee85e40bed1a94a16ef3cfa801fe4e0face3f1

**Closed by kjk** 2020-07-06 18:00 UTC
