### ISSUE TITLE
add close button (X) at upper-right corner on pdf-thumbnails in Frequently Read window

### ISSUE THREAD

**Issue by katpatuka** [sumatrapdfreader/sumatrapdf#768] opened 2017-04-05 15:34 UTC
Maybe one could add a close button (**X**) at upper-right corner of pdf-thumbnails in **Frequently Read** window (similar to Firefox browser's **New Tab** window showing thumbnails of recently visited sites where a hover over a thumbnail displays a close button). 

Up to now one has to right-click on a thumnail and choose **Remove Document** to remove the thumbnail.

**Comment by SumatraPeter** [comment] 2018-03-18 01:07
Duplicate of 283

**Comment by kjk** [comment] 2019-01-15 21:48
closing as dup of 283

**Closed by kjk** 2019-01-15 21:48 UTC
