### ISSUE TITLE
Saving annotations corrupts PDF file

### ISSUE THREAD

**Issue by actimem** [sumatrapdfreader/sumatrapdf#3551] opened 2023-06-24 11:29 UTC
I recently updated to the latest version 3.4.6 64-bit.  I am using Windows 10.

When I open any PDF file, if I annotate it, I can see the "You have unsaved annotations" message at the top as expected.

Then when I save the annotations with Ctrl + Shift + S, I can see the "Saved annotations to ..." message, and the annotations are saved to file.

HOWEVER:
1. I can still see the "You have unsaved annotations" message at the top, i.e. it doesn't disappear.
2. If I attempt to close the file, the "Unsaved annotations" popup warning shows.  
3. If I then select "Save to existing PDF", it always CORRUPTS the file

I have also noticed that when Ctrl + Shift + S, sometimes it also corrupts the file, but I just noticed this like once out of 10 tries.

**Comment by zengpengkindle** [comment] 2023-08-08 16:26
i hava the same problem
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/16894507/2f751629-463c-47ce-9df9-dac7537e6cc0)

**Comment by kerryland** [comment] 2023-09-16 09:31
Does anybody have an example file?

**Comment by kjk** [comment] 2023-09-16 15:32
Could you provide more information:

* Does it still happen with latest pre-release https://www.sumatrapdfreader.org/prerelease ?
* how big is the PDF file?
* is the file on a network drive (e.g. One Drive, DropBox, network storage) ?

I tried a couple of times by adding / moving a bunch of annotations in a small PDF file and couldn't reproduce

Related to #3470 3470

**Comment by kjk** [comment] 2023-09-16 15:37
Also, can you provide a sample file on which it always happens?

Some PDF files are malformed. Our PDF engine (mupdf) tries to fix malformed files but it's possible the corruption only happens on such malformed files.

**Comment by actimem** [comment] 2023-09-16 15:56
I can reproduce 100% of the time.

I just downloaded this book book from gutenberg.org, and then converted to PDF using Calibre version 6.17.0.  Note this happens with most of my PDFs, many that haven't been converted by Calibre.
https://mega.nz/file/LEcgDaQL#fNQ0yNtYKTSdR6d6N4JLtRrr9YiLhD92RcxLuDqLaFU

1. On page 4, I select "Emma Woodhouse, handsome, clever, and rich", and press "a" to annotate.
2. I then see the message "You have unsaved annotations" at the top.
3. I then press (Ctrl + Shift + S) to save the annotation for the same file.
4. Note, then "You have unsaved annotations" message continues on top.  If I open the file on disk with another PDF viewer, the annotation is saved.
5. I then close the first SumatraPDF where I made the change
6. A pop-up comes up warning there are "unsaved annotations", I click "Save to existing PDF" again.
7. The file is corrupted regardless whether I select saving to existing PDF or new PDF.

I am saving to my C drive, so no OneDrive sync'ing.  My current SumatraPDF version is v3.4.6 64-bit.

**Comment by kjk** [comment] 2023-09-16 17:24
Could you clarify steps 4-5: do you open / modify the file using another application? 

I tried with pre-release:
* open
* annotate
* Ctrl + Shift + S to save
* close
* re-open

and I don't get any corruption.

**Comment by kjk** [comment] 2023-09-16 17:28
In 3.4.6 there's a bug that after Ctrl + Shift + S, on closing we still ask to save, but I didn't get the corruption.

**Comment by kjk** [comment] 2023-09-16 17:33
Here's the file in case the other upload goes away:

[bug3551-Emma - Jane Austen.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/12641281/bug3551-Emma.-.Jane.Austen.pdf)

**Comment by GitHubRulesOK** [comment] 2023-09-16 20:56
I agree that last upload 15500 does not seem to "carry on" after ctrl+shift+S using 32bit Win 10

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/363e13f0-43dd-4255-9a18-0062b339ceab)

**Comment by kerryland** [comment] 2023-09-16 22:35
> I agree that last upload 15500 does not seem to "carry on" after ctrl+shift+S using 32bit Win 10

I don't understand "carry on" :-(

I can't reproduce the bug in 15510, or 3.4.6. Could it be a race condition? Are the problems only reproducible on fast (or slow?) computers.

**Comment by GitHubRulesOK** [comment] 2023-09-16 23:11
@kerryland 
sorry I should have been more specific by carry-on I was referencing what the OP said *"Note, then "You have unsaved annotations" message continues on top. "* so my point was that using latest 15500x32bit  "save as" has cleared the warning message/flag correctly and no more save is offered on close

**Comment by actimem** [comment] 2023-09-17 14:18
Regarding my step 4), what I meant is that after pressing Ctrl + Shirt + S to save the annotations, the file is saved to disk correctly and is not corrupted.  If, for example, I opened the file with Adobe Reader I could see the annotation in there.

However, it is at step 6) that the file is corrupted.  After I try to close the Sumatra PDF instance (step 5), it (incorrectly) thinks there are still unsaved annotations, so it prompts me to save the file (step 6).  It is then when I save the file that SumatraPDF corrupts it.

Good news is that the pre-release version is no longer corrupting the file.  As the pre-release version correctly removes the "you have unsaved annotations" warning after Ctrl + Shift + S, when I close SumatraPDF, it is no longer asking to save the file again, so the troublesome steps 6-7 do not take place. 

My suggestion is to release a new version with this patch as soon as possible, as SumatraPDF corrupting files is a major bug.

Many thanks for your help!

**Comment by GitHubRulesOK** [comment] 2023-09-17 14:26
@kjk 
I thnk this is fit for close as no longer an issue
However agree that as soon as current brainstorm is over it may be time for 3.5

**Comment by kerryland** [comment] 2023-09-17 19:57
https://github.com/sumatrapdfreader/sumatrapdf/issues/2227, has he same complaint, but mentions Google Drive, so I installed it and had a play. Using the "streaming" Google Drive option (which is the default) I can reproduce this bug.

I'd guess the bug is related to timing so maybe only effects slow hardware, highlighted by the Google Drive network connection?

**Comment by kjk** [comment] 2023-09-17 20:06
It could be that we auto-reload the file before we finish writing it hence corruption.

Try setting `ReloadModifiedDocuments = false` in settings and see if that fixes it (you can press `r` to reload manually).

If yes, then we have to set a flag around saving annotations to disable auto-reload during saving. We don't even need to reload because we already have the current version.

**Comment by kerryland** [comment] 2023-09-17 20:15
`ReloadModifiedDocuments = false` doesn't fix it. I'll dig some more.

**Comment by GitHubRulesOK** [comment] 2023-09-17 20:49
@kjk  @kerryland 
Just my 2 penny worth of red herrings but "synchronised" drives can cause corrupt files when they are not tagged as "locked" and ONE BIG bonus of SumatraPDF over Acrobat/Foxit is it does not lock files against outside interference, such as partial read/write

**Comment by GitHubRulesOK** [comment] 2023-09-17 21:04
@kjk @kerryland 
Thinking about that aspect it may be why I had that hang 
since I had been using the file in Edge and had saved there but file handle may not have been entirely released while attempting changes in SumatraPDF.
It had not been a noticeable issue in the far past when working one file 2 editors as long as one was careful. and perhaps there has been a recent change to that ability.

**Comment by kerryland** [comment] 2023-09-17 21:45
I can now reproduce the problem (locally sometimes, gdrive always) with a specific file. Here's what happens for me:

1. Open [tiny.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/12643684/tiny.pdf)
2. Add an annotation
3. See "You have unsaved annotations"
4. Press ctrl-shift-s
5. Get told that is has been saved (and it has), but "You have unsaved annotations" remains
6. This file is *good*
7. Close the tab
8. "Close and save to new PDF", that file is "corrupted".

If you skip step 4, the corruption in step 8 does not occur. ctrl-shift-s is critical to the bug.

Here is an example of a file that was corrupted locally:
[tiny - corrupt-local.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/12643746/tiny.-.corrupt-local.pdf)

Here is an example of a file that was corrupted using Google Drive:
[tiny - corrupt-gdrive.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/12643747/tiny.-.corrupt-gdrive.pdf)

The corrupted files seem to have garbage after `%%EOF`.  Acrobat actually will open these files, but then invites me to "save my changes", so they must be automatically fixing then.

I can take a look, but I expect someone with more experience in this code would be much faster at finding this one.

**Comment by kjk** [comment] 2023-09-17 22:13
Any specific annotation?

**Comment by kjk** [comment] 2023-09-17 22:22
Trying to repro both locally and with network drive (but not google drive) by adding highlight and underline annotations, but so far no luck.

You could add logging / set a breakpoint on `EngineMupdfHasUnsavedAnnotations` to narrow down the reason we think we have unsaved annotations even though we've saved them. That seems to be the trigger.

And then figure out why that specific condition happens.

**Comment by kjk** [comment] 2023-09-17 22:22
Also, is it with edit annotations window opened or not?

**Comment by kerryland** [comment] 2023-09-17 22:47
Double click on "Hello" and press "a". No annotations window open.

**Comment by kjk** [comment] 2023-09-17 22:49
It's possible it'll be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/e4a33394f1148fa843684bf0da900af0db585290

I switched to manually tracking if annotations were modified instead of using `pdf_has_unsaved_changes()` because it's unreliable for some corrupt PDF files.

The downside is that we might forget to set `modifiedAnnotations` in some cases (I don't know of any, but it's possible).

On the other hand, it might merely hide the issues.

It's possible that the issue is actually not reloading the file in time. On network drives file notifications do not work so we resort to using a background check, which might take longer. This would explain why we keep showing 'unsaved annotations'.

Also, seems in only one code path where we call `ReloadDocument()` after calling  'EngineMupdfSaveUpdated()' so maybe the fix is to ensure we call  `ReloadDocument()` in all code paths after calling `EngineMupdfSaveUpdated()`.

**Comment by kjk** [comment] 2023-09-17 22:51
also, for some files `    save_opts.do_incremental = pdf_can_be_saved_incrementally(ctx, epdf->pdfdoc);` might be problematic.

The file from https://github.com/sumatrapdfreader/sumatrapdf/issues/3448 `pdf_can_be_saved_incrementally()` will return true but it was modified while loading.

**Comment by kerryland** [comment] 2023-09-17 22:59
Debugger tells me that it flags as 'unsaved' because `doc->xref_sections->subsec->table[3].type == 110`
When the document is initially loaded `doc->num_incremental_sections == 0`
```
int pdf_has_unsaved_changes(fz_context *ctx, pdf_document *doc)
{
	int i;

	if (doc->num_incremental_sections == 0)
		return 0;

	for (i = 0; i < doc->xref_sections->num_objects; i++)
		if (doc->xref_sections->subsec->table[i].type != 0)
			break;
	return i != doc->xref_sections->num_objects;
}
```

**Comment by kerryland** [comment] 2023-09-17 23:01
Also, I'm getting the problem even on my local file system now, apparently all the time.

**Comment by kjk** [comment] 2023-09-17 23:03
Could you update step 2 with details on which annotation you're adding?

I just changed that code so `pdf_has_unsaved_changes()` is not called but the issue might still persist.

I think the issue might be related to not reloading the document in some cases.

**Comment by GitHubRulesOK** [comment] 2023-09-17 23:04
tiny is malformed so acrobat itself will also trigger changes, without any annots or other actions apart from open.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/18fa1a55-b267-46cc-aeb7-ef2c26cfab60)

**Comment by kerryland** [comment] 2023-09-17 23:09
> tiny is malformed

Try this version. I think it is NOT malformed, and it is what I have been using recently -- it is 100% reliable in triggering the bug. For me anyway!

[tiny-v2.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/12643901/tiny-v2.pdf)

**Comment by kerryland** [comment] 2023-09-17 23:12
> Could you update step 2 with details on which annotation you're adding?

Add an annotation (highlight "Hello" and press 'a')

> I just changed that code so `pdf_has_unsaved_changes()` is not called but the issue might still persist.

I had tried that too, especially because that code is called so often. It made no difference.

**Comment by kjk** [comment] 2023-09-17 23:13
Ok, It's actually caused by `ReloadModifiedDocuments = false`.

With that we no longer reload changed documents which means we retain the state and I guess on second save this corrupts the file trying to incrementally saved the same changes.

We need to ensure that document is reload e.g. by explicitly calling `ReloadDocument`.

The repro with Google Drive might happen with  `ReloadModifiedDocuments = true` because file change notification might not arrive quickly enough so we re-save the file again corrupting it.

**Comment by kjk** [comment] 2023-09-17 23:16
Verified that `    save_opts.do_incremental = false;` doesn't cause corruption.

But that's not the best fix, we should just ensure file is reloaded right after saving annotations.

**Comment by kjk** [comment] 2023-09-17 23:20
The best fix would probably be to ensure the following happens in all code paths that call `EngineMupdfSaveUpdated()`:
* disable file change notifications for this file; we don't want re-loading twice
* call `EngineMupdfSaveUpdated()`
* reload the file in all tabs (could be in more than one)
* re-enable file change notifications for this file

**Comment by kjk** [comment] 2023-09-18 12:09
Hopefully this is fixed. Please re-open if you can reproduce a crash with saving annotations in pre-release.

**Closed** 2023-09-18 12:08 UTC
