### ISSUE TITLE
Table in EPUB doesn't show

### ISSUE THREAD

**Issue by Telesto12** [sumatrapdfreader/sumatrapdf#1987] opened 2021-06-16 11:43 UTC
EPUB generated with LibreOffice doesn't show the table but plain text
[DEMO12.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/6662641/DEMO12.zip)

**Comment by GitHubRulesOK** [comment] 2021-06-16 11:51
Known problem with both of the SumatraPDF renderings that would most likely also be a problem if switching to MuPDF

**Comment by GitHubRulesOK** [comment] 2021-06-16 13:36
Closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/565 and https://github.com/sumatrapdfreader/sumatrapdf/issues/1441

covered by more general open issue https://github.com/sumatrapdfreader/sumatrapdf/issues/849

**Closed by GitHubRulesOK** 2021-06-16 13:36 UTC
Labels: ebook
