### ISSUE TITLE
Missing letters in 3.4.5 and 3.4.6

### ISSUE THREAD

**Issue by PIK54** [sumatrapdfreader/sumatrapdf#2703] opened 2022-06-09 05:23 UTC
The new version (3.4.6 and 3.4.5) have place holders instead of letters. I do like to ability to copy text, but not at the price of losing text. Attached are 2 photos: 1/ with 3.4.6 and then, after re-installing 3.3.3, the letter re-appear. Consistently. 64 bit version. Haven't tried the 32 bit version
![SumatraPDF-3 4 6-64  screenshot showing missing letters](https://user-images.githubusercontent.com/12471459/172770427-1d8c80e5-19a3-4af4-b4bc-2dfb1574db48.jpg)

![SumatraPDF-3 3 3-64 Screenshot showing restored letters with older version of Sumatra](https://user-images.githubusercontent.com/12471459/172770476-65a61844-7705-4706-8e70-0271c0cff434.jpg)
.

**Comment by kjk** [comment] 2022-06-10 15:54
The issue is that this epub contains an embedded font quicksand.ttf and the text that doesn't render correctly is set to use that font.

It didn't happen before because previous rendering engine simply ignored embedded fonts.

Don't know if bad rendering of this font is a bug in mupdf or it's a badly created document that is only rendered properly when ignoring font styling.

**Comment by m3h3d1** [comment] 2022-07-13 22:13
Facing same problem.

**Comment by GitHubRulesOK** [comment] 2023-11-04 12:53
I am closing as the example file I found has the odd characters but are rendered correctly in current pre-release 
thus this issue as raised has been resolved !

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/865f03e7-7658-429b-9aee-26bba32bb912)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/b9395343-9512-4a38-b526-cfac5bb72397)

**Closed by GitHubRulesOK** 2023-11-04 12:53 UTC
Labels: ebook
