### ISSUE TITLE
Sometimes Sumatra does not remember opened documents

### ISSUE THREAD

**Issue by akontsevich** [sumatrapdfreader/sumatrapdf#458] opened 2016-03-08 07:54 UTC
Sometimes Sumatra does not remember opened documents, opens empty. Not sure why, probably during PC shutdown, restart. If I just open, close - it remembers.

**Comment by Dynode** [comment] 2016-03-08 17:58
Exactly. This can happen when
1: The computer suffered an unexpected shutdown (BSOD, forced shutdown by power button, ...)
2: The files you had opened were temporarily saved to a temp folder (like when they're "opened from browser" like shown here: [https://imgur.com/0JvUpNe](url) ) Those files seems to disappear after unexpected shutdowns for example (at least happens on my Win. 7 x64 system).

I opened two tickets to air suggestions/possible workarounds, but they were closed due to what I think were misunderstandings:
[https://github.com/sumatrapdfreader/sumatrapdf/issues/452](url)
[https://github.com/sumatrapdfreader/sumatrapdf/issues/451](url)

**Comment by voidray** [comment] 2016-03-14 09:17
Same problem here - after a forced reboot of some installer no tabs were remembered after the reboot.
I also noticed that when I have only one tab open, it will not be remembered, only when there are at least two tabs open.

**Comment by gshadows** [comment] 2016-03-24 07:56
I have similar problem, but much worser. Last opened documents are saved ONLY if I exit using File-Exit command. Closing window with [X] causes start from empty page. Same with windows shutdown etc.

All PDFs are opened from local hard drive folder (not temporary). SumatraPDF version 3.1.1 64-bit, OS: Windows 7 Pro x64.

**Comment by gshadows** [comment] 2016-03-28 12:29
Correction: it does not remember opened document only if single document was opened. Two or more documents remembered correctly.

**Comment by akontsevich** [comment] 2016-03-28 16:40
Does not depend of number of openned documents. I always have few documents
- does not remember them.

--
С Любовью,
Алексей.

Blessings,
Aleksey.

2016-03-28 15:29 GMT+03:00 Denis <notifications@github.com>:

**Comment by EpicWolverine** [comment] 2016-03-29 14:37
I have this issue as well. Open documents are only remembered if there is more than one open.

**Comment by stefanocaselli** [comment] 2016-04-23 10:25
for me too it remembers openend pdf only when two o more (win10 x64)

**Comment by NicolBolas** [comment] 2016-05-27 13:34
The odd part about the session loss is that it doesn't even remember the *previously loaded* session. That is, if you close SumatraPDF normally and then reopen it, it remembers the session. So it must have loaded that from somewhere. Yet if it closes abnormally, I don't necessarily expect ti to remember changes I made in that session.

But there's no excuse for it not loading the old session data that it previously loaded.

**Comment by FlameFractal** [comment] 2017-04-07 07:31
Update on this? @kjk

**Comment by kjk** [comment] 2017-05-14 08:22
The issue of not remembering due to windows reboot should be fixed.

Not reopening when there was only 1 document opened is expected behavior.

**Closed by kjk** 2017-05-14 08:22 UTC

**Comment by vogler** [comment] 2019-01-10 17:51
> Last opened documents are saved ONLY if I exit using File-Exit command. Closing window with [X] causes start from empty page.

This is should be fixed to behave the same way, no?

> Not reopening when there was only 1 document opened is expected behavior.

I didn't expect it and was just trying to find out why `RememberOpenedFiles` doesn't work until I landed here... At least there should be some comment in the settings or `SumatraPDF-settings.txt` to avoid confusion.

**Comment by csengh** [comment] 2019-01-30 22:33
I exit using File-Exit command but unfortunately Last opened documents are not saved!
I use latest version, and yes I have RememberOpenedFiles=true.

**Comment by GitHubRulesOK** [comment] 2019-01-31 00:14
@csengh Ensure that in advanced options
RestoreSession = true
Then when TWO or more windows **or tabs** in a session are closed they will open when restarting SumatraPDF by opening any one of them or even another, beware this can be affected by dual or more sessions since if any session has only one file open in each window it will not meet the two or more per session criteria.

**Comment by csengh** [comment] 2019-01-31 08:44
Oh Yeah, resolved!
Thank you very much!

**Comment by vogler** [comment] 2019-01-31 09:12
> if any session has only one file open in each window it will not meet the two or more per session criteria.
That's a bug and should be fixed.
