### ISSUE TITLE
Not showing thin lines (PCB board outline)

### ISSUE THREAD

**Issue by FandikH** [sumatrapdfreader/sumatrapdf#982] opened 2018-02-28 19:08 UTC
Hello, 
I've observed that SumatraPDFv3.1.2 doesn't show/render/print the "board outline" line in PDF [like this](http://ge.tt/3IO6Dmo2).
The AcroreadDC and FoxitReader and others does, please see below.

What's wrong? 
Can you please fix it?
Thank you,
FH

![mmkbd-sum-x-acro](https://user-images.githubusercontent.com/36932294/36807145-69d10f9c-1cc2-11e8-8e53-1c9bde99c05e.png)

**Comment by SumatraPeter** [comment] 2018-03-01 15:22
Duplicate of #398. Also see [related](https://forum.sumatrapdfreader.org/t/it-is-very-hard-to-read-the-picture-with-this-software/83) forum [threads](https://forum.sumatrapdfreader.org/t/almost-invisible-lines/192).

Similar issues have been reported with printing as well. For example #838 and others.

**Comment by GitHubRulesOK** [comment] 2019-11-15 00:08
@kjk again a marked improvement

![Untitled982](https://user-images.githubusercontent.com/12754913/68906393-00bc6400-073c-11ea-9e67-6409c493b83b.png)

**Comment by kjk** [comment] 2019-11-15 05:26
Thanks @GitHubRulesOK 
Should be improved in latest build https://www.sumatrapdfreader.org/dailybuilds.html

**Closed by kjk** 2019-11-15 05:26 UTC

**Comment by FandikH** [comment] 2019-11-15 07:35
Thanky, works well for me!
Good job guys,
FH
