### ISSUE TITLE
Please make every page same width

### ISSUE THREAD

**Issue by netdcy** [sumatrapdfreader/sumatrapdf#152] opened 2015-03-30 17:12 UTC
For example,
http://ge.tt/6h2DuMD2/v/0?c
If we use "fit width", the width will be set by the largest width, so other pages may be small.
Please add a feature that can make every page same width automatically.
Thanks!

**Comment by ousia** [comment] 2015-03-30 17:45
@DuChunyu, this feature is already implemented in SumatraPDF.

Go to _View_ and uncheck _Show Pages Continuously_.

Or press `Alt`, then `v` and then `p`.

This feature is available in the latest stable release (and probably in previous releases).

Please, close this issue once you confirmed it works for you. Or report issues, if it doesn’t.

**Comment by DuChunyu** [comment] 2015-03-31 04:47
@ousia Thank you, but I wonder if this can be implemented when pages are shown continuously. Because it requires that the width of pages is equal to my screen's. When pages zoom out, their widths   become different again. I think it would be better if this feature can be implemented.

**Comment by kjk** [comment] 2015-03-31 06:18
Implementation notes. In DisplayModel.h, instead of a single zoomReal, we need zoomReal for each page. Need to change CalcZoomVirtual().

**Comment by DuChunyu** [comment] 2015-03-31 10:43
@kjk Wow, good job! And if possible, not only this can be implemented for FIT_WIDTH or FIT_PAGE, but also pages can zoom out or in.

**Comment by KrasnayaPloshchad** [comment] 2015-04-01 16:53
I found this file may have similar problem:
http://www.huanghuagang.org/hhgLibrary/july2008/yan-an_riji.pdf

**Comment by SumatraPeter** [comment] 2015-11-09 15:15
Yes, this is required for comics that have large double-page spreads too interspersed among single pages.

**Comment by mbbrinkman** [comment] 2018-01-17 22:17
I realize this is an old submission, but this is a bit of an annoyance when reading older textbooks.  Many of them have scans with the full sleeve as the first page.  

Are there any updates on if this feature is planning on being added?

**Comment by kjk** [comment] 2019-12-15 06:13
Fixed with https://github.com/sumatrapdfreader/sumatrapdf/commit/48ba64ef4cadc656905026fa274dfb73d19d49aa

**Closed by kjk** 2019-12-15 06:13 UTC
