### ISSUE TITLE
Feature Request: 3 page view for ultrawide monitors

### ISSUE THREAD

**Issue by ntshrocha** [sumatrapdfreader/sumatrapdf#421] opened 2016-01-25 04:07 UTC
![219-ultrawide-monitor-review-increased-productivity-with-three-microsoft-office-pages](https://cloud.githubusercontent.com/assets/5845648/12542296/53fa5644-c308-11e5-8051-2c554f80520b.jpg)

**Comment by GitHubRulesOK** [comment] 2019-11-21 16:04
@kjk duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/246#

**Comment by kjk** [comment] 2019-11-21 21:35
Consolidating into #246

**Closed by kjk** 2019-11-21 21:35 UTC
