### ISSUE TITLE
Looks like a highlight bug.

### ISSUE THREAD

**Issue by suifengpiaoyang** [sumatrapdfreader/sumatrapdf#3417] opened 2023-04-03 11:02 UTC
1. left click and choose some text
2. right click > `Create Annotation From Selection` > `Highlight`
3. `Save changes to existing PDF`, and close this pop window
4. press hot key : `Ctrl + Shift + L` (Full Screen)
5. press `Esc` and then can see texts in red color: You have unsafed annotations.

**Comment by GitHubRulesOK** [comment] 2023-04-03 11:57
Confirmed that behaviour but note 
the change was saved to file
and there are several ways to possibly trigger similar (what may be classed as annotations "appearance change" )

My personal recommendation has always been
ONLY save appendages EITHER by quantity of edits say half an hour or 5 minutes, since each save bloats file.

**Comment by suifengpiaoyang** [comment] 2023-04-03 12:38
> Confirmed that behaviour but note the change was saved to file and there are several ways to possibly trigger similar (what may be classed as annotations "appearance change" )
> 
> My personal recommendation has always been ONLY save appendages EITHER by quantity of edits say half an hour or 5 minutes, since each save bloats file, or on EXIT

I know that clicking the save button will save the changes, but I don't feel comfortable with the red text. Also, the pop-up dialog every time I close it is not ideal. The software itself is great! If possible, could you add a shortcut such as "ctrl+s" to save the changes directly and remove the red warning text at the same time?

**Comment by GitHubRulesOK** [comment] 2023-04-03 13:21
Am not the developer just the very old office boy :-)
So comments are my observations as how IMHO best to use.

The red text does disappear on temporary save but in many PDF re-readers (not just SumatraPDF) the status may accidentally stay as "incomplete incremental changes"

**Comment by suifengpiaoyang** [comment] 2023-04-03 14:21
> Safest workflow is make changes, exit file, open file again from system, add more changes. Same as some other editing applications not just PDF.

I don't quite agree with this point.

I haven't been using this software for long, or you could say it's been a short time. However, I quite like this software because the shortcut keys are very consistent with my usual usage habits. Mainly because I often find myself in this situation: reading a book and marking special sentences, so I often see that red warning. And I may have some OCD tendencies (perhaps many people do in this situation), and the red text is a disruption to the overall comfortable reading experience. Every time I want to completely eliminate this problem, I have to close the file and reopen it. Even if I click "save" in the pop-up window, the red warning will still continue to appear after a while. Hmm... it's a bit frustrating.

**Comment by GitHubRulesOK** [comment] 2023-04-03 15:05
in earlier versions that text was not there but then there were many complaints that without a visual users were loosing edits on closure ! .....  all of the people, all of the time. is end of an old [programmer's adage](http://english.stackexchange.com/questions/366761/ddg#366768)

**Comment by suifengpiaoyang** [comment] 2023-04-03 15:11
:joy:

**Comment by GitHubRulesOK** [comment] 2023-04-03 15:24
I do magree its vERY visual, both the other PDF editors I use daily simply show  avery big **`*`** that I may overlook at times

**Comment by suifengpiaoyang** [comment] 2023-04-03 15:34
It seems a bit too obvious... Actually, the fundamental issue is still with the saving. In fact, almost all file editors have similar features: 1. If you haven't saved the edits and click the close button, a dialog box will pop up; 2. Clicking "save" after editing will eliminate the edited status. Currently, it seems that this software has certain issues in both of these aspects.

**Comment by avorobey** [comment] 2023-04-09 21:41
I think if you explicitly save from the annotation window, it shouldn't ask you again on closing (as long as you don't add more annotations of course). That seems like a bug. It's not easy to fix perfectly because of the way the MuPDF engine works, but I have a reasonable workaround in mind, let's see if @kjk likes it.

**Closed** 2023-04-09 22:59 UTC
