### ISSUE TITLE
Case-sensitive search option

### ISSUE THREAD

**Issue by DavidHaslam** [sumatrapdfreader/sumatrapdf#1111] opened 2018-12-25 18:09 UTC
Please provide options for case-sensitive search and whole word search.

**Comment by GitHubRulesOK** [comment] 2018-12-25 21:33
The "fixed page user interface" menu option will allow for both a word entry and by selecting the case button you can switch between sensitive and insensitive. In CHM, comic book  mode and e-pub mode this was not considered necessary to be exposed as part of those modes as pages are normally read sequentially but hyperlinks are used.

Either .chm or e-pub can be switched to fixed in advanced settings. However comic book can not.

In fixed interface this is not an issue thus
This is either duplicate of ebook mode search i.e. dup of https://github.com/sumatrapdfreader/sumatrapdf/issues/239 or whole word search  https://github.com/sumatrapdfreader/sumatrapdf/issues/410

@kjk Recommend this issue be closed
or

**Comment by GitHubRulesOK** [comment] 2019-11-16 09:56
@kjk I recommend this can be classed as dup of  https://github.com/sumatrapdfreader/sumatrapdf/issues/239

**Comment by kjk** [comment] 2019-11-16 09:58
closing as duplicate

**Closed by kjk** 2019-11-16 09:58 UTC
