### ISSUE TITLE
Window 10 Title Bar Issue

### ISSUE THREAD

**Issue by LingamYoni** [sumatrapdfreader/sumatrapdf#3906] opened 2023-11-24 05:33 UTC
In the screenshot, you can see that on older versions, part of the window title bar outside of the open pages is filled with the system color of the window title bar. However, on newer versions (all versions after 3.4.6), it is always white! This looks very annoying. How can this be fixed?
![sumatra_issue](https://github.com/sumatrapdfreader/sumatrapdf/assets/40486018/91987531-e41c-44ae-aebe-4113e50123f7)

**Comment by GitHubRulesOK** [comment] 2023-11-24 09:47
that area has been discussed many different ways as one or the other mix of dislikes its not a bug bug I will count this as a duplicate of issue https://github.com/sumatrapdfreader/sumatrapdf/issues/3803

**Closed by GitHubRulesOK** 2023-11-24 09:47 UTC
