### ISSUE TITLE
Add thumbnail function for each page sidebar

### ISSUE THREAD

**Issue by abc1044** [sumatrapdfreader/sumatrapdf#1625] opened 2020-06-18 12:00 UTC
Many files lack bookmarks. If the sidebar of the software has the function of displaying thumbnails of each page, it may be more convenient.

**Comment by GitHubRulesOK** [comment] 2020-06-18 12:09
Closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/146

**Closed by GitHubRulesOK** 2020-06-18 12:09 UTC
