### ISSUE TITLE
Error loading of pdf file

### ISSUE THREAD

**Issue by afik14** [sumatrapdfreader/sumatrapdf#2920] opened 2022-09-02 07:32 UTC
Hey all!

I am facing an issue with the software in which one of several pdf files does not load.
The rest of the files are running well.
I have some important annotations in the unloaded pdf file.
What can I do?

Thank you!!

**Comment by tactilis** [comment] 2022-09-02 07:52
Insufficient information supplied.

> What can I do?

You could explain _exactly_ what happens when you try to open the problem pdf. What error message is shown in SumatraPDF?

What happens if you try to open the file in another PDF viewer? Acrobat Reader for example?

What happens if you try to open the file in your browser (open a new tab and drag the file onto the browser window)?

You could attach the defective file here and let others help diagnose the problem.

**Comment by afik14** [comment] 2022-09-02 08:09
Thank you for your reply!

I successfully opened the pdf file on GoogleChrome, but still not through this software..
I cannot upload the file here (too big).

Here is the picture of the error:

![11111](https://user-images.githubusercontent.com/112687548/188092881-4bb8814e-e67c-49f9-87f2-435928135b1f.png)

**Comment by tactilis** [comment] 2022-09-02 08:24
Acrobat say that file is damaged and cannot be repaired, so it doesn't open.

Firefox displays it OK (but no annotations).

PDFill Editor claims the the PDF is password protected.

**Comment by afik14** [comment] 2022-09-02 08:30
I have no idea what happened. 
Yesterday I used it normally and now the error message
any idea what else can I do?

**Comment by tactilis** [comment] 2022-09-02 09:00
I was wrong above. Firefox _does_ display, at least some of your annotations (maybe all?):

![image](https://user-images.githubusercontent.com/4060092/188104249-19261a8d-71d3-41de-9d2d-be2e22a8c3f3.png)

**Comment by afik14** [comment] 2022-09-02 09:44
Some of them :)

**Comment by GitHubRulesOK** [comment] 2022-09-02 13:32
there are ways to fixe failed annotations since they are APPended to the source PDF so the file may be reairable especially using compatible mupdf/mutool (similar code base as SumatraPDF) link is down so cant test

**Comment by tactilis** [comment] 2022-09-02 16:19
I have just tried the free online PDF repair tool at https://www.ilovepdf.com/repair-pdf

It has resulted in a repaired file, which when loaded into Adobe Acrobat Reader, shows that there are 664 annotations consisting of underlined text and highlighted text.
 
![image](https://user-images.githubusercontent.com/4060092/188192126-ef780f25-896c-4f6d-a3ee-a1fc8a182f8e.png)
 
The earliest annotation in the repaired file is timestamped 17 August at 19:04.
The latest annotation is timestamped 1 September at 19:33.

The first annotation is on page 119 of the book (page 140 of the PDF).
The last annotation is on page 1480 of the book (page 1492 of the PDF).

The original document size was 115,913 KB.
The repaired document size is 170,170 KB.

The repaired document displays and scrolls OK in Adobe Acrobat Reader.

SumatraPDF (_v3.5.15239 64 bit Pre-release_)  loads the document OK, scrolls correctly until page 138/139 of the PDF, then **crashes**; presumably as it tries to load pages ahead and encounters the first annotation on page 140.

**Comment by afik14** [comment] 2022-09-02 16:56
> I have just tried the free online PDF repair tool at https://www.ilovepdf.com/repair-pdf
> 
> It has resulted in a repaired file, which when loaded into Adobe Acrobat Reader, shows that there are 664 annotations consisting of underlined text and highlighted text.
> 
> ![image](https://user-images.githubusercontent.com/4060092/188192126-ef780f25-896c-4f6d-a3ee-a1fc8a182f8e.png)
> 
> The earliest annotation in the repaired file is timestamped 17 August at 19:04. The latest annotation is timestamped 1 September at 19:33.
> 
> The first annotation is on page 119 of the book (page 140 of the PDF). The last annotation is on page 1480 of the book (page 1492 of the PDF).
> 
> The original document size was 115,913 KB. The repaired document size is 170,170 KB.
> 
> The repaired document displays and scrolls OK in Adobe Acrobat Reader.
> 
> SumatraPDF (_v3.5.15239 64 bit Pre-release_) loads the document OK, scrolls correctly until page 138/139 of the PDF, then **crashes**; presumably as it tries to load pages ahead and encounters the first annotation on page 140.

Thank you, man!
I finally managed to open the file! it worked!

**Comment by tactilis** [comment] 2022-09-02 17:40
@afik14 
> Thank you, man!
I finally managed to open the file! it worked!

I'm glad to hear that.

It would be a good idea to get into the habit of **_regularly_** backing up your important files to an external disk, or a memory stick, so you have a way of dealing with data loss, file corruption, accidental overwriting, or deletion of a file.

The frequency of backing up depends on the importance to you of the information in the files and the consequence of losing it.

===
@GitHubRulesOK may have a way of establishing what is actually wrong with the original PDF

**Comment by GitHubRulesOK** [comment] 2022-09-02 18:29
@tactilis 
Martin I dont have the file "Sorry, the file you have requested does not exist."

However one point I keep stressing is dont add & delete annotations as deleted ones  still bloat a file so +664 x 2KB = potentially + 1MB for fairly small ones but can naturally be much more

 however file was bloated from 116 MB to 170 MB sounds a lot thus may still be in there, no way to be sure without export import (not a trivial task, perhaps easier using acrobat?)

**Comment by tactilis** [comment] 2022-09-02 19:13
Hey @afik14.

You took the original 'broken' file down from Drive! Could you put it back and supply the link please?

Does the repaired file with 664 annotations cover everything that you highlighted or underlined? Or are there still any (many?) annotations missing?

**Comment by afik14** [comment] 2022-09-03 09:54
Unfortunately, I already deleted the file (even from my PC).
As far as I saw, most/all annotations appear.

**Comment by GitHubRulesOK** [comment] 2022-09-27 03:31
@afik14 
Should be fixed in 3.5.15244+ (see note)
likely caused by annotation instability

Note:- current pre-release is 3.5.15249 and on first run MAY crash for a different reason see https://github.com/sumatrapdfreader/sumatrapdf/issues/2984

**Comment by kjk** [comment] 2022-10-08 02:20
The file is no longer available

**Closed by kjk** 2022-10-08 02:20 UTC
