### ISSUE TITLE
error SumatraPDF-settings.txt file selected when installer and portable exist on a comuter

### ISSUE THREAD

**Issue by zredb** [sumatrapdfreader/sumatrapdf#897] opened 2017-09-26 08:05 UTC
Hi,
    I installed sumatrapdf in path of program file, and another  sumatrapdf with  SumatraPDF-settings.txt at other path, when I open the portable instance, the settings should read from the same path, but I found sumatrapdf load a different settings.

**Comment by SumatraPeter** [comment] 2017-09-26 15:50
Works fine here. I have v3.1.2 64-bit installed and it relies on "%APPDATA%\SumatraPDF\SumatraPDF-settings.txt". I also downloaded the portable version [SumatraPDF-3.1.2-64.zip](https://www.sumatrapdfreader.org/download-free-pdf-viewer.html) and extracted SumatraPDF.exe from it, then ran it once whereupon it created SumatraPDF-settings.txt in the same folder. The portable version responded only to changes made to the settings file it had itself created in the same location as the EXE.

**Comment by GitHubRulesOK** [comment] 2018-06-09 18:30
@zredb 
you can specify which settings file you want to use with the -appdata parameter for more on this see
https://forum.sumatrapdfreader.org/t/sessions-in-sumatra/1272/2
@kjk may I suggest this issue be closed as generally "working as expected", although there may be residual issues when the user has limited rights to the target folder, which is a windows UAC issue rather than caused by SumatraPDF

**Comment by kjk** [comment] 2018-06-09 20:18
Closing as per suggestion.

**Closed by kjk** 2018-06-09 20:18 UTC
