### ISSUE TITLE
"Check for updates" doesn't work

### ISSUE THREAD

**Issue by ssoher** [sumatrapdfreader/sumatrapdf#1704] opened 2020-07-21 06:29 UTC
The "check for updates" option in the help menu always says "you have the latest version" even though the version is 3.1.2

**Comment by GitHubRulesOK** [comment] 2020-07-21 09:15
Recently 3.1.2 is the more robust but we are almost there with 3.2.1
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1548

**Closed by GitHubRulesOK** 2020-07-21 09:15 UTC
