### ISSUE TITLE
Check the file DPI in the properties window

### ISSUE THREAD

**Issue by Shideravan** [sumatrapdfreader/sumatrapdf#2242] opened 2021-11-06 13:26 UTC
There's some useful info that I would like to see in the information info, such as DPI or file resolution of each PDF. This way we can easily choose for example from two files of the same scanned content who has the better resolution without need to trust only in the naked eye judgement.

**Comment by GitHubRulesOK** [comment] 2021-11-06 14:28
PDF is unitless each item has its own scalar values thus text is a font height x matrix values x font metrics. A page can have images at any dpi x scalar thus there could be a unitless gif at 1 inch square that cold have been drawn in 72 dpi at 2 inches and along side that a that a PNG 2" at 96dpi but is now 1" square thus its shown at 100% as 196 ppi but copy it and its saved by default 2" x 96dpi  for jpg its usually 75 150 300 pixels per inch but can be any scale that suits a default of 72points per inch.

Overall there is little value in a viewer (rather than an editor) showing all the different values without their relationship to the scale of the unitless PDF page the only common factor is what scale the page viewing boundary (one of many page boundaries) is, Thus the nominal "page" size.

For images its similar assume the display is set to 96 dpi but user is at 150 scale and its a PNG for simplicity thus the image is now 96 x 1.5 dpi again the only constant is the **nominal** overall shape in local inches or cm.

**Comment by GitHubRulesOK** [comment] 2021-12-12 21:39
here are two files one has an image that was 96dpi
[096.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/7699864/096.pdf)
the other was 300dpi
[300.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/7699866/300.pdf)

both are now placed as an A4 page in a PDF we can see that in info

Here are the stream entries for both
096.pdf /Length 33078/Type /XObject/Subtype /Image/Width 2480/Height 3508/
300.pdf /Length 33078/Type /XObject/Subtype /Image/Width 2480/Height 3508/

Therefor the PDF does not distinguish any difference in dpi. It is an alien concept to a page language, even if we describe printers by their dpi abilities as say 600dpi it will for a nominal 2480x3508 page print 4 times as many dots for each 1, unless we tell it that's better quality when printed out as A6

The PDF file and page size will be the same if the images are both set as A4 
It is the pixels per page width that sets the nominal dpi.
thus in this case both can be extracted equally at any dpi

Admittedly extracting at 300 dpi would make scalar sense but it is not meaningful in terms of the source inputs nor quality.

**Comment by GitHubRulesOK** [comment] 2023-03-30 02:17
@kjk 
unless you consider showing nominal ppi per image or logo or xobject or vector matrix
I suggest this is a non runner for PDF and for images is a duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1394

**Closed by GitHubRulesOK** 2023-03-30 02:17 UTC
