### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by venkat2305** [sumatrapdfreader/sumatrapdf#2973] opened 2022-09-20 18:08 UTC
can you please add dark mode to the app. it reduces the stress on my eyes. when i say dark mode, i mean for the UI of the app, not the content of pdfs. thank you.

**Comment by GitHubRulesOK** [comment] 2022-09-20 19:45
this is covered by dozens of duplicates so closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/743

**Closed by GitHubRulesOK** 2022-09-20 19:45 UTC
