### ISSUE TITLE
Some accent charactes in free text annotations are not rendered properly

### ISSUE THREAD

**Issue by kelesi** [sumatrapdfreader/sumatrapdf#3504] opened 2023-05-19 10:18 UTC
Some Slovak/Czech accent characters (ěřŕĺňčťĚŘŔĹŇČŤ) are rendered only as a dot in free text annotations:
![screenshot](https://github.com/sumatrapdfreader/sumatrapdf/assets/13762520/7c027601-8eb7-4d25-994d-c6e6d2b83fc4)

It's also printed this wrong way.

**Comment by GitHubRulesOK** [comment] 2023-05-19 12:32
yes a known generic problem with non Adobe "Standard base14 fonts" characters

**Comment by kelesi** [comment] 2023-05-19 14:59
Any solution/workaround to this? I just created an empty PDF from an empty new document in LibreOffice Draw.
The rendering works fine in Firefox, Adobe Reader DC, Foxit Reader, but does not work in Sumatra and Chromium based web browsers.

**Comment by GitHubRulesOK** [comment] 2023-05-19 17:31
no real workaround as EDGE with Acrobat is worse than MuPDF which does ay least show dots 
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/d2032462-ed80-46d2-a0fd-e76e3b70f470)

**Comment by GitHubRulesOK** [comment] 2023-10-23 03:45
closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1671
MuPDF only supports PDF Standard 14 fonts in comments.

**Closed by GitHubRulesOK** 2023-10-23 03:45 UTC
Labels: annotations
