### ISSUE TITLE
Command <Ctrl> + Left Mouse - select text or image don't work in ePub files

### ISSUE THREAD

**Issue by filchef** [sumatrapdfreader/sumatrapdf#1456] opened 2020-02-13 19:44 UTC
Command **<Ctrl> + Left Mouse** -  _select text or image_ don't work in ePub files 
Windows 10 Home 64-bit - BG
Sumatra **v3.1.2 64-bit**

**Comment by GitHubRulesOK** [comment] 2020-02-13 19:59
Ctrl + Left mouse does not actually select text or images but an area that can include them both so it can be used by Print or Zoom

Many commands like zoom search etc. are not designed to work whilst text and images are in the E-Book reflowing user interface 
They were written for the FixedPageUI therefore to use them the e-bookUI advanced setting needs to be changed from false to true

**Comment by filchef** [comment] 2020-02-13 21:57
Thank you very match

**Comment by GitHubRulesOK** [comment] 2020-07-06 12:56
Since copy works in FixedPageUI an the initial issue was in ebookUI I am closing as a duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/284

**Closed by GitHubRulesOK** 2020-07-06 12:56 UTC
Labels: ebook
