### ISSUE TITLE
Crash while zooming into a file.

### ISSUE THREAD

**Issue by anwarmou** [sumatrapdfreader/sumatrapdf#1952] opened 2021-05-21 02:19 UTC
I had several PDFs open for several days and upon zooming in on a newly opened file it crashed!
Here is a link to the crash report: https://gist.github.com/anwarmou/0ea237823758c2ac91ff9b5dd200ecb1

**Comment by kjk** [comment] 2021-05-21 04:37
```
Ver: 3.2 64-bit
Git: fc8f35a2d0581735ea361990dc65c674b3cd2dcb (https://github.com/sumatrapdfreader/sumatrapdf/commit/fc8f35a2d0581735ea361990dc65c674b3cd2dcb)
OS: Windows 10 build 19042 64-bit

Exception: C0000005 ACCESS_VIOLATION
Faulting IP: 00007FFC1BADDDAA 01:000000000003CDAA libmupdf.dll!update_ctm_for_subarea+0x4a C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\image.c+633
Fault reading address 0000000000000010

Crashed thread:
00007FFC1BADDDAA 01:000000000003CDAA libmupdf.dll!update_ctm_for_subarea+0x4a C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\image.c+633
00007FFC1BADE62E 01:000000000003D62E libmupdf.dll!fz_get_pixmap_from_image+0x64e C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\image.c+841
00007FFC1BADCD19 01:000000000003BD19 libmupdf.dll!fz_unblend_masked_tile+0x89 C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\image.c+183
00007FFC1BADD733 01:000000000003C733 libmupdf.dll!fz_decomp_image_from_stream+0x5e3 C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\image.c+458
00007FFC1BADDBA9 01:000000000003CBA9 libmupdf.dll!compressed_image_get_pixmap+0x2f9 C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\image.c+577
00007FFC1BADE3E9 01:000000000003D3E9 libmupdf.dll!fz_get_pixmap_from_image+0x409 C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\image.c+791
00007FFC1BB0961C 01:000000000006861C libmupdf.dll!fz_draw_fill_image+0x6cc C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\draw-device.c+1734
00007FFC1BAC4B37 01:0000000000023B37 libmupdf.dll!fz_fill_image+0x97 C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\device.c+337
00007FFC1BAE3B5E 01:0000000000042B5E libmupdf.dll!fz_run_display_list+0xdee C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\list-device.c+1800
00007FF643C88149 01:0000000000187149 sumatrapdf.exe!EnginePdf::RenderPage+0x439 C:\Users\kjk\src\sumatrapdf\src\EnginePdf.cpp+1191
00007FF643BF5ABC 01:00000000000F4ABC sumatrapdf.exe!RenderCache::RenderCacheThread+0x28c C:\Users\kjk\src\sumatrapdf\src\RenderCache.cpp+634
```

**Comment by kjk** [comment] 2021-05-27 07:36
This could be fixed by mupdf updates.

Please try to reproduce with latest daily build from https://www.sumatrapdfreader.org/dailybuilds

If it happens again, please provide the file and detailed reproduction steps.

**Comment by GitHubRulesOK** [comment] 2021-05-27 23:52
@kjk 
uncertain (I have not a clue) if it is fixed by updates, however this pattern looks like a dupe of https://github.com/sumatrapdfreader/sumatrapdf/issues/1883

**Comment by kjk** [comment] 2021-05-28 00:18
Yes, same as #1883

**Closed by kjk** 2021-05-28 00:18 UTC
