### ISSUE TITLE
tab-switch hotkey: use <shift+h> and <shift+L>

### ISSUE THREAD

**Issue by heyuanpi** [sumatrapdfreader/sumatrapdf#652] opened 2016-11-01 06:50 UTC
Hi,
Could you please leave a configuration to config tab-switch hotkey?
It's better to use  <shift+h> to switch to left tab, and <shift+L> to switch to right tab. 
This is more easy compared to default <ctrl+tab> and <shift+ctrl+tab>.

**Comment by kjk** [comment] 2016-11-01 18:20
What other Windows software uses such shortcuts?

Usually we want to follow the conventions of the platform.

**Comment by heyuanpi** [comment] 2016-11-02 00:41
Hi kjk,

I mean, may be you can leave an option for us to config this shortcuts.   
Of course you have your default settings.

sumutra pdf fans.

**Comment by GitHubRulesOK** [comment] 2021-08-02 01:56
Shit H and L are currently assigned
Classing as Duplicate of other requests to change / customise all key values to something else

**Closed by GitHubRulesOK** 2021-08-02 01:56 UTC
