### ISSUE TITLE
Rightmost tab close button overlaps with tab navigation buttons?

### ISSUE THREAD

**Issue by Wuhao1627003** [sumatrapdfreader/sumatrapdf#1224] opened 2019-11-07 06:10 UTC
Now I can't close the rightmost tab anymore... Whenever I mouse over the close button it overlaps with the top-layer tab navigation buttons...
![image](https://user-images.githubusercontent.com/25204397/68364203-42755b00-00fb-11ea-81d4-cd94a3c911fe.png)

**Comment by SumatraPeter** [comment] 2019-11-07 22:53
It's a known issue. Sumatra exhibits this it whenever Windows' scaling level is set to more than 100% and there are a large number of open tabs.

@kjk: Both this one and #1094 are duplicates of #447.

**Comment by kjk** [comment] 2019-11-07 22:57
Closing as duplicate of #447

**Closed by kjk** 2019-11-07 22:57 UTC
