### ISSUE TITLE
Listing the opened documents

### ISSUE THREAD

**Issue by puraminy** [sumatrapdfreader/sumatrapdf#579] opened 2016-08-03 12:11 UTC
However I can see the list of opened documents via tabs, but if a menu bar (like windows) or a sidebar listed all the opened documents with the complete filename, I could faster find the document I want to read.

**Comment by kjk** [comment] 2017-06-11 22:34
Also mentioned in https://forum.sumatrapdfreader.org/t/feature-request-list-all-tabs/131

**Comment by SumatraPeter** [comment] 2017-06-12 22:08
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/371

**Comment by kjk** [comment] 2017-06-12 23:21
Closing as duplicate.

**Closed by kjk** 2017-06-12 23:21 UTC

**Comment by andzi** [comment] 2017-10-21 11:39
why it's closed - what decision?
 Assignees: No one assigned
Labels: None yet
Projects: None yet
Milestone: No milestone

**Comment by SumatraPeter** [comment] 2017-10-21 18:41
It's closed because it's a duplicate of an existing issue. What's so hard to understand about that?

"No one assigned"? Just [how many developers](https://github.com/orgs/sumatrapdfreader/people) do you think are working on this program?

"No milestone" because that's the fate of almost all the issues here (438 open as of now). From what I've observed, kjk doesn't seem to have much free time (or even inclination perhaps) to implement oft-requested features. Mostly the commits seem to be bug fixes and minor tweaks, with no major new feature implemented in quite some time. The app is definitely fine as-is - light-weight and stable, but after zeniko left active development seems to have slowed down a lot. This is just my opinion about the state of things of course, but I do wish I was a coder who could implement some of the long-standing useful ideas (without making the app bloated).
