### ISSUE TITLE
Feature request: Deferred/lazy loading of documents

### ISSUE THREAD

**Issue by pszturmaj** [sumatrapdfreader/sumatrapdf#3011] opened 2022-10-07 16:15 UTC
Similar feature request on Notepad++ repo: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12019

Basically, when you have many documents opened and later open SumatraPDF, for example just to quickly peek some PDF - you need to wait until all of them are loaded. Some of them may be on LAN shares or on HDDs that are put to sleep mode (in the latter case you would need to wait until disks spin up).

Instead, it may be desirable to only load the tab list during startup and load documents when corresponding tab is clicked.

**Comment by GitHubRulesOK** [comment] 2022-10-07 16:55
duplicate of #3009

**Closed by GitHubRulesOK** 2022-10-07 16:55 UTC
