### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by amboris** [sumatrapdfreader/sumatrapdf#2878] opened 2022-08-18 08:48 UTC
https://gist.github.com/amboris/918ffd6366d7fddd10f4e2450297bd07
[CI_en.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9371977/CI_en.pdf)

**Comment by GitHubRulesOK** [comment] 2022-09-13 18:38
looks like the highlights issue 

Highlight annotations have no Rect property

**Comment by GitHubRulesOK** [comment] 2022-09-27 03:34
Should be fixed in 3.5.15244+ (see note)
likely caused by annotation instability

Note:- current pre-release is 3.5.15249 and on first run MAY crash for a different reason see https://github.com/sumatrapdfreader/sumatrapdf/issues/2984

**Closed** 2022-10-08 02:20 UTC
