### ISSUE TITLE
Low Res Icons

### ISSUE THREAD

**Issue by Xashyar** [sumatrapdfreader/sumatrapdf#1097] opened 2018-11-14 16:57 UTC
![image](https://user-images.githubusercontent.com/34171942/48498456-8a94d100-e84b-11e8-860e-3591121fe8ca.png)

is them's being low-fi intentional?

**Comment by GitHubRulesOK** [comment] 2018-11-14 21:11
Sort of, they were designed as pixels when screens were low-dpi thus looked OK
There have been many willing to request a change however none of them seem willing to take up the challenge to convert the code to SVG.

@kjk I suggest this is effectively duplicate of your https://github.com/sumatrapdfreader/sumatrapdf/issues/734

**Comment by kjk** [comment] 2019-03-24 19:04
closing as dup of #734

**Closed by kjk** 2019-03-24 19:04 UTC
