### ISSUE TITLE
v3.4.13925 Git-5ed1a7039 - Crash - Access Violation then try first load ePUB file and sumatrapdfcache not exist or empty.

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#2076] opened 2021-07-29 13:59 UTC
v3.4.13925 Git-5ed1a7039 is crash's (Access Violation) then try first load ePUB file and sumatrapdfcache not exist or empty. [**crash log archive**](https://www.upload.ee/files/13350887/crashinfo_v3.4.13925_Git-5ed1a7039.zip.html) included files:

sumatrapdfcrash.dmp
internals-en.epub
SumatraPDF.exe
libmupdf.map
SumatraPDF.map
SumatraPDF-dll.map
libmupdf.pdb
SumatraPDF.pdb
SumatraPDF-dll.pdb
readme.txt
sumatrapdfcrash.txt
version.txtsumatrapdfcrash.dmp
internals-en.epub
SumatraPDF.exe
libmupdf.map
SumatraPDF.map
SumatraPDF-dll.map
libmupdf.pdb
SumatraPDF.pdb
SumatraPDF-dll.pdb
readme.txt -- _is short description_
sumatrapdfcrash.txt
version.txt

![crash](https://user-images.githubusercontent.com/906886/127505274-641ca35b-0bb5-4cac-89f6-0fd52a2dbbc2.png)

**Comment by VictorVG** [comment] 2021-07-30 09:22
Possible GetMessage() have call like `GetMessage(nullptr, nullptr, 0, 0)` is typo then Win32API [**GetMessage()**](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmessage) 
``
BOOL GetMessage(
  LPMSG lpMsg,   // pointer to [**MSG**](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-msg) structure
  HWND  hWnd, // handle to the window whose messages or NULL
  UINT  wMsgFilterMin,  // Integer
  UINT  wMsgFilterMax // Integer
);
``

**Comment by kjk** [comment] 2021-07-30 09:48
I can't reproduce this crash. Could you provide step-by-step instructions?

I opened internals-en.epub and scrolled through the whole file.

Also, `sumatrapdfcrash.txt` in your crash dumps never have symbols, which makes them not very useful. You must be doing something weird with deleting .pdb files that sumatra downloads or moving files or disabling internet access. Please make sure that symbols are downloaded and callstacks in `symatrapdfcrash.txt` are properly symbolicated.

What I mean:
```
Crashed thread:
000000013F3E805B 01:000000000015705B sumatrapdf.exe
000000013F479A38 01:00000000001E8A38 sumatrapdf.exe
000000013F51DEFD 01:000000000028CEFD sumatrapdf.exe
```

This is bad. There should be names of functions that crashed, not just `sumatrapdf.exe`.

**Comment by GitHubRulesOK** [comment] 2021-07-30 11:27
@VictorVG 
Your build SumatraPDF 12,599 KB   < != than KJK build 12,618 KB
perhaps ? =  your build tool not adding - some linking for pdb communications

**Comment by VictorVG** [comment] 2021-07-30 11:32
I figured out what was happening - my test suite contained a configuration file where there were obsolete parameters - and it crashes on them. I have removed them now - we do not fall at startup, but maybe it makes sense to make a simple protection against such errors?

diff:
```
--- ./OLD/false/SumatraPDF-settings.txt	Thu Feb 27 13:17:31 2020
+++ ./NEW/false/SumatraPDF-settings.txt	Thu Jul 29 16:22:37 2021
@@ -1,4 +1,4 @@
-# For documentation, see https://www.sumatrapdfreader.org/settings3.2.html
+# For documentation, see https://www.sumatrapdfreader.org/settings/settings3-4.html
 
 MainWindowBackground = #80fff200
 EscToExit = false
@@ -13,6 +13,7 @@
 	SelectionColor = #f5fc0c
 	WindowMargin = 2 4 2 4
 	PageSpacing = 4 4
+	HideScrollbars = false
 ]
 EbookUI [
 	FontName = Georgia
@@ -27,7 +28,9 @@
 	CbxMangaMode = false
 ]
 ChmUI [
-	UseFixedPageUI = true
+	UseFixedPageUI = false
+]
+SelectionHandlers [
 ]
 ExternalViewers [
 ]
@@ -46,9 +49,10 @@
 	HighlightColor = #6581ff
 	HighlightPermanent = false
 ]
-AnnotationDefaults [
+Annotation [
 	HighlightColor = #ffff60
-	SaveIntoDocument = true
+	TextIconColor = #ffff00
+	TextIconType =
 ]
 CustomScreenDPI = 0
 
@@ -67,6 +71,7 @@
 ShowToc = true
 SidebarDx = 198
 TocDy = 0
+TreeFontSize = 0
 ShowStartPage = true
 UseTabs = true
 
--- ./OLD/true/SumatraPDF-settings.txt	Thu Feb 27 11:43:44 2020
+++ ./NEW/true/SumatraPDF-settings.txt	Thu Jul 29 16:22:26 2021
@@ -1,4 +1,4 @@
-# For documentation, see https://www.sumatrapdfreader.org/settings3.2.html
+# For documentation, see https://www.sumatrapdfreader.org/settings/settings3-4.html
 
 MainWindowBackground = #80fff200
 EscToExit = false
@@ -13,6 +13,7 @@
 	SelectionColor = #f5fc0c
 	WindowMargin = 2 4 2 4
 	PageSpacing = 4 4
+	HideScrollbars = false
 ]
 EbookUI [
 	FontName = Georgia
@@ -24,11 +25,13 @@
 ComicBookUI [
 	WindowMargin = 0 0 0 0
 	PageSpacing = 4 4
-	CbxMangaMode = false
+	CbxMangaMode = true
 ]
 ChmUI [
 	UseFixedPageUI = true
 ]
+SelectionHandlers [
+]
 ExternalViewers [
 ]
 ShowMenubar = true
@@ -46,9 +49,10 @@
 	HighlightColor = #6581ff
 	HighlightPermanent = false
 ]
-AnnotationDefaults [
+Annotation [
 	HighlightColor = #ffff60
-	SaveIntoDocument = true
+	TextIconColor = #ffff00
+	TextIconType =
 ]
 CustomScreenDPI = 0
 
@@ -67,6 +71,7 @@
 ShowToc = true
 SidebarDx = 198
 TocDy = 0
+TreeFontSize = 0
 ShowStartPage = true
 UseTabs = true
```
Sorry, is my error :(

**Comment by GitHubRulesOK** [comment] 2021-07-30 11:41
@VictorVG 
Normally once "running" after start then SumatraPDF updates settings to flush old (out of date) entries
Can be a problem with kiosk locked/replaced/read only SumatraPDF-settings.txt or restrictions.ini

**Comment by VictorVG** [comment] 2021-07-30 12:23
Yeah, it's understandable - I have these files in the SumatraPDF_testkit.7z archive and the test script unpacks the desired option with each test pass. I corrected this "corner", though I caught a fall when I hurried to enter the password in the process of opening files before its SumatraPDF request - before this trick took place, well, now I will know that it is impossible and wait for the download to complete ...

test's run this script:
```
@echo off
setlocal enableextensions
for /f "tokens=1" %%A in (SumatraPDF\version.txt) do (set vr=%%A)
set vrs=%vr:~1,3%
set wd=%cd%
chdir /d %wd%  > nul
if "%~1"=="test" call :test
start /i spdftest test > nul
exit
:test
setlocal enableextensions
set wd=%cd%
chdir /d %wd% > nul
cp -f %DEVEL%\SumatraPDF\Tools\SumatraPDF_testkit.7z ./ > nul
7z x SumatraPDF_testkit.7z -aoa -y -r > nul
rm -f SumatraPDF_testkit.7z > nul
cp -f tcfg/true/SumatraPDF-settings.txt Тест/SumatraPDF/ > nul
cp -f SumatraPDF/SumatraPDF-%vrs%.* Тест/SumatraPDF/ > nul
mv -f Тест/SumatraPDF/SumatraPDF-%vrs%.exe Тест/SumatraPDF/SumatraPDF.exe > nul
7z e SumatraPDF\SumatraPDF-%vrs%-dbg-x86.zip -oТест\SumatraPDF SumatraPDF.* > nul
mv -f SumatraPDF.* Тест/SumatraPDF/ > nul
start /wait /d Тест\SumatraPDF Тест\SumatraPDF\SumatraPDF.exe > nul
if exist Тест\SumatraPDF\crashinfo (cp -f Тест\SumatraPDF\crashinfo\sumatrapdfcrash.dmp %wd%\sumatrapdfcrash-x86-1.dmp > nul & cp -f Тест\SumatraPDF\crashinfo\sumatrapdfcrash.txt %wd%\sumatrapdfcrash-x86-1.txt > nul )
rm -fR Тест/SumatraPDF/sumatrapdfcache > nul
cp -f tcfg/false/SumatraPDF-settings.txt Тест/SumatraPDF/ > nul
start /wait /d Тест\SumatraPDF Тест\SumatraPDF\SumatraPDF.exe > nul
if exist Тест\SumatraPDF\crashinfo (cp -f Тест\SumatraPDF\crashinfo\sumatrapdfcrash.dmp %wd%\sumatrapdfcrash-x86-2.dmp > nul & cp -f Тест\SumatraPDF\crashinfo\sumatrapdfcrash.txt %wd%\sumatrapdfcrash-x86-2.txt > nul )
rm -fR Тест/SumatraPDF/sumatrapdfcache > nul
rm -f Тест/SumatraPDF/SumatraPDF.exe Тест/SumatraPDF/SumatraPDF.map Тест/SumatraPDF/SumatraPDF.pdb > nul
cp -f tcfg/true/SumatraPDF-settings.txt Тест/SumatraPDF/ > nul
cp -f SumatraPDF/SumatraPDF-%vrs%-x64.* Тест/SumatraPDF/ > nul
mv -f Тест/SumatraPDF/SumatraPDF-%vrs%-x64.exe Тест/SumatraPDF/SumatraPDF.exe > nul
7z e SumatraPDF\SumatraPDF-%vrs%-dbg-x64.zip -oТест\SumatraPDF SumatraPDF.* > nul
start /wait /d Тест\SumatraPDF Тест\SumatraPDF\SumatraPDF.exe > nul
if exist Тест\SumatraPDF\crashinfo (cp -f Тест\SumatraPDF\crashinfo\sumatrapdfcrash.dmp %wd%\sumatrapdfcrash-x64-1.dmp > nul & cp -f Тест\SumatraPDF\crashinfo\sumatrapdfcrash.txt %wd%\sumatrapdfcrash-x64-1.txt > nul )
rm -fR Тест/SumatraPDF/sumatrapdfcache > nul
cp -f tcfg/false/SumatraPDF-settings.txt Тест/SumatraPDF/ > nul
start /wait /d Тест\SumatraPDF Тест\SumatraPDF\SumatraPDF.exe > nul
if exist Тест\SumatraPDF\crashinfo (cp -f Тест\SumatraPDF\crashinfo\sumatrapdfcrash.dmp %wd%\sumatrapdfcrash-x64-2.dmp > nul & cp -f Тест\SumatraPDF\crashinfo\sumatrapdfcrash.txt %wd%\sumatrapdfcrash-x64-2.txt > nul )
rm -fR tcfg Тест test-kit.txt testcase_encrypt.txt > nul
exit
```

**Comment by GitHubRulesOK** [comment] 2021-07-30 12:51
@VictorVG 
you can have minimal Sumatra-settings.txt 

So can have stored just password hashes and other [section] personal preferences #
then SumatraPDF **"should"** (no guaranty, this is unsupported "feature") build all the other defaults including
version header and trailer "# Settings after this line have not been recognized by the current version"

**FULL** SumatraPDF-settings.txt file before open a file
```
FixedPageUI [
	HideScrollbars = true
]
```
**PART** settings.txt after open a file, defaults are added (does not include GradientColors, so I can add that into my template.txt)
```
....

FixedPageUI [
	TextColor = #000000
	BackgroundColor = #ffffff
	SelectionColor = #f5fc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
	HideScrollbars = true
]

....

```

so you can grep (findstr) "# Settings " for testing that after starting with first dummy.pdf file

**Comment by VictorVG** [comment] 2021-07-30 14:12
Of course you can, but the test script provides for fixed settings for the reproducibility of the result, and "pitfalls" like the one with which I was fiddling with it perfectly.

**Comment by kjk** [comment] 2021-07-30 20:40
Different / corrupted settings file shouldn't cause a crash. I copied your `false/SumatraPDF-settings.txt` and started sumatra and it didn't crash for me.

However, I just fixed a crash that would happen when opening multiple .epub files at the same time, which could be this crash as well.

The fix is: https://github.com/sumatrapdfreader/sumatrapdf/commit/cf36f30e5128a84084a3cc148c7d3b5a17416470

Could you re-test when the build finishes and see if this crash is still happening.

**Comment by GitHubRulesOK** [comment] 2021-07-30 21:15
@kjk 
not trying to be picky, just for my understanding, a mention that in the past some **bad** settings.txt with some file types have at some times pulled SumatraPDF down, your reassurance then was it would not happen in a release version https://github.com/sumatrapdfreader/sumatrapdf/issues/1899
however I note here we are discussing pre-release

**Comment by kjk** [comment] 2021-07-30 21:22
https://github.com/sumatrapdfreader/sumatrapdf/issues/1899 is different from what I'm saying here. There the settings file was valid but Sumatra didn't handle one of the values.

What I'm saying here is that syntactically invalid settings file (or one with old settings) shouldn't crash sumatra. If it does, I would like to know.

**Comment by VictorVG** [comment] 2021-07-31 04:22
@kjk 

Big thanks! I try test v3.4.13938 Git-71b203c07 - crash then use my old test config - none, time for open any file in UI - -> 0 s (in to v3.4.13933 this time is long), work success. Exclude only one CHM file "GCC Manual.chm" created MetaProduct Offilne Explorer with non-standard external HTML links like `<a href = "..\..\www.gnu.org .."` and they probably cause an error in parsing HTML code:

![1](https://user-images.githubusercontent.com/906886/127728419-c438ec6e-7bbc-4c56-8bac-9579e8d5a97e.png)

then try load this file. ??? Oher CHM, include standard Windows HTML Help like NSIS.chm (help for NSIS v3.0.7) have TOC work success.

**Comment by kjk** [comment] 2021-07-31 19:49
I can't tell from the comment, is the crash fixed? If yes, please close the issue.

If there are other issues then please open a new issue with step-by-step repro instructions.

**Comment by GitHubRulesOK** [comment] 2021-07-31 20:14
@kjk reading between lines he seems to only have one fiail in his test suite

"one CHM file "GCC Manual.chm" created MetaProduct Offilne Explorer with non-standard external HTML links like <a href = "..\..\www.gnu.org .." and they probably cause an error in parsing HTML code:"

@VictorVG 
is it just 1 file = **problem links** and **no crash** ? 
IF just one can you retest with new compile and is links fail open a **new issue**

**Comment by VictorVG** [comment] 2021-08-01 06:33
@kjk 
@GitHubRulesOK 

Crash is fixed, but the problem file uses non-standard markup in the W3C HTML 5.1 style, allowing for any gag on the part of the page author. I have seen such files more than once - take out the saints, markup to someone that comes to mind, in /dev/>nul it. ; (

**Comment by GitHubRulesOK** [comment] 2021-08-01 11:47
@VictorVG 
I am closing as 
**Crash fixed**
I have many bad .htm / mhtm /html files that need separate issue as MuPDF may not handle / render
 then SumatraPDF crash on file types by contents
needs **new issues by type of fail**
otherwise too many variables

**Closed by GitHubRulesOK** 2021-08-01 11:47 UTC

**Comment by VictorVG** [comment] 2021-08-02 06:42
Ok! Such an incorrect HTML file I have one, the rest has long been corrected, so I can't collect the experimental base for writing a correct engineering report at the moment, but I don't want to write a pacifier. This and without me in life enough. :)

**Comment by GitHubRulesOK** [comment] 2021-08-02 10:56
@VictorVG 
If "GCC Manual.chm" is a typical problem file
just write **one line** 
**"Here is my problem file.chm"**
include the one file as a **zip in new issue**

**Comment by VictorVG** [comment] 2021-08-02 14:08
OK! but today I find only this file...
