### ISSUE TITLE
Problems with printing colored PDFs

### ISSUE THREAD

**Issue by Matt-17** [sumatrapdfreader/sumatrapdf#1172] opened 2019-06-04 15:34 UTC
I bought a new Brother HL-L3230CDW Color Laser Printer (which is working fine). 
When I print with Sumatra (v3.1.2 64-bit) every black line hast incorrect color calibration (I can see red and yellow lines beside the black line). If I print with Edge for example, this does not happen and every letter is pretty clear. 
I did not notice this problem with my old b/w printer. 
This does not happen when I print in b/w single color mode.

**Comment by jtflynnz** [comment] 2019-10-15 17:52
Also having this issue, blacks are printing off-color (purplish on our office's new Kyocera TASKAlfa 5053ci); printing in B/W or Automatic solves this issue for us, but for some reason printing in Color causes blacks to print incorrectly. Can verify that this behavior is unique to SumatraPDF (as other programs do not seem to reproduce this issue testing with the same files).

**Comment by SumatraPeter** [comment] 2019-10-15 19:16
@jtflynnz: Try printing with the older portable version 3.0 (download SumatraPDF-3.0.zip from [here](https://www.sumatrapdfreader.org/download-prev.html)) and see if that helps.

**Comment by jtflynnz** [comment] 2020-02-27 18:56
After a further adventure in dealing with this new printer of ours, the support team finally resolved various issues our users had by resetting the printer color profile. While the behavior was apparently worked around by other programs' default configurations (ie using automatic color settings), our issue was not *instigated* by Sumatra

**Comment by GitHubRulesOK** [comment] 2021-08-02 03:07
Closing as without sample it is difficult to prove However several factors are involved.

The secondary issue can indicate mismatched ICC profiles which SumatraPDF may not be aware of.

The OP issue is almost certainly a by product of Print as Image due to the inflationary nature of higher resolution anti-aliasing and can be seen in some cases on screen when zoomed in. The effect is generally not a problem on most inkjet printers but by its nature unavoidable in SumatraPDF hand off to Windows and its Coloured LaserJet drivers.

**Closed by GitHubRulesOK** 2021-08-02 03:07 UTC
