### ISSUE TITLE
Installer is unable to make SumatraPDF the default PDF reader

### ISSUE THREAD

**Issue by ImportTaste** [sumatrapdfreader/sumatrapdf#1222] opened 2019-10-28 02:58 UTC
Compiled https://github.com/sumatrapdfreader/sumatrapdf/commit/3dbcb8484c945084fee08621148e5de5ace71297 with VS2019 on Windows 10 on the Release x64 configuration.

Due to an unrelated Windows bugfix I needed, I'm on the Release Preview ring (18363 rather than 18362) but I've had this issue in the past so that is certainly not to blame.

When installing, there is an Options button, and within it you can select the option to make it your default PDF reader, like so:

![image](https://user-images.githubusercontent.com/53661808/67648649-57383e80-f904-11e9-97ac-08ef197b9884.png)

However, this does not work, and the program will still ask you if you want to make it your default PDF reader when you first launch it.

**Suggestion:** Disable the option and render it invisible until the installer's method works as reliably as the program's.

**Comment by kjk** [comment] 2019-10-28 03:03
Yeah, this needs to be updated. 

In Windows 10 the program can no longer just set itself as default program by changing the registry. Now the program needs to launch settings and have the user change  the default association.

**Comment by SumatraPeter** [comment] 2019-10-28 20:05
Related/duplicate: #604, and perhaps others since this has been a problem ever since Win10 was released.

It's also why we added [these instructions](https://www.sumatrapdfreader.org/docs/Setting-Sumatra-as-default-PDF-reader.html) to the documentation. Unfortunately Win10 (and the Settings app in particular) is such a moving target that many of the steps listed are incorrect now.

**Comment by SumatraPeter** [comment] 2019-10-28 23:24
Related/duplicates: #438, #589, #604, #615, #862, #883, #1074 and perhaps others as well since this has been a problem ever since Win10 was released.

It's also why we added [these instructions](https://www.sumatrapdfreader.org/docs/Setting-Sumatra-as-default-PDF-reader.html) to the documentation. Unfortunately Win10 (and the Settings app in particular) is such a moving target that many of the steps listed are incorrect now.

**Comment by ImportTaste** [comment] 2019-10-30 04:10
I did notice duplicates, but more for the program itself, not for the installer - plus I figured the current maintainer might not know if this is still an issue considering how many changes there's been in both Windows and SumatraPDF and the age of those issues.

While I'm on the subject, I recommend applying this bot to your repo and changing the comment it leaves on old issues to indicate that a reply should be left if the issue has not been fixed yet: https://github.com/marketplace/stale

**Comment by SumatraPeter** [comment] 2019-10-30 18:54
Thanks, but the installer and program both definitely need to be updated to comply with Win10's requirements.

> I figured the current maintainer might not know if this is still an issue considering how many changes there's been in both Windows and SumatraPDF and the age of those issues.

kjk (Krzysztof) is the original developer and pretty much the only one still around. As you can see by the age of the issues though, not sure when he'll get the time to actually fix this.

**Comment by GitHubRulesOK** [comment] 2019-11-16 11:25
@kjk there should be two open issues with file association
1) range of file types supported during install and
2) inability to force default association
 this one is a duplicate of the later https://github.com/sumatrapdfreader/sumatrapdf/issues/615#

**Comment by SumatraPeter** [comment] 2019-11-16 21:25
@kjk: Re. the default association issue, if this is to be kept as the master bug then all the others I've linked to above that are still open can probably be closed.

**Comment by kjk** [comment] 2019-11-18 00:35
This is now tracked by #1248

**Closed by kjk** 2019-11-18 00:35 UTC
