### ISSUE TITLE
Printing problem

### ISSUE THREAD

**Issue by Giuseppe-1962** [sumatrapdfreader/sumatrapdf#1276] opened 2019-11-29 16:11 UTC
Good Morning,
Sorry for my english, i have a problem printing pdf with a MFC Sharp 3060N in Colour mode.
Sumatra is located in a folder on the server, all the clients print normally only one present the problem.
If i print in another printer or in the same printer but in B/W the prints are good.
If i use another pdf reader in the client the print is normally.
But if i print in the MFC Sharp 3060N in colour mode the print is not good (as you can see in the sample attached)
It's a very strange situation and it makes me crazy.

Can tou help me?
Thank you
![Sample](https://user-images.githubusercontent.com/58338321/69880771-2d8b8200-12cb-11ea-97b7-9547d95d3801.JPG)

**Comment by SumatraPeter** [comment] 2019-11-29 17:18
With certain Xerox printer drivers at least turning off "Print optimization" fixes such issues, so do check if your printer driver has such an option as well buried somewhere.

Also be sure to test the latest [daily build](https://www.sumatrapdfreader.org/dailybuilds.html) to see if things have been improved. You can use the portable release to test if you don't want to mess with your existing installed version of Sumatra.

**Comment by GitHubRulesOK** [comment] 2019-11-29 19:10
@kjk unfortunatly seems to be another duplicate of the problems in https://github.com/sumatrapdfreader/sumatrapdf/issues/919# 

@Giuseppe-1962 the other suggestion in such cases is to see if the print driver may work better with the non image mode that was available in old 32bit version 3.0 Zip file: SumatraPDF-3.0.zip is about 10th item down from https://www.sumatrapdfreader.org/download-prev.html

**Comment by GitHubRulesOK** [comment] 2020-02-29 21:13
Consolidating as similar issue to https://github.com/sumatrapdfreader/sumatrapdf/issues/919

**Closed by GitHubRulesOK** 2020-02-29 21:13 UTC
