### ISSUE TITLE
NightMode

### ISSUE THREAD

**Issue by srbarros** [sumatrapdfreader/sumatrapdf#770] opened 2017-04-06 23:38 UTC
What about to have a night mode, with the background collor in dark and the document text in bright collors, to improve reading confort? I think it will be a nice feature!

**Comment by srbarros** [comment] 2017-04-06 23:50
To be usefull, this night feature must be on/off without restart sumatra.

**Comment by SumatraPeter** [comment] 2017-04-07 17:37
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/437

Tip: A quick search f the [GitHub issues list](https://github.com/sumatrapdfreader/sumatrapdf/issues) and [SumatraPDF forum](http://forums.fofou.org/sumatrapdf) is always recommended first. Adding duplicate issues hardly helps, especially with so many pending.

**Comment by GitHubRulesOK** [comment] 2019-11-25 00:05
@kjk there are several issues about tabs theming but this common request for "night mode" is a dupe as @SumatraPeter suggests of #437

**Comment by GitHubRulesOK** [comment] 2020-02-05 13:37
Closing as duplicates #437

**Closed by GitHubRulesOK** 2020-02-05 13:37 UTC
