### ISSUE TITLE
Incorrectly displayed a PDF file on SumatraPDF Portable x86 & x64 v3.2.10638

### ISSUE THREAD

**Issue by doquan0** [sumatrapdfreader/sumatrapdf#762] opened 2017-03-23 14:19 UTC
Hi SumatraPDF's developers,

I have attached a PDF file which is displayed incorrectly (compared with Adobe Reader v11) on SumatraPDF Portable x86 & x64 of both versions v3.2.10638 & v3.1.2

(The comparision is also attached as an image file .jpg)
![compare](https://cloud.githubusercontent.com/assets/22103247/24251890/3e3a66e2-100e-11e7-888f-41659932dc4f.jpg)

Could you please have a look at this bug?
[test.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/864982/test.pdf)

**Comment by VictorVG** [comment] 2017-03-23 21:40
This is MuPDF problem's - GSView 6.00 + GhostScript 9.20 also display this document incorrectly:

![gsview60](https://cloud.githubusercontent.com/assets/906886/24271497/6d780498-102a-11e7-8abe-71b5f40cb2d5.png)

**Comment by doquan0** [comment] 2017-03-24 07:49
I found the forums of MuPDF and already submitted a bug report there. Here is the link
[](https://bugs.ghostscript.com/show_bug.cgi?id=697682)

**Comment by VictorVG** [comment] 2017-03-24 13:40
Ok! This is a scanned page from the book saved in JBIG2/JPEG2000, and not very small dimensions - 10548x15594 pixels. You just open this file in an ASCII text editor and almost at the very beginning you will see:

```
<<
/ BitsPerComponent 1
/ ColorSpace / DeviceGray
/ Filter [/ JBIG2Decode]
/ Height 15594
/ ImageMask false
/ Interpolate true
/ Length 106051
/ Subtype / Image
/ Type / XObject
/ Width 10548
>>
```
And with black and white JBIG2/JP2k/JPEG2000 this size and many graphic editors will have problems caused by patent restrictions.

Also this page have book title:

Offset [string: col] 00::00:

![1](https://cloud.githubusercontent.com/assets/906886/24295810/8b47050e-10ad-11e7-9bbe-a71d72f389d5.png)

Offset [string: col] 53::00:

![3](https://cloud.githubusercontent.com/assets/906886/24295809/8b475860-10ad-11e7-8c7f-e72b9cfaeb08.png)

Offset [string: col] 88::00:

![4](https://cloud.githubusercontent.com/assets/906886/24295811/8b49741a-10ad-11e7-870d-24471ddb29e5.png)

The exported to Iceni Infix page of this document consists of an HTML file with its table of contents and 7.5 Mb of images in a JPEG with a size of 10548x15594 px. Therefore, the difficulty with its decoding - judging by the size of the picture, the book, provided the A4 page format is scanned at a resolution of about 1300 dpi, and after the page without the OCR it was simply compressed into JPEG-2000 format and encapsulated in PDF creating other problems - after all, the author has the document read , And that PDF still needs to be printed and it might not fit on the page, he just did not think.

**Comment by kjk** [comment] 2017-03-24 16:02
It looks mupdf fixed the issue. At some point I'll update to latest mupdf and we will pick it up as well.

**Comment by VictorVG** [comment] 2017-03-24 17:27
Thank you very much Christophe! You correct other people's mistakes, and some developers and bug-reports ignore their own flaws. At least the answer from them, despite the fact that both the place and the consequences of errors are not known. Their tech support just for years pretends that "does not see" bug-reports. :)

**Comment by VictorVG** [comment] 2017-04-19 09:40
I looked at the new assemblies - this phenomenon is still showing. Compared using [**XnViewMP**](http://www.xnview.com/en/xnviewmp/) v0.85 x64, [**GhostScript v9.21**](https://github.com/ArtifexSoftware/ghostpdl-downloads/releases) x64 - in XnViewMP the image is drawn completely, but you need to use the Open (Ctrl-O) command - the XnViewMP feature, while in SumatraPDF you still see artifacts:

![1](https://cloud.githubusercontent.com/assets/906886/25173553/36f5c904-24fd-11e7-9189-b9b236122ef1.png)

![2](https://cloud.githubusercontent.com/assets/906886/25173556/3c6c2f5e-24fd-11e7-99ca-9472ffd58d83.png)

![3](https://cloud.githubusercontent.com/assets/906886/25173561/424ca692-24fd-11e7-8488-18a80d6f0019.png)

for test I use this file - [**test.pdf**](https://github.com/sumatrapdfreader/sumatrapdf/files/933085/test.pdf)

**Comment by doquan0** [comment] 2017-04-23 17:52
Hi VictorVG,
Please sympathize for my limited English level. I'm not sure about meaning of what you wrote: "in XnViewMP the image is drawn completely". From the picture of XnViewMP you posted, I can see the image is displayed quite strangely, compared to the image of Adobe Reader I posted above. XnViewMP seems to display the OCR text of the image, not the whole image like Adobe Reader or SumatraPDF.

**Comment by kjk** [comment] 2017-04-23 22:14
We should keep this open until it's fixed.

**Comment by GitHubRulesOK** [comment] 2019-11-14 22:12
@kjk resolved with latest updates

![Untitled762](https://user-images.githubusercontent.com/12754913/68900429-c0ed8080-072b-11ea-9296-6a732a95fc67.png)

**Comment by kjk** [comment] 2019-11-15 05:20
Thanks @GitHubRulesOK 
Fixed in latest build https://www.sumatrapdfreader.org/dailybuilds.html

**Closed by kjk** 2019-11-15 05:20 UTC
