### ISSUE TITLE
The problem with printing on Xerox printer

### ISSUE THREAD

**Issue by BIMSteam** [sumatrapdfreader/sumatrapdf#4591] opened 2024-10-14 21:00 UTC
### Discussed in https://github.com/sumatrapdfreader/sumatrapdf/discussions/4590

<div type='discussions-op-text'>

<sup>Originally posted by **BIMSteam** October 14, 2024</sup>
There are two printers installed in the system – Xerox and Canon. Printing on the Canon works fine, but the Xerox prints as if its photoconductor unit has failed – the entire page has a large number of white horizontal lines. At first, I thought it was a driver issue for the Xerox, but all other programs print on it correctly, the problem is only with Sumatra.</div>

**Comment by GitHubRulesOK** [comment] 2024-10-14 21:53
duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/919 https://github.com/sumatrapdfreader/sumatrapdf/issues/1081 etc.
related to https://github.com/sumatrapdfreader/sumatrapdf/issues/1312 https://github.com/sumatrapdfreader/sumatrapdf/issues/417 https://github.com/sumatrapdfreader/sumatrapdf/issues/685

**Closed by GitHubRulesOK** 2024-10-14 21:53 UTC

**Comment by BIMSteam** [comment] 2024-10-15 09:59
I read comments from your links... Disabling ICM solved the problem for me... Printing Preferences -> Advanced tab -> Driver - ICM -> Disable
