### ISSUE TITLE
rendering epub of Chinese format

### ISSUE THREAD

**Issue by q2333gh** [sumatrapdfreader/sumatrapdf#3445] opened 2023-04-17 22:34 UTC
#3407 
can we customize the line height ? or even font-family and  font-size ?
that will be great . i really like sumatrapdf. i recommand this software to my friends all time .
![image](https://user-images.githubusercontent.com/32679742/232624640-3d30f36c-3d36-4556-9dd0-7b8b3868a71d.png)

**Comment by GitHubRulesOK** [comment] 2023-04-18 01:26
Not possible for PDF readers to alter line size . Each letter can be different placement and thus not flowable  in text blocks. USE PDF editor that can combine blocks of text (Foxit/Tracker editors)

Not practical for current ebook handler
Thus a duplicate of open issue https://github.com/sumatrapdfreader/sumatrapdf/issues/3382

**Closed by GitHubRulesOK** 2023-04-18 01:26 UTC
