### ISSUE TITLE
Change internal UI text colors

### ISSUE THREAD

**Issue by Shideravan** [sumatrapdfreader/sumatrapdf#1750] opened 2020-09-08 09:10 UTC
Is there a way to do that? If I change the background color, "MainWindowBackground = #000000" It's changes the background of the document too, and I need to it be in #000000 because if it's not black will cause tired eyes quickly in reading sections (not understanding why "yellow" is the defalut anyway).
But as long I don't know if there's a way to change the internal UI font color, it's black in the black which turns unreadable. I checked the documentation, but suprising this option don't seems to exist, then I kindly ask for it to be implemented if it does not exist 🙂
![image](https://user-images.githubusercontent.com/12163923/92456270-156d5b00-f199-11ea-9559-1d9aaf008ea1.png)

**Comment by DhruvaSambrani** [comment] 2020-09-09 17:07
Change `TextColor`
```
MainWindowBackground = #000000
EscToExit = false
ReuseInstance = false
UseSysColors = false
RestoreSession = true
TabWidth = 300

FixedPageUI [
	TextColor = #dddddd
	BackgroundColor = #242424
	SelectionColor = #f5fc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
]
.
.
.
```
This will however invert ALL colors, including images.

**Comment by GitHubRulesOK** [comment] 2020-09-09 23:26
As mentioned there is an alternative to within limits alter colours, but what you are really after is theming which is covered in many other issues but most related to your issue is https://github.com/sumatrapdfreader/sumatrapdf/issues/1586# so closing as related duplicate of one of many.

**Closed by GitHubRulesOK** 2020-09-09 23:26 UTC
