### ISSUE TITLE
Disadvantage when drawing a dark theme

### ISSUE THREAD

**Issue by subsubsubsubsubsub** [sumatrapdfreader/sumatrapdf#3825] opened 2023-10-29 18:20 UTC
![sshot-002](https://github.com/sumatrapdfreader/sumatrapdf/assets/73518754/9f34fb8a-7307-41c3-bb7e-928e37ca25c9)
![sshot-003](https://github.com/sumatrapdfreader/sumatrapdf/assets/73518754/7fcd50f5-6938-41f7-bf73-4e64167396e7)
![sshot-005](https://github.com/sumatrapdfreader/sumatrapdf/assets/73518754/49fcbaa8-4dfd-4eea-b938-fb3abb7505fd)
![sshot-006](https://github.com/sumatrapdfreader/sumatrapdf/assets/73518754/39824d65-e133-4549-a560-7c121ecb66ca)

**Comment by GitHubRulesOK** [comment] 2023-10-30 10:40
closing as duplicate of #3802 or others 
where windows functions are problematic such as MS theming does not cover sidebars since not a SumatraPDF control
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/9b5cb6af-96ae-4992-88e7-22c96abd2c17)![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/09e61f01-6eb3-47fa-9224-d495ac31f02a)

**Closed by GitHubRulesOK** 2023-10-30 10:40 UTC
