### ISSUE TITLE
for High DPI support

### ISSUE THREAD

**Issue by mengyaoss77** [sumatrapdfreader/sumatrapdf#843] opened 2017-07-07 08:30 UTC
On 1920*1080 , 13-inch, Windows 10, 125% scale.
The buttons on tool bar are not well

**Comment by SumatraPeter** [comment] 2017-07-08 23:45
Yet one more to close as duplicate of #734...

**Comment by kjk** [comment] 2017-07-08 23:54
Closing as duplicate of #734

**Closed by kjk** 2017-07-08 23:54 UTC
