### ISSUE TITLE
File Association does not work

### ISSUE THREAD

**Issue by ChesterCloud** [sumatrapdfreader/sumatrapdf#862] opened 2017-08-15 05:08 UTC
Option which makes SumatraPDF 3.1.2 x64 default PDF reader on Windows 10 Pro x64 1703 Build with latest updates does not work. I don't know why, but default PDF reader still Microsoft Edge... I have to associate files manually via Control Panel or by right click of mouse "Open With" context menu...

**Comment by sandybeachit** [comment] 2017-08-15 10:43
I had this issue but with adobe reader, i dont think its a Sumatra PDF issue, but more of a Windows issue.

**Comment by SumatraPeter** [comment] 2017-08-15 21:51
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/615.

**Comment by kjk** [comment] 2017-08-15 23:12
Closing as dup.

**Closed by kjk** 2017-08-15 23:12 UTC

**Comment by kjk** [comment] 2019-11-18 00:34
This is now tracked by #1248
