### ISSUE TITLE
Feature Request: Magnify feature

### ISSUE THREAD

**Issue by tomchr9** [sumatrapdfreader/sumatrapdf#676] opened 2016-11-30 15:34 UTC
Temporary magnify feature when holding down left mouse button to enlarge details when reading material viewed as 2-page or "Book view" such as speech bubbles in cbr/cbz comics.

**Comment by kjk** [comment] 2019-01-01 22:19
closing as duplicate of #929

**Closed by kjk** 2019-01-01 22:19 UTC

**Comment by tomchr9** [comment] 2019-01-31 12:07
I suggest this feature request be reopened. It is a matter of convenience to have a quick zoom feature at the **single touch of a mouse button**.

The solution to use Windows Magnifier as described in [#929](https://github.com/sumatrapdfreader/sumatrapdf/issues/929) is both inconvenient and inadequate, as the Windows Magnifier feature is clumsy and doesn't scale well.

**Comment by GitHubRulesOK** [comment] 2019-01-31 13:04
@tomchr9 This thread was closed as duplicate of better description in #929 any fresh comments /request to reopen should be raised in #929 (which was closed by OP not developer)
