### ISSUE TITLE
shell extension not only for PDF but also for EPUB (and maybe others)

### ISSUE THREAD

**Issue by froschl** [sumatrapdfreader/sumatrapdf#715] opened 2017-02-02 10:35 UTC
I use the shell extension in Sumtra for showing the covers of my books in the explorer.
Unfortunatly it doesn't work for epubs.
I use CDisplayEx for it, but it doesn't work the right way for every book (showing the first
picture in OEBPS/Images instead of  the file named cover*.*)
So maybe Shell-Extension could be implement in Sumatra also for other formats then PDF?

best regards,
and thank you for very good program...

**Comment by kpym** [comment] 2020-06-13 15:46
I have asked the [same thing](https://github.com/sumatrapdfreader/sumatrapdf/issues/1248#issuecomment-643604358) in #1248.

**Comment by SumatraPeter** [comment] 2020-06-14 00:03
@kjk @GitHubRulesOK: Perhaps close as dupe of #382?

**Comment by GitHubRulesOK** [comment] 2020-06-14 01:43
@SumatraPeter 
agreed older thread covers wider discussion

**Closed by GitHubRulesOK** 2020-06-14 01:43 UTC
