### ISSUE TITLE
left and right narrow

### ISSUE THREAD

**Issue by yanlongbinluck** [sumatrapdfreader/sumatrapdf#2214] opened 2021-10-25 01:58 UTC
Hi，SumatraPDF is my favorite pdf reader. But there may be a bug in 4k screen?
As shown in follow figure, when I want to close the rightmost pdf file, there is a "left and right narrow". It prevents me from closing the pdf file.
But there is no problem using 2k resolution.

![111](https://user-images.githubusercontent.com/35165028/138622352-b0d7adcd-ffac-4aa7-ab50-bd020e7035b5.png)

**Comment by yanlongbinluck** [comment] 2021-11-03 12:01
any solution？

**Comment by yanlongbinluck** [comment] 2021-11-03 12:06
@GitHubRulesOK
Thanks.

**Comment by GitHubRulesOK** [comment] 2021-11-03 12:40
I am closing as duplicate of a longtime issue that the rescaling usually when using high resolution monitors upsets tab bar scaled widths

Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/447

**Closed by GitHubRulesOK** 2021-11-03 12:40 UTC
