### ISSUE TITLE
href run command to open other document not working

### ISSUE THREAD

**Issue by somyadashora** [sumatrapdfreader/sumatrapdf#1634] opened 2020-06-21 17:28 UTC
\href{run:./pdf/abc.pdf}
used to work fine and open the document.
But after i updated to newer version, the file does not open.
Says file not found. Same code works in acrobat reader.

I think the link address generated has 
file:./pdf/abc.pdf
instead of just
./pdf/abc.pdf

**Comment by GitHubRulesOK** [comment] 2020-06-21 19:24
No version info or MWE has been included so I am having to guess that this is a duplicate of relative path issue https://github.com/sumatrapdfreader/sumatrapdf/issues/1506

**Closed by GitHubRulesOK** 2020-06-21 19:24 UTC
