### ISSUE TITLE
View Options/Icons be visible in the Toolbar?

### ISSUE THREAD

**Issue by ASHIT-AXAR** [sumatrapdfreader/sumatrapdf#1117] opened 2018-12-31 17:05 UTC
hello 
i continuously switch between different views in pdf files.
would you please add view options/icons visible in the toolbar ?
i mean those 4 first sub-menu items in VIEW menu and those 4 first sub-menu items in ZOOM menu to be visible in the toolbar.
like this two icons i highlighted in red :

![untitled](https://user-images.githubusercontent.com/24279964/50564631-ad1b7480-0d3b-11e9-89f2-34c8b0e4591b.png)

and zoom level (maybe a selectable combobox in the toolbar )
thanks

**Comment by GitHubRulesOK** [comment] 2019-01-01 17:06
@kjk see comments on 271 suggesting this is duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/332

**Comment by SumatraPeter** [comment] 2020-02-04 22:46
@GitHubRulesOK: Given that kjk isn't rigidly against toolbar customizability (see https://github.com/sumatrapdfreader/sumatrapdf/issues/734#issuecomment-332388398), I'd suggest:

1. Renaming #734 from "Improve toolbar icons" to just "Improve toolbar"

and then

2. Closing all such issues asking for additions to the toolbar as duplicates of #734

**Comment by GitHubRulesOK** [comment] 2020-02-04 23:04
@SumatraPeter 
I am not elevated to editor (just doorman) so can't change only close and I considered priority for current round was mupdf then e-book for next round 
I agree UI is a minefield of duplicates and will look through those but It would help if you can give me any pointers to common requests :-)

**Comment by SumatraPeter** [comment] 2020-02-05 01:45
Will do, as and when I come across them. 🙂

**Comment by kjk** [comment] 2020-02-05 02:42
Let's not necessarily put too much into a single issue. #734 really is just only about changing toolbar icons and nothing else.
Other issues related to a toolbar deserve their own GitHub issue.

**Comment by SumatraPeter** [comment] 2020-02-05 21:51
Fine, then we can just treat any of the numerous toolbar modification related requests as the master for general toolbar customizability, and close all the rest as dupes of that one.

**Comment by GitHubRulesOK** [comment] 2020-02-05 22:32
@SumatraPeter 
Personally not adverse to a new catchall just for iconic requests that can reference those simpler requests the difficulty is may users then go on to suggest OR context / Floating / Autohide / dropdown each of which has its merits

**Comment by SumatraPeter** [comment] 2020-02-06 01:16
*Sigh* Was just a suggestion. Fine, then let's keep them all open then. Not that any of it's gonna be implemented anytime soon.

**Comment by kjk** [comment] 2024-08-05 22:08
Toolbar is now customizable https://www.sumatrapdfreader.org/docs/Customize-toolbar

**Closed by kjk** 2024-08-05 22:08 UTC
