### ISSUE TITLE
Flickering in tooltip display of PDF comments longer than 512 chars in SumatraPDF 3.4.x

### ISSUE THREAD

**Issue by OnceUponATimeInAmerica** [sumatrapdfreader/sumatrapdf#3086] opened 2022-11-12 01:49 UTC
Hello, and thanks for all of your efforts.

There is very irritating flickering in display of user comments/annotations (when shown as tooltips when hovered over) which are longer than 512 characters in PDF files . 

This bug DID NOT happen in SumatraPDF version 3.3.x and earlier versions; It started with SumatraPDF version 3.4.x and is present in the last 3.4.6 version (in both 32 and 64 bit builds).

This bug also does not happen in any version for tooltip display of comments which are shorted than 512 chars.

Thanks.

**Comment by GitHubRulesOK** [comment] 2022-11-14 02:41
without sample cant see if its still an issue taking both your comments as one its 922 bytes without hint of a flicker
![image](https://user-images.githubusercontent.com/12754913/201563872-99d5c3ca-da76-4af7-9f11-a52ce0da0a09.png)

**Comment by andreasvarga** [comment] 2023-02-24 11:50
I am using 3.4.6 and the flickering for large comments is present. Recently I received a lot of comments to my book project and this is very disturbing. To see the text of comments, I have to copy and paste each larger comment into an editor. Fixing this behaviour would really be most welcome.

**Comment by GitHubRulesOK** [comment] 2023-02-24 13:26
@andreasvarga It is Fixed either by use *older version (e.g.3.3.3) OR newer version (3.5.Xperimental)* since "released" versions rarely change retrospectively, thus would need a 3.4.7 targeting this one feature. 3.5 Pre-Release has many improvements over 3.4.6 but may also introduce other unexpected behaviours.

**Comment by kjk** [comment] 2023-02-24 16:54
This is fixed in latest pre-release https://www.sumatrapdfreader.org/prerelease

If not, please re-open and provide a file showing a problem.

**Closed by kjk** 2023-02-24 16:54 UTC

**Comment by GitHubRulesOK** [comment] 2023-02-24 18:03
@kjk there is a sample in the one I left open which has a related sample file see page 6 upper right note cause is the large sizzzze hits screen edge https://github.com/sumatrapdfreader/sumatrapdf/issues/2873
