### ISSUE TITLE
Can't show newly added bookmarks if file was opened before

### ISSUE THREAD

**Issue by 775405984** [sumatrapdfreader/sumatrapdf#1715] opened 2020-07-30 13:33 UTC
When you opened a pdf file without bookmarks, and then close Sumatra to add some bookmarks in another software and save, Sumatra will still thinks the saved file doesn't have any bookmarks when opened again.

It can show bookmarks, it just needs extra steps (F12).

@kjk @SumatraPeter @GitHubRulesOK

**Comment by GitHubRulesOK** [comment] 2020-07-30 13:50
If the file is under 32 Mb then same as with latex editors it "should" be possible to edit PDF whilst open in SumatraPDF but sumatraPDF needs to be triggered to see the change often by pressing R, but on an NTFS drive with the advanced `ReloadModifiedDocuments = true` it can do it automatically without the R. If the file is over 32 MB it must be closed to let the editor have full access.
There can be issues with remote caches of file, so that even if SumatraPDF is triggered to reload, then unlike an NTFS drive a cloud drive may be only offering its former version of that file.

**Comment by GitHubRulesOK** [comment] 2020-07-30 20:58
@775405984 
Matt 
The comment about two editors is not 100% the case, but take it as a normal/natural requirement.
Under your circumstances when closing a file either, whilst ToC is not there, OR more specifically not "Open" then with `Remember these settings for each document` then SumatraPDF is pre-destined NOT to open them next time against a users wishes.
@kjk 
**Edge Case** when editing files, that if there was **NO TOC last time** but NOW has TOC a user MAY want to revert to `Show the bookmarks when available` !

**Comment by GitHubRulesOK** [comment] 2020-07-30 22:16
@775405984 
Matt you may note that your issue has highlighted a problem with recent 3.2 builds, can you check if using an older 3.1.2 version, reduces your problem.

**Comment by 775405984** [comment] 2020-07-30 23:09
> @775405984
> Matt you may note that your issue has highlighted a problem with recent 3.2 builds, can you check if using an older 3.1.2 version, reduces your problem.

 3.1.2 can produce the same issue as well.

**Comment by SumatraPeter** [comment] 2020-07-30 23:34
The issue title here is slightly misleading IMO. It's not that Sumatra _can't_ show the newly added bookmarks if the file was opened before, but that it _doesn't_ due to certain settings as explained above. You open a bookmark-less file and Sumatra doesn't show the bookmarks sidebar for obvious reasons, then when you quit Sumatra it saves the state of the document as last displayed. Next time you open the edited file (now containing bookmarks), Sumatra going by the file name still thinks it's the same file as before, so displays it with the bookmarks sidebar closed since that was the state last saved.

Honestly, seems logical to me and frankly I don't think there's anything that really needs changing here. However it's up to kjk of course.

**Comment by GitHubRulesOK** [comment] 2020-07-30 23:42
@SumatraPeter 
Your right it is "Normal" to change name during multiple editing, e.g. FileSansBkms.pdf and FileWithBkms.pdf primarily to avoid issues like this one.

I left it open for Feedback as the "Issue" is in theory valid even if ones workflow/expectation is offbeat.

**Comment by kjk** [comment] 2020-07-31 02:35
Like @SumatraPeter said, this is caused by remembering state of the document. The amount of work to fix corner cases like this would not be worth it.

**Closed by kjk** 2020-07-31 02:35 UTC
