### ISSUE TITLE
crash repeatedly version 13834 to 8

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#2049] opened 2021-07-23 18:02 UTC
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/6870393/sumatrapdfcrash.zip)

 SumatraPDF-prerel-13837-64 should have been an autoupdate

**Comment by GitHubRulesOK** [comment] 2021-07-23 18:10
Auto updated
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/6870490/sumatrapdfcrash.zip)
 still crashes

**Comment by kjk** [comment] 2021-07-23 19:31
Could you describe steps for reproducing this?

I tried a bunch of PDF files, a bunch of .chm files, even tried NirCmd.chm that seem to be causing the crash but I can't reproduce this.

**Comment by GitHubRulesOK** [comment] 2021-07-23 19:57
[sumatrapdfcrash (2).zip](https://github.com/sumatrapdfreader/sumatrapdf/files/6870920/sumatrapdfcrash.2.zip)
I removed pdb's it should attach if needed :-)
unpack folder to C:\folder or D:\folder or ? seems not to matter
drag and drop the pdf onto the exe.

**Comment by kjk** [comment] 2021-07-23 20:20
Thanks. 

I reproduced the crash with 13837 but I think fixed it with the most recent changes so in about hour, when GitHub CI finishes building, it should be fixed.

**Closed by kjk** 2021-07-23 20:20 UTC

**Comment by GitHubRulesOK** [comment] 2021-07-23 21:45
[NirCmd (2).zip](https://github.com/sumatrapdfreader/sumatrapdf/files/6871339/NirCmd.2.zip)
@kjk this file appears to be my trigger
