### ISSUE TITLE
add  comment to a pdf document

### ISSUE THREAD

**Issue by ladyrick** [sumatrapdfreader/sumatrapdf#591] opened 2016-08-17 11:13 UTC
Please add this feature. It's very useful.
Please comment if you are agree with me.

**Comment by millo-k** [comment] 2017-03-27 08:24
This feature would be very helpful. Please add it.

**Comment by GitHubRulesOK** [comment] 2019-11-27 23:49
@kjk duplicate of I need a feature which allow me to add comment in a pdf #453

**Comment by kjk** [comment] 2019-11-28 00:55
consolidate under #453

**Closed by kjk** 2019-11-28 00:55 UTC
