### ISSUE TITLE
HP M1536dnf Printer issue

### ISSUE THREAD

**Issue by RandySislerJr** [sumatrapdfreader/sumatrapdf#1474] opened 2020-02-26 14:54 UTC
sumatrapdf 3.1.2 64-bit, Windows 10 64-bit, HP M1536dnf network printer
The file opens fine in sumatrapdf but it prints 4 blank pages. I have printed several other PDFs from sumatrapdf and they print fine. I printed this document from FireFox and it printed fine so this is not an issue for me just a FYI.
[WVU-Care-Financial-Assistance-Application-and-checklist-6152018.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4256357/WVU-Care-Financial-Assistance-Application-and-checklist-6152018.pdf)

**Comment by GitHubRulesOK** [comment] 2020-02-26 16:24
Hmmm
I was able to print page 1 (saving trees, ink and pennies) to wireless HP printer from latest pre-release no problem. May be worth you trying a portable copy?
Thus it could be some issue with the full 4 pages via your networked print driver.

**Comment by RandySislerJr** [comment] 2020-02-28 21:48
I tried the portable copy with the same results. Just four blank pages. I also tried sending just a single page. It also came out blank. I also noticed that there was another copy of the printer setup with a TCP/IP port not the WSD port so I tried it also and still just blank pages.

**Comment by GitHubRulesOK** [comment] 2020-02-29 16:33
@RandySislerJr 
It looks like your issue is a duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/974

The workaround there was to use version 3.0 NOT set to images for printing.
A portable copy could probably be set to run from current file in current version with either _current page or whole file_ via command line using "ExternalViewer" options.
Page ranges would be more difficult unless always similar.
I am guessing it may be down to some PCL image optimization setting in the print driver

**Comment by GitHubRulesOK** [comment] 2020-02-29 20:02
@kjk
I am closing/consolidating as appears to be a duplicate of identical **HP print driver issue** as discussed in 
Printing blank pages #625

**Closed by GitHubRulesOK** 2020-02-29 20:02 UTC
