### ISSUE TITLE
"Frequently Viewed" Text does not change to reflect color settings

### ISSUE THREAD

**Issue by APerson4645** [sumatrapdfreader/sumatrapdf#1586] opened 2020-05-15 12:58 UTC
I have noticed that if I change color values in SumatraPDF-settings.txt that, while the PDF/eBook/Djvu text changes to accommodate it, the "Frequently Viewed" tab/window does not. I don't know if I'm just missing a color value or if it's actually a bug. Attached is my settings.txt as well as pictures describing the behavior. Both the settings file as well as the pictures have been edited to remove the book names/text but I can assure that both of those do show up if I use the default white theme, just not if I alter the color values to something like black.
![Proof1](https://user-images.githubusercontent.com/45131377/82052766-6bae0f80-9679-11ea-8479-68de34a7a913.PNG)
![Proof2](https://user-images.githubusercontent.com/45131377/82052770-6e106980-9679-11ea-802b-69be36c09329.PNG)
[SumatraPDF-settings (Black).txt](https://github.com/sumatrapdfreader/sumatrapdf/files/4634491/SumatraPDF-settings.Black.txt)
[SumatraPDF-settings (White).txt](https://github.com/sumatrapdfreader/sumatrapdf/files/4634492/SumatraPDF-settings.White.txt)

**Comment by GitHubRulesOK** [comment] 2020-05-15 23:17
Yes, you are missing a setting since there is none
The text is a mix of colours with a default of black the backgroung used to be yellow but user complained about it being too bright
![image](https://user-images.githubusercontent.com/12754913/82103332-7cf32c80-970a-11ea-998f-41db51f8f720.png)

hence problems arise when users corrupt the settings and the background goes black by accident

**Comment by APerson4645** [comment] 2020-05-16 09:43
Sounds like the color settings should be expanded upon then, not removed. And allow users to change the text color in the "MainWindow"

**Comment by GitHubRulesOK** [comment] 2020-05-17 10:10
@kjk 
are we classing 
    `MainWindowBackground = #80fff200` 
deliberately not reflecting its colour but behaving as 
    `MainWindowBackground = #80f2f2f2`
as a "bug" or do I count this theming request as a duplicate of one of #437 #628 #745 #770 #1023 #1450 #1555 #1580 and many others

Personally I think it's best to treat it as a bug and remove that problem "yellow" setting, once and for all, just "stick" it as if it was MainWindowBackground = #80f0f0f0 or #80f2f2f2 there are a lot less users/complaints now it does not show up as yellow, the custom overriding of that value for gradientcolors is now more frequently the issue.

**Comment by GitHubRulesOK** [comment] 2023-04-09 03:26
@kjk this issue is now invalid as historic settings have been replaced and frequent now has a different behaviour
![image](https://user-images.githubusercontent.com/12754913/230752523-e7ac573e-e85b-4d1b-be10-783f13aa988d.png)

**Closed** 2023-04-09 03:29 UTC
