### ISSUE TITLE
Unexpected behaviour of installer, possibly due to sullied installation

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1241] opened 2019-11-16 19:10 UTC
Windows 10 x64

I frequently run portable versions of the latest build etc. thus know I do not have a "clean" installation to test within. so the following may not be a typical user experience. however some other users have expressed similar issues for example
Uninstaller does not show any buttons #1221 
I have installed clean on a Win 7 machine so other related issues are shown lower down.

As part of current beta testing I was attempting to check installer features, my observations are as follows.

I ran the installer using right click as Administrator (although I have sometimes not bothered)

I was surprised to see NO options to use desktop search  or preview simply the **one checkbox** for set as default PDF reader (which I know does not work. but selected anyway and as usual got the expected message Nanny will reset PDF association back to edge !)

"An App default was reset"
I manually set PDF and e-pub associations to the new SumatraPDF location 
All appeared OK as files now opened as intended and expected in SumatraPDF

I then went to run the installer again (expecting to be offed an uninstall option) however this time I am offered to reinstall with **only the two options for search and preview** shown (unchecked by default) so I proceed to see if all will work, and guess what the default is back to edge (but I can see previews)

Intrigued I tried to see what happens if I again run installer and **this time I get ALL 3 options** but when attempting to over install I get the confusing message from SumatraPDF

**"Please close Windows Explorer and Windows Explorer to proceed"**

I close some windows and it changes to 
"Please close Windows Explorer to proceed"
Then finally "Thank  you for choosing SumatraPDF" (however the install is NOT progressing)
It would help at this point to be reminded to again confirm, so as to proceed which I try and a second installation progress bar confirms the overwrite.
Again of course association for opening PDF's has to be manually reset

Finally happy that all seems _fairly reasonable_ I use Windows option to uninstall and inevitably there are two (why not 3?) again I get the cryptic message
**"Please close Windows Explorer and Windows Explorer to proceed"**
then eventually "Are you sure you want to uninstall SumatraPDF"
Of course I am sure but here the problem  is **there is no button to say so !**
I do not use any screen variation from 100 % scaling so am surprised a button is not visible
on the basis an enter might work I hit enter and uninstall is then confirmed

In order to avoid any further issues I remove the dead entry from Uninstall programs
Obviously the desktop preview feature is no longer available **but** icons for PDF and e-pub are still overprinted with the SumatraPDF logo. (these for PDF do of course disappear on a restart, however the ones I also manually set for e-pub are NOT removed)

As I said mine is not a typical installation but fraught with confusions (which I am aware of) but they must be even more confusing to an experimental first user.

Win 7 x32
-----
This time I used a clean machine and proceeding with more caution, got better results, however problems with buttons still made uninstall difficult
![Untitled](https://user-images.githubusercontent.com/12754913/68998655-48163200-08ad-11ea-8be0-7b0260cf97ae.png)  
![Untitled2](https://user-images.githubusercontent.com/12754913/68998660-52383080-08ad-11ea-9038-1cd174750fe5.png)

**Comment by SumatraPeter** [comment] 2019-11-16 21:45
> I was surprised to see NO options to use desktop search or preview simply the one checkbox for set as default PDF reader

It might help to clarify, were you trying the 32 or 64-bit installer on Win10 x64?

**Comment by GitHubRulesOK** [comment] 2019-11-16 22:37
@SumatraPeter yes as far as i recollect it was certainly 32bit for Win7 home x32 and only x64 for Win10 x64 the feeling I got was that due to prior historic usage the "dirty" x64 installation misbehaved (as is likely when a user tries several attempts at install) whereas the "clean" x32 install only had some problems at the uninstall screen both machines use fairly low res displays at 100% scaling. I could test other mixes but the issues I was confirming is that 1) there is an apparent problem with the button placement on the install & uninstall screens and 2) multiple attempts at install may upset the install logic for options.

**Comment by SumatraPeter** [comment] 2019-11-17 00:23
If you can somehow reliably replicate the conditions causing these weird button sizes in the uninstaller then @kjk should be able to fix #1221. Even otherwise, since it's a custom installer a through perusal of the code related to these buttons might perhaps help?

**Comment by kjk** [comment] 2019-11-17 23:59
Hopefully I'll find time to create a build with more logging in this area, make a build with that logging enabled so that you'll be able to run it and send me the logs. And hopefully I'll be able to figure out the cause from that.

My best guess at this point is something to do with incorrect dpi detection /scaling.

**Comment by kjk** [comment] 2019-11-18 11:37
Missing button in uninstaller should be fixed in by https://github.com/sumatrapdfreader/sumatrapdf/commit/232b3eb42fa98cba5aa8f5073d0c7c592c3270a9

I can't reproduce issues with the installer.

Lack of preview / search options  can happen if the installer is different arch than the OS (i.e. 32-bit vs. 64-bit mismatch). Windows requires those dlls to be of the same architecture as the OS.

Asking to close Windows Explorer is because the preview and/or search dlls were loaded by that process and we want to delete those .dll from disk and it can't be done if they're loaded by some process.

**Closed by kjk** 2019-11-18 11:37 UTC

**Comment by GitHubRulesOK** [comment] 2019-11-18 16:44
@kjk certainly seems much better but there were a few questions raised by running latest installer/uninstaller
![install1d](https://user-images.githubusercontent.com/12754913/69068806-54b99800-0a1d-11ea-9f14-4040fe1270bf.png)

buttons and options behaved well, there was occasionally a lag in selection of check-boxes (thus I on occasion would click a second time to confirm, but of course deactivate, thus needed a 3rd  click to re-activate) and at one point because the focus is on the last option (see 3rd quarter above) just as  I was miss hitting the install button I got the impression the last option unchecked itself, but previewer did seem to be installed.

The continuous update of the central message area is still on occasion clipping the button edges as seen here making them a flickering distruction
![install1](https://user-images.githubusercontent.com/12754913/69069216-01941500-0a1e-11ea-8b1a-dda724de101a.png)

Uninstall screen is also a much improved experience
![Unstall1](https://user-images.githubusercontent.com/12754913/69069756-efff3d00-0a1e-11ea-9f78-458ab3a36d29.png)

**The first message is slightly off since here I can uninstall with explorer open**

![Unstall2a](https://user-images.githubusercontent.com/12754913/69070468-1ec9e300-0a20-11ea-928b-c31f8860b0eb.png)

The final removal message is partly helpful but does not explain there are more than 3 locations that SumatraPDF may not clean up after itself

![Unstall3](https://user-images.githubusercontent.com/12754913/69070613-59cc1680-0a20-11ea-85e4-06ae7fea3bd9.png)

**The one residue that concerned me most was the failure to remove standard \AppData\Roaming\SumatraPDF** since that kept opening historic files including those that crash which would be a reason a user may attempt uninstall & reinstall on having problems

For testing I would frequently and variously delete directories and registry entries to try to provide as  "Clean as possible" installation conditions but always needed after uninstall to remove some application paths that remained

![Unstall2b](https://user-images.githubusercontent.com/12754913/69071838-8b45e180-0a22-11ea-972d-eede24c383dc.png)

**Comment by SumatraPeter** [comment] 2019-11-18 17:11
The MUICache etc. paths are added by Windows itself AFAIK (including the AppCompat ones unless the user has played with the EXE's compat settings). No program uninstaller I know of goes scouring through the registry to remove all such 'extraneous' entries. Sumatra's uninstaller only needs to be concerned with erasing all traces of the program that the program _itself_ is responsible for, which certainly includes the `%AppData%\SumatraPDF` and `%LocalAppData%\SumatraPDF` directories.

**Comment by GitHubRulesOK** [comment] 2019-11-18 19:31
@SumatraPeter  I agree I should hav cut image above MUI history it is only the legacy paths that would potentially case any issue and I have not drilled into registry at any time to check exactly which residues were left (each time I mess with associations it can be different) it was my intention to simply highlight there is a potential need to address such remnants to avoid any erroneous calls when moving applications around, It is potentially possible the installer might read an old installation of say x32 location as target for 64bit but as I did lot look closely into such behaviour perhaps @kjk can confirm such remnants would be ignored on re-install. the main problem that I encountered was the appdata residual entry of file history where the opened files are themselves the cause of crashes.
