### ISSUE TITLE
Text is not copied correctly from PDF

### ISSUE THREAD

**Issue by user1823** [sumatrapdfreader/sumatrapdf#3922] opened 2023-11-28 14:13 UTC
###### Reproduction Steps

1. Copy the last three sentences in the first paragraph of this PDF: [test.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/13488980/test.pdf)

###### Expected Result (text copied using Chrome PDF viewer)

regulating vitamin D metabolism. The physiologic mechanisms that the kidney has developed to carry out these
functions require a high degree of structural complexity.

###### Actual Result (text copied using SumatraPDF)

regulating�vitamin�D�metabolism.�The�physiologic�mecha-
nisms that the kidney has developed to carry out these
functions�require�a�high�degree�of�structural�complexity.

As you can see, there are two issues:
- Many of the spaces are replaced by a spurious character.
- Chrome correctly deduced that mecha- nisms was a single word, but SumatraPDF couldn't.

###### Version

v3.5.2 64-bit

**Comment by GitHubRulesOK** [comment] 2023-11-28 15:06
The problem is that PDF is not words but single lines often as multiple spaced out strings of single letters, in this page all the right column is first, then the left column starts well over half way through the file (see the scroll bar position)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/f63290f9-6df9-4a61-8e5e-27d3175a2196)

So MuPDF has to try to add a nominated spacer character between the short container strings, If the font has nominated a poor character that is what comes out.

So it depends what is substituted for the gaps and in Latest SumatraPDF with current MuPDF there is no problem so am closing as "fixed" in 3.6 and may or may not be a variable interpretation problem with 3.2 /3/4/5 variants.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/2bd40c9f-664f-46d0-b017-25d6ad2b873e)

**Closed by GitHubRulesOK** 2023-11-28 15:06 UTC

**Comment by user1823** [comment] 2023-11-28 15:29
> I do understand that Acrobat does it different for accessibility but that's why it has its own text extraction methods to modify such hyphenated lines. MuPDF is more faithful to the source

I get it. But, I don't think that MuPDF is helping the user by not modifying the hyphenated lines.  The users would be happier if it could modify the hyphenated lines.

**Comment by GitHubRulesOK** [comment] 2023-11-28 15:48
That extra editor feature in Acrobat plus many others (non related to ink printouts) included from Pro version (like forms and signatures) is why its way bigger than one executable.
SumatraPDF simply attempt to show on screen what a printout VIEWER rendering would show.

**Comment by user1823** [comment] 2023-11-28 16:12
> the PDF reader is a very small part of the suite, but bloated by feature creep.

I am not suggesting the inclusion of unnecessary features. I am only suggesting the addition of the feature to "correct" the hyphenated lines.

As shown by you, the Text Extractor file of Adobe is a very small part of the total package. So, even if we implement all the "basic" features (such as this one), the size of SumatraPDF will not increase noticeably.

**Comment by user1823** [comment] 2023-11-28 17:14
If you are interested, I have written regex to find such hyphens:

```
(?<=\w)-\R(?=\w)
```

Just replace what this regex finds with a blank to replicate Adobe's behavior.

**Comment by GitHubRulesOK** [comment] 2023-11-28 19:50
Its not that simple see here the line before  (1834) it unexpectedly is exactly as you might think plain text in a PDF exists (very rarely the case with PDF content)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/f7b2a120-9929-4764-a6aa-8cd90d17badf)

So there are about a dozen ways a single hyphen may be defined, lets see if we can find the one in question we alreadty know its standalone and later in the file (it does not have to be later just like the columns they dont need to be in order for burning a laser drum)
here it is on line 1878 so in the find box we can find it no problem but there are no letters on either side we can replace with a blank at that co-ordinate but why it makes no sense it is the means to see end of the broken word.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/10abeb71-ff57-4a0c-ba36-5961cfc7ec45)

Ok what about the word before that looks like `mecha` again you may not understand why, but it is PHFKD in a different font
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/ed42dd64-9bc0-4645-a02e-ff60c3b74163)

however the next line (1885) also uses plain font then **`functions` is written as `IXQFWLRQV`**

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/cd24537a-9d2f-4e7b-a45b-aad8239ac052)
so its lots of lines of code just to convert the words let alone the spaces ant even considerr wher words may need joining when the are no real clues other than consider a dictionary of words in every language like German French Chinese (about a library full of books).

**Comment by LilGGWzy** [comment] 2023-12-15 07:08
> 只需将此正则表达式找到的内容替换为空白即可复制 Adobe 的行为。

Hello friend, can you share the content of your script

**Comment by user1823** [comment] 2023-12-15 12:30
You can replace the text matched by the following two regex with a blank:

```regex
(?<=\w)\x{00AD}\R(?=\w)
```
```regex
(?<=\w)-\R(?=\w) 
```
