### ISSUE TITLE
File Name In Tab

### ISSUE THREAD

**Issue by gnuarm** [sumatrapdfreader/sumatrapdf#63] opened 2015-01-06 20:18 UTC
When a number of documents are open, the tabs get too small to show the entire file name.  Usually the unique part is the right hand side such as "electric bill 2014-12.pdf".  When the name is shortened to fit the tab the names are no longer unique and I can't tell which file is which.  

It would be nice if the full name could be shown with a mouse-over or perhaps show the first few letters, an ellipsis and then the last few letters.  Or maybe the file that is currently in focus could have a longer tab to show the full file name.  

BTW, I recently gave up on the PDF viewer that came with Windows 8 and started using Sumatra.  It is great!  Thanks a lot!!!

**Comment by GitHubRulesOK** [comment] 2019-11-16 02:55
@kjk dupe of 
Show the popup with info when i hover over the opened pdf. [1188](https://github.com/sumatrapdfreader/sumatrapdf/issues/1188)

**Closed** 2020-02-06 14:42 UTC
