### ISSUE TITLE
Replacement Text (AccSupp ActualText entry) Support

### ISSUE THREAD

**Issue by philsuero** [sumatrapdfreader/sumatrapdf#1772] opened 2020-10-05 18:08 UTC
We noticed that your PDF viewer doesn't have AccSupp ActualText support. This means that copy-pasting technical text such as shellscripts and programming code, does not work in your PDF viewer and this greatly restrains the use of your whole program.

According to the tests made using PDFs produced by pdflatex using the package accsupp, the replacement text support seems to be unreliable at the moment for copy and paste. Those tests are available on the referenced accsupp github page in the end of this text.

We kindly request better support of the replacement text support, because the copy and paste directly from the PDF document is not reliable.

Please also refer to these two pages for further discussion: 

[AccSupp discussion](https://tex.stackexchange.com/questions/563803/how-make-a-latex-document-that-generates-a-pdf-from-which-copy-paste-works-corre)

[AccSupp Github issue (with tests)](https://github.com/ho-tex/accsupp/issues/2)

**Comment by GitHubRulesOK** [comment] 2020-10-05 19:06
Since SmatraPDF is founded on MuPDF (copy paste fail) which in turn is dependant on freetype and that frequently suffers regression in handling LaTeX generated outputs. I would suggest for cross platform use you stick with Evince.
If whitespace is built using say WordPad or similar rich text then it is not usually a problem in windows clipboard thus not a copyNpaste problem
See here where something as simple as a tab space is recognised as terminating the text blocks but in the industry "standard" viewer **one is and one is not !!**
![image](https://user-images.githubusercontent.com/12754913/95120416-6b580300-0745-11eb-9f02-7ac2f1779f04.png)
![image](https://user-images.githubusercontent.com/12754913/95120874-1a94da00-0746-11eb-9c4c-6125042cc97e.png)

**Comment by GitHubRulesOK** [comment] 2020-10-05 20:29
@kjk 
This false into the group of complaints that non-visible Adobe specified contents are not needed to be rendered by a PDF viewing application such as MuPDF.
Thus guess it falls into the MuPDF "wont fix" grouping.

**Comment by GitHubRulesOK** [comment] 2021-06-12 00:26
I note there is no link for tracking in MuPDF however equally there is no further action possible to Unconfirmed status in https://bugs.ghostscript.com/show_bug.cgi?id=702966

**Comment by kjk** [comment] 2024-05-23 21:20
I believe mupdf implemented AccSupp and we imported that change.

However I have no way of confirming that. The linked issue doesn't have a test .pdf and I don't have tex setup to generate myself.

So try latest pre-release https://www.sumatrapdfreader.org/prerelease and if it doesn't work, include a test .pdf and describe what you do, what happens and what do you expect to happen.

**Closed by kjk** 2024-05-23 21:20 UTC
Labels: mupdf

**Comment by GitHubRulesOK** [comment] 2024-05-23 21:39
@kjk 
Th OP was expecting to write a volume of the Encyclopaedia Britannica and call it the ActualTEXT without it BRIEFLY describing an icon  or other single symbol!
