### ISSUE TITLE
SumatraPDF Installer-Version Pre-Release Crashes Upon Launching Documents

### ISSUE THREAD

**Issue by alienfxfiend** [sumatrapdfreader/sumatrapdf#2544] opened 2022-05-07 10:02 UTC
[Github Gist Crash File](https://gist.github.com/alienfxfiend/07a683cf5935c95c7a499dca94aa6a70)
I just updated to the newest SumatraPDF Installer-Version Pre-Release, I haven't been using the Installer-Version for some time, mostly the Portable-Version but I use both so that I can view more files, but when I went back to opening the Pre-Release Installer-Version it just crashed after attempting to open dozens of documents ! Can the dev shed some light on this ? Some of the documents links are broken but others exist. This happened recently, maybe it's a bug in the Pre-Release or that I have been unable to install the Installer-Version (had to literally move it to another folder & run as admin.) Inside the crash it says "Cannot find system font 'serif'." Do I have to remove the SumatraPDF-Settings & re-open each link from scratch ?

**Comment by GitHubRulesOK** [comment] 2022-05-07 10:14
14551 pre-release 64-bit
 please use current prerel there were "Break-ing transmission" between 550-555
For cleaning settings.txt the best way is backup old > build anew > copy file blocks from end of backup 
should work for sessions and history if remember is also set to true, but if there is any rogue doc file it will not stop a new crash

**Comment by alienfxfiend** [comment] 2022-05-07 10:28
Yeah I tried removing the SumatraPDF-Settings > Copying the File Blocks to a fresh Settings file —but it still crashes. Maybe any hint to which document could be causing the crash ?

**Comment by GitHubRulesOK** [comment] 2022-05-07 10:45
verify installer version is fully uninstalled via windows uninstall apps check the previous installed folder is removed (assume it is either program files and or or personal local appdata)

CBR previewing is a new feature thus may be a good suspect especially if newer v5 variants so try first install without preview option check stabillity for a few session changes then re-install with preview activated to see if thats the cause

**Comment by alienfxfiend** [comment] 2022-05-07 10:47
This is the .CBR (Comic Book) file that is crashing SumatraPDF —any idea why ? I'm not certain if it 'caused problems before as it is in my SumatraPDF-Settings file (13 MB attached here…) P.S: Cannot upload file format here so uploaded it to secure Anonymous File Store (Oshi.at) ~>> https://oshi.at/UndL/Classics_Illustrated_-016-_Gulliver's_Travels.cbr
P.S: I will now try /w that file removed from the SumatraPDF-Settings.

**Comment by GitHubRulesOK** [comment] 2022-05-07 11:04
Thanks for link (you can post if wrapped in a zip) but for my install Gullivers.cbr is previewing and viewing no problem thus perhaps not the culprit alone

**Comment by alienfxfiend** [comment] 2022-05-07 11:35
I haven't finished trying to open each link that I have in my Settings file —I have a few more I'll do later (I literally have hundreds of documents in the File Blocks plus most of them are invalid\ relocated.) It's possible that it's a resource exhaustion. I will confirm that there's no rogue doc after sifting through the list again in a few hours time…

**Comment by GitHubRulesOK** [comment] 2022-05-07 11:45
note your crash settings  file had `DefaultZoom = fit width` which was a recent issue at that time so check if thats still the cause

**Comment by kjk** [comment] 2022-05-07 15:07
Please update to 14555, this has been fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/7984835f3069153818937623d658635942dae275

**Closed** 2022-05-07 15:08 UTC

**Comment by alienfxfiend** [comment] 2022-05-07 16:01
Thank you ! ♥
