### ISSUE TITLE
mobi and djvu thumbnails are not showing up

### ISSUE THREAD

**Issue by faridcher** [sumatrapdfreader/sumatrapdf#1078] opened 2018-09-22 09:14 UTC
While pdf and epub thumbnails show fine, mobi and djvu don't.

**Comment by GitHubRulesOK** [comment] 2018-09-22 11:52
Thumbnails is a generic term, **within** SumatraPDF they are shown on the Frequently Read page and are ALL stored as one type (.png) so they are either ALL visible or not irrespective of document type

**Comment by faridcher** [comment] 2018-09-22 13:52
I mean in the shell (Windows File Explorer).  I use the latest sumatraPDF  and I am on Win 10.

**Comment by GitHubRulesOK** [comment] 2018-09-22 14:14
![win10 no sumatra](https://user-images.githubusercontent.com/12754913/45918082-13594700-be71-11e8-8d68-4e302cca913c.png)

Win 10 WITHOUT SumatraPDF

![win10 with sumatra](https://user-images.githubusercontent.com/12754913/45918085-16ecce00-be71-11e8-89f1-c261d1c8e9c0.png)

Win 10 WITH SumatraPDF

Sumatra only adds a previewer for PDF (and changes icons for most of the files it is registered with)
It is generally windows that controls the thumbnails outside SumatraPDF

**Comment by GitHubRulesOK** [comment] 2018-09-22 14:35
Ok now I understand it is changes to the file handling code, That part has generally been depreciated, it was used for embedding into older browsers etc. I have in the past seen it preview some of the formats supported by SumatraPDF and enhanced  versions used by other explorers (e.g. XY)
So it is not strictly an "Issue" with the program as designed (it works the way it "should")
I am not the developer however I suggest you need to be more specific about what you want.
IF you are offering to extend the code to add additional features and having problems then its best to raise a detailed explanation of where your compilation is failing

**Comment by SumatraPeter** [comment] 2018-09-22 18:01
Duplicate of #382.

![PDF](https://discourse-sumatra-backup.s3.amazonaws.com/original/1X/728eecbf03df28bb92437762f69f93f45650cdbe.png)

Only PDF previews are currently supported. From [what I understand](https://forum.sumatrapdfreader.org/t/ebook-thumbnail-preview-handler-installer-for-windows/505), thumbnail handlers for other formats are part of the code but deliberately disabled since the dev has been waiting for years for someone to submit icons for those file types (and apparently no free icon set is acceptable). Frankly if it was me and the feature was stable, I'd not let a mere lack of icons block users from benefiting from such a useful feature, but maybe there are other reasons for the decision...

**Comment by GitHubRulesOK** [comment] 2018-09-23 00:35
Thank Peter I had lost _site_ of those builds

**Comment by musm** [comment] 2018-10-03 20:42
these icons are pretty nice https://www.iconfinder.com/iconsets/sumatrapdf-files-icon

**Comment by GitHubRulesOK** [comment] 2018-10-03 23:01
and this is what they look like at 16 pelsx4![if_pdf_icon_1067101](https://user-images.githubusercontent.com/12754913/46444145-1ea94e00-c760-11e8-9d96-c0200aeac658.png)
![719391-mobi](https://user-images.githubusercontent.com/12754913/46444147-223cd500-c760-11e8-8473-1c1d220973e0.png)

**Comment by ianamk** [comment] 2018-10-07 14:10
afaik the extra preview handlers are disabled by default until new icons for those formats can be found
if you want them you'd need to compile sumatrapdf on your own see this thread on the sumatra forums
https://forum.sumatrapdfreader.org/t/preview-handlers-build-error/55
basically you need to edit premake5.lua and premake5.files.lua to enable the extra handlers then use premake5 to generate new visual studio project files zeniko use to provide builds that had the preview handlers enabled but he's been missing for a few years now I hope he's allright

**Comment by GitHubRulesOK** [comment] 2019-11-26 23:58
@kjk now tracked by #1248 ?

**Comment by kjk** [comment] 2019-11-27 00:01
This one is about enabling thumbnails for those formats in PdfPreview.dll

**Comment by GitHubRulesOK** [comment] 2019-11-27 00:13
@kjk that was the reason for my question mark. these formats are in some part available in developer build but inactive in main release, the inter related question that poses is - should there be more overlap ?

**Comment by SumatraPeter** [comment] 2019-11-27 03:57
Not a dupe of #1248, but is a dupe of (and can be consolidated with) #382 as I mentioned last year.

**Comment by kjk** [comment] 2019-11-27 04:55
Consolidate as #382

**Closed by kjk** 2019-11-27 04:55 UTC
