### ISSUE TITLE
SumatraPDF showing garbled texts in this file

### ISSUE THREAD

**Issue by 775405984** [sumatrapdfreader/sumatrapdf#1585] opened 2020-05-15 08:43 UTC
[123.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4633188/123.pdf)
![Screenshot_1](https://user-images.githubusercontent.com/7196377/82029940-45649000-96ca-11ea-83d0-b3c7124eb17c.jpg)
This file was written in Chinese, it also contains some English words without any problem.
Chrome and Foxit doesn't have this issue.
Interestingly, Microsoft Edge has the same issue.
@kjk @GitHubRulesOK

**Comment by 775405984** [comment] 2020-05-15 08:45
![Screenshot_1](https://user-images.githubusercontent.com/7196377/82030733-67aadd80-96cb-11ea-863f-15b1a020ea55.jpg)
This is what it should looks like.

**Comment by GitHubRulesOK** [comment] 2020-05-15 13:43
My first test in such cases is, can it be viewed differently in MuPDF (no)
what about Adobe Acrobat 9 (e.g. is it a valid PDF) if not why not
![image](https://user-images.githubusercontent.com/12754913/82054258-8a7ec700-96b6-11ea-8667-fb049ce7df2f.png)
![image](https://user-images.githubusercontent.com/12754913/82054357-bbf79280-96b6-11ea-9779-10ac51aa604e.png)
Could it have been made a more universally acceptable PDF ?
![image](https://user-images.githubusercontent.com/12754913/82056104-59ec5c80-96b9-11ea-9a06-a22786bf41cc.png) 
![image](https://user-images.githubusercontent.com/12754913/82056418-dc751c00-96b9-11ea-9ed0-45aa0784579d.png)

Conclusion the poor definition of fonts is beyond MuPDF or Acrobat abilities to substitute fonts
The Author should have tested the  file for embedding in the editor before release
[1585 123ms.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4634710/1585.123ms.pdf)

**Comment by SumatraPeter** [comment] 2020-05-15 20:33
> Interestingly, Microsoft Edge has the same issue.

Clearly you're referring to the legacy version, because if it looks fine in Chrome then it'll look fine in the new ChrEdge too.

**Comment by GitHubRulesOK** [comment] 2020-05-15 20:47
@SumatraPeter 
I think you'l l find it also views bad in new edge
 IF it was good in chrome perhaps its Chinese quality molly**bendy**mum
My conclusion is "BAD file"

**Comment by GitHubRulesOK** [comment] 2020-05-16 02:26
Testing via validator
File 123.pdf 
Result : Document does not conform to PDF/A.

Details : Validating file "123.pdf" for conformance level pdf1.4
The embedded font program 'DY1+ZEKHsO-1' cannot be read.
The embedded font program 'DY2+ZEKHsQ-2' cannot be read.
The embedded font program 'DY3+ZEKHsQ-3' cannot be read.
The document does not conform to the requested standard.
The document contains fonts without embedded font programs or encoding information (CMAPs).
**The document does not conform to the PDF 1.4 standard.**
Done.

e.g. its NOT a valid PDF

**Comment by SumatraPeter** [comment] 2020-05-16 04:07
> I think you'l l find it also views bad in new edge

@GitHubRulesOK: Unless I'm completely mistaken, looks fine here to my admittedly clueless-about-Chinese eyes:

![image](https://user-images.githubusercontent.com/15380332/82109935-00873a80-9758-11ea-88fa-699bd7bdb05c.png)

Sure the substituted font is too fat and blocky, but at least ChrEdge seems to have selected something appropriate, which is _far_ more than can be said for Sumatra (and even Firefox's pdf.js for that matter).

**Comment by GitHubRulesOK** [comment] 2020-05-16 11:11
That's great for some chrome users, however for the rest of the world as (far as) I know it "About Edge logo Microsoft Edge Microsoft Edge is up to date. Version 81.0.416.72 (Official build) (64-bit)"

This browser is made possible by the Chromium open source project and other open source software. Microsoft Edge © 2020 Microsoft Corporation. All rights reserved.

None of the bad Chinese glyphs show (there is no valid global font to substitute) and even the England ones that do work are not the best choice for readability.
![image](https://user-images.githubusercontent.com/12754913/82118269-f6703680-976d-11ea-89a9-245ad8fd4293.png)

**Comment by GitHubRulesOK** [comment] 2020-05-16 16:34
@775405984 
Matt I would send that file back and ask for a refund of your $27.50 since the PDF is clearly not fit for purpose and nor is it the quality one can expect from their current supp;iers.

**Comment by 775405984** [comment] 2020-05-16 23:40
> PS my fee invoice for £27.50 will follow when you confirm you got your $27.50 back 🙂

Why would you spend money on that？It was sent to me by a student at the OB/GYN forum in China. I don't think they'll give me money since I Pirated the file. I guess I should consider myself lucky they didn't sue me.
Thanks for the good detective work. @GitHubRulesOK and @SumatraPeter

**Comment by VictorVG** [comment] 2020-05-17 23:31
@775405984 

Also, Tracker  Software PDF Editor find another error:

> _Error - a displaced object was detected in the document._

**Comment by GitHubRulesOK** [comment] 2020-05-17 23:41
@VictorVG 
interesting there is much **more than** 

> "a" displaced object

I see 
![image](https://user-images.githubusercontent.com/12754913/82163020-52d37300-98a0-11ea-9087-c118a106619f.png)

**Comment by VictorVG** [comment] 2020-05-18 10:27
It was I who looked at a friend in the printing house and reproduced what his package said - I do not have such tools for verification since I use either SumatraPDF under WINE (BSD UNIX) or KPDF (KDE UNIX) more often.

**Comment by GitHubRulesOK** [comment] 2020-05-19 13:02
Closing as duplicate of several other cases such as `Reader is unable to show cyrillic text in pdf file` #378
Where files may only be viewed easily within a locality or machine that has a specific font available However the PDF is not defined using globally available fonts or the font glyphs have not been named/embedded in a rational way, thus breaking the "Portable"DF standard requirements.

**Closed by GitHubRulesOK** 2020-05-19 13:02 UTC
