### ISSUE TITLE
interactive PDF

### ISSUE THREAD

**Issue by Zelev** [sumatrapdfreader/sumatrapdf#206] opened 2015-05-24 18:34 UTC
The other day I was trying to fill a form, the pdf was interactive, but Sumatra couldnt change the values, it could be a goos feature to get the interactive documents and forms to work in sumatra if its not against the sumatra main idea

**Comment by mestaritonttu** [comment] 2015-06-24 08:06
Duplicate of report https://github.com/sumatrapdfreader/sumatrapdf/issues/135

**Closed** 2015-06-24 19:43 UTC
