### ISSUE TITLE
Empty tag is parsed as not closed (FB2)

### ISSUE THREAD

**Issue by newillusion** [sumatrapdfreader/sumatrapdf#860] opened 2017-08-11 05:45 UTC
When SumatraPDF open the file in attachment, all text is 'bold' on screen. If first enter of "<title />" tag will be removed from the file, text become normal (regular), what is OK.
[Kudrin XO.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/1217008/Kudrin.XO.zip)

**Comment by GitHubRulesOK** [comment] 2019-12-18 04:34
<title></title> or <title attribute="empty"></title> = an empty tag
<title /> = self-closing tag

replacing the first <title /> with <title></title> certainly makes the file work OK

**Comment by GitHubRulesOK** [comment] 2021-08-02 02:40
@kjk 
Crash report for current pre-release when opening above extracted FB2 sample
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/6914032/sumatrapdfcrash.zip)

testing above with MuPDF 1.18 suggests it would have behaved reasonably well in MuPDF render if it had not crashed

**Comment by kjk** [comment] 2021-08-02 07:27
@GitHubRulesOK I can't reproduce the crash. Is there anything you do other than opening the file?

**Comment by GitHubRulesOK** [comment] 2021-08-28 01:37
@kjk ignore the crash report in my second coment this file has generally opened well since

Update The OP comment still stands in MuPDF render i.e, it is different to other readers due to the odd tagging

**Comment by GitHubRulesOK** [comment] 2021-12-12 12:32
@kjk 
Interesting change in recent builds due to file handling
If above file is renamed to .fb2z it is using Legacy layout and as reported "All Bold"
![image](https://user-images.githubusercontent.com/12754913/145712226-cbaff345-2279-429f-9279-7d0ce4ff4724.png)

*However if extracted to FB2 then MuPdf engine shows it like this*

![image](https://user-images.githubusercontent.com/12754913/145712292-e67eaebc-b39d-47ab-8cbd-6f8db7115fbf.png)

***Is there a method for MuPdf to be passed the zip contents ?***

**Comment by GitHubRulesOK** [comment] 2022-02-05 17:46
@kjk shifting goalposts
Currently when viewed as FB2 with MuPDF engine the OP is fairly reasonably closed.
![image](https://user-images.githubusercontent.com/12754913/152652775-fd9b11cc-df3d-4ee1-8533-457879dda463.png)

HOWEVER if opened as FB2Z the situation is now worse
![image](https://user-images.githubusercontent.com/12754913/152652833-ab71e041-a9b7-4699-bc21-ccb4b1ca25cd.png)

**Comment by GitHubRulesOK** [comment] 2022-06-19 03:05
@kjk 
Continuous Developments mean this file now is rendered in pre-release 
the same whatever its name e.g. all rendered by MuPDF thus NOT legacy bold
OP issue is thus Addressed ?

**Comment by kjk** [comment] 2022-06-19 03:55
Yes, looks fixed, thanks.

**Closed by kjk** 2022-06-19 03:55 UTC
Labels: mupdf, ebook
