### ISSUE TITLE
[Feature Request] Scroll bar in one page view

### ISSUE THREAD

**Issue by 9Skrip** [sumatrapdfreader/sumatrapdf#1090] opened 2018-11-05 00:40 UTC
Hello, I propose an option to see the scroll bar in one page view for pdf’s
For usability purpose it is good to see how much progress is there in the open document 
and scrolling by page its much faster than scrolling by line for big documents when you need quick skimming through documents.
It would be good for disabled people to.

**Comment by GitHubRulesOK** [comment] 2018-11-05 21:10
@kjk duplicate of closed https://github.com/sumatrapdfreader/sumatrapdf/issues/191

**Closed** 2018-11-05 21:13 UTC
