### ISSUE TITLE
Table inside pdf doesn't display data

### ISSUE THREAD

**Issue by ktomek80** [sumatrapdfreader/sumatrapdf#317] opened 2015-10-14 08:11 UTC
Hello,

 I've uploaded a pdf file that doesn't display data in table on sumatrapdf v3.0.2z.
The same pdf is displayed correctly on Adobe Reader XI.
Link to file: http://ge.tt/4VSXL0Q2 (file will be available for 30 days)

Regards,
 Tomek

**Comment by campbeb** [comment] 2015-10-14 14:48
That link doesn't work for me.

**Comment by kjk** [comment] 2015-10-14 19:10
[Multimedialny_Dom_WWW_v_5_0__cennik_promocji_08-09-2015.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/13506/Multimedialny_Dom_WWW_v_5_0__cennik_promocji_08-09-2015.pdf)

You have to disable adblockers (at least ublock) to use ge.tt. I've attached this file directly.

**Comment by GitHubRulesOK** [comment] 2020-01-28 18:09
@kjk 
Whilst there has been some change since 3.1.2 it is not a usable result.

![image](https://user-images.githubusercontent.com/12754913/73292091-5233a580-41f9-11ea-85fe-d3f4fba3e1c2.png)

Unclear if it is a bug in MuPDF or text identity but **if it is MuPDF suggest it be flagged** as such.

**Comment by SumatraPeter** [comment] 2020-01-28 19:09
Interestingly it fails partially (first page is blank) with a warning ("This PDF document might not be displayed correctly") in Firefox 72.0.2 (PDF.js), although new ChrEdge is able to display it fine just like the old Edge. File analysis reports an invalid xref table, so looks like Adobe Reader and both Edge versions are doing their best to work around the damage.

Unless current MuPDF in Sumatra daily builds has problems with table display, I'd recommend closing this as not a bug. Optionally could be reported to MuPDF, purely to see if they will make it more robust and able to handle same damage that Adobe Reader and Edge can.

**Comment by GitHubRulesOK** [comment] 2020-01-29 11:26
@kjk I agree with @SumatraPeter this file is a bad example it fails with warnings in many viewers including Acrobat 9 when allowed to be corrected much of the excess baggage disapears and the file drops to 245kb (about half size) which then behaves perfectly 

[317 Multimedialny_Dom_WWW_v_5_0__cennik_promocji_08-09-2015mod.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4127677/317.Multimedialny_Dom_WWW_v_5_0__cennik_promocji_08-09-2015mod.pdf)

**Comment by kjk** [comment] 2020-02-01 01:34
Corrupt file, no plans to work on that unless mupdf adds more recovery code.

**Closed by kjk** 2020-02-01 01:34 UTC
