### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by usergitalberto** [sumatrapdfreader/sumatrapdf#2953] opened 2022-09-13 14:20 UTC
[sumatrapdfcrash.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/9557976/sumatrapdfcrash.txt)

**Comment by jddcef** [comment] 2022-09-13 17:49
I get the same crash it seems....
Here are my logs: https://gist.github.com/jddcef/4bd70861cf47f5f016a137c2799ebc2e

and the file that was being opened
[Eucharist-and-Eschatology.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9559624/Eucharist-and-Eschatology.pdf)

**Comment by GitHubRulesOK** [comment] 2022-09-13 18:28
@jddcef  your sample is annotated and that is noted as causing crashes in current pre-release your log shows 3.5.15239 pre-release 64-bit

**Comment by jddcef** [comment] 2022-09-13 18:33
Ok, would be nice to just not crash, but perhaps show a blank page rather
in the meantime?

**Comment by GitHubRulesOK** [comment] 2022-09-13 18:39
@jddcef 
unless you have an older pre-release from a few weks ago we are waiting on a bug fix so stable is official 3.4.6

**Comment by GitHubRulesOK** [comment] 2022-09-27 03:26
@usergitalberto @jddcef 

Should be fixed in 3.5.15244+ (see note)
likely caused by annotation instability

Note:- current pre-release is 3.5.15249 and on first run MAY crash for a different reason see https://github.com/sumatrapdfreader/sumatrapdf/issues/2984

**Comment by jddcef** [comment] 2022-09-27 19:20
It's fixed. Thanks. #2984 is a problem, on every launch. The workaround is mentioned in that issue though, that's how I managed to test that this issue can be closed as fixed.

**Closed** 2022-10-07 19:52 UTC
