### ISSUE TITLE
Open cbr cbz

### ISSUE THREAD

**Issue by lon0** [sumatrapdfreader/sumatrapdf#139] opened 2015-03-20 23:59 UTC
Hi, in win-7-64bit I can't plan the automatic opening of cbr and cbz files with Sumatra as default, while in win-7-32bit I can do it. Could be added a menu for choosing which extensions to open with Sumatra please?

**Comment by GitHubRulesOK** [comment] 2019-11-16 11:29
@kjk this was a separate request to support issues with user setting file type permissions in win-7 x64 (which still plagues win 10 users) however in light of impending MS "End of Life" declaration for win 7
I am reluctantly suggesting this simply be considered a dupe of  https://github.com/sumatrapdfreader/sumatrapdf/issues/615#

**Comment by kjk** [comment] 2019-11-18 00:36
This is now tracked by #1248

**Closed by kjk** 2019-11-18 00:36 UTC
