### ISSUE TITLE
[Feature request] Add new tab button; have the homescreen (the "Frequently Read" screen) show files in OPDS catalogs and online cloud storage (OneDrive, Google Drive, etc); also why can't I see the app on "Set defaults by app"?

### ISSUE THREAD

**Issue by aa1874** [sumatrapdfreader/sumatrapdf#1751] opened 2020-09-08 12:44 UTC
So there should be a new tab button so that people can open the homescreen ("Frequently Read" screen) easier.

Also I'd like the homescreen to show books in OPDS catalogs and cloud drives...

And why when I go to Settings app > Apps > Default apps > Set defaults by app, the SumatraPDF app didn't show up?

**Comment by SumatraPeter** [comment] 2020-09-08 23:06
@kjk @GitHubRulesOK: Maybe split up into 2 separate issues, or close this?

Request 1 is anyway a duplicate of #406 so can be dropped.

**Comment by GitHubRulesOK** [comment] 2020-09-09 01:35
@kjk 
since the first and last topics are covered elsewhere this is then a request to

> "I'd like the homescreen to show books in OPDS catalogs and cloud drives..."

Since the OPDS system was primarily introduced for Mobile IOS / Android / Web Browser support I guess it would be outside your foreseable remit ?

**Comment by kjk** [comment] 2020-09-09 06:04
let's keep one request per issue

**Closed by kjk** 2020-09-09 06:04 UTC
