### ISSUE TITLE
settings location

### ISSUE THREAD

**Issue by lvmm** [sumatrapdfreader/sumatrapdf#2366] opened 2022-02-22 07:39 UTC
SumatraPDF keeps its advanced settings (SumatraPDF-settings.txt) in AppData\Local. AppData\Roaming would be much more appropriate - Local is for files which shouldn't be backed up. And so I didn't, and lost them :(

**Comment by GitHubRulesOK** [comment] 2022-02-22 15:05
Duplicate of other discussions/issues https://github.com/sumatrapdfreader/sumatrapdf/issues/115 https://github.com/sumatrapdfreader/sumatrapdf/issues/1793 but the session data is relative to each single users locality thus all appdata was moved some time ago into one local appdata 
If you want to set it for roaming you can use the -appdata switch so `"c:\program files\sumatrapdf\sumatrapdf.exe" -appdata %APPDATA%\SumatraPDF can work in that folder (HOWEVER it must exist first so `MD %APPDATA%\SumatraPDF`)

**Closed by GitHubRulesOK** 2022-02-22 15:05 UTC

**Comment by froh** [comment] 2022-10-18 13:46
Hi as a new SumatraPDF user (and a very long time computer user) who just moved from one device to another, I found it confusing to not have my settings and configuration and bookmarks in Roaming aka `%APPDATA%`, the equivalent of `~/.config`

I seriously think the SumatraPDF config / settings file should be under Roaming, consistent with Microsofts spec for Roaming (vs Local):

https://learn.microsoft.com/en-us/windows/apps/design/app-settings/store-and-retrieve-app-data#roaming-data-dos-and-donts

**Comment by GitHubRulesOK** [comment] 2022-10-18 14:10
>https://learn.microsoft.com/en-us/windows/apps/design/app-settings/store-and-retrieve-app-data#local-app-data     Local app data should be used for any information that needs to be preserved between app sessions and is not suitable for roaming app data. Data that is not applicable on other devices should be stored here as well. There is no general size restriction on local data stored. Use the local app data store for data that it does not make sense to roam and for large data sets.

**Comment by lvmm** [comment] 2022-10-18 14:20
And? SumatraPDF settings (or any program settings for that matter) is the data which must be kept in sync across all devices.and therefore IS suitable for roaming data

**Comment by froh** [comment] 2022-10-18 14:48
> The data could have been and was split between various roaming locations, but much is specifically local such as screen or file characteristics, running one day on one monitor and next on two has issues.

hm my laptop in the office has one external monitor, the same laptop in home office has three, and traveling it has one.  that problem needs to be addressed inside the application, if it should be addressed at all.

> crashdumps are specific to one set of hardware 

crashdumps are not part of the config, "settings"?

> etc. so keeping everything local avoids multiple settings and ini files. Adobe is a nightmare to trace as it uses 4 or 5 locations for disparate data. see other examples for user data like `Local\Microsoft` vs roaming\Microsoft or both Adobe folders where much is mixed up in wrong folder so "not suitable for roaming".

in unix lingo that's the difference between ~/.local and ~/.config

I'm very specifically talking about favorites, colors, bookmarks, not crash dumps or cached remote files.  Stuff I'd expect to be available on any machine I log into with my network credentials.  Stuff I'd expect to back up.

in Local, I see the .exe and the .dll, so that is not it.

**Comment by froh** [comment] 2022-10-18 15:37
> Roaming data and settings is [no longer supported as of Windows 11](https://learn.microsoft.com/en-us/windows/deployment/planning/windows-10-deprecated-features).

yes I've seen that warning, I fear apps need to sense their environment for a transitional period, whatever you'd have in Roaming on Windows 10 you'd have in that Microsoft Account on Windows 11.

the point @lvmm and myself are trying to make is that the wonderful `SumatraPDF-settings.txt` should reside in the user specific location, not in the computer specific one.
