### ISSUE TITLE
v3.4.13976 x64: Fails to open XML files

### ISSUE THREAD

**Issue by deus-e-x** [sumatrapdfreader/sumatrapdf#2093] opened 2021-08-04 05:49 UTC
Pre-built 13976 64-bit fails to properly open any XML file.

For a few XML files, a fraction of the content is displayed but without proper formatting. No crash is generated.

The previous pre-built 13970 causes a crash with a log:
https://gist.github.com/deus-e-x/a7aef128f61cdfdc20dc9edf1c2ef1ca

The last version I have available to properly open XML files is pre-built 139740.

**Comment by kjk** [comment] 2021-08-04 06:23
The crash has been fixed.

Please when opening bugs caused by a file, attach the file. There are millions of possible .xml files.

I'm going to close this because I'm not promising Sumatra opens .xml files. It happens to work on a file I tested but it's not officially supported.

I'm thinking about adding support for pretty much any text file (including .xml) using Scintilla code but that's not firm and at best in the future.

**Closed by kjk** 2021-08-04 06:23 UTC
