### ISSUE TITLE
All remembered status are missing

### ISSUE THREAD

**Issue by zkosk** [sumatrapdfreader/sumatrapdf#1840] opened 2020-12-23 04:49 UTC
It have been several times (very rare) when the program suddenly can't remember previous opened documents and their status. The reason is unkown, maybe it is system problem.

Although the reason cannot be identified, the program may save status in a more robust way. For example:

1. First create a new temp status file then delete the old one then rename the new one. 
2. Save several previous versions of the status file, then a rollback can be invoked if some of them are corrupted.

**Comment by GitHubRulesOK** [comment] 2020-12-27 00:17
Session Data WAS a problem in earlier versions, e.g. when SumatraPDF is shut abruptly either due to user keyboard selections to quit or more frequently Windows update.

Status is stored in memory as you make viewer changes, it is thus quicker and does not stop to thrash a disk file.
Current behaviour is to only save settings when files are changed e.g. when tabs are opened/closed.

For that reason I would recommend using a current pre-release or daily build, as it should be more robust.

Saving copies of the settings file has been covered elsewhere but its considered a user action, (some users set up chron jobs) otherwise backup management could become yet another drain on resources. For one example I used in the past when settings were less stable see the related discussion when fixed in https://github.com/sumatrapdfreader/sumatrapdf/issues/1659 but elsewhere I have used a startup that copies the settings file with a date and time.

**Comment by zkosk** [comment] 2021-01-07 08:45
@GitHubRulesOK The version is 3.1.1, is that a very old version? It happened again now. 

Why is session status considered "huge data that can use a lot of resource"? Isn't it a ~1MB file? 

If the last opened files are loaded from a file and the write to the file is never interrupted, then how can this happen?

**Comment by GitHubRulesOK** [comment] 2021-01-07 12:12
3.1.1 is now considered old the most reliable for most functions (except your issue) was 3.1.2 (2016)
There have been thousands of changes since then and a fairly stable version released a year ago as 3.2.0, but that still suffered similar "loss of memory".
I prefer to use the daily builds as they have all the latest improvements, but then I know what features may still be better in older versions, so for example I still often use 3.1.2  to copy and paste (or 3.0.0 for some command line printing) as those two features may include regressions in current pre-release.
Its not the size of storing memory, the idea was not saving it constantly as a disk write (disk thrashing) the "bug" was that it was only saved once reliably on clean closure. That is the step that improved to save on tab changing (AFTER version 3.2.0 so only in current pre-releases.)

**Comment by zkosk** [comment] 2021-01-08 08:06
I don'g get it. When I open the program and the file are already there, there is commonly no change of opened file for my use case. And then the problem occures, all file is missing for the next open.

**Comment by GitHubRulesOK** [comment] 2021-01-08 12:12
Without looking over your shoulder to watch step by step let me try to explain what **may** be happening.
On a "clean" closure, the `SessionData [` is stored, towards the end of the SumatraPDF-settings,txt file thus will re-start with **two or more** previous open tabs.
That list is loaded into memory, and the  `SessionData [` may then need to be discarded e.g. opening say a third file as list is no longer valid. That is the source of the problem since at that point in time a "dirty" closure now has no record of open tabs. The new session data is only written when the session closure is called by  for example using the top right red X with the 3 tabs visible.
You can follow the contents of settings during a session to see that section gets blanked on first new tab open (it is not changed on a single tab closure) but if the settings file is open in notepad when closing sumatrapdf do not save it yourself as it may be out of sync. 
That also reminds me there may be other interference from the file system at time of closure.
The most common reason was that if sumatrapdf is shut by the system then the session is never written so windows updates without a clean manual closure which is/was a very common cause of complaint.

**Comment by zkosk** [comment] 2021-01-09 00:18
Yes this is exactly how it happens. Suggestion:

1. Don't remove the session data in the file when the RAM version change. If a accidental exit occure, at least the file have a most recent version of session. In this case the program also need to support loading old session that have potention inconsistent content.

2. Backup the old session to another file before removing it. And add some flag to the new blank session,like:
SessionData [
temporary
]
When start the program again, if there is this temporary flag, the program will use the old session in the backup file.

**Comment by GitHubRulesOK** [comment] 2021-01-09 00:41
0 and 1 are the new behaviour the tabs data is written when they change, as you can see if using daily pre-release, so will be there in next version. Worst case if crash you should only loose the last tab change.

2. many users did/do backup settings file perhaps using a scripted solution, but that should not be needed with latest AFTER 3.2.

**Comment by zkosk** [comment] 2021-01-09 11:23
BTW There has not been Win10 system problems for a very long time, the only possible "abnormal" event is not closing the program before shutdown/reboot Win10. 

Does the program handle Windows 10 system shutdown appropriately? If so a normal system shutdown/reboot without closing the program first should act like the program is closed first then there should not be a problem.

**Comment by GitHubRulesOK** [comment] 2021-01-09 11:48
In all the years using SumatraPDF most days I have never suffered this problem, but then I use widows Pro and the reported issue seem to affect Home users most.
It is more likely that is because I don't let Microsoft pull the plug without warning, which apparently it did in earlier home versions.

**Comment by zkosk** [comment] 2021-01-10 00:27
I don't get your point, how is your response related to my response?

**Comment by kjk** [comment] 2021-01-10 02:56
Can't do anything without steps to reproduce.

**Closed by kjk** 2021-01-10 02:56 UTC
