### ISSUE TITLE
[feature request] full document search for chm

### ISSUE THREAD

**Issue by tolga694** [sumatrapdfreader/sumatrapdf#1787] opened 2020-10-21 13:47 UTC
"microsoft html help" can do this.
if could print how many matches found that would be nice too.

**Comment by GitHubRulesOK** [comment] 2020-10-21 19:44
Closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/804

You have two/three options either use Alt F M and use the native MShelp Search (lists those found by rank and gives the count) or
Use recent version 3.2/pre-release with Alt D T R to toggle Find box on (and go to next matching entry from previous location) there is no count as it searches for the first matching letter (how many D's do want to search the whole **D**ocument for first)
![image](https://user-images.githubusercontent.com/12754913/96774207-91d09c00-13dd-11eb-822a-420c434ebc44.png)
Use any version with ChmUI setting UseFixedPageUI=true

I normaly would be using second choice (Debug Toggle) most of the time and only call HH for bulk showing of related topics.

**Closed by GitHubRulesOK** 2020-10-21 19:44 UTC
