### ISSUE TITLE
.vbkm unexpected order of entries and levels

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1462] opened 2020-02-17 18:04 UTC
Checking a vbkm after adding a child to root, (page 2 which is the real TOC :- )
I noticed 2 unexpected discrepancies

A) I had intended manually adding the page number, but I was surprised to see this order at the start of the file. i.e. the insertion is before the filename rather than after the pages:

```
version: 999
name: default view
colourschemes.pdf open-default open-toggled
  "Page 2 TOC" font:italic,bold
  file: F:\SumatraPDF\3.2\3.2.12154\colourschemes.pdf
  pages: 20
  "Reference Documents" page:3 destkind:scrollTo destname:#3,57,126 destvalue:"Reference Documents" pos:57,126
  Introduction page:4 destkind:scrollTo destname:#4,57,132 destvalue:Introduction pos:57,132

```

Even more surprised that it worked without complaint

![image](https://user-images.githubusercontent.com/12754913/74675882-87a23200-51ac-11ea-8c1a-4a330fb2b600.png)

B) The second issue also works well, but in theory are "wrong", I have no recollection how it happened (it may have been an earlier version) but although the child pages are not indented with respect to their parent they are treated as siblings and could cause issues later.

```
file: F:\SumatraPDF\3.2\3.2.12154\bookmarked.pdf
pages: 4
A4L.jpg page:1 destkind:scrollTo destname:#1,0,0 destvalue:A4L.jpg pos:0,0
"Midway down Page 1" font:italic,bold color:#ff0000 page:1 destkind:scrollTo destname:#1,0,0 destvalue:"Midway down Page 1" pos:0,350
A4P.jpg page:2 destkind:scrollTo destname:#2,0,0 destvalue:A4P.jpg pos:0,0
A5L.jpg page:3 destkind:scrollTo destname:#3,0,0 destvalue:A5L.jpg pos:0,0
A5P.jpg page:4 destkind:scrollTo destname:#4,0,0 destvalue:A5P.jpg pos:0,0
```

However the entries should have been inset
```
file: F:\SumatraPDF\3.2\3.2.12154\bookmarked.pdf
pages: 4
  A4L.jpg page:1 destkind:scrollTo destname:#1,0,0 destvalue:A4L.jpg pos:0,0
  "Midway down Page 1" font:italic,bold color:#ff0000 page:1 destkind:scrollTo destname:#1,0,0 destvalue:"Midway down Page 1" pos:0,350
  A4P.jpg page:2 destkind:scrollTo destname:#2,0,0 destvalue:A4P.jpg pos:0,0
  A5L.jpg page:3 destkind:scrollTo destname:#3,0,0 destvalue:A5L.jpg pos:0,0
  A5P.jpg page:4 destkind:scrollTo destname:#4,0,0 destvalue:A5P.jpg pos:0,0

```

**Comment by kjk** [comment] 2020-02-18 00:13
This code is in flux. Both cases seem like created with earlier build as I can't reproduce it with current build.

For that reason, I'm closing this. 

Please re-open if you find a way to reproduce this using Toc Editor in current build. If that happens, please post repro steps.

Editing manually, while possible, is "do at your own risk".

**Closed by kjk** 2020-02-18 00:13 UTC

**Comment by GitHubRulesOK** [comment] 2020-02-18 01:11
Ok agree current version seems to behave
