### ISSUE TITLE
Toolbar icons have pink background on Win 10 Preview Build 14295

### ISSUE THREAD

**Issue by alanrunner** [sumatrapdfreader/sumatrapdf#484] opened 2016-04-02 00:46 UTC
With the Windows 10 preview build 14295, the toolbar icons in Sumatra PDF look strange.  Furthermore, some communication features are broken.  For example, the forward search from a LaTeX document in WinEdt 9.1 will launch Sumatra PDF, but not open the file and it produces an error message.

**Comment by kjk** [comment] 2016-04-02 00:53
For the icon issue, please provide screenshot. I don't know what "look strange" means.

As to forward search, is it specific to that build i.e. did it work on earlier builds?
What is the exact error message?
How did you configure winEdt? Most problems in this area are due to not configuring things correctly.

**Comment by alanrunner** [comment] 2016-04-05 03:16
Krzysztof,

Here is a detailed reproduction of the problem that I mentioned on my
GitHub post. Perhaps, I should have simply used email since I don't know
how to use GitHub properly.  (I'm cc'ing to Alex at winedt.com since he
should probably know about it too.)

I had no problem with using the default settings for forward and inverse
search between WinEdt and SumatraPDF until Windows Insider installed
Windows 10 Preview Build 14295 on my computers a few days ago.  The I had
trouble and needed to get work done. After I rolled back the installation
to the previous build of Windows, the problem completely went away.  That
is, in Windows Version 1511 (OS Build 10586.164) everything works fine the
way you programmed the two programs.

So, today I replicated the problem in the GitHub post by installed Windows
10 Preview Build 14295.rs1_release.160318-1628) in VirtualBox.  (
Capture0.PNG)

Then I installed MiKTeX, WinEdt 9.1, and SumatraPDF 3.1.1.  (See
Capture1.PNG)

Open a LaTeX file in WinEdt and compile with PDFTexify.  The first page
appears in SumatraPDF and nothing seems wrong. (Capture2.PNG)

I open the settings windows in both WinEdt and SumatraPDF to verify that
the paths and options listed there make sense. (Capture3.PNG)

Place the cursor in WinEdt near the end of the LaTeX file and click on
forward search.  The PDF file is no longer is displayed in SumatraPDF,
WinEdt opens the file "PDF Search.edt" and highlights line 39.  A popup
dialog appears with a warning that "Client Communication is not currently
established" etc.  (Capture4.PNG)

In Windows Options go to Display -> Customize Your Display  and change the
slider below the words "Change the size of text, apps, and other items." to
150% (or just about anything larger than 100%).  Since I have 4K resolution
monitors on my desks, I have them normally set at 150% zoom.

Log out and re-login for the zoom setting to take effect.  Open a PDF file
in SumatraPDF and the toolbar icons are strangely pink.  (Capture5.PNG)
 With the same Windows zoom setting in the earlier Windows version the
toolbar looks normal.

I hope this description will be useful to you

David

**Comment by kjk** [comment] 2016-04-05 03:19
@alanrunner it looks like the screenshots are missing (I imagine they are not supported when responding by email)

**Comment by alanrunner** [comment] 2016-04-05 03:22
Sorry about the missing screenshots. Here they are:
<img width="226" alt="capture0" src="https://cloud.githubusercontent.com/assets/18223141/14270414/2db75128-faab-11e5-9250-1aa65f2b71b5.PNG">
![capture1](https://cloud.githubusercontent.com/assets/18223141/14270416/312cd788-faab-11e5-9ab6-fb07610cfee2.PNG)
![capture2](https://cloud.githubusercontent.com/assets/18223141/14270420/34f73a20-faab-11e5-9ab3-f5650e349a8c.PNG)
![capture3](https://cloud.githubusercontent.com/assets/18223141/14270421/391fc8f6-faab-11e5-863b-e8f3f61aeafb.PNG)
![capture4](https://cloud.githubusercontent.com/assets/18223141/14270423/3da3bf18-faab-11e5-821e-0a802e66a2ae.PNG)
<img width="960" alt="capture5" src="https://cloud.githubusercontent.com/assets/18223141/14270426/41ba99fa-faab-11e5-8cf2-d290c62d839e.PNG">

**Comment by alanrunner** [comment] 2016-04-05 16:39
David,

> Place the cursor in WinEdt near the end of the LaTeX file and click
> on forward search. The PDF file is no longer is displayed in
> SumatraPDF, WinEdt opens the file "PDF Search.edt" and highlights
> line 39. A popup dialog appears with a warning that "Client
> Communication is not currently established" etc. (Capture4.PNG)

WinEdt 10 no longer uses DDE for this purpose for this very reason.

You can replace all 4 lines pertaining to Sumatra DDE

  DDEOpen("%$('PDF-View');","SUMATRA","control",1);
  DDEExe('[Open("%P\%N.pdf",0,1,1)]');
  DDEExe('[ForwardSearch("%P\%N.pdf","%p\%n%t",%!l,0,0,1)]');
  DDEClose;

with a single line

  Run('%$("PDF-View"); -reuse-instance "%P\%N.pdf" -forward-search "%p\%n%t" %!l');

Or update to WinEdt 10 which does this in its default settings.

This is much better than using DDE which is less and less reliable
and it does not (and will not) support Unicode filenames.

The second problem is for Krzysztof. It seems that SumatraPDF uses
(24-bit) bitmaps with (standard) magenta being used as a
transparent color. Something goes wrong with this when
virtualization is enabled (perhaps transparent color hue changes).
I am sure he'll figure it out.

WinEdt, on the other hand, is dpi-aware and it uses a set of png
image collections at different sizes to adjust to your
magnification (dpi) without virtualization: it should not look
blurry in any way on high dpi...

Best regards,

alex

**Comment by kjk** [comment] 2016-06-23 04:39
fixed in e999bd8fd609b9e50ac39d70580c854cf1700ea4

**Closed by kjk** 2016-06-23 04:39 UTC

**Comment by rileal** [comment] 2016-08-11 09:22
This is happening to me after Windows 10 Anniversary Update.

**Comment by Netskeh** [comment] 2016-08-18 06:05
I can confirm this. Installed version is: 3.1.1 64bit

**Comment by Netskeh** [comment] 2016-08-18 06:11
and ofcourse I noticed only after posting there is a v3.1.2 which fixes the problem (for me)
