### ISSUE TITLE
A bug of version 3.5+ when using Total Commander+SumatraPDF to preview PDFs

### ISSUE THREAD

**Issue by YandLiu** [sumatrapdfreader/sumatrapdf#4342] opened 2024-06-26 09:21 UTC
**SumatraPDF version**
- 3.5 ~ 3.5.2

Actually I have exactly the same issue with the discussion below, since bug reports in Discussions are ignored, I quote it here:
https://github.com/sumatrapdfreader/sumatrapdf/discussions/4010

The info that I want to supplement is:
Version 3.4.6 is the last version without the bug, the bug appears from 3.5.

**Comment by GitHubRulesOK** [comment] 2024-06-26 10:44
It is NOT a SumatraPDF bug  there is NO WLX support see https://github.com/sumatrapdfreader/sumatrapdf/issues/418

It is a bug in using SumatraPDF with commander Wix  code base as the control is several of those such as `slister.wlx` or similar. This was discussed as an issue (although it is not a SumatraPDF code)

Closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/3798

**Closed by GitHubRulesOK** 2024-06-26 10:44 UTC
