### ISSUE TITLE
Sumatra Crashed while loading several documents.

### ISSUE THREAD

**Issue by umaarabdullah** [sumatrapdfreader/sumatrapdf#2966] opened 2022-09-19 15:29 UTC
https://gist.github.com/umaarabdullah/d82ae5601772b5fb81620e9bfb8f26cb

I selected multiple pdfs to open and then while sumatra was loading the pdfs it crashed.

**Comment by GitHubRulesOK** [comment] 2022-09-27 03:24
Should be fixed in 3.5.15244+ (see note)
likely caused by annotation instability, please check again

Note:- current pre-release is 3.5.15249 and on first run MAY crash for a different reason see https://github.com/sumatrapdfreader/sumatrapdf/issues/2984

**Comment by kjk** [comment] 2022-10-08 02:18
most likely fixed

**Closed by kjk** 2022-10-08 02:18 UTC
