### ISSUE TITLE
Highlighting on wrong page

### ISSUE THREAD

**Issue by m00xx** [sumatrapdfreader/sumatrapdf#1806] opened 2020-11-11 10:24 UTC
Hi, 

With recent builds I have an issue where highlighting selected text highlights the corresponding area on a previous page, however this only occurs on alternate pages- so:

page 1- pressing a highlights the selected text on page 1 (correctly)
page 2- highlights an area on page 1 corresponding to the selected text on page 2
page 3- highlights the selected text on page 3 (correctly)
page 4- highlights the corresponding area on page 3

...and so on.  Whether it starts on page 1 or 2 seems to vary depending on the pdf I have open. It happens on any of the view settings (single/ book/ facing/ continuous). I'm mostly viewing books (1000+ pages) if that makes a difference.

Thank you!

**Comment by GitHubRulesOK** [comment] 2020-11-11 11:21
Possibly Known issue i.e. duplicate of a previous report
was a long time problem for Highlight Jump see https://github.com/nod5/HighlightJump/issues/5

It is caused when using either 2 page (facing/book) mode or in somecases continuous pages
The page counter report for actions is generally 1 page behind current focus unsure if in rare cases when moving backwards it may be in advance.

**Comment by m00xx** [comment] 2020-11-11 12:27
Ah I missed that -the ideas on the linked page might be a bit beyond me so I guess will have to wait for a fix.

Thanks!

**Comment by GitHubRulesOK** [comment] 2020-11-11 16:41
If you are in single page mode then it should not be a problem when highlighting.
Also since delete in recent builds is per object where page should then be correct in the listing it should not lead to mis-deletion.

**Comment by GitHubRulesOK** [comment] 2020-11-11 23:39
Closing as Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1705

**Closed by GitHubRulesOK** 2020-11-11 23:39 UTC
