### ISSUE TITLE
Sumatra PDF crashes after start after i removed some files

### ISSUE THREAD

**Issue by drweb86** [sumatrapdfreader/sumatrapdf#895] opened 2017-09-19 10:15 UTC
Hello

After removing some files application keeps crashing.

I've uploaded dump to google drive:
https://drive.google.com/open?id=0BxH0trduQjP2SEwwazFHblNHRms

Thanks.

**Comment by drweb86** [comment] 2017-09-19 10:16
Problem disappeared after removing settings file.

**Comment by SumatraPeter** [comment] 2017-09-26 15:59
If the problem is resolved you can close this issue.

Otherwise perhaps it might be useful to provide some additional details to help the dev. For example, what does "some files" refer to? Did you delete some program files, or documents whose **FileStates** were saved in the [settings file](https://www.sumatrapdfreader.org/settings.html)?

**Closed** 2020-02-07 03:43 UTC
