### ISSUE TITLE
Moiré effects on gradients

### ISSUE THREAD

**Issue by eth42** [sumatrapdfreader/sumatrapdf#1742] opened 2020-08-27 16:16 UTC
Hi,

I recently created some graphics with LaTeX/Tikz/pgfplots consisting of gradient colored surfaces that when opened with SumatraPDF (both 3.1.2 and 3.2) create Moiré effects. All other PDF clients manage to properly display these graphics (except for Inkscape, which crashes, but that might be due to a corrupted installation...). I have attached two example PDFs, one without (example1.pdf) and one with (example2.pdf) overlapping transparent gradient surfaces. I hope these examples suffice on your end.

Best regards
eth42

[example1.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5137570/example1.pdf)
[example2.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5137571/example2.pdf)

**Comment by GitHubRulesOK** [comment] 2020-08-27 22:19
Whilst the process is different the root problem appears to be same as in #595 and #1443 i.e. MuPDF does not render PGFplots smoothly.
I am thus closing as a duplicate of either of those (which in turn should probably be consolidated but have been raised as seperate bugs in MuPDF)

**Closed by GitHubRulesOK** 2020-08-27 22:19 UTC

**Comment by GitHubRulesOK** [comment] 2021-01-11 13:33
Note #595 was closed recently so consolidate this with still open issue #1443

**Comment by GitHubRulesOK** [comment] 2021-01-15 02:26
Just an update that this issue was closed in 3.3.13250 daily build today 15/jan/2021
