### ISSUE TITLE
The "UseSysColors = true" setting does not work.

### ISSUE THREAD

**Issue by Accelerator21** [sumatrapdfreader/sumatrapdf#2951] opened 2022-09-11 03:35 UTC
The "UseSysColors = true" setting does not work in Windows10.

![Snipaste_2022-09-11_11-33-58](https://user-images.githubusercontent.com/95729491/189511289-640433f6-7a38-429a-8313-c17cd07a6c70.png)

**Comment by GitHubRulesOK** [comment] 2022-09-11 16:03
it does but starting win 8/10/11 is not using it as it did in XP when it was added nor win 7  when generally ignored

the best way to control those sys colours is via windows blinds

closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/2823

**Closed** 2022-09-11 16:04 UTC

**Comment by thinkfan** [comment] 2023-11-01 04:56
Windows 10 is ok before version 3.5. "UseSysColors = true" is one of my favorite SumatraPdf features, but sadly it's gone...
![2023-11-01_123631](https://github.com/sumatrapdfreader/sumatrapdf/assets/1967862/d964b7e7-bb15-4991-82ea-491a94308efa)
