### ISSUE TITLE
Feature request: Tab and window

### ISSUE THREAD

**Issue by tylerkoh** [sumatrapdfreader/sumatrapdf#630] opened 2016-10-05 09:07 UTC
It would be really useful if we could use tabs and windows at the same time like chrome.
So opening 2 pdfs windows at once while being able to organize your tabs is a really useful feature to have.

Thanks

**Comment by SumatraPeter** [comment] 2016-10-06 17:35
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/18

**Closed** 2016-10-06 18:19 UTC
