### ISSUE TITLE
Cannot use "Find" function or Toolbar for epub

### ISSUE THREAD

**Issue by yEngineer7** [sumatrapdfreader/sumatrapdf#1653] opened 2020-07-01 13:06 UTC
I'm reading epub, and cannot use the "Find" function (Ctrl-F) whatsoever; I can also not toggle the Toolbar (F8). I have set the advance settings of both "ShowToolbar" and "UseFixedPageUI" to be true, to no avail. I have tried with pdf and do not face these problems.

Is there something I forgot to apply, or is this an in-built disability for epub files?

I'm running the latest version (v3.2 64-bit) on Windows 10.

**Comment by GitHubRulesOK** [comment] 2020-07-01 14:16
Manually it should look like this
```
EbookUI [
	FontName = Kai
	FontSize = 16
	TextColor = #5f4b32
	BackgroundColor = #fbf0d9
	UseFixedPageUI = true
]
```


HOWEVER There is a new option in 3.2 to make it "easier"
![image](https://user-images.githubusercontent.com/12754913/86254344-96aedd00-bbad-11ea-9679-a4266a1f600e.png)

**Comment by yEngineer7** [comment] 2020-07-02 05:48
Yea doing so works, but unfortunately it fixed the page width and turned it into a pdf-style reading experience, which I feel is really restrictive for an epub (there is a lot of empty space on both sides even when under Facing mode) ... would really enjoy more customization under non fixed UI mode. Sigh

**Comment by GitHubRulesOK** [comment] 2020-07-02 13:03
Am closing as the "find" issue is addressed by the alternative fixed page UI method, and in effect is a duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/239
@kjk
Tagging as ebook for potential upcomming ? review of interface
@yEngineer7 
I agree it would be desirable to search within re-flow mode (which is possible using the Artifex MuPDF-GL application)

**Closed by GitHubRulesOK** 2020-07-02 13:03 UTC
Labels: ebook
