### ISSUE TITLE
Sort pages from right to left

### ISSUE THREAD

**Issue by AnotherCollector** [sumatrapdfreader/sumatrapdf#1808] opened 2020-11-13 09:13 UTC
Hello,
please add an option so we can sort pages from right to left, facing view would be as follow:
2 1
4 3
6 5

and book view:
   1
3 2
5 4

I can't stress how important is this option, it's really useful for documents in Arabic, Persian, Hebrew.
Thank you

**Comment by GitHubRulesOK** [comment] 2020-11-13 11:31
Closing as Duplicate of 
RT View order support with default LR #1545 and others linked

**Closed by GitHubRulesOK** 2020-11-13 11:31 UTC
