### ISSUE TITLE
3.4.6.0 check for update error

### ISSUE THREAD

**Issue by greenozon** [sumatrapdfreader/sumatrapdf#3306] opened 2023-02-26 21:26 UTC
Help -> Check for update showing this error:

---------------------------
SumatraPDF Update
---------------------------
Can't connect to the Internet (error 0x2).
---------------------------
OK   
---------------------------

Win7 x64 SP1

PS of course internet is fully functional :)

**Comment by GitHubRulesOK** [comment] 2023-02-26 23:54
duplicate of something already issued.

**Comment by kjk** [comment] 2023-02-27 02:21
Yes there are reports that somehow our http code fails on win7.

Could you provide the logs from latest pre-release (https://www.sumatrapdfreader.org/prerelease):
* get latest pre-release
* `Ctrl + K` for command palette and `check for updates`
* if it fails, `Ctrl + K` and `show log`

This should launch a text editor with logs. Could you post the logs here?

This would help me understand where the code fails.

**Comment by greenozon** [comment] 2023-02-27 04:56
Yeah, did as you asked for, here is the contents of log:

```
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF, InstallLocation) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF, InstallLocation) => '(null)'
InstallCrashHandler crashDumpPath: 'C:\Users\user\Downloads\crashinfo\sumatrapdfcrash.dmp'
crashFilePath: 'C:\Users\user\Downloads\crashinfo\sumatrapdfcrash.txt'
symDir: 'C:\Users\user\Downloads\crashinfo'
Starting SumatraPDF 15320, GetCommandLineW():
"C:\Users\user\Downloads\SumatraPDF-prerel-64.exe" 
LoadSettings() took 0.70 ms
ParseTranslationsTxt: 20283 lines, nStrings: 364
StartMonitoringDirForChangesAPC() C:\Users\user\Downloads
HttpGet: url: 'https://www.sumatrapdfreader.org/updatecheck-pre-release.txt?v=15320&os=7&64bit=yes&lang=en&webview=109.0.1518.78&force'
HttpGet: InternetOpenUrl failed
LogLastError: The system cannot find the file specified.

ShowAutoUpdateDialog: http get of 'https://www.sumatrapdfreader.org/updatecheck-pre-release.txt?v=15320&os=7&64bit=yes&lang=en&webview=109.0.1518.78&force' failed with 2

```

**Comment by greenozon** [comment] 2023-02-27 04:59
Please note that exe did not create the above mentioned crashinfo dir
so I do not see any crash txt or dmp file..
any clues?

**Comment by greenozon** [comment] 2023-02-27 05:01
URL itself opens in the browser (Google Chrome) just fine:

![image](https://user-images.githubusercontent.com/765343/221478339-8b25683d-72c8-4ef7-af62-1608acc7dd09.png)

**Comment by kjk** [comment] 2023-02-27 05:54
Could you re-try with latest pre-release 15322 or later?

I've made a change that has a some chance of fixing this on win7 but I don't have access to win7 for testing myself.

**Comment by greenozon** [comment] 2023-02-27 06:01
Could you hint me where could I get the built version you asked for?

**Comment by kjk** [comment] 2023-02-27 06:02
https://www.sumatrapdfreader.org/prerelease

If it shows an older version than 15322, refresh the page

**Comment by greenozon** [comment] 2023-02-27 06:14
Thanks!

executed same steps, looks like same issue:

```
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF, InstallLocation) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF, InstallLocation) => '(null)'
InstallCrashHandler crashDumpPath: 'C:\Users\user\Downloads\crashinfo\sumatrapdfcrash.dmp'
crashFilePath: 'C:\Users\user\Downloads\crashinfo\sumatrapdfcrash.txt'
symDir: 'C:\Users\user\Downloads\crashinfo'
Starting SumatraPDF 15322, GetCommandLineW():
"C:\Users\user\Downloads\SumatraPDF-prerel-64.exe" 
LoadSettings() took 0.61 ms
ParseTranslationsTxt: 20283 lines, nStrings: 364
StartMonitoringDirForChangesAPC() C:\Users\user\Downloads
HttpGet: url: 'https://www.sumatrapdfreader.org/updatecheck-pre-release.txt?v=15322&os=7&64bit=yes&lang=en&webview=109.0.1518.78&force'
HttpGet: InternetOpenUrl failed
LogLastError: The system cannot find the file specified.

ShowAutoUpdateDialog: http get of 'https://www.sumatrapdfreader.org/updatecheck-pre-release.txt?v=15322&os=7&64bit=yes&lang=en&webview=109.0.1518.78&force' failed with 2

```

**Comment by greenozon** [comment] 2023-02-27 06:16
Error  code 2 is a bit misleading...

Could we try instead this WinAPI?  [InternetGetLastResponseInfo](http://msdn.microsoft.com/en-us/library/aa384717(v=VS.85).aspx).

**Comment by kjk** [comment] 2023-02-27 06:41
I've added logging with [InternetGetLastResponseInfo](http://msdn.microsoft.com/en-us/library/aa384717(v=VS.85).aspx), should be in 15323 but I've run out of ideas.

Maybe it would help if I re-wrote http download with https://learn.microsoft.com/en-us/windows/win32/winhttp/using-winhttp

Someone suggested that the issue is that Win7 doesn't support SSL ciphers that cloudflare uses and the update file is hosted on my website proxied by cloudflare.

A reference to similar problem: https://community.cloudflare.com/t/fix-error-ssl-version/361867

If that's the case I'm not sure switching to a different windows api will help.

Chrome might work because they have their own http stack written from scratch.

A fix could be to have multiple locations for https://www.sumatrapdfreader.org/updatecheck-pre-release.txt, at least one of them not on a website proxied by cloudflare.

But then also downloading the .exe for auto-update won't work and I don't want to provide multiple locations for those because those are big files.

Or maybe I need to reconfigure sumatra website as described in https://community.cloudflare.com/t/community-tip-fixing-err-ssl-version-or-cipher-mismatch-in-google-chrome/42162

**Comment by greenozon** [comment] 2023-02-27 08:05
I've tried a fresh build, but I do not see any extra error info..

Does it mean that I do not hit the "if (err == ERROR_INTERNET_EXTENDED_ERROR)"  condition?

```
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF, InstallLocation) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF, InstallLocation) => '(null)'
InstallCrashHandler crashDumpPath: 'C:\Users\user\Downloads\crashinfo\sumatrapdfcrash.dmp'
crashFilePath: 'C:\Users\user\Downloads\crashinfo\sumatrapdfcrash.txt'
symDir: 'C:\Users\user\Downloads\crashinfo'
Starting SumatraPDF 15324, GetCommandLineW():
"C:\Users\user\Downloads\SumatraPDF-prerel-15324-64.exe" 
LoadSettings() took 0.94 ms
ParseTranslationsTxt: 20283 lines, nStrings: 364
StartMonitoringDirForChangesAPC() C:\Users\user\Downloads
HttpGet: url: 'https://www.sumatrapdfreader.org/updatecheck-pre-release.txt?v=15324&os=7&64bit=yes&lang=en&webview=109.0.1518.78&force'
HttpGet: InternetOpenUrl failed
LogLastError: The system cannot find the file specified.

ShowAutoUpdateDialog: http get of 'https://www.sumatrapdfreader.org/updatecheck-pre-release.txt?v=15324&os=7&64bit=yes&lang=en&webview=109.0.1518.78&force' failed with 2

```

**Comment by greenozon** [comment] 2023-02-27 09:05
Am I right supposing that you are using same WinAPI that old IE is using?
I've tried IE11 on my W7 OS and got this:

![image](https://user-images.githubusercontent.com/765343/221519968-5a7abe02-e01c-49b5-b5bb-5424cadbb2e9.png)


the quesiton is: what is the cipher suite your server is using, is it TLS1.3 only?
if yes, then I guess we could do nothing, W7 will never support it, but in case you are proposing TLS1.1 or 1.2 then there still should be some mystery in between...

PS I still would like to see a real error code not just 2 as HttGet() is reporting back..

**Comment by GitHubRulesOK** [comment] 2023-02-27 13:36
hmmm 
@greenozon not on 7 at present so just conjecture, but your possibly looking in the right TLS area.
had problems with powershell and win 7 downloads in the past needing different authorities and protocol switch back and forth between two TLS states, also more recent win 10 issues with reducing trident functionality (MS tugging the Rug slowly?)

**Comment by kjk** [comment] 2023-02-27 15:33
@greenozon Could you try to access https://sumatra-website.onrender.com/free-pdf-reader in ie11 and see if it can be seen?

I'm trying to figure out if its my Cloudflare settings or Cloudflare in general.

> Does it mean that I do not hit the "if (err == ERROR_INTERNET_EXTENDED_ERROR)" condition?

Yes, that would be my guess.

**Comment by greenozon** [comment] 2023-02-27 16:06
1) yes - it works in IE11 under W7!
eg:

![image](https://user-images.githubusercontent.com/765343/221615563-3b17957d-1b0e-448c-8a41-de241311ac2b.png)



Out of curiosity, I've tried curl util under Win7 -  works fine, but it shows a worrying fact - usage of TLS 1.3 ... :(
as well as HTTP/2  (does wininet support it?)

```

c:\Prg\inet\curl>curl -vv https://www.sumatrapdfreader.org/updatecheck-pre-release.txt
*   Trying 172.67.68.92:443...
* Connected to www.sumatrapdfreader.org (172.67.68.92) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: c:\Prg\inet\curl\curl-ca-bundle.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=www.sumatrapdfreader.org
*  start date: Jan 28 18:36:20 2023 GMT
*  expire date: Apr 28 18:36:19 2023 GMT
*  subjectAltName: host "www.sumatrapdfreader.org" matched cert's "www.sumatrapdfreader.org"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* using HTTP/2
* h2h3 [:method: GET]
* h2h3 [:path: /updatecheck-pre-release.txt]
* h2h3 [:scheme: https]
* h2h3 [:authority: www.sumatrapdfreader.org]
* h2h3 [user-agent: curl/7.88.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x2ad350)
> GET /updatecheck-pre-release.txt HTTP/2
> Host: www.sumatrapdfreader.org
> user-agent: curl/7.88.1
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 200
< date: Mon, 27 Feb 2023 16:00:32 GMT
< content-type: text/plain; charset=utf-8
< cache-control: no-store
< vary: Accept-Encoding
< cf-cache-status: DYNAMIC
< x-content-type-options: nosniff
< x-render-origin-server: Render
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=O54udHruVR5O81H0PwILC0d28oKNm3lcY3LcSbYS2ZyGwt45JiovJn9hwDO4q8lbKS8JQR5Xt0TBoREFYB8%2Bv%2BZnSkyePEOTu9rm83mHLk4orN0cj7v1
XrlYHLNxh4nV7h6MTq%2B6SrBTMQ%3D%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 7a02224718e73bd2-WAW
<
[SumatraPDF]
Latest: 15324
Installer64: https://www.sumatrapdfreader.org/dl/prerel/15324/SumatraPDF-prerel-64-install.exe
Installer32: https://www.sumatrapdfreader.org/dl/prerel/15324/SumatraPDF-prerel-install.exe
PortableExe64: https://www.sumatrapdfreader.org/dl/prerel/15324/SumatraPDF-prerel-64.exe
PortableExe32: https://www.sumatrapdfreader.org/dl/prerel/15324/SumatraPDF-prerel.exe
PortableZip64: https://www.sumatrapdfreader.org/dl/prerel/15324/SumatraPDF-prerel-64.zip
PortableZip32: https://www.sumatrapdfreader.org/dl/prerel/15324/SumatraPDF-prerel.zip
* Connection #0 to host www.sumatrapdfreader.org left intact

c:\Prg\inet\curl>curl --version
curl 7.88.1 (x86_64-w64-mingw32) libcurl/7.88.1 OpenSSL/3.0.8 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 WinIDN libssh2/1.10.0 nghttp2/1.52.0 ngtcp2/0.13.1 nghttp3/0.9.0 libgsasl/2.2.0
Release-Date: 2023-02-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets zstd

```

**Comment by greenozon** [comment] 2023-02-27 16:07
But, I"m confused even more - when I tried to curl your 2nd site (as on the picture above which works in IE)
I see it still talks using TLS 1.3 (how come? IE11 as well as Win7 itself does not know/support TLS 1.3!!!??

```
c:\Prg\inet\curl>curl -vv https://sumatra-website.onrender.com/free-pdf-reader
*   Trying 216.24.57.3:443...
* Connected to sumatra-website.onrender.com (216.24.57.3) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: c:\Prg\inet\curl\curl-ca-bundle.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=onrender.com
*  start date: Dec 19 00:00:00 2022 GMT
*  expire date: Mar 19 23:59:59 2023 GMT
*  subjectAltName: host "sumatra-website.onrender.com" matched cert's "*.onrender.com"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* using HTTP/2
* h2h3 [:method: GET]
* h2h3 [:path: /free-pdf-reader]
* h2h3 [:scheme: https]
* h2h3 [:authority: sumatra-website.onrender.com]
* h2h3 [user-agent: curl/7.88.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x15f390)
> GET /free-pdf-reader HTTP/2
> Host: sumatra-website.onrender.com
> user-agent: curl/7.88.1
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 200
< date: Mon, 27 Feb 2023 16:05:31 GMT
< content-type: text/html; charset=utf-8
< cf-ray: 7a0229953dc8bfbe-WAW
< last-modified: Sun, 12 Feb 2023 00:30:20 GMT
< vary: Accept-Encoding
< cf-cache-status: DYNAMIC
< x-render-origin-server: Render
< server: cloudflare
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
<
<!DOCTYPE html>
<html>

<head>
  <meta http-equiv="Content-Language" content="en-us" />
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <meta name="keywords" content="pdf, epub, mobi, chm, cbr, cbz, xps, djvu, reader, viewer" />


.................  ,[ trimmed by myself ]
...........
```

**Comment by kjk** [comment] 2023-02-27 16:29
Could you re-try https://www.sumatrapdfreader.org/prerelease in ie11? I've changed Cloudflare settings to only DNS vs. proxying.

I'm afraid the nuances of TLS are above my head.

The thing is, both addresses are the same site and both are behind Cloudflare.

I run the website on render.com and sumatra-website.onrender.com is the domain name managed by render.com. The thing is, they use cloudflare as a proxy for that.

I then use cloudflare DNS to map www.sumatrapdf.org to sumatra-website.onrender.com.

I chose to proxy mode for that where browser http requests goes to cloudflare and cloudflare does http request to sumatra-website.onrender.com and returns that result.

I don't see why this should break things. I've used default cloudflare settings.

So now I've changed cloudflare to just do DNS so browser http request should go straight to sumatra-website.onrender.com

**Comment by greenozon** [comment] 2023-02-27 17:28
re-tried, result is negative ...

![image](https://user-images.githubusercontent.com/765343/221637354-b2815d05-f613-429d-839d-e1ac73cad64a.png)

Thank you for your tries! I hope we figure the thing out soon!

**Comment by greenozon** [comment] 2023-02-27 17:37
OK, I spent some time by asking one SSL analyzer web site to query both your web sites
Looks like I"ve found the root cause..
Briefly - both sites uses different  set of crypto-options inside TLS1.2  suite

1) working site (IE11/W7  = OK)
sumatra-website.onrender.com

![image](https://user-images.githubusercontent.com/765343/221639877-bedfdb5a-25e2-4bb4-8cad-f808bec35763.png)

2) non-working site (IE11/W7 = ERROR)
www.sumatrapdfreader.org

![image](https://user-images.githubusercontent.com/765343/221640109-5872bf32-0b7b-4d64-a062-2941947a5076.png)



SUMMARY - the 2nd site is missing the following cipher in TLS1.2 suite:

TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)  

I believe once you configur it (or make ciphers same as on 1st site)  you'll finish this crazy journey and unlock the big (I still believe) community of old good lamp Win7  OS :)

**Comment by kjk** [comment] 2023-02-27 17:56
Thanks for digging in ssltest link. I'll fiddle with cloudflare settings to hopefully find a way to make them win7 compatible.

I'm having trouble finding instructions but at least now I can re-test if it works myself with ssltest tool.

**Comment by greenozon** [comment] 2023-02-27 18:23
Good luck!
at least we have some light in the tunnel with approaching train :)

**Comment by kjk** [comment] 2023-02-27 18:49
Some notes: https://community.cloudflare.com/t/ssl-problem-in-some-old-pc/398463/4
Someone fixed it by getting "Advanced Certificate" in SSL/Edge Certificate. $10 month.

I disabled and re-enabled Universal SSL. Didn't help or maybe I didn't wait long enough.

https://community.cloudflare.com/t/missing-ciphers-after-moving-to-cloudflare/3803/2 - says needs "Dedicated SSL certificate" (but it's 2017 so maybe it's "Advanced Certificate"


https://community.cloudflare.com/t/acm-lets-encrypt-certificate-does-not-include-rsa/206965/4

I tried https://developers.cloudflare.com/api/operations/zone-settings-change-ciphers-setting with value: [] but got rejected with ""Advanced Certificate Manager is required to set custom cipher suites""

**Comment by greenozon** [comment] 2023-02-27 20:47
I see that your site now resolves to 6 IP addresses (3 IPv6 and 3 IPv4)
but still I see a sad picture - TLS 1.2 suite does not have the needed cipher, eg:

https://www.ssllabs.com/ssltest/analyze.html?d=www.sumatrapdfreader.org&s=104.26.9.244

![image](https://user-images.githubusercontent.com/765343/221681910-2fb423e6-31c0-449b-8cb7-142ffc4d68f3.png)

**Comment by kjk** [comment] 2023-02-27 21:21
Yeah. I did generate a new certificate and removed the old one in Cloudflare dashboard but the old one is still showing up in those tests.

You can tell because the Issuer of the old one is R3 (Let's Encrypt) and the new one should be DigiCert.

I'm hoping this is just a caching issue (i.e. the old certificate is still on Cloudflare's edge servers) and will solve itself. Various comments suggest it could take hours to propagate certificates. I'll re-check tomorrow.

**Comment by LaurieWilliams5066** [comment] 2023-03-14 02:36
Today I tried updating Sumatra again.
Same error.

I uninstalled Sumatra and installed this version from your pre release page:
Latest SumatraPDF pre-release build version 15345, built on 2023-03-11 , commit b114157d5e7f83a0831e9f7a5e13ab01bbbc5d3b

I tried updating it.
Same error.

The other programs I mentioned
Opera
Thunderbird
VLC Media Player
Internet Download Manager
7+ Taskbar Tweaker
and others
in this earlier discussion about the same problem
https://github.com/sumatrapdfreader/sumatrapdf/issues/3020
all still update with no trouble.
And with no need to pay for "advanced certificates" or anything else.

I know very little about program code and nothing of the detail behind these things, but I note that the error message says
"Can't connect to the internet"
That tells me that either:
the trouble is not at the host end but at the user end
or the error message is wrong or at least misleading.

You said that you do not have a Windows 7 computer available for testing these things.
Why not get one?
A good used computer with Windows 7 should be cheap and easy to get.
This old (2011) Toshiba Satellite Pro 650 has Windows 7 Pro, x64, with SP1, and is still physically good.

Again, thank you for your excellent Sumatra PDF reader.
I hope that this trouble turns out to be something simple and easy to fix permanently, with little difficulty for you.

Minor off topic things I found today.

Sumatra installation puts a shortcut on the desktop, with no prior permission request.
No installation process should ever put a shortcut on any desktop unless that has been offered and specifically accepted by the installer.
Add an option "Create desktop shortcut" with an adjacent tick box.
Tick box must always be clear by default, and never preselected for Space or Enter to tick it.

In the About popup the version text at top right is not selectable and not copyable.
Ideally it should be both - drag to select, or simply right click and Copy to copy all of it to clipboard.
Same as copying email subject lines in Thunderbird.

**Comment by kjk** [comment] 2023-03-14 03:33
The issue is with certificates that combination of CloudFlare / render.com creates for sumatrapdfreader.org.

Unfortunately I have no control over that.

I can fix it by also hosting on some other website and checking both versions, but it wouldn't fix the issue for existing installations.

**Comment by GitHubRulesOK** [comment] 2023-03-14 03:40
@LaurieWilliams5066 
Just an observation 
I agree you should get a suitable feedback but If you installed 15345 then you should only expect 
![image](https://user-images.githubusercontent.com/12754913/224882460-3df489e9-c3c8-4979-9ddd-2560c4ebab9c.png)

On my windows 7 netbook If I ask for "update" I am told 15345 is available and am taken to prerelease address HOWEVER that will not display anything since I have commented in the past that IE cannot handle sumatraPDF.org addresses so I get there This page can't be displayed

@kjk That was unexpected for 32 bit have you added 32bit back into pre-release?

**Comment by GitHubRulesOK** [comment] 2023-03-14 05:00
@kjk 
so after the above am confused the 32 bit 3.4 pre-rel can see an update is required but the 3.5 64bit pre-release cannot connect

[sumatra-log.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/10964243/sumatra-log.txt)

**Comment by kjk** [comment] 2023-03-22 06:36
@LaurieWilliams5066 Could you check with latest pre-release version 15364 or later?

I've added code to check for update in additional website which should have a certificate that win7 / win8 should understand but can't be sure unless someone verifies it works on win7.

**Comment by GitHubRulesOK** [comment] 2023-03-22 11:18
@kjk will try and test 64 bit 
however with sooo many changes since 32 bit was last built I would like to check that works too ??

**Comment by GitHubRulesOK** [comment] 2023-03-23 02:04
@kjk with pre-rel as shown win 7 64 bit home (very slow as thiis unit is mothballed) can see it needs update but internet site is not accessible via trident ,iwill take time to try 3.4.6 but suspect as legacy it may not work ?

**Comment by kjk** [comment] 2023-03-23 02:17
Thanks for verifying.

No need to check 3.4.6, the fix will only be in pre-release.

**Closed by kjk** 2023-03-23 02:17 UTC

**Comment by csengh** [comment] 2023-07-29 07:12
hy! Today I updated to the newest version (3.4.6 64bit) and if I check for update I got the same error:
 
Can't connect to the Internet (error 0x2).


Win7 Ultimate x64 SP1

**Comment by GitHubRulesOK** [comment] 2023-07-29 15:14
@csengh that is correct as per the  comment ***No need to check 3.4.6, the fix will only be in pre-release.***

**Comment by csengh** [comment] 2023-07-30 07:14
I don't understand why don't need to check for update, sometime I want to check and if I have the latest version, I expect to get a response like : You have to latest version, not **Can't connect to the Internet (error 0x2).**

**Comment by GitHubRulesOK** [comment] 2023-07-30 11:51
@csengh 
***No need to check*** in this case = **assume it cannot work** as MS / Tainternet changed security models. 
Thus there is no way to reverse new blockers for old methods.
