### ISSUE TITLE
Problems with pages with Width>Height

### ISSUE THREAD

**Issue by Abs-Alexander** [sumatrapdfreader/sumatrapdf#2137] opened 2021-08-24 15:42 UTC
I am currently using SumatraPDF to print labels with a Citizen bar-code printer using the command-line options.
Everything is far better and faster compared to AcrobatDC and FoxIt Reader. 

There is only one issue - with paper sizes that are "wide"  - like 150x72mm or  72x58mm for example. 
Sumatra threads this "wide" kind of paper sizes correctly only with the "landscape" flag turned on.  

I'm able to print landscape pages without the "landscape" flag  - it looks like there is some kind of heuristics involved that threads the pages with 

   The problem is that I have both landscape and portrait labels with the same paper physical sizes.  I am unable to find a reliable method of printing such files in batches.
  Other PDF implementations like AcrobatDC or FoxIt Reader handle this kind of situation properly.

  In my opinion, a flag, stopping the heuristics may be the best solution. One can imagine that other users are happier with this behavior 

Sample PDFs or scanned printer images can be provided on request.
I can't find a [duplicate](https://github.com/sumatrapdfreader/sumatrapdf/issues?q=is%3Aissue+is%3Aopen+landscape) with a similar subject.

**Comment by GitHubRulesOK** [comment] 2021-08-24 15:48
see if https://github.com/sumatrapdfreader/sumatrapdf/issues/546 describe your problem https://github.com/sumatrapdfreader/sumatrapdf/issues/1246 thus its a fiddle to over-ride default

**Comment by Abs-Alexander** [comment] 2021-08-25 14:25
Yes, the problem is similar. 
May we sponsor the new feature - "disable autodetection"  somehow?

**Comment by GitHubRulesOK** [comment] 2023-10-25 03:20
closing as duplicate of #1246 
however @Abs-Alexander your request of command line switch should be possible with version 3.5 onwards

>add -disable-auto-rotation cmd-line print option

**Closed by GitHubRulesOK** 2023-10-25 03:20 UTC
