### ISSUE TITLE
Can anyone please re-upload sumatraPDF-prerelease-12145-64.exe, please?

### ISSUE THREAD

**Issue by Mark-Joy** [sumatrapdfreader/sumatrapdf#2970] opened 2022-09-20 12:03 UTC
Can anyone please re-upload sumatraPDF-prerelease-12145-64.exe, please?
This is the latest version that support saving highlights in external .smx
Either portable or installation is OK.
I can't believe no one has asked this before...
Search the whole internet, not found!! :(

**Comment by GitHubRulesOK** [comment] 2022-09-20 22:12
closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/discussions/2971

**Closed by GitHubRulesOK** 2022-09-20 22:12 UTC

**Comment by Mark-Joy** [comment] 2022-09-20 23:07
I have found [SumatraPDF v3.2.12206](https://github.com/VictorVG/Software/releases/tag/SPDF-4ace0fccd) which supports [HighlightJump](https://github.com/nod5/HighlightJump) for .smx highlights. 
#1867 [#13](https://github.com/nod5/HighlightJump/issues/13)
**I don't know if it is official build or not.**  So  use with your own risk!

**Comment by GitHubRulesOK** [comment] 2022-09-21 00:33
@Mark-Joy well spotted I forgot VictorG kept raising compilation issues
You will find that SMX was supported in all his 3.2.12### builds up to 12972 however uncertain which work best either in their own right or with Nod5 jumper

**Comment by Mark-Joy** [comment] 2022-09-21 18:50
@GitHubRulesOK 
Thank you for the information!
I checked v3.3.12972, it somewhat works with [HighlightJump](https://github.com/nod5/HighlightJump) but the plugin needs some modifications.
I very much like the smx highlights though!
