### ISSUE TITLE
Japanese Fonts

### ISSUE THREAD

**Issue by schadfield** [sumatrapdfreader/sumatrapdf#330] opened 2015-10-27 01:17 UTC
Here is a link to a PDF extract from my Japanese bank statement. Note the fonts "GothicBBB" and "Ryumin" which do not render in Sumatra PDF.

https://goo.gl/7lAlDe

**Comment by kjk** [comment] 2015-10-27 01:19
[test.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/21364/test.pdf)

**Comment by campbeb** [comment] 2015-10-30 17:00
I can view the PDF in version 3.1 64-bit installed from website, but not in Master branch.
![rendered PDF](http://i.imgur.com/7KXzoYP.jpg)

**Comment by kjk** [comment] 2015-10-30 21:54
I see no difference between master and 3.1 (the letters don't show).

Was it the same computer? It's possible one computer has the right font installed and another computer doesn't.

**Comment by campbeb** [comment] 2015-10-30 22:04
It is all on the same computer. I just tried 3.1 portable and prerelease portable versions and it doesn't show on any of them either.
Only the one I installed when 3.1 was released is working.
This is the properties details.
![image](https://cloud.githubusercontent.com/assets/1089399/10859087/6fdb1b1c-7f30-11e5-9e4f-dd8fbc9c0b2f.png)
)

**Comment by campbeb** [comment] 2015-10-30 22:12
I found what is making it work. My installed version of Sumatra has DroidSansFallback.ttf in the same folder as the .exe. If I copy that to the other versions, they work. If I remove it, they don't.

**Comment by kjk** [comment] 2015-10-30 22:15
Yeah, I was just about to write about that. The relevant code is in pdf-fontfile.c, create_system_font_list().

The font can also be embedded directly into the executable (see NOCJKFONT). I forget if it's intentional that we don't include DroidSansFallback.ttf in the portable executable or did I mess compiler flags when porting makefile.msvc to premake.

**Comment by kjk** [comment] 2015-10-30 22:31
3.0 doesn't render it so I'm going to call intentional.

The problem is that this PDF is broken: it references a non-standard font that is not embedded inside the PDF file.

An installer contains a japanese fallback font DroidSansFallback. A portable version doesn't, because it would add 50% to the size (3 MB to 6 MB exe).

Maybe we can use some Windows system font as fallback for GothicBBB and Ryumin, but if not then this works as expected.

A missing font is actually a frequent problem. It would be a good idea to add some notification when this happens that would list missing font and link to an explanation page.

**Comment by VictorVG** [comment] 2015-11-01 12:53
I ran a test of the file and checked with the help of Process Hacker handles and modules for all threads running copy SumatraPDF. I do not know why, but even if the font is installed in the operating system in the list of fonts downloaded SumatraPDF I do not have. According to hendles downloaded fonts msgothic.ttc, segoeui.ttf but DroidSansFallback.ttf ignore. Why I do not yet understand ...

**Comment by GitHubRulesOK** [comment] 2020-05-19 14:29
Closing as duplicate of several other cases such as Reader is unable to show cyrillic text in pdf file #378 or `SumatraPDF showing garbled texts in this file` #1585 
Where files may only be viewed easily within a locality or machine that has a specific font available However the PDF is not defined using globally available fonts or the font glyphs have not been named/embedded in a rational way, thus breaking the "Portable"DF standard requirements.

Note most of these examples can be easily fixed in the editor to be made acceptable to all viewers
here it is without any english
![image](https://user-images.githubusercontent.com/12754913/82338937-60464580-99e5-11ea-933d-09d4b46a2565.png)

[330 test-fixed.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4651093/330.test-fixed.pdf)


Remaining aspect of this issue i.e notify user of "Bad fonts" is covered by #350

**Closed by GitHubRulesOK** 2020-05-19 14:29 UTC
