### ISSUE TITLE
Feature Request: Word-wrap bookmarks tab

### ISSUE THREAD

**Issue by rleaf** [sumatrapdfreader/sumatrapdf#1887] opened 2021-02-16 22:00 UTC
Have chapters/sections in Bookmarks tab word-wrap to the width similarly to how the main window operates when you adjust the width in either 'Book view' or 'Facing view'.

**Comment by GitHubRulesOK** [comment] 2021-02-16 23:17
Closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1139

**Closed by GitHubRulesOK** 2021-02-16 23:17 UTC
