### ISSUE TITLE
Support for XFA?

### ISSUE THREAD

**Issue by 775405984** [sumatrapdfreader/sumatrapdf#1546] opened 2020-04-07 04:18 UTC
Can't open [this file](https://github.com/sumatrapdfreader/sumatrapdf/files/4442008/BJO-123-815-s002.pdf).

**Comment by kjk** [comment] 2020-04-07 06:53
mupdf doesn't support XFA and we won't until they do

**Comment by kjk** [comment] 2020-04-07 06:54
Duplicate of #27

**Closed by kjk** 2020-04-07 06:54 UTC
