### ISSUE TITLE
Text and Background colors not respected in 'Dark' and 'Darker' Theme

### ISSUE THREAD

**Issue by kierunb** [sumatrapdfreader/sumatrapdf#3829] opened 2023-10-30 20:20 UTC
After setting just those three settings new colors are respected wonderfully in 'Light' theme but not in 'Dark' and 'Darker' one.

```
FixedPageUI [
	TextColor = #f8f8f2
	BackgroundColor = #21222c
	SelectionColor = #44475a
```
Example below - the same file, just Theme setting change.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/233364/5f5a59d1-c452-4108-ae22-4e407c97f393)

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/233364/6d8e8f42-3cb4-4924-ab9e-840c6b7f5add)

Checked on newly generated 'SumatraPDF-settings.txt'. 
Tested on multiple PDFs and EPUBs.

**Comment by GitHubRulesOK** [comment] 2023-10-30 23:51
duplicate of many others colours can only be used with light theme as dark and darker are fixed to inverted colours, because you cannot theme PDF etc.

**Closed by GitHubRulesOK** 2023-10-30 23:51 UTC
