### ISSUE TITLE
Feature request: double-click on top-left hamburger icon to close window

### ISSUE THREAD

**Issue by stijnsanders** [sumatrapdfreader/sumatrapdf#863] opened 2017-08-16 14:12 UTC
This is a really minor request, but just as to get things consistent with other applications:
Since very, very, long back, it's possible in Windows to close a window by double-clicking it's top-left icon.
SumatraPDFViewer has a 'hamburger' icon top left top open the main menu, but doesn't appear to respond to double-clicks. Is it possible to connect the double-click-event to the close action just as the 'X' top-right would have been clicked?

**Comment by pdgessler** [comment] 2017-08-17 13:10
Duplicate of #162 if I'm not mistaken.

**Comment by kjk** [comment] 2017-08-17 22:43
Closing as dup of #162

**Closed by kjk** 2017-08-17 22:43 UTC
