### ISSUE TITLE
Display file name on hover on tab (and maybe in free space on the toolbar)

### ISSUE THREAD

**Issue by orestesgaolin** [sumatrapdfreader/sumatrapdf#573] opened 2016-07-21 08:33 UTC
Hi guys! I would like to see the full title of the document when I read it, but when the number of opened files is large, then the tab gets narrow and it's impossible to read the full title. 

Is it possible to show a title while hovering the mouse on the tab? I think that there's also some space on the toolbar next to the search window.

**Comment by tjcomserv** [comment] 2016-09-07 21:05
Great idea, I was just thinking the same thing. 

Maybe it would look good if when you hover over the tab, the document / file name appeared in a 'bubble' at the cursor, similar to how google chrome show the webpage title when hovering over the tab.

**Comment by SumatraPeter** [comment] 2016-09-20 15:27
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/336

**Closed** 2016-09-20 17:56 UTC
