### ISSUE TITLE
[Feature Request] Add Smooth Scrolling To the Software

### ISSUE THREAD

**Issue by wanzzhehe** [sumatrapdfreader/sumatrapdf#1498] opened 2020-03-15 10:05 UTC

**Comment by GitHubRulesOK** [comment] 2020-03-15 11:18
Closing as undefined duplicate of either
https://github.com/sumatrapdfreader/sumatrapdf/issues/1083
or https://github.com/sumatrapdfreader/sumatrapdf/issues/873
or https://github.com/sumatrapdfreader/sumatrapdf/issues/248
consolidated with https://github.com/sumatrapdfreader/sumatrapdf/issues/606

**Closed by GitHubRulesOK** 2020-03-15 11:18 UTC
