### ISSUE TITLE
Enable highlights of hyperlinks and reference

### ISSUE THREAD

**Issue by lushl9301** [sumatrapdfreader/sumatrapdf#1635] opened 2020-06-23 15:46 UTC
Hi, I recently downloaded a new version of sumatra pdf. It seems that the hyperlinks and reference highlighting (red and green highlights) is no longer available?
I've been searched online for customizations but not working so far.
Please kindly help. Thanks in advance.

These chapter links are not highlighted.
![image](https://user-images.githubusercontent.com/2193051/85425296-9611b780-b5ab-11ea-82b7-0ad617316d1c.png)

Same as the reference.
![image](https://user-images.githubusercontent.com/2193051/85425371-af1a6880-b5ab-11ea-9b17-f9d577e38c56.png)

Although they are still functional. I can click them to jump to the referred location..

**Comment by GitHubRulesOK** [comment] 2020-06-23 19:01
The tooltip indicator of hyperlinks went missing in version 3.2 see
Tooltips no longer displayed for URLs in Sumatra 3.2 #1517
So use the Debug Highlight option to see them
![image](https://user-images.githubusercontent.com/12754913/85436688-5635da80-b581-11ea-86f4-7c7d3cd6826a.png)


Using the Pre-release for next version tooltips are back However the debug menu is unlikely to be included and red/green outlines were not always visible in each version
Tooltips should be visible for 32 seconds rather than 5

**Comment by GitHubRulesOK** [comment] 2020-06-23 19:12
Since the residual question about showing the hyperlink border is covered by "pdfborderstyle #157" I am closing this one as a duplicate of that request.

**Closed by GitHubRulesOK** 2020-06-23 19:12 UTC
