### ISSUE TITLE
SumatraPDF.exe (3.4.6) White lines in XEROX J-B271 printer

### ISSUE THREAD

**Issue by dsdsdfsdfsfsdfsfsdf** [sumatrapdfreader/sumatrapdf#3349] opened 2023-03-14 09:33 UTC
I have problem (regular horizontal white lines) when printing PDF files on a XEROX J-B271 printer. I print short PDF files of approx. 2-3 pages. SumatraPDF.exe in version 3.4.6 32-bit installation. I print through the command line according to the instructions: https://www.sumatrapdfreader.org/docs/Command-line-arguments
Where is problem? 
![image](https://user-images.githubusercontent.com/99869018/224957666-6b40fc82-d05e-48d1-b517-74a87c14e0db.png) Thanks.

**Comment by GitHubRulesOK** [comment] 2023-03-14 12:32
In general
---
PDF was designed as a Computer Aided Design means to transfer Vector Data between Apple laser devices thus primarily a variation on Postscript. It was primarily a means to adapt PostScript data for Visual Displays.

Windows default printing is a means to provide RIP (Raster Image Processor) system onboard the PC OR via drivers a Vector output suited to a manufacturers print engine.

SumatraPDF is based on one of two Artifex Technologies (MuPDF and Ghostscript) 
MuPDF is highly designed for the Raster Screen End of the outputs whilst GhostScript concentrates on printing Drivers.

For bulk printing to commercial printers via programs GhostScript should clearly be used, as the secondary alternative to Adobe Products.

**Comment by dsdsdfsdfsfsdfsfsdf** [comment] 2023-03-14 15:55
> > ## In general
> > PDF was designed as a Computer Aided Design means to transfer Vector Data between Apple laser devices thus primarily a variation on Postscript. It was primarily a means to adapt PostScript data for Visual Displays.
> > Windows default printing is a means to provide RIP (Raster Image Processor) system onboard the PC OR via drivers a Vector output suited to a manufacturers print engine as an alternative to direct print control.
> > SumatraPDF is based on one of two Artifex Technologies (MuPDF and Ghostscript) MuPDF is highly designed for the Raster Screen End of the outputs whilst GhostScript concentrates on printing Drivers.
> > For bulk printing to commercial printers via programs GhostScript should clearly be used, as the secondary alternative to Adobe Products.

I don't have experience with this program, but there are no problems when using Adobe Reader to print PDF files. So the problem of white lines in SumatraPDF.exe cannot be fixed?

**Comment by GitHubRulesOK** [comment] 2023-10-25 03:54
Closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/919

**Closed by GitHubRulesOK** 2023-10-25 03:54 UTC
Labels: printing
