### ISSUE TITLE
The memory will unlimited increase abruptly by continue zoom in and zoom out

### ISSUE THREAD

**Issue by Bambooin** [sumatrapdfreader/sumatrapdf#1393] opened 2020-01-08 01:49 UTC
The memory will unlimited increase abruptly by continue zoom in and zoom out, and it doesn't release it even when close windows.

Maybe it's memory leak?? I try a start memory 3.8MB to incease it to 800MB by continue zoom in and zoom out.

**Comment by GitHubRulesOK** [comment] 2020-01-09 12:06
@Bambooin I could not reproduce certainly my resource usage went up but it naturally reduced when I stopped zooming.
Can you please check current build from https://www.sumatrapdfreader.org/dailybuilds.html then descibe steps you use e.g. is it first file, just any file or one type of file .cbz .pdf etc. and how big #mb #pages

**Comment by GitHubRulesOK** [comment] 2020-01-09 17:51
@kjk confirmed whilst the value will fluctuate and partially reduce on closure
Memory usage continues upwards over time

![image](https://user-images.githubusercontent.com/12754913/72091568-62e2b100-3308-11ea-8216-a63f17c1ab28.png)

**Comment by amurzeau** [comment] 2020-01-21 21:32
I'm reproducing this, it will take more than 200Mb after many zoom in / out.
If its not a memory leak, it can be caused by memory fragmentation preventing available memory to be freed to Windows

**Comment by kjk** [comment] 2020-01-22 04:16
Should be fixed in latest daily build https://www.sumatrapdfreader.org/dailybuilds.html

**Closed by kjk** 2020-01-22 04:16 UTC
