### ISSUE TITLE
Links jump to wrong horizontal position

### ISSUE THREAD

**Issue by fangly** [sumatrapdfreader/sumatrapdf#987] opened 2018-03-08 09:54 UTC
Hi,

I have a [PDF](https://github.com/sumatrapdfreader/sumatrapdf/files/1792553/handbook_sections.pdf) mostly of A4 pages, but some are _much_ larger. The index has a list of links to the different sections. When I click on one of these links, SumatraPDF 3.1.1 64-bit jumps, but only a grey area is visible.

To reproduce:
1. Open the attached PDF
1. In Menu > View > Make sure "display pages continuously" is checked
1. In Menu > Zoom > 150%
1. Navigate down to page 1-5
1. Click on the link "Autoloader"
1. Notice that the window content is grey (because it is positioned too far to the left).
1. Scroll to the right to access the content of chapter "Autoloader".

Obviously, the last step is not expected nor desired; Sumatra should detect that the page is farther to the right and display the page's content centered in the middle of the window. This behaviour is likely observed because some pages are very large and the display is aligned to the left of this very large pages.

Cheers,
Florent

**Comment by SumatraPeter** [comment] 2018-03-08 18:15
If #152 is fixed it might take care of this as well.

**Comment by GitHubRulesOK** [comment] 2020-02-04 12:23
Closing as resolved, as per comment by SumatraPeter.
Actions as described in the sequence above are now fixed in current pre-release.

**Closed by GitHubRulesOK** 2020-02-04 12:23 UTC

**Comment by GitHubRulesOK** [comment] 2020-04-10 12:08
Unclear if there has been some regression
This issue appears to still be a problem in current build
Since an issue has been opened for horizontal positioning I am cross-linking to 
Scrollto still not always as expected #1508
