### ISSUE TITLE
Different icons for different file types.

### ISSUE THREAD

**Issue by Yanpas** [sumatrapdfreader/sumatrapdf#34] opened 2014-12-13 13:01 UTC
I use sumatra for reading epubs, but icon on the books is yellow with PDF letters. This confuses.

**Comment by SumatraPeter** [comment] 2019-09-03 01:54
@kjk: Since you've opened #600 yourself a couple of years after this one, maybe you should close this one as a dupe of it?

**Comment by kjk** [comment] 2019-09-03 02:49
closing as dup

**Closed by kjk** 2019-09-03 02:49 UTC
