### ISSUE TITLE
Display of File is very light.

### ISSUE THREAD

**Issue by bhasyah** [sumatrapdfreader/sumatrapdf#2117] opened 2021-08-10 17:24 UTC
Hi Sir,

Recently I have started using Sumatra PDF and before anything I would like to appreciate you for the product. It is one of the lightest and the fastest PDF viewer I have every used, so thank you for your effort,

Now coming back to my issue. I work with lot of PDF files generated from CAD Drawing Software. When one of the PDF file I generated on my CAD software today and opened it on Sumatra PDF the display was so light that few of the text were hard to read. The same file when open in a browser and the right display.

I am attaching an image showing you the difference between the two application and I also the PDF generated for further reference.

Kindly look into the issue and see if any improvements can be done.

Regards

![PDF Issue](https://user-images.githubusercontent.com/88728070/128891931-e90ef727-5c9a-4b04-a2b4-7ca37054409e.PNG)
[ALPHION PRODUCTION LAYOUT-Model ARES.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6962712/ALPHION.PRODUCTION.LAYOUT-Model.ARES.pdf)

**Comment by GitHubRulesOK** [comment] 2021-08-22 13:41
It is the way the Lines are defined in the CAD software here is the same file with Line Thickness corrected for A4 Viewing.
[2117 out.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/7027458/2117.out.pdf)

They will still appear "Lighter" in SumatraPDF compared to some other viewer settings since they are vectors drawn to scale, so only get thicker as you zoom in. basically there is no bug as SumatraPDF is using the PDF values

![image](https://user-images.githubusercontent.com/12754913/130357280-3d7b840b-3413-4ab7-9bab-f8f945bbcbab.png)

Closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1732

**Closed by GitHubRulesOK** 2021-08-22 13:41 UTC
