### ISSUE TITLE
Display of bookmarks appears abnormal in "black mode"

### ISSUE THREAD

**Issue by Markhng** [sumatrapdfreader/sumatrapdf#1904] opened 2021-03-21 08:14 UTC
Since SumatraPDF 3.2, the background color in pdf bookmarks is the same as `BackgroundColor`. However when I configure to "black mode":
```
FixedPageUI [
	TextColor = #ffffff
	BackgroundColor = #000000
	...
]
```
and hover the mouse over an item in bookmarks, the item will not be visible.

The reason for this may be that a transparent color is added when hover on an item. but when the background is black, the display appears abnormal.

In recent pre-release version (from v3.3), I notice that the font size of bookmarks is configurable (`TreeFontSize`). If the background and text color are also configurable, the problem will be solved.

**Comment by GitHubRulesOK** [comment] 2021-03-21 12:58
Currently working correctly i.e. the dark text colour is the same in all cases and the light background is the same in all cases, You could argue the "Black Text" **page number** should also be red, but then we have enough problems when it goes white in other cases.
![image](https://user-images.githubusercontent.com/12754913/111905509-e9823a80-8a43-11eb-8366-e9f586128ab6.png)

Duplicate of request to control colours beyond the two settings, There is currently no such thing as "mode" only the ability to temporarily -invert-colors for blueprints or negatives.

Am thus counting this as a duplicate request for theming.

**Closed** 2021-03-21 13:32 UTC

**Comment by Markhng** [comment] 2021-03-22 09:14
![image](https://user-images.githubusercontent.com/32028289/111965124-5a068580-8b30-11eb-876c-dc5aeda2366e.png)
The **green** arrow in the picture indicates the position of the cursor. When the cursor hovers over the section with the following settings, the item in the bookmark will not be seen. @GitHubRulesOK 
```
FixedPageUI [
	TextColor = #ffffff
	BackgroundColor = #000000
	...
]
```

The source of the [**`test.pdf`**](https://github.com/sumatrapdfreader/sumatrapdf/files/6180820/test.pdf) file (compiled by XeLaTeX):
```tex
\documentclass{article}
\usepackage{hyperref}
\begin{document}
	\section{Unhovered Section}
	\section{Unhovered Section}
	\section{Hovered Section*}
	\section{Unhovered Section}
\end{document}
```

**Comment by Markhng** [comment] 2021-03-22 09:51
![image](https://user-images.githubusercontent.com/32028289/111970608-6b529080-8b36-11eb-9f7c-55496e9eda05.png)
When click an item in the bookmark (blue arrow in the picture), and click anywhere other than the *Bookmarks* panel (orange arrow) to make the *Bookmarks* panel inactive, the item will be invisable. The same happened in the *Favorates* panel.

**Comment by GitHubRulesOK** [comment] 2021-03-22 12:28
@kjk 
how do you wish to classify this bookmarks highlighting issue 
Is it a bug that darkening the current entry does not contrast with the background
or is it a need for more user control of the contrast colour as can be applied when selecting text
![image](https://user-images.githubusercontent.com/12754913/111989657-f8cbbb80-8b09-11eb-8c0b-5f5b538006d4.png)
