### ISSUE TITLE
This epub 3 file will not load and display correctly.

### ISSUE THREAD

**Issue by riordans** [sumatrapdfreader/sumatrapdf#849] opened 2017-07-25 21:49 UTC
https://www.dropbox.com/s/ugb0jvrpgvyx5sz/antoniostale.epub 
This is how it should it should look
![antonio-tale](https://user-images.githubusercontent.com/25023799/28595135-25d3d722-7158-11e7-850e-8fa945f66401.png)
This is how it looks in sumatra
![antonio-tale-sumatra](https://user-images.githubusercontent.com/25023799/28595259-c2240be2-7158-11e7-8908-55fd5144421f.png)
I want to be able to use sumatra to view this epub and others like it

**Comment by pcdinh** [comment] 2017-10-31 03:18
SumatraPDF is unable to render tables in epub yet

**Comment by AbsolutelyFreeWeb** [comment] 2018-12-20 03:09
Hello, i have the same issue. The epub bacground pictures are now shown. However, it is not a table issue in my case. The images are referred to in the css, where they are given as background images. Also, their sizes need to be honored for correct rendering.

e.g:
#page-img-left { margin-left: 0px; margin-right: 0px; margin-top: 0px; margin-bottom: 0px; background-image: url(../Images/image00037.jpeg); background-size: 960px 960px; width: 960px; height: 960px; }
#page-img-right { margin-left: 0px; margin-right: 0px; left: 960px; margin-top: 0px; margin-bottom: 0px; background-image: url(../Images/image00038.jpeg); background-size: 960px 960px; width: 960px; height: 960px; }

Not sure if I should create a new bug, or it can be handled at the same time. The problem is the same. The background pictures are not shown.

**Comment by GitHubRulesOK** [comment] 2019-12-02 03:03
@kjk the latest daily builds seem to behave oddly with some variants of epub 3.0 the attached file is one of many where the download is ###.epub3 which will not now open in epub UI until renamed to ###.epub but these were generally acceptable to earlier versions of SumatraPDF with the new extension
[anna-sewell_black-beauty.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/3909239/anna-sewell_black-beauty.zip)

**Comment by SumatraPeter** [comment] 2019-12-02 04:24
anna-sewell_black-beauty.epub3 gives me the loading error on 3.1.2 as well, whereas anna-sewell_black-beauty.epub works.

Also, I'm guessing the new extension is to indicate possibly significant differences between EPUB versions. I remember testing the EPUB3 given above back in 2017 and of course it did fail in Sumatra 3.1.2 (don't recall how the then latest MuPDF behaved). Simply changing its extension from EPUB3 to EPUB _might_ enable Sumatra to display the EPUB 2.x compatible sections, but of course that won't make it magically EPUB 3.x capable.

**Comment by GitHubRulesOK** [comment] 2019-12-02 12:12
@SumatraPeter As usual you are correct, retesting a call to 3.1.2 the action has not changed,that is calling `SumatraPDF filename.epub3` using
```
EbookUI [
	...
	UseFixedPageUI = true
```
Opens the file (in a 2.0 compatible way) whereas
```
EbookUI [
	...
	UseFixedPageUI = false
```
Raises an error message in **both 3.1.2 and current builds**

**Comment by GitHubRulesOK** [comment] 2023-10-28 01:58
closing as without any samples other than a working one with unconventional file extension there is no longer a fixable issue !

similar/related sample of problem with enhanced epub DRM in open issue #1293

**Closed by GitHubRulesOK** 2023-10-28 01:58 UTC
Labels: ebook
