### ISSUE TITLE
Middle-click drag get stuck on after releasing middle click

### ISSUE THREAD

**Issue by expikr** [sumatrapdfreader/sumatrapdf#4529] opened 2024-09-14 18:11 UTC
**SumatraPDF version**
- Version 3.5.2

**Describe the bug**
Middle-click drag get stuck on after releasing middle click

**To Reproduce**
1. open a pdf
2. hold middle click, move the cursor to start autoscroll
3. end autoscroll by releasing middle click.
4. autoscroll doesn't actually end.

**Expected behavior**
should behave like all normal web browsers, ending autoscroll on release of middle button

**Additional context**
No issues mentioning this bug is found from a prelim search. If it had already been fixed in a pre-release, the issue should stay open until it's in a proper release version.

**Comment by GitHubRulesOK** [comment] 2024-09-14 20:06
Most document viewers and mice expect more than the one page thus Middle Click Auto-Scroll is usually latched on and off (a toggle switch) It behaves as such here (and has done as long as I can remember since DOS years) for me in this Edge Browser, (and thus Acrobat, SumatraPDF, PDFxEdit, have the same behaviour for me). It does not work in all applications, so in my favourite image viewer OR MS Paint where scroll is not always applied/expected it does not function at all.

It may be a setting in your browser to over-ride that standard behaviour, as it is a legacy Windows function

The historic answer and apparently the same in [Windows 11](https://answers.microsoft.com/en-us/windows/forum/all/how-to-disable-middle-button-auto-scroll-feature/ee0e6651-3ef5-4803-b3b8-ae064eaad079) is
>That middle mouse click option to auto-scroll is a part of the default settings in Windows, really the only way to disable that function would be to use a 3rd party utility like the free 'X-Mouse Button Control' utility to set your preferred action for the middle click action.

**Comment by GitHubRulesOK** [comment] 2024-09-14 20:15
Hmmm agreed that is Chromium based Edge behaviour, However not of most PDF focused Applications as I mentioned 

HOWEVER this is a duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/167

**Comment by GitHubRulesOK** [comment] 2024-09-14 20:41
@expikr you could either raise a pull request or at least confirm where that is applied and no other kick back in other functions.

**Closed** 2024-09-15 17:15 UTC

**Comment by kjk** [comment] 2024-09-15 17:16
@expikr thanks for the code
