### ISSUE TITLE
CLI option for "Print as Vector"?

### ISSUE THREAD

**Issue by floralsystems** [sumatrapdfreader/sumatrapdf#389] opened 2015-12-11 03:28 UTC
I'm using SumatraPDF for printing only from a web application and it's fantastic, thanks for that.  I recently upgraded from v3.0.0 and it resolved an issue with printing to legal size, but it created a new issue with printing to receipt printers that cut the paper based on contents. The end result is that with v3.0.0 the receipt paper was as long as the printable content, but with v3.1.1 the receipt printer always feeds 3276mm of paper, most of which is unprinted.

This is the command I use:
"C:\sumatra.exe" "C:\printable.pdf" -print-to "Citizen Receipt Printer" -print-settings "bin=Automatically Select"

This is what I _think_ is happening:

The receipt paper doesn't match any common paper size (80mm x 280mm). GetPaperSize(), GetPaperByName(), and GetPaperFormat() all return 0 (or Paper_Other.. does that equate to 0 as well?)... which means dmPaperSource get set to 0. For this particular printer, that size happens to be 80mm x 3276mm (whoa, that's a long receipt).

That _used_ to be okay with v3.0.0 because the receipt printer detects the height of the printjob. However, with version 3.1.1 printing is done as an image, so the receipt printer is no longer able to detect the end of the printable contents.

---

If I provide the paper size by command line using "paper=", the paper is no longer 3276mm long, but it is still not auto sized to the contents, the same is true if printing through Sumatra's GUI.

---

It seems offering an option to "Print as Vector" would help with this issue, as well as alleviate large files sizes over the network (mentioned https://github.com/sumatrapdfreader/sumatrapdf/issues/329).

Additionally, it makes sense that the "Print as Image" method would trim the document's whitespace before converting to bitmap (mentioned https://github.com/sumatrapdfreader/sumatrapdf/issues/381)
## 

Either of those methods would solve my problem, although I would personally opt for a "Print as Vector" option. I'm not rich, but I would make a donation to see this implemented. I need it rather soon.

**Comment by GitHubRulesOK** [comment] 2020-02-07 00:57
The second best method of triming to suit has been identified above and as #381

The primary request is to NOT "print as image" thus this request is for a cli option or default which is a duplicate of the unfortunately worded 'print as image' as option (rather than default) #329

**Closed by GitHubRulesOK** 2020-02-07 00:57 UTC
