### ISSUE TITLE
Line Spacing

### ISSUE THREAD

**Issue by richardajyoung** [sumatrapdfreader/sumatrapdf#576] opened 2016-07-26 04:42 UTC
Hi,

Can the ability to change line spacing when viewing an ePub be added please?

Some ePub files display with lines very close together which ruins the readability.

Thank you for taking the time to read this.

**Comment by vespas** [comment] 2018-01-22 14:29
this looks like a bug, ignoring some of the file's contents. MuPDF loads spaces between paragraphs properly. See screenshot:

https://imgur.com/a/mhswa

MuPDF 1.12.0 is on the left, sumatrapdf 3.1.2 64bit on the right.

**Comment by sergeevabc** [comment] 2018-03-18 08:02
Err… Hello?

**Comment by GitHubRulesOK** [comment] 2020-02-03 17:37
For reference I am enclosing the comparison image from vespas post above in this thread

![image](https://user-images.githubusercontent.com/12754913/73675991-69680c80-46ab-11ea-8f42-53024fa7cb13.png)

However, I am closing this one as a duplicate of wider discussion in #476

**Closed by GitHubRulesOK** 2020-02-03 17:37 UTC
