### ISSUE TITLE
Memory cache option.

### ISSUE THREAD

**Issue by Achaean** [sumatrapdfreader/sumatrapdf#1802] opened 2020-11-06 13:43 UTC
It would be nice I think, if the user had the option to change it.
Apparently, I couldn't find, such an option.

Bye!  A.

**Comment by SumatraPeter** [comment] 2020-11-10 22:28
Duplicate of #327.

**Comment by GitHubRulesOK** [comment] 2020-11-10 22:35
@SumatraPeter 
Thanks I had not spotted that one

@kjk 
Many recent cache changes may have altered historic view but I suspect allowing user to mess it up then complain their bug is better than anyone elses is not on the cards.

**Closed** 2020-11-18 01:20 UTC
