### ISSUE TITLE
bug(encoding): incorrect display of non-ASCII characters in some files

### ISSUE THREAD

**Issue by Kristinita** [sumatrapdfreader/sumatrapdf#2292] opened 2022-01-23 17:10 UTC
### 1. Summary

SumatraPDF doesn’t correctly display non-ASCII characters for some files. Other PDF viewers display the same characters correctly.

### 2. Example

[**Example book on IPFS**](https://ipfs.io/ipfs/bafykbzacedz45jbfflgiatrdsjlv3tigx6qwsslv72ajmxbew3xik7yb7umj2?filename=%D0%AD%D0%BB%D0%B8%D0%BD%D0%BE%D1%80%20%D0%9E%D1%81%D1%82%D1%80%D0%BE%D0%BC%20-%20%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D1%8F%20%D0%BE%D0%B1%D1%89%D0%B8%D0%BC-%D0%98%D0%A0%D0%98%D0%A1%D0%AD%D0%9D%2C%20%D0%9C%D1%8B%D1%81%D0%BB%D1%8C%20%282010%29.pdf)

#### 3.1. Unwanted — SumatraPDF

Mojibake:

![SumatraPDF 1](https://i.imgur.com/REdIwXN.png)

![SumatraPDF 2](https://i.imgur.com/Ubc1d7V.png)

#### 3.2. Desirable — another viewers

Normal Cyrillic symbols in MuPDF:

![MuPDF](https://i.imgur.com/BkvzidT.png)

![MuPDF](https://i.imgur.com/c4GOWCk.png)

#### 4.1. “We don’t need to fix it. This is a bad file”

Not all books files have a perfect quality. I constantly come across books of such quality as in the example. What to do with such bad files? Users want to read the contents of books regardless of the quality of the files. Reworking all files scanned and processed long ago and badly will take a huge amount of time.

I don’t think SumatraPDF should be a viewer for perfect quality PDF files. In my opinion, it would be much better if SumatraPDF supports the bad file capabilities that other viewers support.

#### 5.1. Operating system

1. Windows 10.0.19041.1415

#### 5.2. SumatraPDF

1. SumatraPDF v. 3.3.3. 64-bit

#### 5.3. Another viewers

Cyrillic symbols from example normally displayed for me in these viewers:

1. MuPDF 1.19.0
1. Okular 20.04.0
1. Firefox 96.0.2, PDF.js v2.12.313

Thanks.

**Comment by GitHubRulesOK** [comment] 2022-01-23 18:23
@kjk thats odd second report of similar see yesterdays "Ligature" complaint 

https://github.com/sumatrapdfreader/sumatrapdf/issues/2291 but I am not seeing that isue
![image](https://user-images.githubusercontent.com/12754913/150692285-fcdd2392-aad3-4e04-a3c6-21069aecc947.png)

Again I am using current Pr-Release 3.4.14246 on 32bit widows 7 english and fonts are Type 1 Loaded from my system as not embedded within the PDF, so wondering if its a Windows 10 thing ?

**Comment by GitHubRulesOK** [comment] 2022-01-23 19:05
@kjk testing on a new windows 10 all updates

 the issue is evident for both files reported in 64 bit portable version 3.3.3 BUT NOT in 3.4 pre-release 64bit portable !

**Comment by kjk** [comment] 2022-01-23 22:31
For me as well it is fixed on win11 in latest pre-release https://www.sumatrapdfreader.org/prerelease

**Closed by kjk** 2022-01-23 22:31 UTC
