### ISSUE TITLE
Feature request: Button or menu choice to show the Frequently read page

### ISSUE THREAD

**Issue by Murplugg** [sumatrapdfreader/sumatrapdf#470] opened 2016-03-19 12:04 UTC
Being able to go back to that page and open other frequently read documents would be a nice function. Perhaps a keyboard shortcut could do as well.

**Comment by sastools** [comment] 2017-03-09 16:35
I agree with this. Can a toolbar item be added to just open a new tab with the Frequently Read page there?
Probably, it needs to be the first item on the toolbar and maybe could be called Home?

**Comment by SumatraPeter** [comment] 2018-03-18 01:09
Essentially a duplicate of #406

**Comment by GitHubRulesOK** [comment] 2020-01-06 14:09
@kjk ? consolidate with https://github.com/sumatrapdfreader/sumatrapdf/issues/406#

**Comment by kjk** [comment] 2020-01-06 22:12
Consolidate as #406

**Closed by kjk** 2020-01-06 22:12 UTC
