### ISSUE TITLE
Support copy and paste in ebook ui

### ISSUE THREAD

**Issue by TonyChuh** [sumatrapdfreader/sumatrapdf#284] opened 2015-09-10 03:35 UTC
I can't copy and paste text, when I read books in format of mobi, epub

**Comment by hickford** [comment] 2015-10-01 17:33
Yes please.

See also https://code.google.com/p/sumatrapdf/issues/detail?id=2219

**Comment by Fixer-007** [comment] 2017-11-16 22:40
Actually it can copy/paste text, if you read that link above it has an answer:
>You can now **enable copy/pasting** for ebooks also in the official builds. To do that, select Settings -> Advanced Options... and change the UseFixedPageUI value to true in the EbookUI section (and then reopen the document for the setting to take effect).

I verified it, copy pasted with success, also it changes interface to better one (with more features)

I'm not really sure why on earth it is hidden in such an obscure way o_O I suggest adding some "advanced gui" checkbox in settings or menus.

**Comment by GitHubRulesOK** [comment] 2020-02-03 13:31
For related issue about enabling Select and Copy text in EbookUI see #239

**Comment by msnbcorp** [comment] 2020-04-07 17:44
I don't open a new issue, but simply re-up this one : it would be nice to have the possibilities to select and copy-paste text of e-pub document in the classical default interface of Sumatra (not the UseFixedPageUI = true which is kind of ugly).

**Comment by GitHubRulesOK** [comment] 2020-04-07 18:04
FixedPageUI = clasic PDF interface  = copy paste zoom etc
Flowing EPub interface = Pretty ! = text is always reflowing = not fixed to copy

**Comment by msnbcorp** [comment] 2020-04-07 18:40
@GitHubRulesOK , yes i have understand that, but it would be great to have a select/copy function for the flowing version. I guess it is not impossible as other reader appear to achieve this. 
I understand, though, that this is lock by the fact that there is only few devs on the ebookUI part of sumatra.

**Comment by GitHubRulesOK** [comment] 2020-04-07 18:45
@msnbcorp 
Yes "One dev fits all"
e-book is potentially scheduled to be reviewed by KJK after 3.2 release cycles
Never is there a promise of milestones.

**Comment by ImportTaste** [comment] 2021-07-15 21:54
Could this issue be renamed to reflect the desire to also search/find within ebooks, since all of those issues were merged into here? All the title mentions is copy and paste.

**Comment by GitHubRulesOK** [comment] 2021-08-28 12:26
@kjk 
with the removal of legacy ebook UI I guess this issue is now fully closed

**Comment by lvmm** [comment] 2022-02-22 07:28
There is an issue with using FixedPageUI = true for ebooks - in this mode colour and font settings in ebookUI section are ignored, so I sincerely hope that you are joking about ebook UI removal. For me it will make SumatraPDF unusable as ebook reader.

**Comment by GitHubRulesOK** [comment] 2022-02-22 14:16
@lvmm colours are the same as main and size is a variable as before but I will grant you that font seems to have no noticable effect

@kjk if font is no longer required for ebooks is it best to remove that historic setting as I does not seem to apply to palm book or other legacy formats, and MuPDF should be providing best font it can for its formats?

**Comment by ImportTaste** [comment] 2022-02-22 18:52
> But I don't want colours to be the same - that's the point. I need ebook colours to be different from the ones used for PDF.

What I do is use a portable version of SumatraPDF in conjunction with an installed version. In the installed version, I have this in the settings file:

```
ExternalViewers [
	[
		CommandLine = "C:\Example\Path\SumatraPDF-Dark\SumatraPDF.exe" -page %p "%1"
		Name = SumatraPDF Dark
	]
]
```

Then this portable SumatraPDF has this in its settings:

```
FixedPageUI [
	TextColor = #cccccc
	BackgroundColor = #333333
	SelectionColor = #0a03f3
```

The downside is that illustrations will be inverted. Shift+i allows me to invert (which, in this case, uninverts) so that I can get a good look at them, but, because I prefer #333333 (dark gray) over #000000 (black), the images will be a bit washed out.

I wish 'color modes' that you could easily switch between were a feature, which would include setting a default color mode per-extension and having per-document color modes saved in FileStates.

**Comment by GitHubRulesOK** [comment] 2022-02-22 22:28
@ImportTaste
Nice workaround the issue and if using an older portable the ebook UI  fonts and colours willl be the legacy ones.

The issue with colours is it does not matter if its PDF or scanned images the paper is the background colour and the text is the forground colour but if you invert the range then images look naff, however you cant say I want this page inverted but not that part of this page, the colour model is very simple it is page colours not theming. For reducing eye strain a simpler warm glow (red hue not blue hue) is the recommended method as seen using Windows night light setting.

**Comment by ImportTaste** [comment] 2022-02-22 22:33
> The issue with colours is it does not matter if its PDF or scanned images the paper is the background colour and the text is the forground colour but if you invert the range then images look naff, however you cant say I want this page inverted but not that part of this page, the colour model is very simple it is page colours not theming. For reducing eye strain a simpler warm glow (red hue not blue hue) is the recommended method as seen using Windows night light setting.

Yeah, I know how it works, I was just listing the caveat to doing it that way. Also, I already keep Windows night light on, so that would be redundant for my purposes.

Being able to switch the color model without editing a text file would make this a lot more convenient.

**Comment by GitHubRulesOK** [comment] 2022-02-22 22:57
>Being able to switch the color model without editing a text file would make this a lot more convenient.
Thats why SHIFT I as you mention was added to flip to and fro without edits or using command line -invert.
As I said its a very very basic feature, ideal for negatives, blueprints or inverted images.

**Comment by lvmm** [comment] 2022-02-24 06:25
@ImportTaste there is a simpler way - you can specify different profiles for the same installation with -appdata switch. But if I have to use any workarounds I'd rather install calibre. I don't like kludging, sorry.

**Comment by kjk** [comment] 2022-03-05 20:53
Copy & paste has been fixed in pre-release. Regression in colors is a separate issue.

**Closed by kjk** 2022-03-05 20:53 UTC
Labels: ebook
