### ISSUE TITLE
v3.5+ erroneously complains about "unsaved annotations"

### ISSUE THREAD

**Issue by samepaul** [sumatrapdfreader/sumatrapdf#3448] opened 2023-04-19 15:59 UTC
It shows this for no reason:
![image](https://user-images.githubusercontent.com/81985296/233131846-1be6f6d5-43cb-417f-a541-04832ce7a1b3.png)
I do not have any annotations, be it saved or unsaved.
This message is shown for every PDF file I open.

In previous 3.5 version, it just shown red warning, but after updating to 3.5.15481, it also asks if I want save annotations or not.
Which is somewhat annoying.
Fortunately it only asks for currently displayed PDF, not for each opened tab.

**Comment by GitHubRulesOK** [comment] 2023-04-19 16:17
There are several reasons that message is triggered that can be caused by upen a PDF that was not closed by another app with annotations in active state (appearance changes), If you can post a sample of one that incorrectly triggers as "changes pending", then it may be possible to exclude that type of content trigger.

**Comment by samepaul** [comment] 2023-04-19 16:22
[USB4 DROM Specification - Rev1.0 - Feb 2021.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/11275314/USB4.DROM.Specification.-.Rev1.0.-.Feb.2021.pdf)

**Comment by samepaul** [comment] 2023-04-19 16:46
One question though. Why not put this indication and exit warning **only** if the user indeed made any change?
Why it is any important of some other application did something? 
Whatever it was it is already saved in the file. No point to ask warn user about it or ask to save.

**Comment by GitHubRulesOK** [comment] 2023-04-19 16:57
Hmmm the file has been heavily modified with unfinished actions which MuPDF inside SumatraPDF  will try to heal, so if you save as new the error will be resolved but all the redactions will not be cleaned up. that needs MuPDF to resave the file, however when it does attempt to correct the file the size is ingcreased suggesting there were other issues resolved that required a different decompression.

**Comment by kjk** [comment] 2023-04-19 20:26
In this document `pdf_was_repaired()` returns false but `pdf_has_unsaved_changes()` returns true because there was a modification of the outline.

**Comment by samepaul** [comment] 2023-04-19 23:13
But *I* did NOT modify anything!

**Comment by kjk** [comment] 2023-04-19 23:27
Yes. The document is malformed and mupdf modified it during loading to repair it.

**Comment by samepaul** [comment] 2023-04-19 23:42
First, as long as PDF can be opened and displayed without errors by Acrobat Reader - it is not malformed.
Second, even if it did some “repairing”, it doesn’t meant that USER did any modification. Therefore, there is nothing to save and no point to nag user about it. 
Imagine if Norepad++ will ask you save file every time just because you resized main windows and some long lines got wrapped. Because Notepad easily can considered it as “malformed text”, and therefore “repair” it and therefore claim as “modified”. Would you seriously consider this behavior valid? I doubt.

**Comment by netsonicyxf** [comment] 2023-05-13 08:12
I have the same issue. When I open any PDF file, 

1. it shows "unsaved annotation"
2.  it asks to save the PDF when existing

The behavior is very annoying.  3.5.15481

**Comment by pulbitz** [comment] 2023-05-20 04:45
I see a lot of PDF documents like this. It's very annoying.

I don't use the annotation feature itself, and don't intend to in the future. Is there any way to completely turn off the annotation feature in SumatraPDF?

**Comment by JuWod** [comment] 2023-08-03 16:54
Adding to the issue, I noticed that e.g. zooming in and out of the document triggers "unsaved annotations" for me. 

Also, triggering CmdSaveAnnotations doesn't fix this - the "unsaved annotations" warning only disappears after I click "save changes to existing pdf" in the annotations editor window. It might just be an issue with the command shortcut though - both using the command and clicking in the editor prompt the same "saved annotations to 'C:\..." notification. Its just that one successfully erases the "unsaved annotations" warning and the other doesn't. No clue what to make of any of this lol

**Comment by GitHubRulesOK** [comment] 2023-08-03 17:57
@JuWod zooming should not on its own cause a trigger condition so samples on a case by case basis are needed to see why.

Generally MuPDF will detect/flag more than DC Reader will admit, since Adobe are more tolerant of some aberrations and other readers have their own accept/ignore lists . Actually in the OP sample the problem fix is fairly minor, and in other cases (not this one) SumatraPDF does not object but DC may insist on rebuilding the file drastically, but it does not say so until closing the file so on exit it can be more simply "ignore changes".

**Comment by GitHubRulesOK** [comment] 2023-08-04 13:14
@samepaul 
3.5 is "experimental" for the reasons such as this given i.e. it provides feedback before an official 3.5 so its up to the sole current developer (there is a good related pending annotation enhancement not yet a Pull Request, but AFAIK it does not address this issue either)

**Closed** 2023-09-17 22:41 UTC
