### ISSUE TITLE
Store `FileStates [  ]` in a different file

### ISSUE THREAD

**Issue by yashpalgoyal1304** [sumatrapdfreader/sumatrapdf#3050] opened 2022-10-23 17:41 UTC
* Currently the [FileStats](https://www.sumatrapdfreader.org/settings/settings3-2#FileStates) are stored within the `SumatraPDF-settings.txt` file
* this makes the file kinda hard to navigate and use it to your needs for corner cases like in \
for storing values of some property/setting in comments as discussed at https://github.com/sumatrapdfreader/sumatrapdf/issues/3043#issuecomment-1287993792
* this also makes it hard to diagnose the cause of error as in https://github.com/sumatrapdfreader/sumatrapdf/issues/2983#issuecomment-1257131317

So, 
* having storing the filestats in a separate file as logs or something will likely help with these and make things a bit more modular/manageable
* ofcourse, there ain't a very strong need for it, but i thought to file it to share it

**Comment by GitHubRulesOK** [comment] 2022-10-23 20:24
that question was raised by me and many others many times :-) 
so closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1174

**Closed by GitHubRulesOK** 2022-10-23 20:24 UTC
