### ISSUE TITLE
Usability: Add a few pixels above tab bar when maximized to drag maximized window from the titlebar

### ISSUE THREAD

**Issue by sahil48** [sumatrapdfreader/sumatrapdf#2011] opened 2021-07-07 17:42 UTC
![image](https://user-images.githubusercontent.com/6100774/124805032-f78f9480-df28-11eb-9b9f-36d8d394a610.png)

It would be very helpful to add 1 or 2 pixel tall row above the tab bar so that a maximized windows can be dragged with a mouse without the tabs interfering.

The unmaximized state is shown below for reference.
![image](https://user-images.githubusercontent.com/6100774/124805179-2a398d00-df29-11eb-9405-1925c81f1a62.png)

I can drag on the blue part of the titlebar. If I try to drag by the tabs, I reorder the tabs.

**Comment by GitHubRulesOK** [comment] 2021-07-07 19:31
There are users that want minimal dressing.
When maximised the complaint was the icon was not needed
Eventually it was thus ensured that Yellow Icon could be used for grab and drag as you require !

**Comment by GitHubRulesOK** [comment] 2021-07-07 22:35
Closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/423

**Closed by GitHubRulesOK** 2021-07-07 22:35 UTC
