### ISSUE TITLE
Crash opening pdf nullptr

### ISSUE THREAD

**Issue by sleepyspider1** [sumatrapdfreader/sumatrapdf#2946] opened 2022-09-09 00:36 UTC
[Crash Log](https://gist.github.com/sleepyspider1/e10bb840c74401fb6d220dad2bc41d01)

Look like this is important:

MakePageElementCommentsFromAnnotations: annot 11 'StrikeOut', contents: '', label: 'CP27'
StrikeOut annotations have no Rect property
aborting process from uncaught error!

00007FF9E348FA53 01:000000000012EA53 libmupdf.dll!fz_rethrow+0xf D:\a\sumatrapdf\sumatrapdf\mupdf\source\fitz\error.c+301
00007FF9E34EBD3F 01:000000000018AD3F libmupdf.dll!pdf_annot_rect+0x153 D:\a\sumatrapdf\sumatrapdf\mupdf\source\pdf\pdf-annot.c+1007
00007FF7C7BF6AF5 01:00000000000A5AF5 sumatrapdf.exe!MakePdfCommentFromPdfAnnot+0x2d D:\a\sumatrapdf\sumatrapdf\src\EngineMupdf.cpp+2389
00007FF7C7BF6E82 01:00000000000A5E82 sumatrapdf.exe!MakePageElementCommentsFromAnnotations+0x2b2 D:\a\sumatrapdf\sumatrapdf\src\EngineMupdf.cpp+2412
00007FF7C7BF706A 01:00000000000A606A sumatrapdf.exe!EngineMupdf::GetFzPageInfo+0x166 D:\a\sumatrapdf\sumatrapdf\src\EngineMupdf.cpp+2504

**Comment by CharlesMengCA** [comment] 2022-09-10 17:37
Same error here.

**Comment by GitHubRulesOK** [comment] 2022-09-27 03:27
@sleepyspider1 @CharlesMengCA 

Should be fixed in 3.5.15244+ (see note)
likely caused by annotation instability

Note:- current pre-release is 3.5.15249 and on first run MAY crash for a different reason see https://github.com/sumatrapdfreader/sumatrapdf/issues/2984

**Closed** 2022-10-08 02:19 UTC
