### ISSUE TITLE
静默打印PDF，打印出来错位

### ISSUE THREAD

**Issue by PPScript** [sumatrapdfreader/sumatrapdf#3053] opened 2022-10-25 09:15 UTC
`SumatraPDF.exe -print-to-default  "${pdfUrl}"`

**Comment by PPScript** [comment] 2022-10-25 09:19
![WX20221025-171911](https://user-images.githubusercontent.com/21254998/197735476-ce9b18fa-3918-4524-8704-7d8d6abeaab4.png)

**Comment by GitHubRulesOK** [comment] 2022-10-25 12:18
Please use English Titles

[静默打印PDF，打印出来错位] = **Print PDFs silently, print out misaligned**

The quality of convert pixels for printing is down to windows driver
SumatraPDF passes coloured lines to system
================
System needs to convert to mono
-_-_-_-_
Nothing SumatraPDF VIEWER can do about that, either use Adobe Acrobat adjust pdf align to print or try a thermal driver that adjusts colour input to mono averaging of anti-alias. [Seagull Bartender](https://www.seagullscientific.com/support/downloads/drivers/) is a good alternative **for some cases**

**Comment by GitHubRulesOK** [comment] 2023-10-20 02:33
closing as SumatraPDF since version 3.0 is tied to Windows image Printing and its settings for a B&W print a B&W driver such as MS fax or alternative is required, especially for thermal devices pixelation..

A driver such as designed for label printers will work better by aligning pixels with thermal device pin heads.

**Closed by GitHubRulesOK** 2023-10-20 02:33 UTC
