### ISSUE TITLE
version 3.1.2 prviews not working on Outlook

### ISSUE THREAD

**Issue by kihapet** [sumatrapdfreader/sumatrapdf#590] opened 2016-08-17 10:10 UTC
Hi 
I had to go back to ver 3.0 for the Previews to Work
It says No previewer can be found
I have Outlook 2010

**Comment by irvinm** [comment] 2016-10-13 19:12
This is a duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/393.

**Closed** 2016-10-13 21:15 UTC
