### ISSUE TITLE
Usability/design of tabs

### ISSUE THREAD

**Issue by pablotheissen** [sumatrapdfreader/sumatrapdf#938] opened 2017-12-07 08:14 UTC
As much as I like the tabbed interface, the usability is not very high:

- the color difference between active and not-active is not big enough
- the tabs are cluttered with the X symbol for closing; only show the X while hovering the tab
- the color when hovering the active tab is the same as the not-active tabs. Does a color change when hovering the active tab even make sens? No other software does that.
- hovering non-active tabs doesn't lead to a color change as it does in almost every other software.
- rounded tabs don't work well in Windows, as nothing else is rounded (anymore)

Proposal:
- less round tabs
- active tab light color
- background tabs dark color
- hover over background tab: slightly lighter color, but not as light as active tab
- hover over active tab: no color change
- darkest color should be lighter than the active tab color as it is now, so you can read the black font more easily
![tabs](https://user-images.githubusercontent.com/13626568/33705023-02854b66-db2f-11e7-90fa-6b434066ebd0.png)

**Comment by SumatraPeter** [comment] 2017-12-07 18:41
Can be marked as duplicate of (take your pick): #343, #559, #743, #898.

**Comment by GitHubRulesOK** [comment] 2019-11-21 23:03
@kjk most of above sugestions have actually been implimented and as @SumatraPeter has identified the above recomendations were also duplicated elswhere

**Comment by GitHubRulesOK** [comment] 2020-02-06 14:18
As suggested these points are discussed elsewhere especially in #559 so closing as duplicate to be consolidated with that

**Closed by GitHubRulesOK** 2020-02-06 14:18 UTC
