### ISSUE TITLE
Toolbar Icons

### ISSUE THREAD

**Issue by Tuinpad** [sumatrapdfreader/sumatrapdf#1190] opened 2019-08-18 10:57 UTC
Has development stopt for SumatraPDF?
Several years the issue excist for the toolbar icons, they are not ment for 2K and 4K monitors.

Still hope for a update......

**Comment by SumatraPeter** [comment] 2019-08-19 00:19
@kjk: Duplicate of #734

**Comment by kjk** [comment] 2019-08-19 01:17
closing as duplicate of #734

**Closed by kjk** 2019-08-19 01:17 UTC
