### ISSUE TITLE
Bug with tabs overlapping the minimize button (Win10)

### ISSUE THREAD

**Issue by DaneWeber** [sumatrapdfreader/sumatrapdf#586] opened 2016-08-11 15:56 UTC
SumatraPDF v3.1.1 64-bit (git commit 5d317fd) works pretty well for me in Windows 10, but once I have enough tabs open the right-most tab obscures the "minimize window" button.

[![enter image description here](http://i.stack.imgur.com/2Ba5y.png)](http://i.stack.imgur.com/2Ba5y.png)

**Relevant details**

I also tried this with the portable pre-release with the same results. (v3.2.10534 64-bit pre-release; git commit d431528).

I'm using a Surface Book with the main screen at 200% zoom. The external monitor is at 100% zoom. The behavior is the same on both screens.

**Comment by GitHubRulesOK** [comment] 2020-02-04 14:52
This issue is another duplicate of / consolidated as #447

**Closed by GitHubRulesOK** 2020-02-04 14:52 UTC
