### ISSUE TITLE
Unable to generate thumbnails

### ISSUE THREAD

**Issue by cmkpl** [sumatrapdfreader/sumatrapdf#2080] opened 2021-07-30 06:30 UTC
Hi, I found that for the latest pre-release 13925, thumbnails were unable to be generated in Windows Explorer.

OS: Windows Server 2016

**Comment by GitHubRulesOK** [comment] 2021-08-01 18:12
@kjk 
I just installed the recent build 13949 as standard/elevated install and can confirm that the previewer is only showing a blank grey field without content. I had not previously updated from working 3.3.3. formal build

**Comment by cmkpl** [comment] 2021-08-02 01:16
I have tried the following but no help:
1. install a newer build (prerelease)
2. uninstall and install with reboot in between
3. regsvr32 the dll

**Comment by GitHubRulesOK** [comment] 2021-08-02 01:38
@cmkpl 
THANK YOU
current pre-release seems broken since your report (may be fived in a day or two ?

You would need to roll back installed to stable 3.3.3 for current  pre-viewer support

**Comment by kjk** [comment] 2021-08-03 08:34
Should be fixed, please re-test.

**Comment by GitHubRulesOK** [comment] 2021-08-03 14:15
@kjk  its part working here 50% of the pdfs i.e. those with small blue Edge icon are fine, but unsure of the cause for the red ones, I know file security such as password blocks viewing thumbnails or preview and here the blank preview is a file that crashes SumatraPDF However the other 3 red ones will preview 
![image](https://user-images.githubusercontent.com/12754913/128030322-31453797-e711-48a1-8c6a-ce38829d7857.png)
![image](https://user-images.githubusercontent.com/12754913/128030499-cd3ed37e-c91b-4770-9bf3-42c32b7a854e.png)

**Comment by GitHubRulesOK** [comment] 2022-05-01 02:00
@kjk suggest this is closed due to significant changes for thumbnail's/preview and any new rogue files become fresh issues

**Closed** 2022-05-01 02:07 UTC
