### ISSUE TITLE
Allow 2 (or more?) views of the same file

### ISSUE THREAD

**Issue by mklhmnn** [sumatrapdfreader/sumatrapdf#1575] opened 2020-05-03 13:45 UTC
Imagine a PDF file which shows a graphic at one page and its description at a different page, e.g. a car manual. Currently, I can't look at the graphic and its description at the same time and have to scroll back and forth. With 2 views I could see the graphic in one view and the description in the other one.

**Comment by GitHubRulesOK** [comment] 2020-05-03 14:24
Without tabs it is easy to open same file using a second window

Using tabs then CTRL SHIFT N in recent versions should open same file in a second window

There are other older variations on this issue and workarounds so am closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/18# and many others linked within it

**Closed by GitHubRulesOK** 2020-05-03 14:24 UTC
