### ISSUE TITLE
[Feature request] Allow "Frequently read" page to stay in its own tab after we open the first file

### ISSUE THREAD

**Issue by jdarias** [sumatrapdfreader/sumatrapdf#924] opened 2017-11-07 02:21 UTC
It would be very convenient to allow the "Frequently read" page to inhabit a permanet tab. This way we would have access to the recent files thumbnails at all times.

Currently we have access to the thumbnails when no file is open. 

Once we open a file, the thumbnails page is gone (gets replaced by the file we opened).

If we need to open more files, we have to guess the correct file from the list of recent files in the "file" menu. Having the thumbnails page at hand would be more convenient.

**Comment by SumatraPeter** [comment] 2018-03-18 01:09
Essentially a duplicate of #406

**Comment by GitHubRulesOK** [comment] 2020-01-06 14:10
@kjk ? consolidate with #406

**Comment by kjk** [comment] 2020-01-06 22:13
Consolidate under #406

**Closed by kjk** 2020-01-06 22:13 UTC
