### ISSUE TITLE
Make the scrolling animation more flow and smooth

### ISSUE THREAD

**Issue by michelecafagna26** [sumatrapdfreader/sumatrapdf#1083] opened 2018-10-17 20:30 UTC
I think that it could be improved scrolling and zooming animation to have better user experience. Just to have something to refer to, I intend something like macOS pdf reader

**Comment by GitHubRulesOK** [comment] 2018-11-05 21:46
Always difficult to know how much is platform specific e.g. One Mac PDF Preview feature is "by pressing and holding the button, then adding pressure; the more firmly you press, the faster you move through the pages." That would not apply to many windows machines. Using animations to slow down movement is unlikely to be favoured by most users, I always switched it off in previous windows and haven't a clue if available in windows 10. SumatrPDF ethos has always been to be fast with minimal UI just like any physical screen reader but hardware variations can cause issues with response rate especially touchscreen/pads/balls.

**Comment by SillyBirds** [comment] 2019-06-24 18:48
It would indeed be nice if the scrolling was nicer. I don't use it for pdfs, but for manga, with continuous view. How about custom scrolling like in PicWalker? (I would still use it, if it wasn't that it doesn't support webp)

![image](https://user-images.githubusercontent.com/22528910/60043602-c127a980-96c0-11e9-88b4-1ee19808c003.png)

Another thing... if it was possible that the zoom didn't reset when going to the next file, that would be awesome.

**Comment by GitHubRulesOK** [comment] 2019-06-24 20:23
@SillyBirds  Zoom per file should be stored if "remember" is on

When opening fresh the choice is on standard menu `settings` `options` `default zoom` or in settings file for example 
DefaultDisplayMode = single page
DefaultZoom = 75

**Comment by SillyBirds** [comment] 2019-06-24 21:18
Thanks, but that doesn't help much... I see the remember setting allows you to remember alteady viewed files, but still resets on new ones. I don't want to set a default zoom in advance, since not all files have the same resolution. Different series have different resolutions. It would be nice to keep the same settings when you start going trough volumes.
Thanks for the reply though.

**Comment by GitHubRulesOK** [comment] 2020-02-18 03:36
Since original post is a duplicate of other scroll speed issues I am consolidating with #606

@SillyBirds on your separate specific preset zoom issue
You can have different preset profiles for say zoom settings etc by using different settings.txt files see method 2 here https://forum.sumatrapdfreader.org/t/sessions-in-sumatra/1272/2

Please raise a separate New Issue if you can't get separate setting files working to your advantage

**Closed by GitHubRulesOK** 2020-02-18 03:36 UTC
