### ISSUE TITLE
Large toolbar icons 

### ISSUE THREAD

**Issue by rornor** [sumatrapdfreader/sumatrapdf#824] opened 2017-06-05 01:15 UTC
This issue is a bit older but wanted to report as I already reported another issue at the same time.

I have 1920x1080 laptop, and use 125% display scaling as recommended by Windows 10 system.
Here is screenshot of latest SumatraPDF:

![image](https://cloud.githubusercontent.com/assets/3144780/26767109/f17d141c-499c-11e7-9a21-05d8ff6d4e13.png)

This does not happen with any other application I have.

**Comment by kjk** [comment] 2017-06-05 03:02
Is the issue that they are too large or not large enough?

**Comment by kjk** [comment] 2017-06-11 22:25
Closing as duplicate of #734

**Closed by kjk** 2017-06-11 22:25 UTC
