### ISSUE TITLE
Background color choice for tree text with Dark(er) themes makes text unreadable

### ISSUE THREAD

**Issue by KingRabbid** [sumatrapdfreader/sumatrapdf#4016] opened 2024-01-09 11:43 UTC
**SumatraPDF version**
- Version [e.g. 3.5.2, pre-release]

**Describe the bug**
Using Dark/Darker themes with view Bookmarks tree list makes selected leaf unreadable as the background is also black, same as text color.
Note there are 2 behaviors in scope:
1. Selecting the leaf, focus remains on the tree window => one color is used to fill the background of selection
2. Selecting the leaf, focus changes to the document page => a different color is used to fill the background of selection

**Note**: I'm using Windows 11 with a theme Personalization->Colors as following: 
1. default Windows mode: Dark
2. default App mode: Light
3. custom Accent color (#7E98A1), not sure if this has any side-effect?

**To Reproduce**
1. Select Dark/Darker themes
2. Select anything from the Bookmarks tree
3. Keep the mouse in Bookmark tree window
4. Select anything from the document window

**Expected behavior**
Selected bookmark text should be readable.

Thank you

**Comment by GitHubRulesOK** [comment] 2024-01-09 14:22
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/3849 
and related to  https://github.com/sumatrapdfreader/sumatrapdf/issues?q=is%3Aissue+is%3Aopen+bookmarks

**Closed by GitHubRulesOK** 2024-01-09 14:22 UTC

**Comment by kjk** [comment] 2024-06-04 14:22
It's closed as duplicate of another bug, which is still open and describes the same issue.
