### ISSUE TITLE
Different PDF view against Firefox

### ISSUE THREAD

**Issue by prostraction** [sumatrapdfreader/sumatrapdf#1860] opened 2021-01-17 17:20 UTC
This PDF: 
[1.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5826505/1.pdf)
Wrong Sumatra view:
![issue](https://user-images.githubusercontent.com/47314760/104850651-5a508d80-5901-11eb-9964-2d2229774843.PNG)
Correct view (Firefox):
![correct](https://user-images.githubusercontent.com/47314760/104850661-705e4e00-5901-11eb-84f8-fefc57335648.PNG)

**Comment by GitHubRulesOK** [comment] 2021-01-17 19:19
@kjk 
fine in 3.1.2 looks bad in 3.2 and MuPDF-GL (most versions I tested going back pre 3.1.2) so unsure if it was always poor render (somehow fixed within 3.1.2) or a regression?
![image](https://user-images.githubusercontent.com/12754913/104853439-c7abf080-58f8-11eb-957a-a3255047cd84.png)

**Comment by prostraction** [comment] 2021-01-17 19:42
> @kjk
> fine in 3.1.2 looks bad in 3.2 and MuPDF-GL (most versions I tested going back pre 3.1.2 to MuView 2008) so unsure if it was always poor render (somehow fixed within 3.1.2) or a regression?
It was on 3.2 version, I've downgraded to 3.1.2, now it looks fine, thanks.
There are some problems with -  _ symbols on several documents.
3.1.2 vs 3.2 compare:
![example1](https://user-images.githubusercontent.com/47314760/104853929-22ebdc00-5915-11eb-8042-49dee541a047.PNG)

**Comment by GitHubRulesOK** [comment] 2021-01-17 19:50
That file seems  to present those lines oddly in other viewers too, so I suspect the source is the cause
![image](https://user-images.githubusercontent.com/12754913/104854179-38550c00-58fd-11eb-993a-1a4c252f5a7e.png)

**Comment by prostraction** [comment] 2021-01-17 19:58
Okay, sorry for issue then. I've tested this file on Firefox, and it shows it correctly, so I think it's a reader problem.

**Comment by GitHubRulesOK** [comment] 2021-01-17 20:02
@prostraction I have reopened for now as I agree it currently looks bad in SumatraPDF, but need to see if MuPDF agree its their problem

**Comment by GitHubRulesOK** [comment] 2021-01-17 21:17
Reported as potential bug https://bugs.ghostscript.com/show_bug.cgi?id=703350

**Comment by GitHubRulesOK** [comment] 2021-01-27 14:20
Feedback from MuPDF say it is a badly crafted file (much as I suspected)
When I (one editor) refresh the core area with a single height font (admittedly I then introduce a different line spacing) 

However we can see it now does not have a problem with differing line heights within each line.
[1860-1 (reedited).pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5880739/1860-1.reedited.pdf)

**Closed by GitHubRulesOK** 2021-01-27 14:20 UTC
Labels: mupdf
