### ISSUE TITLE
Problem with displaying text and images in fb2 files in assembly 3.5.14958 x64.

### ISSUE THREAD

**Issue by Dharmainiciativ** [sumatrapdfreader/sumatrapdf#2619] opened 2022-05-28 19:19 UTC
The images in the files began to overlap with the text, the text itself was difficult to read and became somehow bold.
With epub files, the same problem with images. Plus, epub and fb2 files do not open through the Open menu. But it seems that this applies to paths with Cyrillic names.
Sample files at https://www.upload.ee/files/14180760/Gippenreyter_Obshchatsya-s-rebenkom-Kak-.jn6v6A.263993.fb2.zip.html

**Comment by kjk** [comment] 2022-05-28 19:33
Test file: .fb2 inside .zip:

[Gippenreyter_Obshchatsya-s-rebenkom-Kak-.jn6v6A.263993.fb2.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/8791746/Gippenreyter_Obshchatsya-s-rebenkom-Kak-.jn6v6A.263993.fb2.zip)

**Comment by kjk** [comment] 2022-05-28 19:37
Recent mupdf regression, reported at https://bugs.ghostscript.com/show_bug.cgi?id=705374

**Comment by Dharmainiciativ** [comment] 2022-05-28 19:50
Thank you, with images the answer is clear. What can be done with the display of text in fb2?
Checked more carefully the problem with opening files. Stopped opening all types of files if there is Cyrillic in the path.
Win7 x64 system.

**Comment by kjk** [comment] 2022-05-28 20:53
I can't reproduce the cyrliic issue. I used  File / Open in latest build and was able to open "C:\Users\kjk\Downloads\bug2619\Юлия_Гиппенрейтер_Как_бы_ты_поступил.epub" 

As to fb2 rendering: looks like another regression in latest mupdf.

**Comment by kjk** [comment] 2022-05-28 20:56
Reported cyrllic issue at https://bugs.ghostscript.com/show_bug.cgi?id=705375

**Comment by GitHubRulesOK** [comment] 2022-05-28 21:04
@kjk 
possibly/not MuPDF
The TOC is handled differently
![image](https://user-images.githubusercontent.com/12754913/170842796-c42dd98f-dfd8-4079-8d70-ef3645880794.png)

**Comment by Dharmainiciativ** [comment] 2022-05-28 21:05
> I can't reproduce the cyrliic issue. I used File / Open in latest build and was able to open "C:\Users\kjk\Downloads\bug2619\Юлия_Гиппенрейтер_Как_бы_ты_поступил.epub"
You have Latin at the beginning of the path, in my case there are paths starting with Cyrillic. For example "E:\Книги\" or "E:\Мои документы\"
![2022-05-29 00_02_20-SumatraPDF](https://user-images.githubusercontent.com/10089507/170842804-c0589272-e1aa-4a82-ae44-999de4ae7407.png)
![2022-05-29 00_03_37-SumatraPDF](https://user-images.githubusercontent.com/10089507/170842806-55cf50d5-535a-4d4b-b708-0f1a39fcb68e.png)

**Comment by Dharmainiciativ** [comment] 2022-05-28 21:11
> @kjk возможно/не MuPDF TOC ![изображение](https://user-images.githubusercontent.com/12754913/170842796-c42dd98f-dfd8-4079-8d70-ef3645880794.png)
I have a problem with opening not only fb2 and epub. The problem also affected pdf and djvu files.
The screenshots show that the opening paths are not the same, they are added or distorted.

**Comment by GitHubRulesOK** [comment] 2022-05-28 21:14
@Dharmainiciativ 
If E: is a usb drive formatted as FAT e.g. (non NTFS) then some Unicode characters may work and others may not

However that is often a Windows issue the "? in Diamond" is a signal that that UTF combination of 1-4 characters was not recognized within the current range. 

It is possible to sometimes get around that limit by changing windows settings or in cmd console using a different code page. but on one "Korean" occasion nothing seemed to help in a users name even on their main Drive !!.

**Comment by Dharmainiciativ** [comment] 2022-05-28 21:19
> If E: is a usb drive formatted as FAT e.g. (non NTFS) then some Unicode characters may work and others may not

In my case, it's just another local drive, NTFS. Not systemic!
And again, in the stable version of this problem there is no, so the point is in the current changes. In which commit the error crept in, I'll never know, I'm not a programmer.

**Comment by GitHubRulesOK** [comment] 2022-05-28 21:33
Ok just to prove me partially wrong D: in my current win 11 is an OLDer FAT drive so may not have always supported Cyrillic in all apps
However with the sample file in a Cyrillic path its not a problem in current configuration !

![image](https://user-images.githubusercontent.com/12754913/170843528-48c70090-003f-4b48-bc38-3a7c4b6ac2fc.png)

**Comment by Dharmainiciativ** [comment] 2022-05-28 21:40
> Хорошо, просто чтобы доказать, что я частично не прав D: в моей текущей Win 11 используется СТАРЫЙ FAT-диск, поэтому, возможно, он не всегда поддерживал кириллицу во всех приложениях . Однако с образцом файла в кириллическом пути имя файла не является проблемой в текущей конфигурации!
> 
> ![изображение](https://user-images.githubusercontent.com/12754913/170843528-48c70090-003f-4b48-bc38-3a7c4b6ac2fc.png)
Maybe it's in the system, I have Windows 7 x64.
And once again, I do not open ALL files where there is Cyrillic at the beginning of the path.
As an assumption, the culprit is most likely Visual Studio, and its assembly of the program under Windows 7.

**Comment by kjk** [comment] 2022-05-28 21:41
The issue with File / Open files with cyrillic should be fixed in 14962+

**Comment by GitHubRulesOK** [comment] 2022-05-28 21:55
***Ahh*** I was on that device using a slightly older 3.5 pre-release thus working
on update to more recent agreed to 3.5.14961 there was a problem

**Comment by kjk** [comment] 2022-05-29 00:20
Regarding difference in Bookmarks: mupdf seems to auto-add table of contents entries for sections.

It's not exactly wrong, just different to what was before. Those auto-added entries are useful, so I'm not going to try to change that.

**Comment by kjk** [comment] 2022-05-30 19:41
The issue of images overlapping text is fixed in latest pre-release 14994 or later

**Closed by kjk** 2022-05-30 19:41 UTC
Labels: mupdf
