### ISSUE TITLE
How to solve the error: Not enough room in an internal buffer?

### ISSUE THREAD

**Issue by TianZhengjie-lxc** [sumatrapdfreader/sumatrapdf#1868] opened 2021-01-27 04:58 UTC
In the latex, there are a lot of pictures, and the latex code is like this:\includegraphics[width=\linewidth]{../../result/single_factor/JQ_indicator_operating_expense_to_total_revenue_4q_1/reset_20/801150.0/Net_balance__short_bottom_mkt_cap_square_root_weighted.jpg}%,
the error:pdflatex.exe:Not enough room in an internal buffer

**Comment by GitHubRulesOK** [comment] 2021-01-27 09:55
I am going to close this issue since, That error is a (PDFLa)TeX error message thus should be a problem using any pre-viewer i.e. should not be caused by using SumatraPDF. If you can find any reason it is affected by only using SumatraPDF then you would need to provide more details, however such problems are best answered in TeX forums.

Google the error and see it is usually caused by large number of graphics with one or more file path problems so look at those.
The paths should be short to fit in the buffers and ideally **avoid spaces or other "non Latin" characters** causing doubled entries, etc.

**Closed by GitHubRulesOK** 2021-01-27 09:55 UTC

**Comment by TianZhengjie-lxc** [comment] 2021-01-27 10:04
Thank you,
I find it's the filepath length problem vie google and tex forum,  this is the problem of latex', I try to move the pic file to the same folder
Thanks again
