### ISSUE TITLE
Incorrectly rendered characters

### ISSUE THREAD

**Issue by WalrusInAnus** [sumatrapdfreader/sumatrapdf#836] opened 2017-06-24 12:18 UTC
See [here](http://zbranekvalitne.cz/d/zp/formulare/kupni-smlouva-na-zbran.pdf).
There are question marks over the document in place of czech characters.

**Comment by SumatraPeter** [comment] 2017-06-27 16:33
What's interesting is that the text where Sumatra 3.1.2 displays question marks doesn't even show up in Firefox and Edge's own PDF viewers.

Sumatra 3.1.2:
![sumatra](https://user-images.githubusercontent.com/15380332/27598788-301693f8-5b84-11e7-92eb-6e38d730eb83.png)

Firefox 54.0:
![firefox](https://user-images.githubusercontent.com/15380332/27598801-3ebb4c14-5b84-11e7-9d04-2cfa518e48bd.png)

Edge 40.15063.0.0:
![edge](https://user-images.githubusercontent.com/15380332/27598807-44be6646-5b84-11e7-8884-b4e67ae21184.png)

What does the latest Adobe Reader display?

**Comment by WalrusInAnus** [comment] 2017-06-27 17:30
I have no ide about the Adobe bloatware, I happily ditched it years ago (around version 10) when I discovered Sumatra and never looked back.

**Comment by tschoening** [comment] 2017-10-27 09:37
Opera 48.0.2685.50:

![opera 48 0 2685 50](https://user-images.githubusercontent.com/6223655/32097820-12d598ca-bb0b-11e7-8b63-d5dfb82d1986.png)

Adobe Reader DC 2017.012.20098:

![adobe reader dc 2017 012 20098](https://user-images.githubusercontent.com/6223655/32097831-16e6116a-bb0b-11e7-81a9-e766703a6f04.png)

**Comment by GitHubRulesOK** [comment] 2020-02-21 22:30
This appears to be a javascript driven form and latest pre-release render the static parts of the form correctly same as Firefox and Edge above
![image](https://user-images.githubusercontent.com/12754913/75076872-2904ed00-54f9-11ea-93e1-89a687cea6ad.png)

Since the OP issue is resolved I am consolidating residual issue as dupe of #48 and consolidating per "Support for filling forms is tracked in #1249 "

**Closed by GitHubRulesOK** 2020-02-21 22:30 UTC
