### ISSUE TITLE
Thin lines, exceptional processing output

### ISSUE THREAD

**Issue by Canule** [sumatrapdfreader/sumatrapdf#1076] opened 2018-09-20 09:10 UTC
The only thing holding be back for ditching that terrible massive, nonsense bloated, pdf file locking(notes) Acrobat ?Reader, is the processing of drawings compared to this lovely lightweight Sumatrapdf

At the moment Sumatra give such thin lines(layer VIS,VIS if pushed towards PDF during export) they are barely shown. *example doc below.

Would it be possible to adjust its processing output to equal Acrobat/Xreader/Firefox/...?

Example files output difference; Source pdf + Sumatra output(scanned prints Adobe vs Sumatra)
https://github.com/Canule/sumatrapdf/blob/master/sumatrapdf.zip :x:

**Comment by GitHubRulesOK** [comment] 2018-09-20 15:10
@Canule this is a duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1034

here are the results of ensuring your file meets DIN/ISO standard I see no problem with this file
[out thinlines 0.18.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/2401907/out.thinlines.0.18.pdf)

**Comment by Canule** [comment] 2018-09-24 13:28
Thank you for the awareness, I had no idea Adobe had such dirty function enabled by default(made necessarily) discouraging the source output to be towards DIN/ISO.

I imagine that Adobe function is probably the cause the CAD(EPLAN) software and its own product macro's(as in example drawing of that Rital panel) being without line thickness / not applied on PDF export / no warnings of it during the checkup of the object based electrical scheme.

**Comment by GitHubRulesOK** [comment] 2018-09-24 15:27
I note you have removed your sample and am willing to remove my link if you wish for privacy?

**Comment by Canule** [comment] 2018-09-25 18:05
Since the situation is clear, that would be nice, ty.

**Closed** 2018-09-26 07:29 UTC
