### ISSUE TITLE
Sumatra don't shows bold characters in some epubs.

### ISSUE THREAD

**Issue by CC51** [sumatrapdfreader/sumatrapdf#1125] opened 2019-01-18 00:34 UTC
I have some books in epub format with texts in bold characters, but Sumatra shows them as normal.
[Aveskulov-Improving_the_Endgame_Technique_Opposite-Colored_Bishop_Endgames(2018).zip](https://github.com/sumatrapdfreader/sumatrapdf/files/2771119/Aveskulov-Improving_the_Endgame_Technique_Opposite-Colored_Bishop_Endgames.2018.zip)

**Comment by GitHubRulesOK** [comment] 2019-01-19 20:45
That's because **.bold** is not in the body style as normally done but is set in the browser style sheet (built with 17 different "calibre" tags) They will work in tolerant HTML viewers such as Edge but they are not good generic HTML

You could ask for an alternative format from the author (looks like it was designed for Kindle/Mobi use $3.70 from Amazon) or reconvert (but NOT with calibre)

![untitled](https://user-images.githubusercontent.com/12754913/51431927-b2c3f600-1c27-11e9-91e9-20c76de7e11c.png)

**Comment by GitHubRulesOK** [comment] 2019-01-19 20:47
@kjk this converted file crashes latest MuPDF and as it is poorly converted/constructed suggest it is not strictly a failing in SumatraPDF, perhaps tag as future MuPDF needs to accept this method of "styling"

**Comment by GitHubRulesOK** [comment] 2020-02-03 05:27
Recent MuPDF engine could handle this issue
![image](https://user-images.githubusercontent.com/12754913/73627770-d943ac00-4645-11ea-9216-aa28a9c6e9b2.png)

**Comment by GitHubRulesOK** [comment] 2021-08-16 01:26
Closing as file is handled correctly and pre-release meets expectations to show fonts as bold
![image](https://user-images.githubusercontent.com/12754913/129499711-5007431f-3a2f-4686-bb63-9df710cca763.png)

**Closed by GitHubRulesOK** 2021-08-16 01:26 UTC
Labels: ebook
