### ISSUE TITLE
Bug report: Version:prerel-13925-64

### ISSUE THREAD

**Issue by terrypa** [sumatrapdfreader/sumatrapdf#2077] opened 2021-07-29 15:10 UTC
https://gist.github.com/terrypa/baf63e1131b08c26a67127a854c4c31e

**Comment by VictorVG** [comment] 2021-07-29 21:16
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/2076

**Comment by kjk** [comment] 2021-07-30 09:52
Looks like a crash in mupdf but can't investigate without the file that caused the crash.

Could you make it available as described in https://www.sumatrapdfreader.org/docs/How-to-submit-bug-reports

Also please provide step-by-step instructions on how to reproduce the crash.

Does it happen every time or just sometimes?

**Comment by terrypa** [comment] 2021-07-30 20:08
Hello, I'm tried to replicate a crash and from what I see the specific file do not play a role, Crash happens when sumatra is restarted again and try to load previous files (whatever they may be)

Also from current crash log (crash number 2) looks like sumatra got log (and maybe trying) to open every pdf i ever had opened, crash log got over 20k lines picture:
https://i.imgur.com/8S2ihBP.png

do to the privacy reason i will delete part with file names

Also i did combine both bug reports in one git with 2 separate files named first crash and second crash and I'm uploading all 3 files to the dropbox (could not upload to the git)

https://gist.github.com/terrypa/fac69402a5c7ca36127733be110f72b4

https://www.dropbox.com/sh/xftdhxefa9wwr08/AAB9XQGOi6t7xzwJKedXxnYIa?dl=0

P.S some after thoughts that maybe helpful

https://i.imgur.com/NbZoK5c.png

**Comment by kjk** [comment] 2021-07-30 20:24
Thanks, I can reproduce this. Looks like multi-threading issue with how mupdf uses harfbuzz.

**Comment by terrypa** [comment] 2021-07-30 20:25
I'm glad I could helped :) 
Pozdro ! :)

**Closed** 2021-07-30 20:33 UTC
