### ISSUE TITLE
FR: Touchpad Support

### ISSUE THREAD

**Issue by dylanchu** [sumatrapdfreader/sumatrapdf#1521] opened 2020-03-25 11:08 UTC
Hi dear sumatra developers, you guys have made an amazing software! I like it very much and thanks for your efforts! 

But the only problem is that I found the support for touchpad is not good. **It just moves too fast when I use 2-finger guestures to scroll the page.**  （Yes, I'm already using the contiguous mode）

I believe Windows is not doing very well on processing the touchpad signals as I found almost every software on my Linux can have a nice scroll experience, but different when it comes to Windows. Even the new Edge browser can't scrolls well enough when using a touchpad. That's really awful experience for users who use the touchpad a lot.

@GitHubRulesOK has post a comment to explain how to [adjust the scroll speed from Windows](https://github.com/sumatrapdfreader/sumatrapdf/issues/606#issuecomment-587218862) in a somehow similar issue. But I dont think that should be the solutions because it is adjusting the scroll speed for the whole windows, and both for the touchpad and the mouse.

As I found my Chrome and Firefox both provide a perfect scrolling experience, l think there still could be some workarounds from the application level. So could you guys please write some codes to process the signals that Windows passed in, so that sumatra can provide a good scrolling experience as Firefox does? (maybe sth. like a software smoothing filter with a maximum value limit?)

Thanks guys!

**Comment by GitHubRulesOK** [comment] 2020-03-25 11:33
Duplicate of #606

**Closed by GitHubRulesOK** 2020-03-25 11:33 UTC
