### ISSUE TITLE
PDF file incorrectly displayed

### ISSUE THREAD

**Issue by kuklis** [sumatrapdfreader/sumatrapdf#399] opened 2015-12-22 18:19 UTC
Hello,

this file cannot be viewed correctly in SumatraPDF, Acroread works fine:
https://business.americanexpress.com/hu/~/media/Files/GCP/hu/Vallalati_Kartyabirtokosi_Keretszerzodes_es_Igenylolap.pdf

**Comment by PF4Public** [comment] 2016-06-23 14:00
Some files are indeed displayed incorrectly by SumatraPDF.
This is another example: www.skanco.se/assets/files/zia_xl_6s_g_i.pdf

**Comment by GitHubRulesOK** [comment] 2019-11-21 16:36
@kjk the first example is Adobe forms format that can not work well in non adobe readers see latest fire fox rendering
![untitled](https://user-images.githubusercontent.com/12754913/69357138-81b7b600-0c7c-11ea-893d-2ad1809378b1.png)
the second example is not accesible however we know "Blanco" use a range of very offbeat formats
![untitled3](https://user-images.githubusercontent.com/12754913/69357314-c7747e80-0c7c-11ea-91c8-8d500c22fcf4.png)

however  the first example renders well in latest builds even if you cant change language
![untitled2](https://user-images.githubusercontent.com/12754913/69357430-fe4a9480-0c7c-11ea-8787-0ed09229aa92.png)

**Comment by PF4Public** [comment] 2019-11-21 20:52
I can confirm, that `zia_xl_6s_g_i.pdf` is poorly rendered in 3.1.2, but current prerelease renders it just fine.

**Comment by GitHubRulesOK** [comment] 2019-11-21 21:00
@PF4Public Thank you for that confimation, it seems skanco files are no longer available from the old site.

**Comment by PF4Public** [comment] 2019-11-21 21:01
I've found it here: https://blanco-shop24.ru/data/PDF/zia_xl_6s_g_i.pdf

**Comment by GitHubRulesOK** [comment] 2019-11-21 21:06
@PF4Public thanks again for link that example is one of the Pro/Engineer files where ISO values for pen line thickness have not been correctly set by the draughtsman for PDF plotting.

**Comment by kjk** [comment] 2019-11-21 21:54
The first file `Vallalati_Kartyabirtokosi_Keretszerzodes_es_Igenylolap.pdf` has form so it'll be addressed if we ever implement form support as described in #1249 

Second file `zia_xl_6s_g_i.pdf` seems to be fixed in latest build https://www.sumatrapdfreader.org/dailybuilds.html

**Closed by kjk** 2019-11-21 21:54 UTC
