### ISSUE TITLE
Tried Zooming in on an image

### ISSUE THREAD

**Issue by danielzimmer-github** [sumatrapdfreader/sumatrapdf#1950] opened 2021-05-19 18:41 UTC
Tried zooming in on an image and suddenly thin red and blue lines started showing up around pixels then it crashed.
https://gist.github.com/danielzimmer-github/accb156c72d1305db3888992c2eed90b

**Comment by kjk** [comment] 2021-05-19 19:35
```
Ver: 3.2 64-bit

Crashed thread:
00007FFEF1B4D5EC 01:000000000004C5EC libmupdf.dll!template_affine_N_near_fa0+0x11c C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\draw-affine.c+634
00007FFEF1B579B1 01:00000000000569B1 libmupdf.dll!fz_paint_image_imp+0x1011 C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\draw-affine.c+4081
00007FFEF1B699DF 01:00000000000689DF libmupdf.dll!fz_draw_fill_image+0xa8f C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\draw-device.c+1803
00007FFEF1B24B37 01:0000000000023B37 libmupdf.dll!fz_fill_image+0x97 C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\device.c+337
00007FFEF1B43B5E 01:0000000000042B5E libmupdf.dll!fz_run_display_list+0xdee C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\list-device.c+1800
00007FF7BFFD8149 01:0000000000187149 sumatrapdf.exe!EnginePdf::RenderPage+0x439 C:\Users\kjk\src\sumatrapdf\src\EnginePdf.cpp+1191
00007FF7BFF45ABC 01:00000000000F4ABC sumatrapdf.exe!RenderCache::RenderCacheThread+0x28c C:\Users\kjk\src\sumatrapdf\src\RenderCache.cpp+634
```

Unfortunately this is a crash in mupdf that I've been unable to track down.

It might be fixed in latest daily builds: https://www.sumatrapdfreader.org/dailybuilds

If it still happens in daily builds, please re-open and provide instructions on how to reproduce it.

**Closed by kjk** 2021-05-19 19:35 UTC

**Comment by GitHubRulesOK** [comment] 2021-05-19 20:12
@kjk 
to an uneducated eye the description  and crash sequence is fairly similar to https://github.com/sumatrapdfreader/sumatrapdf/issues/1514#

**Comment by kjk** [comment] 2021-05-19 21:40
You're right, it's a dup of #1514 

I just try to reproduce it again by zooming around arrowhead in step 7 and it didn't crash for me.

Not saying it's fixed, just that I couldn't reproduce it.
