### ISSUE TITLE
Wrong interpretation of print permissions

### ISSUE THREAD

**Issue by MarkoD** [sumatrapdfreader/sumatrapdf#1192] opened 2019-08-23 08:53 UTC
I'm using the latest stable release (v3.1.2) and when opening a password-protected file saved from Microsoft Word 2019, SumatraPDF reads the Print permission as "Not allowed", whereas Adobe Reader shows "Allowed" and can print without problems:

![adobe](https://user-images.githubusercontent.com/904050/63578578-108b3880-c591-11e9-9c86-1da739b647bf.png)

The issue is also discussed [here](https://forum.sumatrapdfreader.org/t/cant-print-password-protected-files/1068), however there's only Foxit Reader mentioned and noone there tried Adobe Reader and its permission view.

PS: I can't attach the PDF since it contains personal information. If you need a sample PDF, I can try to strip out the personal data and send it.

**Comment by SumatraPeter** [comment] 2019-08-23 23:07
![image](https://user-images.githubusercontent.com/15380332/63628031-f8b2c380-c627-11e9-8be2-b83af32f503b.png) ![image](https://user-images.githubusercontent.com/15380332/63628065-2566db00-c628-11e9-9e6d-20f3b8c0bccc.png)

Cannot reproduce issue with latest Word 365, so might be a bug in Word 2019. I assume you aren't doing anything very different from what the screenshots above display, but in case you are then do provide exact steps to reproduce the bug and I'll check again at my end.

**Comment by MarkoD** [comment] 2019-08-23 23:14
@SumatraPeter I'll try to reproduce, however the file was created by a 3rd party. I can send you an example PDF via e-mail (cannot post it here).

**Comment by SumatraPeter** [comment] 2019-08-24 22:45
Do test it first with the [latest pre-release version](https://www.sumatrapdfreader.org/prerelease.html) as well.

**Comment by MarkoD** [comment] 2019-08-25 12:33
Tried it, same result. I've shared a sample PDF with you: https://github.com/MarkoD/sumatrapdf

**Comment by SumatraPeter** [comment] 2019-08-26 00:20
Thanks, but I'll defer to the [dev](https://github.com/orgs/sumatrapdfreader/people) to do the actual investigation into the PDF's internals.

**Comment by GitHubRulesOK** [comment] 2019-11-22 11:58
@kjk the forum discussion concluded that SumatraPDF appeared to be honouring flags indicating print restrictions even if the flag was ignored in some PDF editors and not clearly set in MSword. Again without a recent sample to retest, I suggest this issue can be closed as "insufficient info to confirm in current builds"

**Comment by SumatraPeter** [comment] 2019-11-22 22:30
@MarkoD: Can you test the PDF with the latest [daily build](https://www.sumatrapdfreader.org/dailybuilds.html)?

**Comment by MarkoD** [comment] 2019-12-05 08:49
@SumatraPeter I've tested it with the latest daily build (SumatraPDF-prerelease-11520-64), however the problem still persists.

**Comment by MarkoD** [comment] 2019-12-05 08:51
@GitHubRulesOK @kjk Here's the test file (password is "Simimain18"):
[test.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/3925842/test.pdf)

**Comment by GitHubRulesOK** [comment] 2019-12-05 13:05
Interestingly I ask Acrobat to give its interpretation of its security settings and I get conflicting reports since it appears acrobat itself overrides the document settings when the password is given

HOWEVER as SumatraPDF is honoring the document security settings then it cannot copy or print

![image](https://user-images.githubusercontent.com/12754913/70237065-31e9ec00-175e-11ea-82a4-9044f7a88329.png)

**Comment by kjk** [comment] 2019-12-05 18:07
Looks like mupdf bug, I've opened https://bugs.ghostscript.com/show_bug.cgi?id=701974

If they fix it, we'll inherit the fix.

**Comment by kjk** [comment] 2019-12-06 00:34
Pdfiums' FPDF_GetDocPermissions() returns 0xfffffffc, which is different than 0xfffff2c2 (-3390) returned by mupdf.

**Closed** 2020-07-06 23:56 UTC
Labels: mupdf

**Comment by MarkoD** [comment] 2025-11-29 17:59
> Looks like mupdf bug, I've opened https://bugs.ghostscript.com/show_bug.cgi?id=701974
> 
> If they fix it, we'll inherit the fix.

@kjk Looks like mupdf has finally fixed the bug: https://bugs.ghostscript.com/show_bug.cgi?id=701974
