### ISSUE TITLE
Feature: tab is cool, but single window is limited, tab detach/attach feature or create new window request.

### ISSUE THREAD

**Issue by nobk** [sumatrapdfreader/sumatrapdf#510] opened 2016-05-01 07:33 UTC
Please add tab detach feature to allow one tab can be drag to become a new window, and attach back to parent window, or like firefox tab, all windows are equally tabs can move to each others.

If this feature take time longer, please on main Menu add 'create new window' item (or shortcut Ctrl+N), so we can using the new window open the other tabs, instead of the only single window limit.

**Comment by pdgessler** [comment] 2016-05-01 13:22
See also #485 #413 #345 (all similar requests) and the main issue on this topic, #18

**Comment by kjk** [comment] 2018-09-28 01:41
Closed as duplicate of #18

**Closed by kjk** 2018-09-28 01:41 UTC
