### ISSUE TITLE
A .cbz archive crashes SumatraPDF when opened from Explorer, can't be viewed at all

### ISSUE THREAD

**Issue by 07416** [sumatrapdfreader/sumatrapdf#1199] opened 2019-09-03 16:06 UTC
[issue 1.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/3570384/issue.1.zip) (extract, Github doesn't support the CBZ format)

When opened from Windows Explorer with Sumatra closed, the program crashes. If Sumatra is open, no error message is displayed and the file isn't opened.

**Comment by GitHubRulesOK** [comment] 2019-09-03 18:08
The structure seems "wrong" I can only see the cover when i attempt extraction although there is other data, I suggest asking the author to check the format of their their output
![issue 1](https://user-images.githubusercontent.com/12754913/64197511-2dbbe300-ce7e-11e9-9395-c52176f8dd8a.png)

**Comment by GitHubRulesOK** [comment] 2019-09-03 18:47
@kjk I suggest the file ( when extracted correctly is a malformed (truncated) partial file thus not a SumatraPDF issue I would require a pkzip "fix" to replace the missing header and work as intended

**Comment by kjk** [comment] 2019-09-03 19:15
It does seem to start with 'PK' and I was able to unpack it on Mac, so it's possible zip decompression code in Sumatra needs to be updated.

**Comment by GitHubRulesOK** [comment] 2019-09-03 19:56
@kjk the upload is zip the content should be cbz also zip I do not see a pk header in the unpacked file so it may be a platform issue ?

**Comment by SumatraPeter** [comment] 2019-09-04 00:51
Ok, so let me clear things up  now. 😄

The file is a simple [**TAR** archive](https://en.wikipedia.org/wiki/Tar_(computing)) and _not_ a ZIP, so its extension is obviously wrong and there's nothing the matter with Sumatra.

If you need proof, here's a screenshot from WinRAR:

![TAR_Archive](https://user-images.githubusercontent.com/15380332/64217211-26c2be00-ceda-11e9-8bf9-d933130460dc.png)

As you can see @GitHubRulesOK, it has 12 PNGs inside and no duplicates, so whatever extractor you used probably got confused by the incorrect file extension.

You can also check what any file actually is using the UNIX/Linux [**file** utility](https://en.wikipedia.org/wiki/File_(command)) (Windows binaries are also available on googling), or [**TrID**](http://mark0.net/soft-trid-e.html) on Windows. Also, if the file size is ≤10MB you can upload it to the [online version of **TrID**](http://mark0.net/onlinetrid.html), which will spit out a report like so:

![image](https://user-images.githubusercontent.com/15380332/64217540-6b028e00-cedb-11e9-98cc-dd11dbff9f79.png)

So there you go @kjk, problem solved and you can close this as Not an Issue. 🙂

**Comment by GitHubRulesOK** [comment] 2019-09-04 01:00
@SumatraPeter you beat me to it  I had again downloaded the example and find that when extracted by windows the content is not a cbz file HOWEVER after many many attempts to see what was wrong I stumbled on the fact that it reported as some form of UNIX archive format (as you found out~) and I was able to extract all the contents as the 12 named images 
By simply right click compress I was able to store as the attached zip file which if you rename to .cbz should work perfectly
[issue 1.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/3572231/issue.1.zip)

**Closed** 2019-09-05 05:45 UTC
