### ISSUE TITLE
[Feature Request] Higher resolution for toolbar buttons

### ISSUE THREAD

**Issue by 63tjpm7z** [sumatrapdfreader/sumatrapdf#753] opened 2017-03-18 13:29 UTC
![01](https://cloud.githubusercontent.com/assets/3512954/24072225/7b45cbf6-0bec-11e7-8c3c-f3b8cb688938.jpg)

I have setting up 150% scaling in Windows10
and SumatraPDF toolbar buttons pixelated

**Comment by bananakid** [comment] 2017-03-28 18:20
I double that. Toolbar looks very outdated & fuzzy on any modern computer display (I'm using 200% scaling in Windows 10 with 15-inch 4K screen). Please update!

**Comment by SumatraPeter** [comment] 2017-04-09 08:49
Related / duplicate of: https://github.com/sumatrapdfreader/sumatrapdf/issues/430

Also, looks like it's being worked on: https://github.com/sumatrapdfreader/sumatrapdf/issues/734

**Comment by kjk** [comment] 2017-06-09 19:16
Closing as duplicate of #734

**Closed by kjk** 2017-06-09 19:16 UTC
