### ISSUE TITLE
MSI instead of EXE

### ISSUE THREAD

**Issue by MaxG-Enpal** [sumatrapdfreader/sumatrapdf#2278] opened 2022-01-06 12:09 UTC
Hey, could you please provide an MSI file for installation instead of an EXE.
This would make everything much easier.

I would like to use it in our company, but we cannot deploy exe files.

**Comment by GitHubRulesOK** [comment] 2022-01-06 13:49
@kjk presuming nothing has changed so closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1099

**Closed by GitHubRulesOK** 2022-01-06 13:49 UTC

**Comment by GitHubRulesOK** [comment] 2022-01-06 13:51
@MaxG-Enpal you only need to deploy the single portable .exe no need for any wrapper but you can wrap that using many exe to msi tools
