### ISSUE TITLE
[regression] wrong/unexpected settings file location

### ISSUE THREAD

**Issue by MayanKoyote** [sumatrapdfreader/sumatrapdf#1504] opened 2020-03-19 14:31 UTC
Release 3.2 store SumatraPDF-settings.txt in %LOCALAPPDATA%\SumatraPDF\ instead of %APPDATA%\SumatraPDF\
This break inheritance of settings (including history, etc) from previous installed version and expected work in the environment of roaming profiles.

**Comment by GitHubRulesOK** [comment] 2020-03-19 14:37
Duplicate of #1502

**Closed by GitHubRulesOK** 2020-03-19 14:37 UTC
