### ISSUE TITLE
Smooth touchpad experience.

### ISSUE THREAD

**Issue by zycsss** [sumatrapdfreader/sumatrapdf#2149] opened 2021-08-29 12:41 UTC
I know it might be a nightmare for the developer. But is there a possibility to make the zooming and rolling experience on a touchpad as smooth as what one can get with a Chrome or Chromium Edge on a laptop supports precision touchpad?
Thanks a lot.

**Comment by GitHubRulesOK** [comment] 2021-08-29 13:22
with current version for me, touchpad zoom is smoother than chrome (edge) 
I avoid scroll in edge as its too course jumping top to bottom in a second,
In SumatraPDF I use thumb on pad right and finger on pad it perfectly smooth for smooth precision panning

Closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/606

**Closed by GitHubRulesOK** 2021-08-29 13:22 UTC
