### ISSUE TITLE
When I enable the dark theme, the title bar remains white, and the icons appear pixelated.

### ISSUE THREAD

**Issue by farag00672** [sumatrapdfreader/sumatrapdf#4580] opened 2024-10-11 21:32 UTC
![image](https://github.com/user-attachments/assets/34e4bf8f-011e-4a7e-b834-68886061dee5)

**Comment by GitHubRulesOK** [comment] 2024-10-12 00:04
duplicate of several lets see 
discussion https://github.com/sumatrapdfreader/sumatrapdf/discussions/4579
related https://github.com/sumatrapdfreader/sumatrapdf/issues/4475 https://github.com/sumatrapdfreader/sumatrapdf/issues/4443 https://github.com/sumatrapdfreader/sumatrapdf/issues/4299 
closed again in https://github.com/sumatrapdfreader/sumatrapdf/issues/4390
https://github.com/sumatrapdfreader/sumatrapdf/issues/4328
https://github.com/sumatrapdfreader/sumatrapdf/issues/4213 
closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/3794 and https://github.com/sumatrapdfreader/sumatrapdf/issues/3793 and https://github.com/sumatrapdfreader/sumatrapdf/issues/3802

**Closed by GitHubRulesOK** 2024-10-12 00:04 UTC
