### ISSUE TITLE
UAF at SumatraPDF!pdf_load_xref

### ISSUE THREAD

**Issue by expend20** [sumatrapdfreader/sumatrapdf#1430] opened 2020-01-25 00:19 UTC
tag: 3.1.2rel

![](https://i.imgur.com/9GP9Tco.png)

UAF inside of `pdf_load_xref()`. Memory pointed by local variable `entry` is free'd inside of `ensure_solid_xref()` which is called from `pdf_get_xref_entry()`, but it's still used when throwing exception. Crash happens on dereferencing `entry->ofs` with page heap enabled.

![](https://i.imgur.com/TcsKvxc.png)

[id_000000_00.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4111423/id_000000_00.pdf)

**Comment by kjk** [comment] 2020-01-25 01:35
I couldn't reproduce this in master. There's been a lot of changes. Could you see if it still reproduces for you with code in the master branch?

**Comment by expend20** [comment] 2020-01-25 11:06
Hi @kjk!

I actually couldn't build master (commit 6b30d5477e411fceaf768d845e70bb03e522db12) because of following errors:

```
2>C:\Program Files\Windows Kits\10\Include\10.0.17763.0\ucrt\corecrt_math.h(702): error C2169: '_hypotf': intrinsic function, cannot be defined (compiling source file ..\mupdf\source\fitz\color-fast.c)
2>colorspace.c
2>C:\Program Files\Windows Kits\10\Include\10.0.17763.0\ucrt\corecrt_math.h(702): error C2169: '_hypotf': intrinsic function, cannot be defined (compiling source file ..\mupdf\source\fitz\color-lcms.c)
2>draw-affine.c
2>C:\Program Files\Windows Kits\10\Include\10.0.17763.0\ucrt\corecrt_math.h(702): error C2169: '_hypotf': intrinsic function, cannot be defined (compiling source file ..\mupdf\source\fitz\colorspace.c)
2>C:\Program Files\Windows Kits\10\Include\10.0.17763.0\ucrt\corecrt_math.h(702): error C2169: '_hypotf': intrinsic function, cannot be defined (compiling source file ..\mupdf\source\fitz\draw-affine.c)
2>draw-blend.c
```

How I can avoid them? Or please tell me which revision you tried.

**Comment by kjk** [comment] 2020-01-25 19:19
@expend20 I imagine this is because 17763 is an older Windows SDK.

Please re-run Visual Studio installer and make sure to install the latest Windows SDK (it should be version larger than 18000).

**Comment by expend20** [comment] 2020-01-26 12:11
@kjk thanks. I've tested it and it's not reproducible to me on master too. I wonder why 3.1.2rel is still the latest release which is available for [download](https://www.sumatrapdfreader.org/download-free-pdf-viewer.html)?

**Comment by kjk** [comment] 2020-01-26 12:43
This was fixed only recently. Releases take time.

**Closed by kjk** 2020-01-26 12:43 UTC
