### ISSUE TITLE
file:// links don't work

### ISSUE THREAD

**Issue by abma** [sumatrapdfreader/sumatrapdf#763] opened 2017-03-23 16:27 UTC
when clicking on file:// links nothing happens, sumatrapdf seems to ignore it.

see attachment as example:
[test.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/865432/test.pdf)

http:// links work as excepted...

**Comment by SumatraPeter** [comment] 2017-04-07 17:40
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/618

**Comment by kjk** [comment] 2017-04-07 20:02
See #618 for explanation.

**Closed by kjk** 2017-04-07 20:02 UTC
