### ISSUE TITLE
Crashed while checking PDFs no longer on disk and zooming.

### ISSUE THREAD

**Issue by eduardosalaz** [sumatrapdfreader/sumatrapdf#1953] opened 2021-05-21 16:16 UTC
I have been using SumatraPDF for the last 6 years and never in my life had it crashed before.

I opened SumatraPDF and there were some files that I deleted, of course they were just blank pages and I closed them. When I moved to a different file and started zooming it crashed.

https://gist.github.com/eduardosalaz/855ecf4470b8e50eec06298cf18bd2d2

**Comment by kjk** [comment] 2021-05-21 19:07
```
Crashed thread:
00007FF94A48CA83 01:000000000004BA83 libmupdf.dll!template_affine_N_lerp+0x293 C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\draw-affine.c+493
00007FF94A4979B1 01:00000000000569B1 libmupdf.dll!fz_paint_image_imp+0x1011 C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\draw-affine.c+4081
00007FF94A4A99DF 01:00000000000689DF libmupdf.dll!fz_draw_fill_image+0xa8f C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\draw-device.c+1803
00007FF94A464B37 01:0000000000023B37 libmupdf.dll!fz_fill_image+0x97 C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\device.c+337
00007FF94A483B5E 01:0000000000042B5E libmupdf.dll!fz_run_display_list+0xdee C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\list-device.c+1800
00007FF6F7D88149 01:0000000000187149 sumatrapdf.exe!EnginePdf::RenderPage+0x439 C:\Users\kjk\src\sumatrapdf\src\EnginePdf.cpp+1191
00007FF6F7CF5ABC 01:00000000000F4ABC sumatrapdf.exe!RenderCache::RenderCacheThread+0x28c C:\Users\kjk\src\sumatrapdf\src\RenderCache.cpp+634
```

This looks like a duplicate of #1514 and is most likely fixed in latest daily build https://www.sumatrapdfreader.org/dailybuilds

**Comment by GitHubRulesOK** [comment] 2021-05-21 19:10
I don't think the crash it was related to the file handling, but  you do seem to have a fair number of old Internet entries, some of which you may have desired to open again at last historic position as/when downloaded again. If you have some downloaded files that are more frequently visited  than others, have you considered adding those pages to "Favorites" 

Back to your "crash"
@kjk to me it also looked more like 
https://github.com/sumatrapdfreader/sumatrapdf/issues/1874#
so are the two in effect a duplicate cause.

**Closed** 2021-05-25 05:07 UTC
