### ISSUE TITLE
inorder to search for persian text you should type it backwards.

### ISSUE THREAD

**Issue by fakher-alavi** [sumatrapdfreader/sumatrapdf#4732] opened 2024-12-21 20:48 UTC
**SumatraPDF version**
- Version  3.5.2

**Describe the bug**
when I want to search for a specific persian word in a persian document I should type it backwards in the search bar.

**Comment by H5820121** [comment] 2024-12-21 21:34
This issue was solved in pre-release 3.6.

‫בתאריך שבת, 21 בדצמ׳ 2024 ב-22:49 מאת ‪fakher‬‏ ***@***.***
‬‏>:‬

**Comment by GitHubRulesOK** [comment] 2024-12-21 23:08
@fakher-alavi different versions may have different abilities since AFAK it was good enough in XP ? 
but agree with @H5820121 ONLY pre-release could now be altered if necessary

**Comment by GitHubRulesOK** [comment] 2024-12-21 23:13
Different documents can exhibit odd search patters but generally the find functions well in latest pre-release
Closing as duplicate of most recently closed https://github.com/sumatrapdfreader/sumatrapdf/issues/2655

**Closed by GitHubRulesOK** 2024-12-21 23:13 UTC
