### ISSUE TITLE
v3.5 unexpected behaviour of Remember opened file options

### ISSUE THREAD

**Issue by nikitascattolin** [sumatrapdfreader/sumatrapdf#3800] opened 2023-10-25 07:41 UTC
With the version 3.5 enabling the option 'Remember opened file' the application reopen the last viewed file eve if not required:

- Open file1 (file1 is opened)
- Close file1
- Open file2 (file2 is opened AND file1 is opened)

Opening file2 the file1 shouldn't be opened.

Disabling the option 'Remember opened file' option the application behaves as expected.

Verified on Windows 10 operating system.

**Comment by kjk** [comment] 2023-10-25 09:47
There are many ways to open a file. How are you opening the files?
Also, I'm assuming you're closing the app in between? 
Please provide more detailed steps to reproduce.
Also, check you're not mixing admin / non-admin SumatraPDF process and that you're not somehow launching two or more SumatraPDF processes.

**Comment by raminsadre** [comment] 2023-10-25 13:41
> that you're not somehow launching two or more SumatraPDF processes

Could you elaborate on that? Because I have a similar issue to OP:

1. Option "Remember opened file" enabled.
2. No SumatraPDF process running (according to task manager)
3. I double click file A in Windows file explorer. The SumatraPDF window with file A opens. One process running.
4. I do not close A.
5. I double click file B in Windows file explorer. Two new SumatraPDF windows open showing file A and file B, i.e., there are now two SumatraPDF windows open (two showing file A and one showing file B). Two processes running now.

It seems the second process wants to restore A and show B and doesn't care that there is already a process showing A. Is that the intended behavior?

**Comment by nikitascattolin** [comment] 2023-10-25 15:26
> There are many ways to open a file. How are you opening the files? Also, I'm assuming you're closing the app in between? Please provide more detailed steps to reproduce...

On windows 10 logged with a domain user belonging to the Administrator group.
- Installed Sumatra PDF 3.5.2 using SumatraPDF-3.5.2-64-install.exe.
- Sumatra is the default PDF reader for the OS.
- No sumatra process is running.

Using double clicking on explorer or be means of context menu command 'Open with->SumatraPDF':

1. Open file1 (file1 is opened, 1 Sumatra process is running for the logged user)
2. Close file1 (Sumatra process is closed)

the sequence 1. 2. can be repeated with the same results.

3.  Open file2 (file2 is opened AND file1 is opened, 1 Sumatra process is running for the logged user)

4. Close file1 (1 Sumatra process is running for the logged user)

5. Close file2 (Sumatra process is closed)

Steps 3-5 can be repeated with the same results.

6.  Open file3 (file3 is opened AND file2, the last closed in the previous test, is opened, 1 Sumatra process is running for the logged user)

If with no sumatra process running the last closed file is opened only 1 instance of the PDF is opened and displayed (as expected).

**Comment by kjk** [comment] 2023-10-25 22:12
@raminsadre Is one of those processes an admin process? Are they the same executable? (you can check both in task manager).

When a new Sumatra process starts and it sees already running Sumatra process it doesn't open the file but sends it via DDE to existing process and exit.

It won't happen if already running process is admin and and the new process is non-admin due to Windows security rules. People sometimes start Sumatra as admin because it's executed from an admin process (explorer running as admin or from Everything app that runs as admin).

The other case is if those are 2 different Sumatra executables.

**Comment by raminsadre** [comment] 2023-10-26 06:59
@kjk I just checked in Taskmanager. Both processes are coming from C:\Program Files\SumatraPDF\SumatraPDF.exe and both are running under my user account. My account is a local admin account. I am using Windows 10, SumatraPDF v3.5 64-bit.

**Comment by kjk** [comment] 2023-10-26 11:26
@raminsadre did you disable tabs?

Looking at the code if tabs are disabled and `ReuseInstance` advanced setting is `false` (which is the default) this will happen.

I (and most people) never run into that because tabs are default.

So in the short term if you set advanced setting `ReuseIntance = true` it should fix it for you.

I should also fix it somehow but not sure how.

Changing `ReuseInstance` to true would be backwards-incompatible and could break people expecting current behavior.

Maybe I should disable restoring session if the executable is the same but that will cause issues later anyway because 2 processes will be over-writing each  other's session.

**Comment by raminsadre** [comment] 2023-10-27 07:38
@kjk  Right, I don't use tabs. Thank you for having followed up on the problem.

**Comment by GitHubRulesOK** [comment] 2023-11-02 02:29
For pre-release 3.6.15850+ 
default ReuseInstance has been changed to true (should help many users including LaTeX users)

**Comment by kjk** [comment] 2023-11-02 20:53
Should be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/26cbe5c1376310391dc169028e363c1636820f6f and available in next pre-release

**Closed by kjk** 2023-11-02 20:53 UTC

**Comment by mplattner** [comment] 2023-11-15 14:18
I had the same issue after the last update. In addition to setting `ReuseInstance = true`, I needed to set `RememberOpenedFiles = false`. Thanks @kjk, Sumatrapdf is fantastic! 🙏

**Comment by robertf** [comment] 2023-12-16 16:27
For whatever reason, in version 3.5.2 with tabs not being used, I did not have to also change `RememberOpenedFiles` to `false` in order to avoid opening additional instances of already opened files. I just changed `ReuseInstance` to `true`.
