### ISSUE TITLE
Proper Touch Support

### ISSUE THREAD

**Issue by fefrei** [sumatrapdfreader/sumatrapdf#64] opened 2015-01-07 12:15 UTC
I'd love to see proper touch support in SumatraPDF. The two core things that are missing:
1. Panning while zooming with two fingers (which sounds unnecessary, but not having it feels really awkward).
2. Disabling page flipping while panning horizontally with one finger

I cannot help developing it directly, but am willing to test versions on my hardware. I can try tormenting SumatraPDF with up to 10 touch points or a pen.

**Comment by KrasnayaPloshchad** [comment] 2015-02-05 07:14
Windows 8+ have so many fixes for touch support, IE 10/11 zooming with two fingers very well on touch screen.

**Comment by KrasnayaPloshchad** [comment] 2015-10-31 10:10
Windows 10 also provide operations for touch screen.

**Comment by KrasnayaPloshchad** [comment] 2015-11-14 04:15
The zooming and rotating operation by two fingers performenced proper in Sumatra 3.1.1, tested on Windows 10.

**Comment by fefrei** [comment] 2015-11-14 12:09
I no longer accidentally flip pages while panning horizontally, but zooming still focuses around the top left corner, not the point between the fingers. I'm running Windows 10, too.

**Comment by KrasnayaPloshchad** [comment] 2015-11-14 12:20
> I no longer accidentally flip pages while panning horizontally, but zooming still focuses around the top left corner, not the point between the fingers. I'm running Windows 10, too

 OK, I reproduced this small problem after you pointed out.

**Comment by vvRFvv** [comment] 2016-09-01 21:35
The touch-support is already very good but the pinch-to-zoom gesture always has the center of zoom at the top-left. It would be nice if it was between the fingers as it is usually implemented.
Otherwise thank you for your great pdf-reader!

**Comment by GitHubRulesOK** [comment] 2019-12-15 20:49
@kjk the inital issues has generally dissapeared except for the pinch zoom issue which is a duplicate of #481

**Comment by GitHubRulesOK** [comment] 2020-07-05 18:52
Closing as the residual issue is that zero datum for zoom is the top left datum thus a duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/481

**Closed** 2020-07-05 18:53 UTC
