### ISSUE TITLE
Suggestion - unlimited numbers of thumbs in main pane?

### ISSUE THREAD

**Issue by pipecleaner** [sumatrapdfreader/sumatrapdf#609] opened 2016-09-06 23:31 UTC
I own 233 ebooks. At the moment there is on the main pane 10 slots for thumbs of the 10 most recently opened ebooks. I will suggest a feature making it possible to scroll thumbnail images of my whole collection. Portable SumatraPDF plus ebooks installed on a USB stick could then make a library fit into a pocket. Very impressed of this fine and stable viewer btw.

**Comment by GitHubRulesOK** [comment] 2020-02-07 03:37
Am counting as duplicate of Feature request: Ability to display 'Home' screen with frequently read/pinned files #406

**Closed by GitHubRulesOK** 2020-02-07 03:37 UTC
