### ISSUE TITLE
Crashing when opening document with synctex

### ISSUE THREAD

**Issue by HenrikStef** [sumatrapdfreader/sumatrapdf#2262] opened 2021-12-07 11:06 UTC
SumatraPDF sometimes crashes when trying to open a document from TeXnicCenter, with the following viewer arguments:

Executable path: "c:\Program Files\SumatraPDF\SumatraPDF.exe" -inverse-search "\"C:\Program Files\TeXnicCenter\TeXnicCenter.exe\" /ddecmd \"[goto('%f','%l')]\""
Open DDE command: [DocOpen("%bm.pdf")][FileOpen("%bm.pdf")]
Forward search DDE command: [ForwardSearch("%bm.pdf","%Wc",%l,0,0,1)]

I tried compiling a debug version. The error seems to be happening in something to do with synctex.
The document created with --synctex=1. 

[sumatrapdfcrash.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/7667705/sumatrapdfcrash.txt)

**Comment by GitHubRulesOK** [comment] 2021-12-07 12:17
I always recommend removing the -inverse search part of command after it has been set the first time as it introduces unnecessary delays. ONCE it has been included in SumatrPDF settings it should stick for all future calls so this part
`-inverse-search ""C:\Program Files\TeXnicCenter\TeXnicCenter.exe" /ddecmd "[goto('%f','%l')]""`
is surplus to requirements as it should now be in advanced settings
note you shoulde be able to add /nosplash before /ddecmd like so  `.exe"  /nosplash /ddecmd "go`

so looking at the remainder we see
```
"c:\Program Files\SumatraPDF\SumatraPDF.exe" Open DDE command: [DocOpen("%bm.pdf")][FileOpen("%bm.pdf")]

Forward search DDE command: [ForwardSearch("%bm.pdf","%Wc",%l,0,0,1)]
```

Without a working copy I cant test both those but the last ending is unfamiliar (not necessarily wrong) but in the past  I used `[ForwardSearch("%bm.pdf","%Wc",%l,0)]`

So we are left with how the SumatraPDF exe should be called and calling twice as both `DocOpen` AND `FileOpen` seems odd since once opened it only needs to be recalled once. 

In SumatraPDF settings ReuseInstance should be `true` (with tabs switched on)

perhaps read https://github.com/GitHubRulesOK/MyNotes/raw/master/AppNotes/SumatraPDF/SumatraPDF%20with%20TeXnicCenter.pdf however it seems those notes do not say how the doc open or file open should be constructed internally by TeXnicCenter (an omission to spot that in my previous checks) however I don't think both would be needed, just one.

**Comment by HenrikStef** [comment] 2021-12-09 10:45
Thanks for looking into this!
Following the guide in your link seemed to fix it. Much appreciated!
I noticed the guide mentions a 32 MB limit on file locking. I'm getting very close to that. Could that have an impact as well?

Before following the guide, I tried fixing the DDE commands by removing the FileOpen command and changed ForwardSearch as you suggested, but it still crashed.

**Comment by GitHubRulesOK** [comment] 2021-12-09 12:34
Most likely culprit for chrash would be a badly run compile thus bad synctex index usually you can check the compile log file for happy ending.
the 32bit limit was increased after my more extensive LaTex tests but don't remember the old 10mb limit being the cause of crashes then (version 3.1.2 & briefly 3.2), just needing close and open newly compiled file.

**Comment by kjk** [comment] 2022-05-31 23:39
From the callstack it looked like memory corruption in synctex code.

I've updated synctex to 1.21 and either way I would need a way to reproduce this locally.

**Comment by GitHubRulesOK** [comment] 2022-06-01 01:21
@kjk 
I am wondering about this (now you raise it) and the other odd GZ behavior's, (perhaps not related)

Here the crash was during an attempt to set inverse search since It does not seem to have been included in the settings body but `EnableTeXEnhancements = true` thus had been previously triggered !

Sadly there are may web recipes that use `-inverse-search` EVERY time SumatraPDF is called, but its a potential recipe for corruptions, hence advise against constant calling (only needed once if not manually added by a portable batch file)

**Comment by GitHubRulesOK** [comment] 2023-03-30 02:58
@kjk I think that this was a misconfiguration issue inducing bad call, which you closed out recently ?

**Comment by kjk** [comment] 2023-03-30 05:17
Yes, looks like the same issue as #3381, fixed in https://github.com/sumatrapdfreader/sumatrapdf/commit/2930c7b9fe9d8c88a8ec880e6b5110f096e67fa9

Except it was my own code that was crashing and not synctext 👀

**Closed by kjk** 2023-03-30 05:17 UTC
