### ISSUE TITLE
Feature request: undo close tab

### ISSUE THREAD

**Issue by jddcef** [sumatrapdfreader/sumatrapdf#1020] opened 2018-05-13 22:26 UTC
If I have many PDF's open I would like to undo a tab closed by mistake.. especially when it doesn't appear in the Recent files list...

Or just add the recently closed tab to the File menu list of recent files...

**Comment by benryanau** [comment] 2018-06-14 12:02
History and bookmark/fav management work would be a great improvement!

**Comment by GitHubRulesOK** [comment] 2019-11-22 12:16
@jkj duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/788

**Comment by kjk** [comment] 2019-11-23 00:24
Consolidate as #788

**Closed by kjk** 2019-11-23 00:24 UTC
