### ISSUE TITLE
Support zoom for epub file

### ISSUE THREAD

**Issue by zydxhs** [sumatrapdfreader/sumatrapdf#1281] opened 2019-12-01 13:37 UTC
I used sumatrapdf to read the epub file, it's very good.

I want to add zoom to protect my eyesight, can it be implemented in a future release?

**Comment by GitHubRulesOK** [comment] 2019-12-01 18:13
@zydxhs 
you can either change `UseFixedPageUI = true` which alters mode to include search and zoom 
OR change the Font/Size 
EbookUI [
	FontName = Georgia
	FontSize = 15

both accesible via Settings > Advanced Opions

@kjk duplicate of #80

**Comment by zydxhs** [comment] 2019-12-03 13:44
Thanks, it takes effect.
It would be nice to have some common action buttons on the toolbar.

**Comment by GitHubRulesOK** [comment] 2021-08-15 23:53
@kjk 
Again zoom is now available by default for epub (but mobi/axz still uses ebookUI, thus may be less obvious to those users)

**Comment by GitHubRulesOK** [comment] 2021-08-28 13:07
Closing as legacy issue, no longer relevant in pre-release

**Closed by GitHubRulesOK** 2021-08-28 13:07 UTC
Labels: ebook
