### ISSUE TITLE
Allow multiple windows with tabs UI

### ISSUE THREAD

**Issue by fishstik** [sumatrapdfreader/sumatrapdf#62] opened 2015-01-05 18:27 UTC
I'm enjoying the tabs UI but missing the ability to have multiple window instances up at the same time. Currently clicking on Sumatra with a tabs-enabled window already open does nothing. Additonally, dragging tabs "out" to create a new window a la Chrome and Sublime Text would be a welcome feature.

**Comment by kjk** [comment] 2015-01-05 19:34
Duplicate of #18

**Closed by kjk** 2015-01-05 19:34 UTC
Labels: duplicate
