### ISSUE TITLE
Weird first rows problem at each chapter of certain epubs

### ISSUE THREAD

**Issue by Pocokk** [sumatrapdfreader/sumatrapdf#3619] opened 2023-08-20 14:46 UTC
If the chapter starts with `<p class="noindent"><span class="stickup">`, the first two rows collide/mesh together like this on the picture

 
![0CrZt0v](https://github.com/sumatrapdfreader/sumatrapdf/assets/81096046/324e8d8d-18e3-4f89-bdf7-5aacd7c185ca)

Here is an example of epub if you wish to inspect it closer https://we.tl/t-fn7jwY0CRY

Using this (then latest) pre-release version of SumatraPDF for reference (however after I updated to the current pre-release, its still a problem)

![laD7fvo](https://github.com/sumatrapdfreader/sumatrapdf/assets/81096046/13af1868-8409-4674-aa59-ba4739011ba3)

**Comment by Pocokk** [comment] 2023-09-14 13:03
Reuploaded the sample file for closer inspection.

**Comment by Pocokk** [comment] 2023-10-20 21:36
The file was expired, so reuploaded once again + after all these updates, unfortunately the problem still lingers (hoped its related to one of the fixes, but that's not the case).

**Comment by GitHubRulesOK** [comment] 2023-10-20 22:55
[14 Halo B3 First Strike.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/13059077/14.Halo.B3.First.Strike.zip)

There are natural difference between ePub Readers and we can see some of those even in the forward, Current Edge is the one on the right.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/c9ef2b5c-59fe-453f-a099-83d4eeb33b4f)

The issue in this case is the use of DropCapital which disturbs the natual height of the First Line. Traditional eBooks would not start a line then alter the height of the second character in a word.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/5d4cf089-4ca5-4732-ad13-8c055759a936)

**Comment by Pocokk** [comment] 2023-10-20 23:05
So its the fault of the ebook itself and there is nothing to improve on the software side of things?

**Comment by GitHubRulesOK** [comment] 2023-10-20 23:37
I think its a mupdf related problem but @kjk would need to check how much, if any, that SumatraPDF deviates from that method.

**Comment by GitHubRulesOK** [comment] 2023-10-20 23:45
Ahhh is a duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/3438 which has been supposedly reported, but neverknow if Artifex will fix in 1 mimute or one decade (or even two)

**Closed by GitHubRulesOK** 2023-10-20 23:45 UTC
Labels: ebook

**Comment by Pocokk** [comment] 2023-10-21 10:36
Thank you so much. 

I've figured out a temporary nasty solution in the mean time: delete the drop cap (stickup class) .css styles from the css file and then the first rows became readable (albeit loosing that height altering thing)

**Comment by Pocokk** [comment] 2023-10-28 13:39
It seems the issue has been resolved in one of the fixes in the previous couple of days.
