### ISSUE TITLE
v3.4.13894 Git 768e86dd3 - AV and crash if try load .fb2 test file

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#2070] opened 2021-07-28 13:38 UTC
v3.4.13894 Git 768e86dd3 - AV and crash if try load .fb2 test file if I run test script spdftest.cmd (included in 
[**CrashReport.zip**](https://github.com/sumatrapdfreader/sumatrapdf/files/6893462/CrashReport.zip). For test I use (7-Zip split (multi volum) archive SumatraPDF_testkit.7z - https://raw.githubusercontent.com/VictorVG/test/master/SumatraPDF_testkit.7z.7z.001 (part 1) and https://raw.githubusercontent.com/VictorVG/test/master/SumatraPDF_testkit.7z.7z.002 (part 2). Just copy part 1 and part 2 in to some dir and use  command like 7z x SumatraPDF_testkit.7z.7z.001 for extract test kit).

In to crash report I see whats exists untranslated strings. Needed for I translate it or white other translation's?

**Comment by VictorVG** [comment] 2021-07-28 14:05
I re-test all files in to test kit and find whats crash's only for .fb2 and try test use another FB2 file - crash and AV - please, see crash-report (.pdb included) - https://www.upload.ee/files/13348430/crashinfo.zip.html

**Comment by GitHubRulesOK** [comment] 2021-07-28 17:25
@kjk 
I opened two simple Fb2 files without problems but the Third had links and gave me a
CalcDestKind(): unknown uri: '#'1'
crash
I see the same in VictorVG crash-report
I am thus "Guessing it is a Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/2066

**Comment by VictorVG** [comment] 2021-07-28 17:52
I somehow did not pay attention to the possible links in the checked files. :( 

Now I looked at _example.fb2_ - it uses internal hyperlinks like `xlink:href="#note_5"` for their purpose, similar to internal HTML hyperlinks like: 

`<a href="#note_5">note_5</a> ... <a name="note_5"> </a>`.

**Comment by VictorVG** [comment] 2021-07-28 18:03
Yes, I almost forgot - MuPDF, in principle, itself supports the FB2 v3.0 specifications, but although the internal structure of the FB2 file uses XML-like markup, it differs from HTML/CHM files and is very sensitive to the correctness of the file markup and compliance with the FB2 standard in the renderer, and for example STDU Viewer (currently not developing) refuses to play FB2 files at the slightest deviation of their markup from the specifications of the FB2 standard.

**Comment by kjk** [comment] 2021-07-29 02:39
The crash should be fixed now.

**Closed by kjk** 2021-07-29 02:39 UTC

**Comment by VictorVG** [comment] 2021-07-29 04:36
@kjk 

Big thanks! Now I'll put it together and see what happened (to be honest, I was afraid that my .pdb would have to be edited under the path to your source code, and apart from the idea of a hex edit, nothing came to mind).Now I'll put it together and see what happened (to be honest, I was afraid that my .pdb would have to be edited under the path to your source code, and apart from the idea of a hex edit, nothing came to mind).

**Comment by VictorVG** [comment] 2021-07-29 05:11
It turned out great! And the paragraphs (in example.fb2 they are) worked, which we did not see in earlier versions:

**v3.4.13879 Git-9618b2d4d:**

![v3 4 13879 Git-9618b2d4d](https://user-images.githubusercontent.com/906886/127435226-94a88755-cf36-4c96-8341-72e0764a2ade.png)

**v3.4.13918 Git-51f824e43:**

![v3 4 13918 Git-51f824e43](https://user-images.githubusercontent.com/906886/127435330-7ac404e7-46b6-4a08-8d28-a27802ad0891.png)
