### ISSUE TITLE
Some PDF can not display the normal use of special fonts！

### ISSUE THREAD

**Issue by sankeya** [sumatrapdfreader/sumatrapdf#616] opened 2016-09-14 02:28 UTC
The font name's HiraginoSans GB W3.oft (MAC OS).

**Comment by kjk** [comment] 2016-09-14 05:16
In order to fix a bug we need access to PDF file that shows the problem. 
We also need to know the version of Sumatra used and what other PDF program shows the file correctly.

Many PDFs are malformed in that they are missing fonts they are referencing.

**Comment by GitHubRulesOK** [comment] 2020-01-18 23:26
@kjk as far as I can tell this font is supported when embedded
![image](https://user-images.githubusercontent.com/12754913/72671884-84027a80-3a49-11ea-8f60-eb996b60b9a8.png)

**Comment by GitHubRulesOK** [comment] 2020-05-19 13:20
Closing as duplicate of several other cases such as Reader is unable to show cyrillic text in pdf file #378 or `SumatraPDF showing garbled texts in this file` #1585 
Where files may only be viewed easily within a locality or machine that has a specific font available However the PDF is not defined using globally available fonts or the font glyphs have not been named/embedded in a rational way, thus breaking the "Portable"DF standard requirements.

Note most of these examples can be easily fixed in the editor to be made acceptable to all viewers

**Closed by GitHubRulesOK** 2020-05-19 13:20 UTC
