### ISSUE TITLE
Problem with version 3.1.2, version 3.0 OK

### ISSUE THREAD

**Issue by xavbill** [sumatrapdfreader/sumatrapdf#837] opened 2017-06-29 06:55 UTC
Hello,
Here is a problem with version 3.1.2, version 3.0 works fine.
Thanks.
Best regards.
Xavier
[erreur bvr.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/1111101/erreur.bvr.pdf)
[facture.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/1111105/facture.pdf)

**Comment by SumatraPeter** [comment] 2017-07-05 01:10
See https://github.com/sumatrapdfreader/sumatrapdf/issues/329.

**Comment by GitHubRulesOK** [comment] 2020-02-02 00:54
@kjk effectively duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/919

**Comment by kjk** [comment] 2020-02-02 01:13
Consolidate as #919

**Closed by kjk** 2020-02-02 01:13 UTC
