### ISSUE TITLE
When printing, why is it printed in reverse order? 

### ISSUE THREAD

**Issue by wangpai1998** [sumatrapdfreader/sumatrapdf#1827] opened 2020-12-11 13:49 UTC
When printing, why is it printed in reverse order? ?
For example, in general printing, printing starts from page 1 to page 10, but ours starts printing from page 10 to 1. Is there any way to print in order? ?

**Comment by GitHubRulesOK** [comment] 2020-12-11 14:26
its a driver setting
mentioned in another issue, don't have time to check just now see https://github.com/sumatrapdfreader/sumatrapdf/issues/107 and https://github.com/sumatrapdfreader/sumatrapdf/issues/1558
 but its controlled by default printer collate  setting not SumatraPDF

**Comment by GitHubRulesOK** [comment] 2020-12-13 17:40
I am closing since
 in common with collation and other variable print settings this issue
 is caused by **user print driver settings** outside of SumatraPDFs direct control.

**Closed by GitHubRulesOK** 2020-12-13 17:40 UTC
