### ISSUE TITLE
File name in tab does not change on Save As

### ISSUE THREAD

**Issue by wigster** [sumatrapdfreader/sumatrapdf#93] opened 2015-02-11 10:26 UTC
Hi,

SumatraPDF 3.1.10125z on Win 8.1 x64 Pro.

When I open a PDF file and then choose save as and change the name of the file the file name in the tab remains as it was when it was opened, rather than changing to the new filename. This may be the intended behaviour, but it is at odds with other Windows software.

**Comment by motial** [comment] 2015-06-07 10:10
Any plan to change this behavior? Maybe make a setting to select the requested behavior.

**Comment by Chungalin** [comment] 2016-09-18 19:17
I second this too!!

When you Save as... the program should update filename in user interface.

**Comment by Wikiwide** [comment] 2018-05-03 01:47
Not just update the filename, but also close the old-opened-file, and open new-just-saved-file.
PDF reader on my mobile knows to do that. Sumatra PDF on my desktop doesn't know to do that, yet.

**Comment by GitHubRulesOK** [comment] 2018-05-03 22:37
The behaviour may not be the same as expected from editors such as notepad etc,
however when viewing a web page I dont expect that a copy saved to a local  mht format will be automatically opened, in fact for security I  would NOT want that to be the case
SumatraPDF file save was a bonus feature for normalising some but not all formats to pdf (e.g. images or e-pub not txt with embedded links) and its easy to then re-open the output possibly with a different User Interface

@kjk I suggest that this be classed as feature request (may not fix) or closed as expected behavior

**Comment by GitHubRulesOK** [comment] 2019-12-04 00:56
@kjk The OP requested behaviour to rename and reopen the renamed file is the reason for F2 (
Rename). Tested as **working as designed** and as here requested in latest builds. 

The additional confusion here is that some users expect "Save as" to duplicate the F2 action, where as if that was the case we would then get an issue that some users do not want that to be the default.

Save as is the method for changing output / duplicating with annotation, thus in that case the suitable feature request is to open a second tab with the altered file in addition to the original.

**Comment by kjk** [comment] 2024-07-29 11:03
Works as designed. `Saves as` creates a copy of of the file on disk, it doesn't re-load it.

In pre-release you can use `Rename file` command (`Ctrl + K`)

**Closed by kjk** 2024-07-29 11:03 UTC
