### ISSUE TITLE
Show a small tip

### ISSUE THREAD

**Issue by czghzc** [sumatrapdfreader/sumatrapdf#1301] opened 2019-12-06 06:36 UTC
If I open many files at the same time, the tab of the file will be very short. 
If I want to switch to other files, but I don't know which file each tab corresponds to, 
this is very unfriendly. 
      I suggest: 
      When you Show a small tip when I scroll over the tabs, 
let me know what file the current tab is, this will be very convenient.
![pdf](https://user-images.githubusercontent.com/23645596/70300987-0b968000-1834-11ea-9438-82ebbe189fbe.gif)

**Comment by GitHubRulesOK** [comment] 2019-12-06 15:09
@kjk dupe of #1188

**Comment by kjk** [comment] 2019-12-06 19:23
Consolidating under #1188

**Closed by kjk** 2019-12-06 19:23 UTC
