### ISSUE TITLE
When you use tabs, the toolbar disappears

### ISSUE THREAD

**Issue by jg-github** [sumatrapdfreader/sumatrapdf#658] opened 2016-11-13 02:17 UTC
I'm using the latest beta (10551). As mentioned in the title, if I set the program to use tabs, the toolbar disappears. I'd like to be able to use both.

Thank you.

**Comment by GitHubRulesOK** [comment] 2019-11-22 14:16
@kjk duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/549

**Comment by kjk** [comment] 2019-11-23 00:26
consolidate as #549

**Closed by kjk** 2019-11-23 00:26 UTC
