### ISSUE TITLE
Diacritics disappear when copy/pasted into Favourites

### ISSUE THREAD

**Issue by bren102** [sumatrapdfreader/sumatrapdf#577] opened 2016-07-29 12:02 UTC
Can support for diacritics be added so that they remain when text is copy/pasted into Favourites? Noted when copying text containing diacritics from a pdf file. (SumatraPDF v3.1.1, Windows 7 Pro). Great reader!

**Comment by kjk** [comment] 2016-07-29 18:44
Please attach a document that shows this problem and describe where in the document is the text that doesn't get copied correctly.

**Comment by GitHubRulesOK** [comment] 2019-12-30 00:11
@kjk my test sugests that Latin Greek Hebrew etc  Diacritics are retained in the settings.txt
![image](https://user-images.githubusercontent.com/12754913/71564485-d4189d80-2a98-11ea-883b-595012b6c0a9.png)

however it is possible on saving advanced settings in some editors they may be stripped on save,
thus in such cases could disappear ?

I suggest this be closed as working by design unless a specific character fault can be provided

**Closed** 2019-12-30 00:54 UTC
