### ISSUE TITLE
Inconsistent icons in dark mode

### ISSUE THREAD

**Issue by m-martinm** [sumatrapdfreader/sumatrapdf#4054] opened 2024-01-31 16:07 UTC
**SumatraPDF version**
- Version 3.5.2.0

**Describe the bug**
The icons in the toolbar are inconsitent (see screenshots) using the dark or darker theme. The strange thing is that they appear normal on the home tab.
![Screenshot 2024-01-31 165944](https://github.com/sumatrapdfreader/sumatrapdf/assets/61714317/4ba2f57c-f787-488e-b9d7-154c95737c6d)
![Screenshot 2024-01-31 165917](https://github.com/sumatrapdfreader/sumatrapdf/assets/61714317/073d42e7-52cd-4a2c-924a-0e570271a52a)

**To Reproduce**
Set dark theme.

**Expected behavior**
Normal looking icons like in the light theme.
![Screenshot 2024-01-31 170054](https://github.com/sumatrapdfreader/sumatrapdf/assets/61714317/5ba6f835-ca1d-4a01-bd8c-acd6c69028a1)

**Additional context**
OS: Windows 10 Pro 22H2 with Dark system settings.

**Comment by GitHubRulesOK** [comment] 2024-02-01 02:37
they are not all fine on the home tab see the first active black on black, it is simply the greyed out ones are higher contrast.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/5ee6929c-0554-41e0-b87e-634837f850f9)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/1810655a-58c7-4234-8e23-4e1b202f761a)


closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/3794  and https://github.com/sumatrapdfreader/sumatrapdf/issues/3793 and https://github.com/sumatrapdfreader/sumatrapdf/issues/3802

**Closed by GitHubRulesOK** 2024-02-01 02:37 UTC
