### ISSUE TITLE
The annotation icon is to large

### ISSUE THREAD

**Issue by H5820121** [sumatrapdfreader/sumatrapdf#3272] opened 2023-02-12 18:59 UTC
PDF doc. in 'PDF-XChange Editor':
<img width="503" alt="image" src="https://user-images.githubusercontent.com/105562828/218331842-189c3f02-90b4-46f4-aa94-47a53add2a5f.png">

The same PDF doc. when opened in **'SumatraPDF'**:
<img width="513" alt="image" src="https://user-images.githubusercontent.com/105562828/218331793-59f8d5e9-510f-4514-b27a-59932cc34512.png">

The same PDF doc. when opened in 'Adobe Acrobat':
<img width="464" alt="image" src="https://user-images.githubusercontent.com/105562828/218331139-9e1ec698-2d56-419c-ad13-023c9b105c47.png">

The same PDF doc. when opened in 'FoxitPDF':
<img width="460" alt="image" src="https://user-images.githubusercontent.com/105562828/218331235-f40e50cb-f0e2-4f77-93bf-3d6a7e238b9f.png">

Thanks!

**Comment by GitHubRulesOK** [comment] 2023-02-12 20:30
Closing as duplicate of https://bugs.ghostscript.com/show_bug.cgi?id=702544 reported i https://github.com/sumatrapdfreader/sumatrapdf/issues/1600

**Closed by GitHubRulesOK** 2023-02-12 20:30 UTC

**Comment by GitHubRulesOK** [comment] 2023-10-23 03:06
Please  test current Pre-Release as the above linked issue is closed without any samples to prove this is still a problem.
