### ISSUE TITLE
Cannot exit full screen mode using Windows Tablet

### ISSUE THREAD

**Issue by kenkangxgwe** [sumatrapdfreader/sumatrapdf#678] opened 2016-12-04 10:27 UTC
It seems that pressing <code>Esc</code> is the only way to exit full screen mode, but what if I use windows tablet? I can never exit any more once I enter the full screen mode.

**Comment by kantoniak** [comment] 2017-01-15 13:59
You can enter/exit fullscreen tapping once with fingers, two to five works for me (Goclever Insignia 1010 Win).

**Comment by mirh** [comment] 2017-12-16 11:18
Duplicate of #882 imo.

**Comment by kjk** [comment] 2017-12-16 21:11
Closing as duplicate of #882.

**Closed by kjk** 2017-12-16 21:11 UTC
