### ISSUE TITLE
Add auto-save config option when high-light text into .smx

### ISSUE THREAD

**Issue by Mark-Joy** [sumatrapdfreader/sumatrapdf#1096] opened 2018-11-14 06:17 UTC
I am using the sumatra_highlight_helper.ahk to assist the highlighting process. Every time text is high-lighted it opens and (auto) closes the save dialog box. It would be very help full if you add the option to auto-save to .smx so that the .ahk script doesn't have to open the save dialog box.

**Comment by GitHubRulesOK** [comment] 2018-11-14 09:34
Whilst sumatra_highlight_helper.ahk is very useful, it not a supported feature (similarly highlighting and .smx are not a release feature) The methods that Nod5 uses are by necessity down to his code or the way AHK interacts with other files. I do understand his need to save on the fly. However That feature works as designed and is unlikely to be changed, unless there is another reason or author to modify that code. 
@kjk I suggest code is working as currently intended thus not an issue.

**Comment by GitHubRulesOK** [comment] 2020-01-06 02:04
@kjk I have reviewed Nod5 code and got it generally working in Latest SumatraPDF (with a few minor wrinkles accepted)
Out of necessity his script autosaves each change. It would not be a good idea to change SumatraPDF behaviour to auto save and since you have recently made it easier for scripts to use the new option to **"Save Annotations"** on demand what would potentially allow such scripts to avoid the save as command is a Hotkey / shortcut such as **"Save &Annotations" = CTRL H** and so close this issue

**Comment by GitHubRulesOK** [comment] 2020-02-17 22:36
This Issue is addressed in pre-release using right click Save Annotations
and by Nod5 producing a renewed application SumatraPDF HighlightJump

**Closed by GitHubRulesOK** 2020-02-17 22:36 UTC
