### ISSUE TITLE
Inconvenient to edit existing annotations 

### ISSUE THREAD

**Issue by shui-dun** [sumatrapdfreader/sumatrapdf#1992] opened 2021-06-19 02:33 UTC
I use prerel-13418-64 version and I find that it's inconvenient to edit existing annotations.
Specifically, when I select a piece of text that contains annotations, right click and choose "edit annotation", the software does open the annotation window, but it do not locate the specified annotation, I need to find the annotation I want in a large number of annotations.

**Comment by kjk** [comment] 2021-06-19 02:38
Yes, there should be an easy way to select an annotation for editing e.g. click with mouse and have it selected in the annotation editor list.

**Comment by GitHubRulesOK** [comment] 2021-06-19 11:36
@jkj
I am not sure but this sounds like duplicate of selecting focused annotation in edit window should "GO TO" on the page

**Closed** 2021-06-19 20:03 UTC

**Comment by kjk** [comment] 2021-06-19 20:07
This isn't the most obvious solution, but in latest daily build, if you use `Edit Annotations` context menu and mouse cursor is over annotation, the annotation will be selected.

Maybe should also add explicit `Select Annotation in Editor` context-menu item?

**Comment by kjk** [comment] 2021-06-19 23:59
I've added `Select Annotation in Editor` to the context menu (if cursor is over an annotation)
