### ISSUE TITLE
Allow a mix of tabs and windows

### ISSUE THREAD

**Issue by tactidact** [sumatrapdfreader/sumatrapdf#530] opened 2016-05-21 21:05 UTC
Like how with any browser like Firefox or Chrome, tabs can be dragged away from the window to have them spawn as a separate window. For my particular use case I would like to have multiple SumatraPDF windows open on different workspaces, with tabs for my work pdfs open in my "work" workspace and my play(game guides/flowcharts) pdfs on my "play" workspace.

Sumatra currently only allows either tabs in a single window instance OR multiple windows, one for every file.

**Comment by SumatraPeter** [comment] 2016-10-06 17:31
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/18

**Closed** 2016-10-06 18:19 UTC
