### ISSUE TITLE
HOME page open default

### ISSUE THREAD

**Issue by imyu37** [sumatrapdfreader/sumatrapdf#3896] opened 2023-11-20 06:57 UTC
When i open a file with double-click,the blank HOME page open simultaneously at the same time.
How to disable it?
![图片](https://github.com/sumatrapdfreader/sumatrapdf/assets/4496251/4aa7b4ac-25ff-4e92-be53-50088d6bc867)
![图片](https://github.com/sumatrapdfreader/sumatrapdf/assets/4496251/4d9b244e-9988-4f75-8c00-6f2029d7823b)

**Comment by GitHubRulesOK** [comment] 2023-11-20 09:26
duplicate of [something ?](https://github.com/sumatrapdfreader/sumatrapdf/issues/2682)
set `NoHomeTab = true`

**Closed by GitHubRulesOK** 2023-11-20 09:26 UTC
