### ISSUE TITLE
Major rendering performance issue

### ISSUE THREAD

**Issue by neremin** [sumatrapdfreader/sumatrapdf#904] opened 2017-10-03 10:31 UTC
Based on forum discussion, which can be found here:
https://forum.sumatrapdfreader.org/t/major-performance-issue/454

> I’m using current version of Sumatra. If I try to open PDF document with OCR layers under image, rendered by FineReader then Sumatra takes forever to open such document. Sometimes running optimization over such PDF (i.e. using shrinkpdf.com) might help, but in 90% cases it doesn’t. At the same time Adobe Acrobat Reader and most other readers can open such documents instantly.
> So, this appears to be a major performance issue. Hopefully it can be fixed shortly.
> 
> P.S.: link to sample PDFs (image only and OCR versions of the same pages) 
[Sample.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/1351938/Sample.zip)

**Comment by ehea617** [comment] 2017-10-07 17:35
I am able to reproduce this issue with my own PDF files also.

**Comment by neremin** [comment] 2018-01-31 10:16
The same issue comes with decoding jbig compressed b\w images. It takes almost 15 longer to decode and render 14400x14400 b\w page comparing to Google Chrome embedded pdf viewer.

**Comment by HalliHalloSchatz** [comment] 2018-11-09 12:54
Yes, I have the same problem.
Any fix for that?

**Comment by GitHubRulesOK** [comment] 2020-01-30 00:49
@jkj
Whilst there may be some way to allocate more resources to allow for these severely compressed bloated files, I think the time taken to decompress a page that is 16 times the area required is perfectly understandable.
Using aggressive compression always leads to very slow decompression and once the file is reduced to A4 pages it results in a significantly smaller file that takes practically no time at all to load.
It is simple to fix by using Microsoft print to file and setting the page size to A4
![image](https://user-images.githubusercontent.com/12754913/73410217-7ecee680-42f9-11ea-8cf8-b7a29c1a7a65.png)
Since the file is 4times oversize in both directions and uses maximum compression it naturally will take a long time to decompress then even longer to navigate (a loose loose situation) to get "win win" dont overscan at high resolution and then there is no need to waste time waiting for compressing or decompressing.

**Comment by kjk** [comment] 2020-02-01 02:06
It seems to render even quicker that Chrome now, so closing.

**Closed by kjk** 2020-02-01 02:06 UTC
