### ISSUE TITLE
Bad print quality for barcode

### ISSUE THREAD

**Issue by PratikMMohite** [sumatrapdfreader/sumatrapdf#2140] opened 2021-08-25 11:24 UTC
I am printing barcode through sumetraPDF command line with the print setting contains orientation set to "landscape" the image quality drastically decreases. So the barcode scanner not able to detect it. Please fix it
![image](https://user-images.githubusercontent.com/32018912/130781915-2939f852-fbbc-4d0c-8f57-a51e6f7e7998.png)

**Comment by GitHubRulesOK** [comment] 2021-08-25 12:21
SumatraPDF only uses Windows generic image printing to handle the output, there is nothing to fix in that process except change input file quality or print driver settings. The output quality will depend on efficient barcode print drivers. Most users with similar problems find switching print drivers resolves thermal printing problems. check if your printer is supported by a better thermal driver such as bartender. 

However if the issue here is that orientation has a significant effect, then a sample input file is needed to check if SumatraPDF is altering output due to orientation. also type of printer & driver and typical command line.

**Comment by PratikMMohite** [comment] 2021-08-25 12:57
I Tried on following printers 
[Citizen Cl-s621](https://www.citizen-systems.com/us/products/printer/label/cl-s621)
[TSC-244] (https://usca.tscprinters.com/en/products/ttp-series-4-inch-performance-desktop-printers)
[Xprinter XP350B](https://www.xprintertech.com/usb-serial-lan-80mm-direct-thermal-label-printer-xp-350b)
but still getting similar result instead of straight lines getting zig zag lines

**Comment by GitHubRulesOK** [comment] 2021-08-25 13:49
the "zig zag" is usually a grey boundary line output as 50% black and 50% white (alternating) its thus a frequent problem for a monochrome printer a good black and white driver should avoid such output
If possible ensure the images are mono png image right way up at 100% scaling and print the png not a pdf
afaik those models may work well with bartender so thats worth a try https://www.seagullscientific.com/support/downloads/drivers/

**Comment by GitHubRulesOK** [comment] 2023-03-30 00:46
closing as in effect a duplicate of mono thermal/label printers issues due to print as image expects color thus convert to mono will cause issues unless using a driver that corrects pixel mismatches.

see https://github.com/sumatrapdfreader/sumatrapdf/issues/203

**Closed by GitHubRulesOK** 2023-03-30 00:46 UTC
