### ISSUE TITLE
The translations arent included in the pre-release builds

### ISSUE THREAD

**Issue by Felipefpl** [sumatrapdfreader/sumatrapdf#4104] opened 2024-02-23 11:19 UTC
**SumatraPDF version**

Version 3.6.15966

**Describe the bug**

I updated the translation to brazilian portuguese and the program still uses the old translations.

**Comment by GitHubRulesOK** [comment] 2024-02-23 12:24
duplicate of some other issues currently no time to find @kjk current progress ?

**Comment by kjk** [comment] 2024-02-28 22:42
Should be available in next pre-release after 15966 (should be available within next 24 hrs)

**Closed by kjk** 2024-02-28 22:42 UTC
