### ISSUE TITLE
Middle click does not close tabs reliably

### ISSUE THREAD

**Issue by noperator-zz** [sumatrapdfreader/sumatrapdf#880] opened 2017-09-04 05:18 UTC
In order to close a tab with the middle click button, 'TabBarProc' (Tabs.cpp) must receive a 'WM_MBUTTONDOWN' message followed by a 'WM_MBUTTONUP'. The 'WM_MBUTTONDOWN' handler calls 'TabNotification(..., T_CLOSING, ..., ...)' which puts the clicked tab into tab->xClicked. Then the 'WM_MBUTTONUP' handler closes the tab.

A problem occurs when multiples tabs are middle clicked in quick succession. 'TabBarProc' misses the 'WM_MBUTTONDOWN' event so tab->xClicked is never set, which causes 'WM_MBUTTONUP' to do nothing.

I don't know how 'TabBarProc' is called, but the best solution would be to make sure it never misses messages, as I'm sure that causes other unwanted effects.
Alternatively, the functionality of 'WM_MBUTTONDOWN' can probably just be copied into 'WM_MBUTTONUP'

**Comment by imsoenthused** [comment] 2021-07-14 19:35
Middle-click also has an issue caused by any high enough DPI sensor mouse. The click to close tabs absolutely will not register unless the mouse is in the same EXACT position for the entire process. With high DPI mice, the act of clicking will cause an almost imperceptible movement of the mouse but the high-resolution sensor registers it causing the attempt to close to completely fail.

**Comment by GitHubRulesOK** [comment] 2021-07-14 20:01
@kjk 
I observe in my browser I can click middle down at one point within a tab move mouse elsewhere in the zone then release while close the tab, but cant do that in Sumatra.
I know you worked hard recently on tooltips but can that constant detection not also be used to boundary the up middle mouse ?

**Comment by GitHubRulesOK** [comment] 2021-09-17 18:10
@kjk 
just a reminder that current middle click seems not comparable to previous see https://forum.sumatrapdfreader.org/t/closing-tab-with-middle-click/3421/7

**Closed** 2023-03-27 19:24 UTC
