### ISSUE TITLE
Offset the page based on Annotation Position

### ISSUE THREAD

**Issue by taooceros** [sumatrapdfreader/sumatrapdf#2512] opened 2022-04-29 01:36 UTC
It would be great to offset the page when selecting the annotation in edit window based on the annotation position. Currently any selection will only go to the top of the specific page.

It's a bit annoying though acceptable. Thanks

**Comment by GitHubRulesOK** [comment] 2022-04-29 01:59
@kjk dupe of https://github.com/sumatrapdfreader/sumatrapdf/issues/1688 ?

**Comment by kjk** [comment] 2022-04-29 08:44
Makes sense and it does seem like the same as #1688

**Closed by kjk** 2022-04-29 08:44 UTC
Labels: annotations
