### ISSUE TITLE
ESC key should exit active presentation / fulscreen mode only, not exit globally

### ISSUE THREAD

**Issue by WhiteChairFromIkea** [sumatrapdfreader/sumatrapdf#1910] opened 2021-03-24 12:28 UTC
Steps to reproduce:
1) Configure advanced settings ```EscToExit = true``` (press esc to close sumatra, when in normal reading mode);
2) Hit F5 or F11 to view pdf in fullscreen mode;
3) Hit ESC;
4) Whole sumatra is closed.

Expected behavior in step 4 is to exit fulscreen mode only (the same as hitting F5 or F11 again when in fulscreen mode);
Expected behavior to exit sumatra when currently in fulscreen mode is to hit ESC key twice.

![image](https://user-images.githubusercontent.com/46539653/112310072-cf976080-8cac-11eb-8d29-1d9a6e7b7509.png)

**Comment by GitHubRulesOK** [comment] 2021-03-24 12:47
Basically a duplicate of the 3.1 and later methodology compared to 3.0 and before see https://github.com/sumatrapdfreader/sumatrapdf/issues/1741

also related to https://github.com/sumatrapdfreader/sumatrapdf/issues/1773

**Closed by GitHubRulesOK** 2021-03-24 12:47 UTC
