### ISSUE TITLE
Very high memory usage when printing

### ISSUE THREAD

**Issue by johnrowell** [sumatrapdfreader/sumatrapdf#68] opened 2015-01-19 22:39 UTC
Running SumatraPDF 3.0 on Windows XP.
I can open the file located at http://www.discountpv.com/pdf/cedeclaration.pdf , but when I try to print it the memory use skyrockets and bogs down my computer - it takes several minutes for it to even begin printing. To clarify, I download the file to my computer and then open it with SumatraPDF - I do not open it in the browser. It opens and displays fine, but it's a real memory hog when printing. So far, I do not have this problem with other documents. Also, I did not have this problem printing this same document with SumatraPDF version 2.2.1.

Regards,

John

**Comment by zeniko** [comment] 2015-01-20 18:56
Thanks for the report. This is a duplicate of https://code.google.com/p/sumatrapdf/issues/detail?id=2456 and thus likely also one of issue #37. Using the "Print as image" advanced printing option might help in this case (despite its claim to the contrary).

**Closed by zeniko** 2015-01-20 18:56 UTC

**Comment by johnrowell** [comment] 2015-01-21 07:08
Thanks for the response and suggested remedy. I (and others using a computer with limited memory) would consider this a serious issue that should be urgently resolved. At the very least, until a proper resolution can be implemented, perhaps the user could be alerted with a warning in such an event stating something to the effect of "this document is requesting a large amount of memory to print. should we try printing as a single-layer flattened document instead?"

**Comment by kjk** [comment] 2015-01-21 09:47
We can't do that because we don't know up-front which document will result in using lots of memory during printing.

**Comment by johnrowell** [comment] 2015-01-21 19:38
Ok I see. Thanks for the explanation. Well, I hope it is possible for this issue to be solved in some way. Otherwise, the program is so fast it's amazing. Never going back to Adobe!
