### ISSUE TITLE
Feature request: Dark mode

### ISSUE THREAD

**Issue by ema93a** [sumatrapdfreader/sumatrapdf#628] opened 2016-10-01 11:22 UTC
Some of us spend many hours in front of PDF documents and it really makes a difference to our eyes to have a dark mode that makes text white and the background black. I tried it in another PDF viewers and even in Chrome reader with Dark Reader extension enabled and my eyes are healthier and more relaxed when it is enabled. It makes reading long documents so much easier.

**Comment by pdgessler** [comment] 2016-10-01 11:58
Did you try using the command line option `-invert-colors` as described in the [List of recognized command line options](https://github.com/sumatrapdfreader/sumatrapdf/wiki/Command-line-arguments#list-of-recognized-command-line-options)?

There is another issue ([#275](https://github.com/sumatrapdfreader/sumatrapdf/issues/275)) about adding a keyboard shortcut to invert colors. This may have some relevant discussion if you are wanting to invert the colors without restarting SumatraPDF with the command line option set.

**Comment by nativeAndroid** [comment] 2016-10-08 18:06
good

**Comment by creamynebula** [comment] 2017-04-22 23:41
Thank you pdgessler, I thought the feature simply didn't exist on sumatrapdf outside of editing the configuration text file to manually change the colors. I use sumatra on windows and -invert-colors added to the shortcut worked fine.

**Comment by carloswm85** [comment] 2017-06-01 18:45
Add nightmode, please. Really really useful. And there are not much light weighted pdf readers with that feature.

**Comment by kjk** [comment] 2017-06-12 09:28
closing as dup of #275

**Closed by kjk** 2017-06-12 09:28 UTC

**Comment by JJenkx** [comment] 2017-08-31 02:15
I found a better solution for Windows. My setup is all black boarders and black start-up screen and total black in full-screen with white text.

Setting/Advanced Options, add line **GradientColors** to **FixedPageUI** then choose your hex color. Here is mine setup for all black and white.

```
MainWindowBackground = #000000
EscToExit = false
ReuseInstance = false
UseSysColors = false
RestoreSession = true

FixedPageUI [
	TextColor = #ffffff
	BackgroundColor = #000000
	SelectionColor = #f5fc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
	GradientColors = #000000
]
```

https://i.stack.imgur.com/vMHOQ.png

**Comment by spcogg** [comment] 2019-10-10 13:25
Bumping this as the only way to get a 'dark mode' equivalent.

Also doesn't work for epubs, is there a workaround for this?

**Comment by SumatraPeter** [comment] 2019-10-10 19:47
@spcogg: You can try modifying **EbookUI**'s _TextColor_ and _BackgroundColor_ options, or else set _UseFixedPageUI_ to **true** to make the settings specified by JJenkx above apply to eBooks as well.

**Comment by jonbar12** [comment] 2020-05-12 00:31
would there be some way to put a dark theme for the interface ?

**Comment by GitHubRulesOK** [comment] 2020-05-12 00:44
@jonbar12 
there are several occasions I have allowed windows to mess with the interface colors see some of my answers to the many dark mode requests but at the end of the day (pardon the pun) I remove them as causing other problems within a multiformat application

**Comment by ZurMaD** [comment] 2020-10-18 18:39
Can be this enable with a small button on the tab? Will be very useful to active/deactivate quickly as possible

**Comment by kulalsk2** [comment] 2021-02-01 17:59
@jonbar12 Yeah What you are telling is correct It will be great if we had a dark mode

**Comment by rwperrott** [comment] 2021-02-28 21:07
@JJenkx this idea is part of the way there, but all the window colours must change too, _not just the page content_, which is why  `-invert-colors` is probably inadequate too.  Any reasonable solution needs to be switchable inside the application anyway.

Colour palette switching maybe better supported by switchable themes, to part fix the *nix-style laziness of having to hand edit config files, for so-called 'advanced' features *.

\* A dynamically rendered 'advanced' configuration editor, using name/type/default value templates, possibly as json map files, could have been provided for this, significantly reducing the need for GUI revision development, while retaining the existing configuration storage.

**Comment by GitHubRulesOK** [comment] 2021-02-28 23:10
@rwperrott 
The trail is above this is in effect at the time a duplicate of #275 which in turn was combined in parts with older https://github.com/sumatrapdfreader/sumatrapdf/issues/79 ,still open as one of a few multiple issues the primary thread for theming is https://github.com/sumatrapdfreader/sumatrapdf/issues/743 but there are other separate aspects that users mix up.

**Comment by rwperrott** [comment] 2021-03-01 00:48
@GitHubRulesOK thanks for pointing to these earlier issues, so I've update #79.

It looks Github should support key-word lists for issues, if it doesn't already, to better assist Github search and external search engine indexing, so that the most appropriate search result matches are provided, with "closed" status issues ranked later in search results, to avoid needless commenting on closed issues.  I may look to request this myself, after checking, given current inadequate search results.
