### ISSUE TITLE
Swapping tabs forgets closing bookmarks

### ISSUE THREAD

**Issue by Muon** [sumatrapdfreader/sumatrapdf#1721] opened 2020-08-04 07:31 UTC
Starting with 3.2, if I close an expanded bookmark group and switch to a different PDF tab and then back, it forgets the bookmark group was closed.

**Steps to reproduce:**
1. Open two PDFs with bookmarks in two tabs.
2. Open a bookmark group in PDF 1.
3. Close the bookmark group in PDF 1.
4. Switch to PDF 2.
5. Switch back to PDF 1.

**Expected behavior:** the bookmark group is still closed.
**Actual behavior:** the bookmark group is open.

**Comment by GitHubRulesOK** [comment] 2020-08-04 09:05
The bookmarks display is subject to a few mutually related options
![image](https://user-images.githubusercontent.com/12754913/89274311-a8feb980-d638-11ea-9fd5-a150a60906fa.png)
If just `Show the bookmarks sidebar when available` is active then on opening the tabs the Bookmarks will always show
If you have `Remember these settings for each document` active then **after the first closing** it will stay closed until you request they be reopened

**Comment by Muon** [comment] 2020-08-04 09:31
Just tested it with the prerelease, same thing happens. Also, I might've been unclear, it's about expanding/contracting groups of bookmarks, not opening/closing the bookmark pane.

**Comment by GitHubRulesOK** [comment] 2020-08-04 12:23
I did slowly understand its expansion/collapse of the marks hence the suggestion to use latest where session data is now better but it requires `remember for each document` **to be active**

**Comment by Muon** [comment] 2020-08-04 12:33
I made sure both the settings were active when I was testing.

**Comment by GitHubRulesOK** [comment] 2020-08-04 12:55
The wrinkle in this situation is the two tabbed files need to be different since if they are two tabs or windows of same file then there will be a contest in the one settings file.
My test files behaved as I expected, can you provide two small examples with description of each step you took ?

**Comment by SumatraPeter** [comment] 2020-08-04 23:21
@Muon: Confirmed with 3.2, and it's not just PDFs but happens with EPUBs too, and probably all file types.

**Comment by GitHubRulesOK** [comment] 2020-08-04 23:38
@SumatraPeter 
this is related to session history so 3.2 and before will fail it was to a degree resolved by saving session data on changing tabs, hence my suggestion to use recent pre-release. The files and sequence I use to partially colapse and expand work in latest. but that is not to say that other file combinations  or methods (excluding two references to the same file) will not work. So only testing against pre-release cam highlight what fails.

**Comment by GitHubRulesOK** [comment] 2020-08-05 00:17
@kjk 
My understanding is that there is still an issue with session data,
the `TocState` is only saved when closing tabs whereas it is static when switching between tabs.
If I am correct then the flush of TocState from memory to settings needs to be triggered in the focused tab when either selecting another OR opening another tab
The edge case of flushing when using CTRL [Shift] N would also need consideration

**Comment by SumatraPeter** [comment] 2020-08-05 04:36
@GitHubRulesOK: Yes, I know you're referring to #1659, but since it didn't make sense that simply switching to a different tab and back again would necessitate reading TocState from the settings file again, IMO those changes didn't matter here and so I simply tested with 3.2 (as confirmed by the fact that 3.2 and prerel-13105 behave the exact same way). Matter of fact, watching very carefully it seems to me that the expanded and then closed TOC node starts re-expanding _as soon as_ one clicks on a different tab.

**Comment by Muon** [comment] 2021-07-26 03:13
Appears to be fixed with the current release.

**Comment by Muon** [comment] 2021-07-26 03:14
Never mind, still broken.

**Comment by GitHubRulesOK** [comment] 2023-05-17 14:42
@kuro68k 
to change behaviour a sample and steps to cause repeatable behaviour are needed if it is "random" it is likely a historic setting or document default is causing that "odd" behaviour. so testing current pre-release with current file from a different (non-existing) issue. and ensuring OPTIONS REMEMBER FOR **EACH** document. my findings are that this issue is valid I.E. the closure of bookmarks is not persisted since the re opened tab has not commited any change to its history which will happen if the tab is closed and reopened
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/7ae2e511-64f8-4094-a708-e0e0552c840f)

bookmarks closed then tab closed  will remember state for reopen in new tab
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/242797ee-fe5d-445b-ac9a-cc914edf5caa)

bookmarks left open then tab closed will remember state for reopen in new tab
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/5fe6d701-cef3-49ec-9dc9-9e8643c4a6b3)

The issue is as per original report that its expected moving focus from tab to tab should offer the same functionality which it does not.

**Comment by kuro68k** [comment] 2023-05-17 15:10
Ah, my issue is a little different. I don't have to close and re-open the document, only switch to a different tab and back again. Sometimes it happens when I'm browsing the affected document itself.

The "remember settings for each document" setting has no effect.

**Comment by misaz** [comment] 2023-12-28 16:16
Any news about this issue?

**Closed** 2023-12-29 17:38 UTC

**Comment by kjk** [comment] 2024-01-02 17:13
@misaz wait for next-prelease (https://www.sumatrapdfreader.org/prerelease), build AFTER 15928 and see if it fixes the issue.

If not, please open a new issue and provide detailed description of the bug, preferable with screen recording showing the problem.

**Comment by misaz** [comment] 2024-01-02 17:42
@kjk Thanks for reply. I am author of the fix. I asked the question about status, but later deciced to fix it myself. Currently, I use custom build of older 3.4.6 containing the same fix because I do not like new design (https://github.com/sumatrapdfreader/sumatrapdf/issues/3803#issuecomment-1789062859) introduced in 3.5.
