### ISSUE TITLE
Bookmark fontsize changeable

### ISSUE THREAD

**Issue by GerdHirsch** [sumatrapdfreader/sumatrapdf#120] opened 2015-03-01 11:49 UTC
make the fontsize für the bookmark view changeable, for older people, it would be better

**Comment by GitHubRulesOK** [comment] 2019-02-27 13:17
@kjk seems to now be duplicated by https://github.com/sumatrapdfreader/sumatrapdf/issues/710 which has more details

**Comment by kjk** [comment] 2019-02-27 19:43
Closing as duplicate of #710

**Closed by kjk** 2019-02-27 19:43 UTC
