### ISSUE TITLE
is it possible to stop 'Home' tab automatically opened in ver. pre-3.5.15162 64bit

### ISSUE THREAD

**Issue by LqkUWp** [sumatrapdfreader/sumatrapdf#2697] opened 2022-06-08 14:25 UTC
'Home' tab is automatically opened when I open a pdf file if there is no old tabs opened. It occupies a precious position so I would like not to open 'Home' tab if it's possible.

**Comment by GitHubRulesOK** [comment] 2022-06-08 15:32
Closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/2682

**Closed by GitHubRulesOK** 2022-06-08 15:32 UTC
