### ISSUE TITLE
Goldendict Dictionary(or other dictionary) can't scan popup in sumatrapdf

### ISSUE THREAD

**Issue by xngnln** [sumatrapdfreader/sumatrapdf#682] opened 2016-12-07 06:58 UTC
Small popup window can be used for rapid translation, it will be popup beside mouse cursor and will be automatically closed when cursor move away from it, but it doesn't work in sumatrapdf, it can't get any text, though the text can be copied directly.

**Comment by GitHubRulesOK** [comment] 2020-02-02 21:51
@kjk duplicate of #427 however this description highlights the much wider issue that standard screen based products like NVDA audio reader cannot access the text in the SumatraPDF canvas

**Comment by kjk** [comment] 2020-02-03 02:48
This is most likely about missing accessibility support in Sumatra (which is why NVDA doesn't work). I started some work there but it's hard.

**Comment by GitHubRulesOK** [comment] 2020-03-20 18:26
Issue is covered by https://github.com/sumatrapdfreader/sumatrapdf/issues/947 https://github.com/sumatrapdfreader/sumatrapdf/issues/1280 and nvda issues in https://github.com/sumatrapdfreader/sumatrapdf/issues/321
Also see a dictionary app (QTranslate) that does work with local and online dictionaries on selected SumatraPDF text in forum discussion https://forum.sumatrapdfreader.org/t/sumatrapdf-built-in-dictionary/2198

**Closed by GitHubRulesOK** 2020-03-20 18:26 UTC
