### ISSUE TITLE
Session not saved/restored if only one tab was open

### ISSUE THREAD

**Issue by LucasMetal** [sumatrapdfreader/sumatrapdf#1055] opened 2018-08-07 23:10 UTC
Hi! Great app!

Version: 3.1.2 64-bits

Steps:
- Leave only one tab (only one file) open in the app
- Close the app
- Open the app
- The tab is not restored, no file is shown in the app

I think it would be intuitive to restore the previous tab, even if it was only one. As any internet browser user would, I find this behavior a bit annoying.

Thanks!

**Comment by GitHubRulesOK** [comment] 2018-08-08 01:08
Hi Lucas
I think this needs to be added to the many feature requests for changes to "Tabs" behaviour
I note from your profile you have some experience in C, it may be possible that if you make the necessary change to drop the minimum number of files stored on closure from 2 to 1 and issue a PR then @kjk might add it to his commits

For any one else who needs this behaviour "now" a crude work-around can be run from a cmd file as below
NOTE this as it stands it works in the same relative directory  (you will need to add your own "c:\file paths\") It presumes both the last tag standing is the first FilePath in settings.txt (it shound be unless you have "Pinned" files (in which case why would you need this general fix as its much easier to have a shortcut to a single file) and you have the latest 1.99b copy of Find & Replace TeXT from http://fart-it.sourceforge.net/
P.S there are 2 Tab characters in the third line

find /i "FilePath =" sumatrapdf-settings.txt >temp.txt
fart --remove -- temp.txt "---------- SUMATRAPDF-SETTINGS.TXT"
fart temp.txt "		FilePath" "ReopenOnce"
copy SumatraPDF-settings.txt /A + temp.txt /A SumatraPDF-settings.txt /A
start "" SumatraPDF

**Comment by LucasMetal** [comment] 2018-08-08 18:05
Hi! 

Thanks for the fast response!

I guess I could do it, the problem wouldn't be the change itself but finding the place to do it.
As I have never participated in this project, it would be a LOT of time involved to just change one number, that seems to affect only me.

I could use some help on where to start looking, but I can't promise I'd have time to dedicate right now.

Thanks!!

**Comment by GitHubRulesOK** [comment] 2018-08-08 18:10
Thanks
I can take a look, as I did forty hours of C  forty years ago (so not up-to date) and may be blind leading … …
I will reply If I think I have located it, but as you say its a lot of effort to fork for one small change, however if you have an input to make any change it would help.

**Comment by LucasMetal** [comment] 2018-08-08 18:17
hahah awesome, let me know if you have located it :)
Thanks!

**Comment by GitHubRulesOK** [comment] 2018-08-08 18:55
@LucasMetal possibility in SumatraPDF.cpp
 
 
```
1667      ResetSessionState(gGlobalPrefs->sessionData); 
1668      for (WindowInfo* win : gWindows) { 
1669          if (win->tabs.size() == 0) 
1670              continue; 
1671          SessionData* data = NewSessionData(); 
1672          for (TabInfo* tab : win->tabs) { 
1673              DisplayState* ds = NewDisplayState(tab->filePath); 
1674              if (tab->ctrl) 
1675                  tab->ctrl->UpdateDisplayState(ds); 
1676              // TODO: pageNo should be good enough, as canvas size is restored as well 
1677              if (tab->AsEbook() && tab->ctrl) 
1678                  ds->pageNo = tab->ctrl->CurrentPageNo(); 
1679              ds->showToc = tab->showToc; 
1680              *ds->tocState = tab->tocState; 
1681              data->tabStates->Append(NewTabState(ds)); 
1682              DeleteDisplayState(ds); 
1683          } 
1684          data->tabIndex = win->tabs.Find(win->currentTab) + 1; 
1685          // TODO: allow recording this state without changing gGlobalPrefs 
1686          RememberDefaultWindowPosition(*win); 
1687          data->windowState = gGlobalPrefs->windowState; 
1688          data->windowPos = gGlobalPrefs->windowPos; 
1689          data->sidebarDx = gGlobalPrefs->sidebarDx; 
1690          gGlobalPrefs->sessionData->Append(data); 
1691      } 
1692  } 
1693  
 

```line 1684 looks a good contender with a zero value in place of the +1 could that make the change ?

**Comment by LucasMetal** [comment] 2018-08-08 19:53
Well, finally I forked it, and I checked the code on my machine. But you pointed me to the right file I must say.

What you pasted is indeed the code that saves the state, but that code will save everything without caring about the number of tabs open. The problem is that the function is not being called at all.

The real magic seems to start on line 2104:
```
    bool lastWindow = (1 == gWindows.size());
    // RememberDefaultWindowPosition becomes a no-op once the window is hidden
    RememberDefaultWindowPosition(*win);
    // hide the window before saving prefs (closing seems slightly faster that way)
    if (!lastWindow || quitIfLast) {
        ShowWindow(win->hwndFrame, SW_HIDE);
    }
    if (lastWindow) {
        // don't call RememberSessionState if OnMenuExit already has
        // also don't remember a single document (unless quitting through Menu -> Exit)
        if (quitIfLast && gGlobalPrefs->sessionData->size() == 0 && win->tabs.size() > 1) {
            RememberSessionState();
        }
        prefs::Save();
    } else {
        // this happens otherwise in prefs::Save
        for (TabInfo* tab : win->tabs) {
            UpdateTabFileDisplayStateForWin(win, tab);
        }
    }
```

but it has a very explicit comment for that behavior, so I don't know if changing that would be accepted.
What do you think?

**Comment by GitHubRulesOK** [comment] 2018-08-08 19:58
@LucasMetal  Honing in on tabIndex above also leads to 

```

src/Tabs.cpp 
Showing the top match Last indexed on Jan 14 
C++  

836   void TabsSelect(WindowInfo* win, int tabIndex) { 
837       int count = (int)win->tabs.size();
838       if (count < 2 || tabIndex < 0 || tabIndex >= count)
839           return;
840       NMHDR ntd = {nullptr, 0, TCN_SELCHANGING};

```
that <2 looks like another possibility as does -1 in the following, sorry but that about as best as I can see with my limited knowledge, but at least its a few places to test behavioural change
```
src/SumatraStartup.cpp 
Showing the top match Last indexed on Jan 14 
C++  
704                   RestoreTabOnStartup(win, state);
705               }
706               TabsSelect(win, data->tabIndex - 1); 
707           }
708       }
709       ResetSessionState(gGlobalPrefs->sessionData); 
```

**Comment by kjk** [comment] 2018-08-08 20:11
I'm not saying I made the perfect choice but this indeed works as intended.

My thinking was: when you quit while having 2 or more pages open, we re-open all pages because it would be a pain to re-open them manually.

When you quit with 1 page open, we re-open on Home page because that document is listed on home page so it's just one click to re-open it.

It's inconsistent but it's a trade-off: Home page gives you quick access to all recent documents.

**Comment by LucasMetal** [comment] 2018-08-08 20:42
@kjk thanks for answering!

Have in mind that no one is criticizing your choices, just trying to understand and discuss them. We are all really grateful for your work :)

I'm glad this is working as expected (as I discovered by your comments in the code) and that it's not a bug.
I just personally found it misleading, because the look & feel of the app resembles a lot a web browser, but this particular behavior is different.
Personally, I would have left the same behavior for all the cases, less code and consistent behavior.

Also @GitHubRulesOK case is valid, it would be nice to remember the page position for long files, even if it's the only one have you open. 

The home page is a nice touch to open recent documents without having to hunt for them, but IMHO shouldn't replace the remembering of the only open tab. I think I saw another ticket suggesting being able to open a new tab, and seeing the home page there (more and more like a web browser).

Anyway, I didn't want to waste your time. Thanks for answering!
You can close this as it's the expected behavior :)

**Comment by kjk** [comment] 2022-06-08 04:10
this is now fixed in pre-release builds

**Closed by kjk** 2022-06-08 04:10 UTC
