### ISSUE TITLE
Feature request: Organize pages dynamically depending on zoom level

### ISSUE THREAD

**Issue by el-hult** [sumatrapdfreader/sumatrapdf#4365] opened 2024-07-05 14:18 UTC
**Is your feature request related to a problem? Please describe.**
I typeset latex documents and use sumatra as my previewer. It is amazing in how fast it is, the synctex support, the automatic reloading etc. But I find it hard to get an overview of my document when it starts to become 10+ pages.
Just zooming out places all pages in a vertical list for scrolling, meaning most of my computer screen is filled with grey background color, unused.

**Describe the solution you'd like**
I would like a third view mode. Currently I can chose Single page or Side by side, which shows a single page or two pages next to each other. A mode called "auto" or "overview" would automatically show a dynamic number of pages side by side depending on your zoom level. 

**Describe alternatives you've considered**
An alternative would be a manual dialogue box asking how many pages to place side-by-side.

**Additional context**
I got the idea of this behavior from past experiences with MS Word. When authoring documents in the range 10-50 pages indended for physical print, I would often zoom out, the layout change to put many pages side-by-side and I got a feel for the text flow. Depending on the zoom level, It would show 2 or more pages side by side. Given most computer screens are 

10 pages zoomed out in word:
![bild](https://github.com/sumatrapdfreader/sumatrapdf/assets/11832922/27716518-2b5e-45de-9171-2c31377133cc)

Same 10 pages zoomed to fit on screen in sumatra, after pdf print

![bild](https://github.com/sumatrapdfreader/sumatrapdf/assets/11832922/92680631-b424-44fe-9eed-05084f41b20c)

**Comment by GitHubRulesOK** [comment] 2024-07-05 15:09
There is already an open issue covering the experiments in spread out sheet viewing . but its not easy to manage in a MultiFormat viewer.

Dedicated one format viewers like Acrobat Tracker or Foxit can do it simply for just PDF.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/ecf68eb6-f823-4b71-b6fb-92d1429262de)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/e4a3b98e-4df4-4288-b870-948e57786d3f)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/2bd1003c-a59d-4250-82f1-b9650755a004)

closing soon as duplicate of something else

**Closed** 2024-07-05 15:15 UTC

**Comment by el-hult** [comment] 2024-07-05 16:15
Wow thank you for swift response! Have a nice weekend!
