### ISSUE TITLE
Print problems with Canon SecurePrint

### ISSUE THREAD

**Issue by chomee011** [sumatrapdfreader/sumatrapdf#992] opened 2018-03-16 13:10 UTC
Hi, 

My company has recently switched to Canon SecurePrint system, and I have problems printing with SumatraPDF ever since.   

Printouts are missing large portions in horizontal bands. 

Previously we used Xerox printers and there were no issues.  I tried printing several documents, both from latest release (3.1.2) and portable prerelease (10776).  Interestingly, the banding is different on different documents, but consistent when printing same document from both versions.

Here's how the pdf renders on-screen:
[sumatra1](https://user-images.githubusercontent.com/24589596/37522014-f33d19ee-2922-11e8-97f9-2f1932cdd3e2.png)

And how it comes out (printed + scanned back):
[0262_001.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/1819231/0262_001.pdf)

Here's source PDF:
[RB Limfjord Alborg, 19.03.-23.03..pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/1819259/RB.Limfjord.Alborg.19.03.-23.03.pdf)

My laptop is running Windows 10 Enterprise, if that matters.

Please take a look

**Comment by SumatraPeter** [comment] 2018-03-17 14:35
See if [this](https://github.com/sumatrapdfreader/sumatrapdf/issues/974#issuecomment-366553431) helps.

**Comment by chomee011** [comment] 2018-03-18 14:56
Thanks, will do and let you know....

Milan

суб, 17. мар 2018. у 15:35 Peter <notifications@github.com> је написао/ла:

**Comment by GitHubRulesOK** [comment] 2019-11-27 18:04
@kjk effectively dupe of https://github.com/sumatrapdfreader/sumatrapdf/issues/919

**Closed** 2019-11-27 22:01 UTC
