### ISSUE TITLE
Closing multiple tabs

### ISSUE THREAD

**Issue by antgustech** [sumatrapdfreader/sumatrapdf#656] opened 2016-11-07 08:38 UTC
Requesting the feature to close multiple tabs like in modern browsers. So If you right click a tab, a meny will appear letting you choose between "Close all tabs", "Close all tabs to the right" or "Close all tabs to the left". And maybe additional optiions like "Close all tabs that is older than a week" and so forth.
![close](https://cloud.githubusercontent.com/assets/8721113/20051167/e7344fa8-a4cd-11e6-947e-157bae5687f5.png)

**Comment by SumatraPeter** [comment] 2016-11-12 20:58
+1 Tab-related improvements have been on my wish list ever since Sumatra started supporting tabs.

See request no. 2 in my forum thread for example: http://forums.fofou.org/sumatrapdf/topic?id=318471

**Comment by GitHubRulesOK** [comment] 2020-02-06 15:07
Duplicate of #496 which also suggests

**- Properties e.g. the most important info from a files tab is **which file is currently open**
- Open Containing Folder. (or Rename and Reopen)**

**Comment by GitHubRulesOK** [comment] 2020-02-06 21:36
Duplicate of #388 which includes a link to the forum user requests so am closing this one

**Closed by GitHubRulesOK** 2020-02-06 21:36 UTC
