### ISSUE TITLE
New SVG icons for toolbar in Windows 10

### ISSUE THREAD

**Issue by djzn** [sumatrapdfreader/sumatrapdf#430] opened 2016-02-09 03:34 UTC
I suggest that new scaleable icons (SVG) are used in the application's toolbar.
I usually have a huge screen panel, 22 inches, and set Windows to 125% of its image resolution.
Specially fixed small icons will suffer and pixelate when the user resize Windows screen elements.
That's what's happening with Sumatra.

There is an issue already saying it's a bug, but it's not a bug. 
It's just that the icons can't cope when Windows tries to resize its image elements.
Usually all applicaitons work well with this, but Sumatra deserves fresh new SVG implementation of icons.

Thank you!

**Comment by bananakid** [comment] 2016-03-23 05:15
I double this. It's a great little app with outdated UI.

**Comment by kjk** [comment] 2017-06-09 19:15
Closing as duplicate of #326

**Closed by kjk** 2017-06-09 19:15 UTC
