### ISSUE TITLE
[ Feature request ]: Make Ebook's text copyable (fb2, epub, mobi)

### ISSUE THREAD

**Issue by umokk** [sumatrapdfreader/sumatrapdf#1439] opened 2020-01-29 23:33 UTC
Is it possible to modify the browser-based window (which I believe is used to show ebook's content) to make its text copyable, allowing the user to select a part of the text and copy it into the clipboard? I mean for any ebook: fb2, epub, mobi...

**SumatraPeter**, thank you for your answer!

**Comment by SumatraPeter** [comment] 2020-01-30 02:00
Please search before opening - this has been requested many, _many_ times over the years.

Workaround is to set **UseFixedPageUI = true** for EbookUI from `Settings > Advanced Options`.

In the latest [pre-release](https://www.sumatrapdfreader.org/prerelease.html) and [daily builds](https://www.sumatrapdfreader.org/dailybuilds.html) you can do this easily by going to `Debug > Toggle ebook UI`.

Note that you might need to close and re-open the ebook to see the changes.

@kjk: Can be closed as duplicate of #284. Also related: #289.

**Closed** 2020-01-30 03:06 UTC
