### ISSUE TITLE
Keyboard shortcut for Favorites

### ISSUE THREAD

**Issue by Arklytte** [sumatrapdfreader/sumatrapdf#727] opened 2017-02-23 09:29 UTC
I make/utilize a significant number of PDF's daily that dont have Bookmarks.  Being able to quick add favorites would be a HUGE timesaver.

FYI, I'm a HUGE fan of your software, and have been using it for a couple of years.  I use it exclusively at work and at home and find it to be (mostly) far more user friendly than it's competition.  However, the lack of user customizability for keyboard shortcuts is very frustrating.

**Comment by kjk** [comment] 2017-05-21 19:59
"Alt - a" followed by Enter works as a shortcut.

Closing as duplicate of #265

**Closed by kjk** 2017-05-21 19:59 UTC
