### ISSUE TITLE
Regular crashes with TeXnicCenter and DDE commands

### ISSUE THREAD

**Issue by DigNative** [sumatrapdfreader/sumatrapdf#1607] opened 2020-06-02 20:10 UTC
First of all, thank you very much for spending your time for developing and maintaining such a great PDF reader!

I am experiencing regular crashes when using SumatraPDF 3.2 with TeXnicCenter and DDE commands. The PDF document usually opens once in SumatraPDF, but then on reload by DDE commands (e.g. upon compilation of the PDF in TeXnicCenter), SumatraPDF crashes. This happens sometimes also when just scrolling within the PDF file. I experienced the same behavior with v3.1.2, too.

Please find the crash log here: https://gist.github.com/DigNative/4f9773026774508e958b44f72a492187

**Comment by GitHubRulesOK** [comment] 2020-06-02 20:57
@kjk 
can you narrow down a possible  cause

My comment on usage is that you are constantly multi calling thus twice the potential for failure

The start up shown above is Starting SumatraPDF
CmdLine: "C:\Program Files\SumatraPDF\SumatraPDF.exe" -inverse-search "\"C:\Program Files\TeXnicCenter\TeXnicCenter.exe\" /ddecmd \"[goto('%f','%l')]\""

However the inverse search is already there from last time so now you are constantly overwriting it
There should only be a -forward-search call **NO** -inverse-search **call** it is always stored ONCE in the settings file. See https://github.com/GitHubRulesOK/MyNotes/blob/master/AppNotes/SumatraPDF/SumatraPDF%20with%20TeXnicCenter.pdf

**Comment by DigNative** [comment] 2020-06-03 20:52
Thank you very much for your fast response as well as for providing the PDF file with explanations how an ideal setup of TeXnicCenter with SumatraPDF could be configured. I created a demo profile with this configuration to test it. So far, I didn't experience any crash, however, allow for some days of additional testing. I will get back to this issue report once I can confirm that this configuration prevents the issues.

**Comment by GitHubRulesOK** [comment] 2020-06-03 21:12
Version 3.2 has a higher locking threshold of 32 MB (3.1.2 was 10 MB) but note it is a **"threshold"** value thus it may be possible to trip over about that point (so keep an eye out for pdf compiled file size)

**Comment by DigNative** [comment] 2020-06-08 17:47
After trying a bit more intensely, I, unfortunately, have to report that the issue is still there. It was just a coincidence that I did not observe additional crashes before since I was only trying for a short period of time.

Concerning the locking threshold: I am not exactly sure what this means, but the document file sizes are way below 10 MB (usually ~2 to 3 MB).

**Comment by GitHubRulesOK** [comment] 2020-06-08 19:16
@kjk 
the file log shows at the end
"cannot find startxref \ trying to repair broken xref \ repairing PDF document"
which suggests the TeX compilation either failed to complete (a common problem whilst editing TeX) or was read prematurely during said process before the file was completed.
I dont understand why there are so many page 15/16/17/18 references when the direct call was to page 88, can you shed any light on the large number of those without any references to pages 1-14  or 19-87

@DigNative
What is so differentl about pages 15-18 in the last working PDF are they external references / images ?

**Comment by DigNative** [comment] 2020-06-08 20:25
Can you explain what you exactly understand as _external_ references or images?

If I recall right, pp. 15--18 contain some pictures, but there are pictures throughout the entire document (not only pp. 15--18). They should also be very similar in terms of data format as they have been created in the same way (these are screenshots, produced with the same program and file format). I can't figure out any specific difference of those pages compared to the other ones.

Additionally, the following notes may help for debugging:
* These crashes do not only happen with one particular document, but with many others (~20+), too. However, I was not able to figure out any kind of systematic in these documents triggering this behavior so far.
* But I can say that crashes happen with completely compiled documents just opened for reading natively in SumatraPDF, too. So it seems to be independent from the calling of SumatraPDF by TeXnicCenter.
* I can exclude an issue with my computer hardware or software environment, too, as I experience these issues with other computers and other software environments (Windows 7/10) as well.

**Comment by GitHubRulesOK** [comment] 2020-06-08 21:45
@DigNative 
I have frequently run TeXnicCenter & 3.1.2 on windows 7 and 10 without issues except when TeX failed and reported compilation errors, however I recollect it did not always show those unless opening the runtime logs. Normally that would result in a no PDF output error message at end of log.
However you say the problem also manifests as random crashes outside TeXnicCenter
And is also a problem with both version 3.1.2 and version 3.2 of SumatraPDF 

Those factors combined suggests one of

A) files compiled have some uncommon content, however if that were the case you should be able to narrow it down to one/two files that frequently trigger repeated failure in either / both versions.
B) source or compiled files are in a system with external interference such as a network or cloud drive / sync folder / agressive anti-virus scanning of data files such as pdf. but if on different platforms there should be a common bond.

Assuming a standard user compiles both tex files and pdf in the same c:\data\folder, using standard TeX system, and microsoft defender, how could your usage vary ?

**Comment by DigNative** [comment] 2020-06-09 19:22
> Assuming a standard user compiles both tex files and pdf in the same c:\data\folder, using standard TeX system, and microsoft defender, how could your usage vary ?

That is a very good question.

Most of my files on my workstations are indeed located on network drives. However, I experience the issues also on my notebook, where I compile the documents locally. I would exclude an anti-virus scanner from the list as am using the standard one of Windows 10 and Security Essentials on Windows 7, i.e. the standard mechanisms most of users will likely use.

I will try if I am able to provoke crashes with demo PDF files that I can provide you for debugging. Just allow for some days of trying --- since I don't figured out any systematics for the crashes yet, I have to spend more time in narrowing down an example.

**Comment by jan-glx** [comment] 2021-07-03 13:55
Not sure if this adds anything valuable to this issue but my TeXstudio also manages to crash Sumatra. [log](https://gist.github.com/jan-glx/159c794212fabb8deb82679f0ad24c7)1 [the last 1 is missing in the url to keep that way from search engines] Happy to provide .tex .synctex.gz & .pdf privately.

**Comment by kjk** [comment] 2021-07-03 14:39
@jan-glx the crash from https://github.com/sumatrapdfreader/sumatrapdf/issues/1607#issuecomment-873411430 should be fixed in latest daily build https://www.sumatrapdfreader.org/dailybuilds

That crash happened with 2021-06-09 build and latest is 2021-07-02

Note: I'm not saying all crashes are fixed, just the one with call stack:
```
00007FF778F46626 01:0000000000155626 sumatrapdf.exe!strconv::WstrToCodePage+0x26 D:\a\sumatrapdf\sumatrapdf\src\utils\StrconvUtil.cpp+34
00007FF778EF2BF5 01:0000000000101BF5 sumatrapdf.exe!HandleDdeCmds+0x115 D:\a\sumatrapdf\sumatrapdf\src\SearchAndDDE.cpp+868
00007FF778F0EFFC 01:000000000011DFFC sumatrapdf.exe!WndProcFrame+0x92c D:\a\sumatrapdf\sumatrapdf\src\SumatraPDF.cpp+4882
```

The crashes that @DigNative reported seems to be a memory corruption due to reloading a document and / or synctex parsing.

If I was able to reproduce this locally it would probably be relatively easy to figure out but I'm not fluent with TeXnicCenter

**Comment by jan-glx** [comment] 2021-07-03 17:01
I remembered Sumatra nagging me about the new build this morning when writing above comment but thinking well this one is open for two years, I just (last month) updated, what could have changed? Well I was wrong - awesome! Thank you! Will for sure share a reproducible if end up running into another crash (would not require using TeXnicCenter, I beleive)!

**Comment by kjk** [comment] 2022-06-01 01:47
Can't repro locally and no new information so I'll assume it's fixed.

**Closed by kjk** 2022-06-01 01:47 UTC
