### ISSUE TITLE
Find annotations on document

### ISSUE THREAD

**Issue by espettia** [sumatrapdfreader/sumatrapdf#2917] opened 2022-09-01 22:38 UTC
When searching for a note that is in the annotation window by clicking it, the program shows the page where it is, however it is not highlighted in any way making it difficult to find them if you have annotations made on different lines of the same page.

**Comment by GitHubRulesOK** [comment] 2022-09-01 22:44
duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1688

**Closed by GitHubRulesOK** 2022-09-01 22:44 UTC
