### ISSUE TITLE
annotation

### ISSUE THREAD

**Issue by pakistanofficial** [sumatrapdfreader/sumatrapdf#2286] opened 2022-01-15 07:06 UTC
Please provide short key for "Save Annotation".

**Comment by GitHubRulesOK** [comment] 2022-01-15 11:34
There are several but as per past policy none are currently listed (shortest is use context key)
Thus closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/2169#

**Closed** 2022-01-15 11:34 UTC
