### ISSUE TITLE
Window size

### ISSUE THREAD

**Issue by roaxial** [sumatrapdfreader/sumatrapdf#3635] opened 2023-09-03 20:52 UTC
The window can't be resized to below about 650 pixels across, despite the content of the pdfs remaining legibale at significantly smaller widths. this results in a lot of wasted screen space when using multiple applications side by side

**Comment by GitHubRulesOK** [comment] 2023-09-03 23:08
It should be less e.g. 450 I think, but can stick in some odd cases so see this discussion https://github.com/sumatrapdfreader/sumatrapdf/discussions/3109#discussioncomment-4268015

For me currently it is 466

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/65034685-9018-4655-ab6c-44dbe4464449)


Closing this issue as it will be a duplicate of any other where the minimal  sidebar  setting is not  returning to 150

**Closed by GitHubRulesOK** 2023-09-03 23:08 UTC
