### ISSUE TITLE
Can't define SumatraPDF as the predefined program for EPUB

### ISSUE THREAD

**Issue by fennelsgi** [sumatrapdfreader/sumatrapdf#174] opened 2015-04-21 15:57 UTC
I use Windows 7 32-bit. I had Sumatra 2.4 as my default .epub reader. Since upgrading to the 3.0 version (with the installer), I can open the ebook files using the open function in Sumatra, but I can no longer open them directly (with double click). I try to choice Sumatra as the default program for .epub files: I select it, but after that the Sumatra icon do not appear in the list of programs that may used and the former association with other program is not changed.
I have uninstalled Sumatra 3.0 and installed again the 2.4 version and the association Sumatra/.epub becomes again possible.
Thank you

**Comment by GitHubRulesOK** [comment] 2019-11-16 11:25
@kjk there should be two open issues with file association
1) range of file types supported during install and
2) inability to force default association
 this one is a duplicate of the later https://github.com/sumatrapdfreader/sumatrapdf/issues/615#

**Comment by kjk** [comment] 2019-11-18 00:35
This is now tracked by #1248

**Closed by kjk** 2019-11-18 00:35 UTC
