### ISSUE TITLE
Continuous view with more than two pages wide

### ISSUE THREAD

**Issue by oucil** [sumatrapdfreader/sumatrapdf#2952] opened 2022-09-12 13:14 UTC
In my work flow, when I'm reviewing presentations, quotes, manuals, anything really, I need to be able to see more pages on screen than the two that Sumatra currently allows for.  Sumatra is great, but this one shortcoming actually slows down my productivity.  LibreOffice for instance allows an infinite zoom where the further out I scroll, it simply fits more rows and columns of pages on the screen.  This is ideal and depending on the size of screen you have, you can still have legible documents packed in within the view.

**Comment by GitHubRulesOK** [comment] 2022-09-12 14:15
hmm you can have continuous view of all page and if using a tablet rotated all pages will be scrollable left to right or (vice versa) not so simple on a laptop, 
![image](https://user-images.githubusercontent.com/12754913/189676725-af400c17-b429-42c7-89a7-7128eb5a97f3.png)


**somewhere I showed how you could see 3 pages or 4 pages wide** by temporary convert current file to 9 up or 4 up but it is a hack only fit for presentation users.

As it stands SumatraPDF can display 2 x 2 pages no problem but so much depends on using a suitable rotated screen as found in a publishing house or my old monitor turned on its side with a brick. 
![image](https://user-images.githubusercontent.com/12754913/189675874-fffcc8ee-46ce-445a-a3aa-a041106480d6.png)

**Comment by GitHubRulesOK** [comment] 2023-10-20 11:19
closing as a duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/246 and https://github.com/sumatrapdfreader/sumatrapdf/issues/1171

**Closed by GitHubRulesOK** 2023-10-20 11:19 UTC
