### ISSUE TITLE
Find/search doesn't work unless spaces are put between characters

### ISSUE THREAD

**Issue by Axel-Shark** [sumatrapdfreader/sumatrapdf#1651] opened 2020-06-30 18:38 UTC
Tried this in several different PDFs in Sumatra against Adobe. While the on-screen rendering appears ok, if you try searching for a word as displayed (eg "initalizer"), nothing will be found. If you type "i n i t a l i z e r" into the search it'll find it without a problem. When copying-&-pasting text, spaces are placed between characters.

**Comment by GitHubRulesOK** [comment] 2020-06-30 20:20
Known problem with several open issues (since the freetype update last year) generally occurs with some sources (PDFLaTeX, or OCR) that have unconventional character spacing should/may be fixed when thats next updated.
I know its not an ideal workaround but if searching (rather than reading) is an important feature you could temporarily add a portable version 3.1.2 (uses a more robust freetype version) as an external viewer until this issue is fixed.

**Comment by GitHubRulesOK** [comment] 2020-06-30 23:05
Without samples such as those supplied with https://github.com/sumatrapdfreader/sumatrapdf/issues/1561 or https://github.com/sumatrapdfreader/sumatrapdf/issues/1505 or Problem copying text from PDFs #544
I am "guessing" it is a duplicate of one of the above

**Closed by GitHubRulesOK** 2020-06-30 23:05 UTC
