### ISSUE TITLE
Scrolling through a folder of pdfs

### ISSUE THREAD

**Issue by musm** [sumatrapdfreader/sumatrapdf#1161] opened 2019-04-30 02:36 UTC
Suppose you have a folder of pdfs each being a figure. I'd like to open one of these pdfs and then by using the mouse scrollbar or left and right  keys  flick through the other pdfs in the folder, similar to windows photo viewer.

**Comment by GitHubRulesOK** [comment] 2019-04-30 03:32
@musm there are shifted left & right control keys for navigating next/previous file
@kjk possible duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/351

**Comment by musm** [comment] 2019-04-30 03:39
`Ctrl +Shift ` then left or right seems to work

**Comment by musm** [comment] 2019-04-30 03:39
however, it does seem to reset the window size after scrolling several pdfs, not sure why.

**Comment by GitHubRulesOK** [comment] 2020-02-04 23:59
Closing this issue as "shortcuts working by design", however on re-testing I will open a fresh issue about erroneous file handling

**Closed by GitHubRulesOK** 2020-02-04 23:59 UTC
