### ISSUE TITLE
Print comes out garbled on Canon imagerunner advance c5535i with v3.2 64-bit 

### ISSUE THREAD

**Issue by AreGranhaug** [sumatrapdfreader/sumatrapdf#1762] opened 2020-09-18 05:32 UTC
![Screenshot 2020-09-18 072912](https://user-images.githubusercontent.com/32803298/93559706-b077e900-f980-11ea-8059-f55819d87007.jpg)

Every PDF comes out like this. I have to use a different PDF reader to print PDF's, and then it works fine, with the same documents that come out garbled on Sumatra PDF.

No errors. The PDF looks fine in on the monitor using Sumatra PDF. It's just the prints that come out like this.

Sumatra v3.2 64-bit 
Windows 10 64-bit
Canon imagerunner advance c5535i

**Comment by GitHubRulesOK** [comment] 2020-09-18 08:07
Unfortunatly a long time problem with Xerox/Cannon/Sharp/HP/Richo business print drivers not seen on simpler printers. (may be PCL related?)
Stock suggestions are to check any optimisation settings
or try earlier SumatraPDF 3.0 for printing workflows (ensure "print as image" is OFF, since print as image is the only current method).

Am closing as a duplicate of **White horizontal straps on print-outs** #919 
However please provide feedback of your findings testing above.

**Closed by GitHubRulesOK** 2020-09-18 08:07 UTC
