### ISSUE TITLE
Support AcroForm forms

### ISSUE THREAD

**Issue by sebma** [sumatrapdfreader/sumatrapdf#2141] opened 2021-08-25 20:52 UTC
Hi,

Can you please add AcroForm form support to sumatrapdf ?

**Comment by GitHubRulesOK** [comment] 2024-03-20 01:35
closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1249

**Closed by GitHubRulesOK** 2024-03-20 01:35 UTC
