### ISSUE TITLE
Allow to select the whole word on double click on words that contain dots or commas.

### ISSUE THREAD

**Issue by ANTONIOPSD** [sumatrapdfreader/sumatrapdf#4044] opened 2024-01-24 13:14 UTC
When double-clicking on text with commas or dots, the selected part doesn't include the text after the comma or dot.

It works on Adobe Reader.

Let's take "ETT12.01" as an example. If I double-click on "ETT", I expect to select the whole word "ETT12.01" but currently it only selects "ETT12"

Could there be a feature where users can switch between partial selection and full selection? Maybe triple clicking, a key or an option in the settings could do the trick. This would give users more control over how they select text.

Thanks!

Related:

https://github.com/sumatrapdfreader/sumatrapdf/issues/2504

**Comment by GitHubRulesOK** [comment] 2024-01-24 13:26
closing as duplicate of #2504

**Closed by GitHubRulesOK** 2024-01-24 13:26 UTC

**Comment by GitHubRulesOK** [comment] 2024-01-25 13:25
I added a comment (ping developer) on old thread but with nobody working on that aspect I have no idea if MuPDF or SumatraPDF will make any changes, it may be a few years to get any update, but that's why #2504 is kept open.
