### ISSUE TITLE
EPUB hyphenation

### ISSUE THREAD

**Issue by lanes1** [sumatrapdfreader/sumatrapdf#241] opened 2015-07-17 10:10 UTC
I find it really annoying, so I copy here issue no 2738 from the old google code tracker. The problem is that the program should not make the possible hyphenation marks visible (UTF8 character C2 AD) when UseFixedPageUI is set to false in the advanced options.
Example EPUB file: http://wolnelektury.pl/media/book/epub/sienkiewicz-sachem.epub

**Comment by ousia** [comment] 2015-07-19 11:10
@lanes1, isn’t it the soft hyphen (`&shy;`)?

**Comment by lanes1** [comment] 2015-08-24 09:49
It is.

**Comment by lanes1** [comment] 2015-08-24 09:50
It is

**Comment by ousia** [comment] 2015-08-24 13:34
The issue is about the wrong display of `&shy;` in ePub files, not about hyphenation in general.

**Comment by lanes1** [comment] 2015-10-26 06:00
First of all, thank you for correcting this annoying bug. However the problem still exists in the bookmarks area.

**Comment by GitHubRulesOK** [comment] 2020-07-16 11:02
@kjk 
I cannot see any evidence of above described misbehaviour in 3.1.2 or 3.2 ?

**Comment by ousia** [comment] 2020-07-16 15:09
@lanes1,

I would say that discretionary hyphen is out of the scope of bookmarks, since they aren’t intended to build a paragraph.

BTW, have you checked that the bookmarks contain the `&shy;` character? It would be a total surprise for me. 

@kjk & @GitHubRulesOK,

the issue was fixed in MuPDF a while ago ([this commit](https://git.ghostscript.com/?p=mupdf.git;a=commit;h=ca4af51ba401595acc76cecc8d6c0cc2c4cf6711)).

**Comment by GitHubRulesOK** [comment] 2020-07-16 21:38
@ousia , thanks
Since we have no example of an ongoing issue within current SumatraPDF (epub engine) and your link suggests switching to MuPDF should not show a similar situation, I am closing till proven otherwise.

**Closed by GitHubRulesOK** 2020-07-16 21:38 UTC
Labels: ebook
