### ISSUE TITLE
cannot open google pdf

### ISSUE THREAD

**Issue by pdedek** [sumatrapdfreader/sumatrapdf#4661] opened 2024-11-26 07:18 UTC
**SumatraPDF version**
- Latest SumatraPDF pre-release build version 16779, built on 2024-08-23,

**Describe the bug**
cannot open google pdf invoice
[5061276147-1.pdf](https://github.com/user-attachments/files/17914508/5061276147-1.pdf)

**Comment by GitHubRulesOK** [comment] 2024-11-26 10:35
This was a known problem with the way they write odd header at start of PDF.
It was corrected in recent as yet unsigned (unpublished) Pre-releases so not in current offering.
I will close as duplicate of previously closed https://github.com/sumatrapdfreader/sumatrapdf/issues/4514
but you will need to await next published version (perhaps this week or next ?)
![image](https://github.com/user-attachments/assets/c7ac4d4f-e1ed-415f-86d2-6927ef5e5011)

**Closed by GitHubRulesOK** 2024-11-26 10:35 UTC

**Comment by GitHubRulesOK** [comment] 2024-11-29 01:09
@kjk I dont know if you absorbed or did different but MuPDF has apparently now allowed for such cases see https://bugs.ghostscript.com/show_bug.cgi?id=708056
