### ISSUE TITLE
Advanced Search Feature

### ISSUE THREAD

**Issue by WongUrip** [sumatrapdfreader/sumatrapdf#2935] opened 2022-09-05 07:24 UTC
![FireShot Capture 038 - Sumatra PDF - Advanced Search _ software - www reddit com](https://user-images.githubusercontent.com/112851804/188391786-eb1fd354-0b22-4e46-a996-8b42c0e33912.png)

Is it possible to add this feature? Surely this feature will be really helpful.

**Comment by GitHubRulesOK** [comment] 2022-09-05 13:59
Duplicate of 
https://github.com/sumatrapdfreader/sumatrapdf/issues/154

Its not that simple see related
https://github.com/sumatrapdfreader/sumatrapdf/issues/217 https://github.com/sumatrapdfreader/sumatrapdf/issues/544 https://github.com/sumatrapdfreader/sumatrapdf/issues/804 https://github.com/sumatrapdfreader/sumatrapdf/issues/893 https://github.com/sumatrapdfreader/sumatrapdf/issues/933 https://github.com/sumatrapdfreader/sumatrapdf/issues/943 https://github.com/sumatrapdfreader/sumatrapdf/issues/995 https://github.com/sumatrapdfreader/sumatrapdf/issues/1189 https://github.com/sumatrapdfreader/sumatrapdf/issues/1649 https://github.com/sumatrapdfreader/sumatrapdf/issues/1870 https://github.com/sumatrapdfreader/sumatrapdf/issues/2302  https://github.com/sumatrapdfreader/sumatrapdf/issues/2357 https://github.com/sumatrapdfreader/sumatrapdf/issues/2376 https://github.com/sumatrapdfreader/sumatrapdf/issues/2410 https://github.com/sumatrapdfreader/sumatrapdf/issues/2631 https://github.com/sumatrapdfreader/sumatrapdf/issues/2655

**Closed by GitHubRulesOK** 2022-09-05 13:59 UTC
