### ISSUE TITLE
Add option to make Toolbar Buttons larger

### ISSUE THREAD

**Issue by karthikgopalakrishnan** [sumatrapdfreader/sumatrapdf#2319] opened 2022-02-05 04:22 UTC
On small-screen tablets, the Toolbar Buttons are too small, making it hard to use with the touch-screen. Adding an option to make the Toolbar Buttons larger would resolve this issue. An option in SumatraPDF-settings.txt should be acceptable.

**Comment by GitHubRulesOK** [comment] 2022-02-05 11:19
Note this was possible with bitmap icon fixed interface, and I will sometimes use my tablet older versions 3.12 or 3.2. clearly this is a workaround since newer 3.3 features will be missing but the one portable exe is low overhead for such occasions.

There are multiple examples in github and old forum use `toolbar_11.bmp` as search term 

closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1519

**Closed by GitHubRulesOK** 2022-02-05 11:19 UTC

**Comment by kjk** [comment] 2022-02-05 14:23
Well, in 3.3 the toolbar size is adjusted by DPI so  it should be more or less the same physical size on all screens

**Comment by GitHubRulesOK** [comment] 2022-02-05 14:52
@kjk the small problem is high res small factor (high dpi) 
thus the icons are visually smaller then may be pressed by my old chubby fingers
there is no easy solution for a single already full ribbon
but by fiddling scale I can accept the quality might be inferior or the annotation warning be "off-screen"

**Comment by GitHubRulesOK** [comment] 2022-04-17 00:28
@karthikgopalakrishnan 

Now possible in pre-release 3.4.14458
ToolbarSize = 36

**Comment by kgopal3-intel** [comment] 2022-04-17 04:05
Verified that it works perfectly. Thank you!!!

**Comment by karthikgopalakrishnan** [comment] 2022-04-17 04:06
Verified that this works perfectly. Thank you!!!
