### ISSUE TITLE
cbr files encoded with rar v5.0 don't open

### ISSUE THREAD

**Issue by amesman** [sumatrapdfreader/sumatrapdf#1215] opened 2019-10-09 10:58 UTC
cbr files encoded with a lower version (e.g. rar v2.9) do open properly, but files encoded with rar v5.0 won't open (message simply says "Error loading <filename>.cbr")

**Comment by SumatraPeter** [comment] 2019-10-09 12:20
Read the following comment for the solution: https://github.com/sumatrapdfreader/sumatrapdf/issues/1032#issuecomment-396040094

@kjk: Duplicate of #1032, #1191 etc.

**Comment by kjk** [comment] 2019-10-09 20:33
Closing as dup of #1032 1032

**Closed by kjk** 2019-10-09 20:33 UTC
