### ISSUE TITLE
In LaTEX-made PDF search not works because of added spaces between characters

### ISSUE THREAD

**Issue by desk7** [sumatrapdfreader/sumatrapdf#1526] opened 2020-03-27 21:08 UTC
In PDFs made by LaTEX search function not works. For example, if PDF contains the word "Example" and I search for "Example" it finds nothing. It finds occurrences only if I search for "E x a m p l e", with characters separated by spaces.
The bug occurs in SumatraPDF 3.2 64bit portable for Windows. It doesn't occur in SumatraPDF 3.1.2 64bit portable for Windows.
Probably linked to #1505.

**Comment by GitHubRulesOK** [comment] 2020-03-27 21:41
duplicate of #1505

**Closed by GitHubRulesOK** 2020-03-27 21:41 UTC
