### ISSUE TITLE
Two SumatraPDF in Control Panel

### ISSUE THREAD

**Issue by skipik** [sumatrapdfreader/sumatrapdf#1339] opened 2019-12-20 14:07 UTC
Steps to reproduce:

1. Install SumatraPDF via installer to Program Files\SumatraPDF
2. Update it via installer to a newer build

Actual behavior:

There will be 2 SumatraPDF in Control Panel
![111](https://user-images.githubusercontent.com/24621645/71260086-0b75a480-234b-11ea-8d5a-3be412bf468a.png)

Expected behavior:

There will be only one SumatraPDF in Control Panel

**Comment by skipik** [comment] 2019-12-20 14:13
I think there's a bug in Installer.
Am I the only one with such problem?

**Comment by GitHubRulesOK** [comment] 2019-12-20 14:40
No you are not alone
This seems to be a problem across most recent builds unsure which version 
I had not reported as I usually over install thus in that case may be an expected result
I just uninstalled all versions and reinstalled one
@kjk I can confirm as showing two uninstaller icons for version 3.2.11737

**Comment by SumatraPeter** [comment] 2019-12-20 19:24
@kjk: Can consolidate by closing either this one or #1328 as a duplicate.

**Comment by GitHubRulesOK** [comment] 2019-12-20 21:03
@kjk appears to be closed 
showing only one install of 3.2.11742

**Comment by kjk** [comment] 2019-12-20 21:10
Yes, should be fixed in 11742 or later.

**Closed by kjk** 2019-12-20 21:10 UTC
