### ISSUE TITLE
Tab Navigator Blocks Last Tab Close Button

### ISSUE THREAD

**Issue by Xashyar** [sumatrapdfreader/sumatrapdf#1094] opened 2018-11-09 21:10 UTC
there is no way u can close the last tab:

![image](https://user-images.githubusercontent.com/34171942/48288089-3de27c00-e480-11e8-8585-d5f6d58d0c34.png)
----
![image](https://user-images.githubusercontent.com/34171942/48288117-4c309800-e480-11e8-9f1c-733b168cb6dc.png)
----

Sumatra Version: 3.2.11063
OS: Windows 10 1809
Screen: High DPI (3820x2160p, 250% Scaling)

**Comment by GitHubRulesOK** [comment] 2018-11-10 00:08
@kjk likely duplicate of Windows Scaling issue https://github.com/sumatrapdfreader/sumatrapdf/issues/447

**Comment by Xashyar** [comment] 2018-11-10 05:06
> 
> 
> @kjk likely duplicate of Windows Scaling issue #447

@GitHubRulesOK 
Yeah it's the same, does it only happen on High Res screens?

**Comment by GitHubRulesOK** [comment] 2018-11-10 13:16
This seems to only be noticed with scaling set to more than 100 and a large number of tabs and will potentially disappear if you open or close one. The tabs have to adjust in the measured space with a constant that works at 100% but due to rounding at larger values that allowance is probably not conservative enough. I have not tested pre-release feature of tab width but guess it does not make any significant difference as the underlying calc will still be rounded up to be too wide at some time. @kjk The answer is possibly to increase the tolerance thus reduce the space set aside for tabs.

**Comment by perina** [comment] 2019-01-21 02:16
@GitHubRulesOK This is happening in any scale for me. On hi-res monitor 3000x2000 px m Win10. The problem is the location of the Navigator bar - perhaps shifting is a little left would solve the problem as the closing button X would stay exposed. Or tottaly relocation the Navigation bar to far left as the issue is logical - you;re most likely to close the latest document - and that's the one on very right having issue with.

**Comment by kjk** [comment] 2019-11-07 22:57
Closing as duplicate of #447

**Closed by kjk** 2019-11-07 22:57 UTC
