### ISSUE TITLE
Need to implement .JXL support

### ISSUE THREAD

**Issue by Vonarak08** [sumatrapdfreader/sumatrapdf#4729] opened 2024-12-20 12:42 UTC
got some .cbz, the picture format inside was .jxl. Sumatra pdf was unable to read the jxl files

**Comment by GitHubRulesOK** [comment] 2024-12-20 16:08
jxl has been discussed before so will close if this is similar

**Comment by GitHubRulesOK** [comment] 2024-12-20 16:11
Ah here it is the status was
 `Feedback from MuPDF is currently "RESOLVED WONTFIX"`

but will leave that open and close this as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1943

**Closed by GitHubRulesOK** 2024-12-20 16:11 UTC
