### ISSUE TITLE
No issues at all!

### ISSUE THREAD

**Issue by tadkaliszewski** [sumatrapdfreader/sumatrapdf#631] opened 2016-10-06 13:21 UTC
Hi there

I must say this. Sumatra pdf is everything I've dreamed about when I was using other heavy famous readers.

You've just read my mind and created a perfect lightweight reader. It is basically perfet out of the box. 

Continue pages scroll perfectly, zoom stays as is selected even efter I click a bookmark. No mees on the screen. At least those basic features they should have correctly handle like you have done.

The only thing I would add is a 'tooltip' over tabs. Often my PDF have long names and I can;t see what the full titles are.

Congratulations.

Cheers

**Comment by SumatraPeter** [comment] 2016-10-06 17:28
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/336

**Closed** 2016-10-06 18:18 UTC
