### ISSUE TITLE
How to disable all shortcut keys

### ISSUE THREAD

**Issue by GithubABCDEFG** [sumatrapdfreader/sumatrapdf#1779] opened 2020-10-15 08:12 UTC
I want to say, it's really too bad, why do you set countless shortcut keys? which will cause serious conflicts, and that damn collection. I hope the simpler the software, the better, any additional functions are stupid.
Please tell me how to disable all of Shortcut keys?

**Comment by SumatraPeter** [comment] 2020-10-16 02:40
🙄 Most of us find the keyboard shortcuts to be extremely useful.

A few possible solutions for you (that you'll need to figure out on your own):

1. Modify the source and compile.
2. Write an AutoHotkey script or similar that will disable the shortcuts while Sumatra is active.

@kjk: Duplicate of #1719.

**Comment by GitHubRulesOK** [comment] 2020-10-16 23:25
@SumatraPeter Thanks (was worried to not see you chasing me, past fortnight, glad you'r about again)
Agreed duplicate

**Closed by GitHubRulesOK** 2020-10-16 23:25 UTC

**Comment by SumatraPeter** [comment] 2020-10-17 03:03
@GitHubRulesOK: Thanks; Real Life™ issues kept me mostly offline, so glad to be back with lots of catching up to do everywhere!

**Comment by novocaiin** [comment] 2026-04-06 03:58
I've achieved this by putting the following in my *SumatraPDF-settings.txt* inside `Shortcuts`:
```
	[
		Cmd = CmdNone
		Key = Ctrl + 0
	]
	[
		Cmd = CmdNone
		Key = Ctrl + 1
	]
	[
		Cmd = CmdNone
		Key = Ctrl + 2
	]
	[
		Cmd = CmdNone
		Key = Ctrl + 3
	]
	[
		Cmd = CmdNone
		Key = Ctrl + 6
	]
	[
		Cmd = CmdNone
		Key = Ctrl + 7
	]
	[
		Cmd = CmdNone
		Key = Ctrl + 8
	]
	[
		Cmd = CmdNone
		Key = Ctrl + A
	]
	[
		Cmd = CmdNone
		Key = Ctrl + Add
	]
	[
		Cmd = CmdNone
		Key = Ctrl + B
	]
	[
		Cmd = CmdNone
		Key = Ctrl + C
	]
	[
		Cmd = CmdNone
		Key = Ctrl + D
	]
	[
		Cmd = CmdNone
		Key = Ctrl + Down
	]
	[
		Cmd = CmdNone
		Key = Ctrl + End
	]
	[
		Cmd = CmdNone
		Key = Ctrl + F
	]
	[
		Cmd = CmdNone
		Key = Ctrl + F3
	]
	[
		Cmd = CmdNone
		Key = Ctrl + F4
	]
	[
		Cmd = CmdNone
		Key = Ctrl + G
	]
	[
		Cmd = CmdNone
		Key = Ctrl + Home
	]
	[
		Cmd = CmdNone
		Key = Ctrl + Insert
	]
	[
		Cmd = CmdNone
		Key = Ctrl + K
	]
	[
		Cmd = CmdNone
		Key = Ctrl + L
	]
	[
		Cmd = CmdNone
		Key = Ctrl + N
	]
	[
		Cmd = CmdNone
		Key = Ctrl + O
	]
	[
		Cmd = CmdNone
		Key = Ctrl + P
	]
	[
		Cmd = CmdNone
		Key = Ctrl + PageDown
	]
	[
		Cmd = CmdNone
		Key = Ctrl + PageUp
	]
	[
		Cmd = CmdNone
		Key = Ctrl + Q
	]
	[
		Cmd = CmdNone
		Key = Ctrl + S
	]
	[
		Cmd = CmdNone
		Key = Ctrl + Shift + PageDown
	]
	[
		Cmd = CmdNone
		Key = Ctrl + Shift + PageUp
	]
	[
		Cmd = CmdNone
		Key = Ctrl + Shift + Tab
	]
	[
		Cmd = CmdNone
		Key = Ctrl + Subtract
	]
	[
		Cmd = CmdNone
		Key = Ctrl + Tab
	]
	[
		Cmd = CmdNone
		Key = Ctrl + Up
	]
	[
		Cmd = CmdNone
		Key = Ctrl + W
	]
	[
		Cmd = CmdNone
		Key = Ctrl + Y
	]
	[
		Cmd = CmdNone
		Key = Shift + Backspace
	]
	[
		Cmd = CmdNone
		Key = Shift + Ctrl + Add
	]
	[
		Cmd = CmdNone
		Key = Shift + Ctrl + F3
	]
	[
		Cmd = CmdNone
		Key = Shift + Ctrl + L
	]
	[
		Cmd = CmdNone
		Key = Shift + Ctrl + Left
	]
	[
		Cmd = CmdNone
		Key = Shift + Ctrl + N
	]
	[
		Cmd = CmdNone
		Key = Shift + Ctrl + Right
	]
	[
		Cmd = CmdNone
		Key = Shift + Ctrl + S
	]
	[
		Cmd = CmdNone
		Key = Shift + Ctrl + Subtract
	]
	[
		Cmd = CmdNone
		Key = Shift + Ctrl + T
	]
	[
		Cmd = CmdNone
		Key = Shift + Down
	]
	[
		Cmd = CmdNone
		Key = Shift + F11
	]
	[
		Cmd = CmdNone
		Key = Shift + F12
	]
	[
		Cmd = CmdNone
		Key = Shift + F3
	]
	[
		Cmd = CmdNone
		Key = Shift + i
	]
	[
		Cmd = CmdNone
		Key = Shift + Left
	]
	[
		Cmd = CmdNone
		Key = Shift + Return
	]
	[
		Cmd = CmdNone
		Key = Shift + Right
	]
	[
		Cmd = CmdNone
		Key = Shift + Space
	]
	[
		Cmd = CmdNone
		Key = Shift + Up
	]
	[
		Cmd = CmdNone
		Key = Alt + Left
	]
	[
		Cmd = CmdNone
		Key = Alt + Right
	]
	[
		Cmd = CmdNone
		Key = Backspace
	]
	[
		Cmd = CmdNone
		Key = Space
	]
	[
		Cmd = CmdNone
		Key = Delete
	]
	[
		Cmd = CmdNone
		Key = Up
	]
	[
		Cmd = CmdNone
		Key = Down
	]
	[
		Cmd = CmdNone
		Key = End
	]
	[
		Cmd = CmdNone
		Key = Home
	]
	[
		Cmd = CmdNone
		Key = Left
	]
	[
		Cmd = CmdNone
		Key = PageDown
	]
	[
		Cmd = CmdNone
		Key = PageUp
	]
	[
		Cmd = CmdNone
		Key = Return
	]
	[
		Cmd = CmdNone
		Key = Right
	]
	[
		Cmd = CmdNone
		Key = F1
	]
	[
		Cmd = CmdNone
		Key = F2
	]
	[
		Cmd = CmdNone
		Key = F3
	]
	[
		Cmd = CmdNone
		Key = F5
	]
	[
		Cmd = CmdNone
		Key = F6
	]
	[
		Cmd = CmdNone
		Key = F8
	]
	[
		Cmd = CmdNone
		Key = F9
	]
	[
		Cmd = CmdNone
		Key = F11
	]
	[
		Cmd = CmdNone
		Key = F12
	]
	[
		Cmd = CmdNone
		Key = a
	]
	[
		Cmd = CmdNone
		Key = A
	]
	[
		Cmd = CmdNone
		Key = c
	]
	[
		Cmd = CmdNone
		Key = f
	]
	[
		Cmd = CmdNone
		Key = g
	]
	[
		Cmd = CmdNone
		Key = h
	]
	[
		Cmd = CmdNone
		Key = i
	]
	[
		Cmd = CmdNone
		Key = j
	]
	[
		Cmd = CmdNone
		Key = k
	]
	[
		Cmd = CmdNone
		Key = l
	]
	[
		Cmd = CmdNone
		Key = m
	]
	[
		Cmd = CmdNone
		Key = n
	]
	[
		Cmd = CmdNone
		Key = p
	]
	[
		Cmd = CmdNone
		Key = q
	]
	[
		Cmd = CmdNone
		Key = r
	]
	[
		Cmd = CmdNone
		Key = u
	]
	[
		Cmd = CmdNone
		Key = U
	]
	[
		Cmd = CmdNone
		Key = w
	]
	[
		Cmd = CmdNone
		Key = z
	]
	[
		Cmd = CmdNone
		Key = .
	]
	[
		Cmd = CmdNone
		Key = [
	]
	[
		Cmd = CmdNone
		Key = ]
	]
```
I based it on https://raw.githubusercontent.com/sumatrapdfreader/sumatrapdf/refs/heads/master/docs/md/Keyboard-shortcuts.md
