### ISSUE TITLE
[v3.4.13894 pre-release] problem with colors in UI and bookmark when color-inverted mode

### ISSUE THREAD

**Issue by yuishin-kikuchi** [sumatrapdfreader/sumatrapdf#2071] opened 2021-07-29 01:54 UTC
![3 4-prerelease-color-inveted](https://user-images.githubusercontent.com/24489828/127419223-2eb720c2-830f-4204-85c8-22f6da8fd710.png)
I found v3.4 prerelease supports color-inverted mode and tried but colors in UI/bookmark is strange.
(I opened PDF file and typed i to invert colors and r to reload)

When inverted mode...
1. The texts in above toolbar are colored in white (inverted), so I cannot read.
2. The background color of bookmark bar turns to black (inverted)
3. and color of texts in bookmark bar is white (inverted)
4. but ones of selected items and arrows in the tree remains.
(partially not inverted so I cannot read some because the bg is black)

Is there any way to specify colors when color-inverted mode?
Or any way to fix colors regardless of modes?

**Comment by GitHubRulesOK** [comment] 2021-07-29 03:05
Not a pre-release Issue, That issue has been there in one form or another
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1904#

Part of theming issue #79 & #794

**Closed by GitHubRulesOK** 2021-07-29 03:05 UTC
