### ISSUE TITLE
Dark Content

### ISSUE THREAD

**Issue by Mike-Reddick** [sumatrapdfreader/sumatrapdf#1450] opened 2020-02-05 12:40 UTC
Please add and Dark Mode to change colors of content text, links, backgrounds etc, with customizable colors and a button and keyboard shortcut toggles. And setting to choose the UI colors. Thanks!

**Comment by GitHubRulesOK** [comment] 2020-02-05 13:39
Closing as duplicate of multiple other requests
For discussions on theming see #1275 #437 #743 #898

**Closed by GitHubRulesOK** 2020-02-05 13:39 UTC
