### ISSUE TITLE
Dark theme improvements

### ISSUE THREAD

**Issue by Gitoffthelawn** [sumatrapdfreader/sumatrapdf#2738] opened 2022-06-18 21:16 UTC
When using a dark Windows 7 theme, Sumatra v3.4.6 has some issues (see [this screenshot](https://ibb.co/hBjBWQR) and [this one](https://ibb.co/MRFGGxC)):

1. The toolbar icons are very hard to discern.
2. The tabs do not honour the theme colours.
3. The `About` dialog box and default Sumatra opening screen are not legible.

**Comment by GitHubRulesOK** [comment] 2022-06-18 22:50
experimenta themes were dropped a very long time ago so widows 7 (dead) had some effects such as your blue header, but current win 11 has very little its like white cows in a snow field unless using some high contrast settings,

- new black vector icons should be dark grey on light grey fields
- there are no theme colours in 3.4.6
- windows main colour background is for mid to light contrast you should not invert the UI colors only the paper as required.
- Did I say there is no longer theming ?

**Comment by GitHubRulesOK** [comment] 2022-06-18 23:09
Effective Duplicate of status in March 2017 https://github.com/sumatrapdfreader/sumatrapdf/issues/743 inter related to 
https://github.com/sumatrapdfreader/sumatrapdf/issues/559
https://github.com/sumatrapdfreader/sumatrapdf/issues/898
https://github.com/sumatrapdfreader/sumatrapdf/issues/1275 
https://github.com/sumatrapdfreader/sumatrapdf/issues/2048
https://github.com/sumatrapdfreader/sumatrapdf/issues/2224
https://github.com/sumatrapdfreader/sumatrapdf/issues/2320
https://github.com/sumatrapdfreader/sumatrapdf/discussions/2335
https://github.com/sumatrapdfreader/sumatrapdf/discussions/2360
https://github.com/sumatrapdfreader/sumatrapdf/discussions/2441
https://github.com/sumatrapdfreader/sumatrapdf/discussions/2475 
https://github.com/sumatrapdfreader/sumatrapdf/discussions/2552
https://github.com/sumatrapdfreader/sumatrapdf/discussions/2555

**Comment by Gitoffthelawn** [comment] 2022-06-19 05:00
I think perhaps the easiest place to start is to use the colours (background and text colours) defined by the Windows theme for the Sumatra tabs.  Because the Sumatra UI is already picking up and using those colours for some of its UI elements, it seems like perhaps a reasonable place to start.

**Comment by GitHubRulesOK** [comment] 2022-06-19 12:10
@Gitoffthelawn 
there is often user confusion due to naming, so others abuse Media TEXT "background and text colours"
   TextColor = #000000
   BackgroundColor = #ffffff"
 
so should not be used as UI colors the reason they are inside the FixedUI settings is historic, different for pdf and ebook
that is often the reason everyone complains color's are "wrong"

The color's for external UI elements such as scrollbars, title panel etc. are controlled by Windows but SumatraPDF has to maintain its own control (that works evenly, across every user system OS and color settings) otherwise its mayhem as seen when sys colors High Contrast is used.

**Comment by GitHubRulesOK** [comment] 2022-09-20 19:46
this is covered by dozens of duplicates so closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/743

**Closed by GitHubRulesOK** 2022-09-20 19:46 UTC
