### ISSUE TITLE
Some Greek letters missing in epub

### ISSUE THREAD

**Issue by PIK54** [sumatrapdfreader/sumatrapdf#442] opened 2016-02-18 09:04 UTC
Hi folks, Just love Sumatra for it's speed, error tolerance etc.
However, I've noticed that at times Sumatra doesn't play nice with some Greek letters. e.g. attached is an English epub document, liberally scattered with vital Greek words. 
When I open this same file using say, Sigil (yeah there are some folk using this great epub editor), it shows all the letters. Open it in Sumatra, and I get a lot of square boxes interspersed with Greek letters... Is this a bug?
Thanks
Peter

**Comment by ousia** [comment] 2016-02-18 15:37
@PIK54, many thanks for your report, but there is an important question.

First and foremost, could you delete link from your and the file from GitHub?

Sorry, I can understand that you didn’t intend that, but I guess that the work is under copyright protection. I’m not a big copyright fan (in fact, I’m the harshest critic of stupid copyright protection or maximalism), but I’m afraid that posting that file is a blatant copyright violation.

Don’t get me wrong. I would like to spare you stupid problems. If you don’t anything, I’m going to sleep as well as before :stuck_out_tongue_winking_eye:.

A better sample file is a public domain text, such as [the works of Homer](https://github.com/ousia/homerus-opera/blob/master/homerus-opera.epub?raw=true).

Either the ePub document includes the file or not, SumatraPDF (either latest stable or pre-release version 10488 [latest development version) doesn’t use another font than the one predefined in the system.

The issue is that the font used by SumatraPDF by default (_Georgia_) only includes glyphs for monotonic Greek (written after 1982) and ancient Greek uses extended or polytonic Greek characters. (Just in case you wonder, polytonic Greek was the official Greek orthography until 1982 and ancient Greek was written until 1453 [modern Greek is also polytonic, only contemporary Greek is monotonic]).

To solve this, edit the file `SumatraPDF-settings.txt` with `notepad.exe` and replace _Georgia_ with any font that includes polytonic Greek. _Tahoma_ or _Palatino Linotype_ include them. I’m afraid I don’t do _Windows_, so I don’t know of any other fonts in that operative system may contain it. The _Noto_ font family also includes them (you may download the fonts [here](https://www.google.com/get/noto/)). In that case, replace _Georgia_ with _Noto_ in `SumatraPDF-settings.txt`.

@kjk, the current git master from mupdf solved the issue with both embedded and not embedded fonts.

With non-embedded fonts, they bundled the _Noto_ font family with mupdf.

And for embedded fonts, they implemented `@font-face` rules ([this commit](http://git.ghostscript.com/?p=mupdf.git;a=commit;h=f501211e904d2c01e47b03e774ffc6f93faeae25)).

I don’t know whether it is feasible do merge that part of code from mupdf. But embedded fonts in ePub documents are a must.

**Comment by PIK54** [comment] 2016-02-18 22:35
That works brilliantly, thank you. For both urging me to remove a link and for suggesting editing the settings file. I plugged in Tahoma rather than go the route of installing Noto (a 471MB install!) and the text forms perfectly. Thanks. Interesting history..

One final question: If I update Sumatra in the future, I presume I will have to edit the SumatraPDF-settings.txt file again?

Peter

**Comment by kjk** [comment] 2016-02-18 22:46
@PIK54 Updates preserve SumatraPDF-settings.txt

@ousia We don't use mupdf's epub functionality (we wrote ours in Sumatra long before they had it). Switching to mupdf's is a possibility or we could extend our implementation with @font-face support.

**Comment by PIK54** [comment] 2016-02-18 22:47
Thanks

**Comment by ousia** [comment] 2016-02-18 23:13
@PIK54, glad to see it worked.

@kjk, you are right, I forgot that ePub code is independent from mupdf. Implementing `@font-face` would be a must.

**Comment by GitHubRulesOK** [comment] 2019-11-22 18:14
@kjk obviously the choice of font for local character support is available to users via advanced settings
However since Georgia is limited and there are fuller fonts now generally available in windows, would it be worth setting default to dare I sugest Calibri for example ?

**Comment by GitHubRulesOK** [comment] 2021-08-15 22:26
@kjk 
I had hoped this was closed by switch to MuPDF and it is so much better

However there is still a noticeable oddity in font handling

I do not know Ancient Greek but the rendering of
**Ῥ**αψωδία A
Μ**ῆ**νιν **ἄ**ειδε, θεά, Πηληιάδεω Ἀχιλῆος
is now missing some key non Latin characters visually
![image](https://user-images.githubusercontent.com/12754913/129494487-78aa0912-7062-490b-a53d-e0ae9f131ebd.png)

**Comment by GitHubRulesOK** [comment] 2023-02-09 17:47
Fixed in https://github.com/sumatrapdfreader/sumatrapdf/issues/3265
![image](https://user-images.githubusercontent.com/12754913/217895736-e772d9a6-7c49-4e69-8d94-1c0a420dcfc8.png)

**Closed by GitHubRulesOK** 2023-02-09 17:47 UTC
Labels: mupdf, ebook
