### ISSUE TITLE
Cannot associate .cbr and .djvu files with SumatraPDF in Windows10 1803

### ISSUE THREAD

**Issue by M2evorah** [sumatrapdfreader/sumatrapdf#1089] opened 2018-11-03 21:27 UTC
Hello!

In Windows10 1803, I cannot associate .cbr and .djvu files.
When I try with either open with and tick on default app for SumatraPDF, Windows10 does not anything and the files keep been unassociated.
I have successfully associated the .pdf files, but not .cbr and .djvu files.
I have also gone to Settings->Apps->Default apps and choose applications by file type but not any luck there either.

**Comment by GitHubRulesOK** [comment] 2018-11-05 21:59
win 10 does not correctly work with "open with"  often offering to use many old failed entries. Looks like a good opportunity for something like the Nirsoft utility associate to let you clean-up poor entries.

You need to Open With CHOOSE ANOTHER app go down to more apps go down to look for another app on this PC find SumatraPDF.exe, that should work for most power users. IF your a basic user you may need to switch to administrator account, and hope it works system wide.

**Comment by GitHubRulesOK** [comment] 2018-11-05 22:08
win 10 does not correctly work with "open with" often offering to use many old failed entries. Looks like a good opportunity for something like an extension to a good associate type tool [Nirsoft fileman utility](http://www.nirsoft.net/utils/file_types_manager.html) but like ccleaner needs to let you clean-up poor entries.
You need to Open With CHOOSE ANOTHER app go down to more apps go down to look for another app on this PC find SumatraPDF.exe, that should work for most power users. IF your a basic user you may need to switch to administrator account, and hope it works system wide.

**Comment by GitHubRulesOK** [comment] 2018-11-05 22:59
@kjk related to win 10 not respecting user requested file associations https://github.com/sumatrapdfreader/sumatrapdf/issues/438, I suggest link and close

**Comment by kjk** [comment] 2018-11-05 23:01
Closing as duplicate of #438

**Closed by kjk** 2018-11-05 23:01 UTC
