### ISSUE TITLE
Unreadable graphics

### ISSUE THREAD

**Issue by bsd04** [sumatrapdfreader/sumatrapdf#812] opened 2017-05-29 08:57 UTC
The graphics on the page 7 are unreadable.
[http://bsd.ee/~kalts/Infineon-FF400R06KE3-DS-v03_00-en_de.pdf](url)

**Comment by GitHubRulesOK** [comment] 2020-07-05 03:06
![image](https://user-images.githubusercontent.com/12754913/86524565-140b7380-be74-11ea-95a0-e93fd89a020c.png)

Closing as duplicate of many similar diagrams from Infineon etc. 
https://forum.sumatrapdfreader.org/t/change-line-widths-e-g-cad-drawings/192/9
https://github.com/sumatrapdfreader/sumatrapdf/issues/982#

**Closed by GitHubRulesOK** 2020-07-05 03:06 UTC
