### ISSUE TITLE
Scaling not correct when printing (64 bit version only)

### ISSUE THREAD

**Issue by sebrandt** [sumatrapdfreader/sumatrapdf#468] opened 2016-03-18 09:50 UTC
When printing a A4 PDF, the page is not correctly scaled and on the right side of the sheet a small part is cut off (SumataPDF 3.1.1 64-bit). I tried reinstalling but had the same result. 
Then I tried the 32 bit version and here everything is fine. This seems to be something specific to the 64 bit version.

**Comment by GitHubRulesOK** [comment] 2021-09-12 22:28
clearing old support issues whilst this did specifically say 3.1.1 there was no driver mentioned or input sample available 

So testing virtual prints from 3.1.1 x32 and x64 using adobe standard document file output was similar bytes and there was no visible shift in position
Oddly there was a difference in file size for an image based file and the 64bit was smaller but cannot see any visible difference.

A fix could only be applicable to current version due to many interim changes in printing however the output (flawed or not ) should not differ as printing method is still similar to 3.1+ and a 64 bit 3.4 virtual print is the same size as 3.1.1 but I still cant see a difference to 32bit output.

I am closing as cannot reproduce a noticeable difference using windows 10 driver in 3.1 or 3.4
Please test with current pre-release and reopen if necessary with a sample and named driver

**Closed by GitHubRulesOK** 2021-09-12 22:28 UTC
