### ISSUE TITLE
Can't open PDF (instant crash)

### ISSUE THREAD

**Issue by PASAf** [sumatrapdfreader/sumatrapdf#582] opened 2016-08-05 21:44 UTC
Here is PDF: http://ge.tt/8RBNP9d2

**Comment by kjk** [comment] 2016-08-05 21:47
Which version of sumatra? 32bit version or 64bit version?

Also, how much memory does the computer have? It looks like a big file so the issue could be running out of memory.

**Comment by PASAf** [comment] 2016-08-05 22:00
v3.1.1 64-bit, portable
Have 16 gigs of RAM, 11 are free.
Here is crash dump: http://ge.tt/9YVWQ9d2

**Comment by PASAf** [comment] 2016-08-05 22:09
By the way I could view it in internal PDF viewer of Firefox without problems.

**Comment by gschenck** [comment] 2016-08-15 07:33
Opens without problem for me (portable 64 bit, v3.2.10529)

**Comment by PASAf** [comment] 2018-01-11 20:51
Rechecked, master version (63c9ce3), still crashes.
Windows 10 LTSB 2015 (10.0.10240) if it matters. And my TEMP placed on ImDisk RamDisk.

Crash dump: http://ge.tt/5NAE84o2

@gschenck did you tried to scroll down till last page?

**Comment by gschenck** [comment] 2018-01-26 09:18
@PASAf I don't remember, so please reshare file and  I will try again.

**Comment by PASAf** [comment] 2018-01-26 09:24
Download it from old link. it still available

**Comment by gschenck** [comment] 2018-01-26 12:31
Tried again, all pages are displayed without problems. 
SumatraPDF v.3.2.10766 64bit

**Comment by GitHubRulesOK** [comment] 2018-06-09 23:36
@kjk 
confirmed this file is still a crash whilst scrolling towards last two pages (59/60)
tested on 32 bit windows 10 1803 (17134.81) using version 3.1.2 both installed and portable 
also crashes other more recent versions such as pre-rel 10156 & 10766 and later :-)
also it caused issues with older GSView version 5

HOWEVER noticed whilst testing with 3.1.1.10417z  (Zeniko commit5d317df) :-)
it did not crash BUT found problems rendering page 60

I suspect there is an issue around page 60 that may causes problems with older MuPDF since all 60 pages render well both in MuPDf 1.13 and newer GSView 6

the file would need deeper analysis towards the last page / EOF for flaws or unsupported features 
I suggest this may be flagged as a MuPDF issue (since format error appears to be handled better in latest version)

**Comment by kjk** [comment] 2019-11-20 09:36
Unfortunately the file is no longer available. If someone has it, please repost. If not, will have to close the issue.

**Comment by GitHubRulesOK** [comment] 2019-11-20 12:24
@kjk I think i have a copy on a test machine but that pc has a mechanical problem that may not be resolved for a day or two perhaps one of the others can upload before then

**Comment by GitHubRulesOK** [comment] 2020-01-01 03:11
@kjk file was 41MB It was a problem with 3.1.2. but has not been a crash since 3.2.11325
This issue can be closed when using recent 3.2 pre-release onwards

**Closed** 2020-01-01 03:35 UTC
