### ISSUE TITLE
Multi-user (system) installation

### ISSUE THREAD

**Issue by byyxx128** [sumatrapdfreader/sumatrapdf#1794] opened 2020-10-27 18:13 UTC
I remembered [Sumatra PDF](https://www.sumatrapdfreader.org/) should be able to install in `%PROGRAMFILES%`. However, it is not now.
https://github.com/sumatrapdfreader/sumatrapdf/issues/1626#issuecomment-646348740

It is obviously a good solution for those who do not have administrator rights. However, it is inconvenient for those who want to install Sumatra PDF for all users' account. I have three ideas about this problem:

1. [Chrome](https://www.google.com/chrome/browser/desktop/index.html) way. If the user has administrator rights, install in `%PROGRAMFILES%` for all users. Otherwise, install in `%LOCALAPPDATA%` for only the current user.
2. [Opera](https://www.opera.com) way. Give an option to choose while installing for all users or just the current user before the installation progress.
3. Release two separate installers, user installer and system installer. Some programs like [VS Code](https://code.visualstudio.com/download) use this way.

Please consider and adopt the best way for you.

**Comment by Pajdzik** [comment] 2021-12-17 18:23
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1643

**Comment by GitHubRulesOK** [comment] 2021-12-17 21:32
@Pajdzik there is a slight difference that one was only about the multi-user method did not place desktop icon into public (all users) desktop, this one is more (but not only) detect install of system dlls requires admin elevation thus should then default to be in program files

**Comment by Pajdzik** [comment] 2021-12-17 21:35
You're right. Removing my comment.

**Comment by kjk** [comment] 2022-04-30 20:51
In latest[ pre-release](https://www.sumatrapdfreader.org/prerelease):
* cmd-line option `-all-users`
* in the installer, a checkbox for `all users`

When installing for `all users`, requires admin privileges and installs to `%PROGRAMFILES%`. Writes registry info to HKLM.

When installing for current user, no admin privileges required, installs to `%LOCALAPPDATA%` and writes registry info to HKCU.

**Closed by kjk** 2022-04-30 20:51 UTC
Labels: installer
