### ISSUE TITLE
Feature request: support tiling tabs

### ISSUE THREAD

**Issue by gylns** [sumatrapdfreader/sumatrapdf#851] opened 2017-07-26 07:40 UTC
It will be convenient to tile two tabs in one window just like the [Tile Tabs](https://addons.mozilla.org/en-US/firefox/addon/tile-tabs/) add-on for firefox.

**Comment by SumatraPeter** [comment] 2017-07-30 01:02
Seems to be a duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/345

**Comment by GitHubRulesOK** [comment] 2020-02-06 18:49
Agreed dead duck link

**Closed by GitHubRulesOK** 2020-02-06 18:49 UTC
