### ISSUE TITLE
Vertical scroll bars

### ISSUE THREAD

**Issue by pmennen** [sumatrapdfreader/sumatrapdf#369] opened 2015-11-30 00:14 UTC
I see that this issue has been discussed before, but I don't think the issue is fully understood. I tried to add this comment in and earlier thread, but then I couldn't find it in the forum, so I'm not sure if it was lost or not. So my apologies if this is a duplicate entry:

Sumatra is the best epub/mobi reader for PCs by a huge margin so I will always use it for that. I had it as my default pdf reader for a while because it was so much faster to load and so much better than adobe acrobat in nearly every respect. Eventually I had to give up on it and go back to acrobat because the lack of a scrollbar made it too frustrating to use when I needed it (which is often actually). Sure you can use the page up/down keyboard buttons or the left/right arrows at the top, but if I just want to scroll to say the middle of the book or near the end and see what is there I would have to type a page number into the page field ... which is plain inconvenient. 

> If we always had vertical scrollbar in single-page 
> view then it would be the same as continuous view, 
> so use continuous view if that's what you want. 

It seems that Krzysztof doesn't quite understand what continuous view is useful for. If the pdf was generated from a text or html document, page boundaries have no significance and you can just as well ignore them using continuous view. However the majority of pdf files were created with the idea that the page is the basic unit making the single page view the most convenient. In this case continuous view is still useful if your screen is too small to comfortably read the whole page or in the less common case when you prefer to see more than a page at once. Since I have a large screen (as most people do these days) I prefer to see the whole page 99% of the time and single page mode is the only way to do this since advancing in continuous mode usually puts the page break somewhere in the middle of the window. I find it hard to imagine that anyone who uses Sumatra PDF on a 24" or bigger display would fail to find the missing scroll bars annoying. Even if I am wrong and only say 10% of the users would use the scroll bars, they take up so little space I see little drawback to providing them. 

~Paul

**Comment by GitHubRulesOK** [comment] 2018-11-05 21:11
@kjk duplicate of closed #191

**Closed** 2018-11-05 21:13 UTC

**Comment by GitHubRulesOK** [comment] 2020-04-06 14:16
Since there seems to be some confusion  over this aspect of comparing SumatraPDF and Acrobat

>  I find it hard to imagine that anyone who uses Sumatra PDF on a 24" or bigger display would fail to find the missing scroll bars annoying. 

YES many aspects are similar as this but not all, if they were then simply just buy acrobat

The way SumatraPDF does it may not be the way you do it in Acrobat,
SumatraPDF scrollbars have hybrid functions so to use scrollbar with single pages forget the terminology **just do it.** 
**Full screen or not** hitting the RH sidebar in the trough (above or below slider) moves one page up or down. The problem as experienced by many fresh users is that they then drag the slider and stop so the gap between pages appears, the solution to reset the page is double click on the single page icon.
