### ISSUE TITLE
some drawing PDF files are displayed incompletely

### ISSUE THREAD

**Issue by whorainzone** [sumatrapdfreader/sumatrapdf#1034] opened 2018-06-20 10:40 UTC
Drawing files from www.blanco.de are displayed only partial in SumatraPDF.
Tested with Version 3.2.10766 and Version 3.1

[subline_500-u_k_un.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/2118879/subline_500-u_k_un.pdf)

![compare](https://user-images.githubusercontent.com/33731038/41653386-2e8f5724-7486-11e8-997e-14722f15025f.png)

**Comment by GitHubRulesOK** [comment] 2018-06-22 14:44
@kjk This is related to / a duplicate of thin line issue
[#982](https://github.com/sumatrapdfreader/sumatrapdf/issues/982)
[#838](https://github.com/sumatrapdfreader/sumatrapdf/issues/838)
[#624](https://github.com/sumatrapdfreader/sumatrapdf/issues/624) ** kjk response
[#398](https://github.com/sumatrapdfreader/sumatrapdf/issues/398)
forum (https://forum.sumatrapdfreader.org/t/almost-invisible-lines/192/1)
forum (https://forum.sumatrapdfreader.org/t/it-is-very-hard-to-read-the-picture-with-this-software/83)

**Comment by GitHubRulesOK** [comment] 2018-07-11 14:47
many cad systems have a default line thickness of 0 width
it is a good CAD operator that ensures it is set to the minimum default as say 0.18 mm for ISO drawings
for commercial use I sometimes import / export drawings to be changed via Acrobat

there is a NOT for commercial use tool that can improve (some but not all) lines to a given value  for home use I usually use thicken to 0.25pt see http://community.coherentpdf.com/

**Comment by thenktor** [comment] 2019-03-11 16:12
Wouldn't it be possible to set a minimum line thickness option in Sumatra?

**Comment by GitHubRulesOK** [comment] 2019-11-15 00:03
@kjk another "thin line" file that is better rendered in latest builds

![Untitled1034](https://user-images.githubusercontent.com/12754913/68906183-63f9c680-073b-11ea-9895-b910d3216dd4.png)

**Comment by kjk** [comment] 2019-11-15 05:22
Thanks @GitHubRulesOK 
Fixed in latest build https://www.sumatrapdfreader.org/dailybuilds.html

**Closed by kjk** 2019-11-15 05:22 UTC
