### ISSUE TITLE
Print speed

### ISSUE THREAD

**Issue by AVR3331** [sumatrapdfreader/sumatrapdf#622] opened 2016-09-26 10:17 UTC
Too bad the print speed is very slow (transfer to the printer) compared to AdobeReader for the same documents. I do not know if it requires the addition of a new feature or a simple setting.

**Comment by madbad** [comment] 2016-09-26 13:11
Hi AVR3331, I had the same issue,
You may resolve the problem by changing in the "adanced settings" the settings called "PrintAsImage" and set it to false.

"""
 PrinterDefaults [
	PrintAsImage = false
]
"""

Unfurtunately this setting/option has been removed in recent versions of Sumatra but is available in the version 3.0 (witch I'm using).
If you want to get an older version of Sumatra look here: https://www.sumatrapdfreader.org/download-prev.html

See issue #373

**Comment by GitHubRulesOK** [comment] 2020-02-29 20:56
Consolidating as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/373

**Closed by GitHubRulesOK** 2020-02-29 20:56 UTC
