### ISSUE TITLE
"Saving" a copy of a document at a new location should make Sumatra from this point on use the copy at the new location

### ISSUE THREAD

**Issue by Pjotrrr** [sumatrapdfreader/sumatrapdf#612] opened 2016-09-11 16:28 UTC
When I "open" some pdf-file from the net, my browser downloads it, puts the downloaded copy in some temp-directory (automatically) and has it opened in Sumatra. 

In order to really save this copy for later use I of course have to save it at a "real" location, because 
a) the browser from time to time deletes files from this temp-directory
b) I would not look for a document at a later time in such a temp-directory but at a place where it belongs to (topic-specific)

So far so good, but there is a "problem" in daily usage of reading through pdf-files. Sumatra keeps information per document of the last state of the document (e.g. the page I was on) when I quit the program.

The next time I start Sumatra it opens all documents which were open the last time and opens them in their own state last recorded. So in the case of pdf-files files downloaded as described above it again opens the docs from the temp-directory (IF they are still there!!). If not, I have to open the doc from the location where I actually saved it from within Sumatra, but of course Sumatra no longer has any information on it about its last state (page opened), because it is a "new" document.

So what I am suggesting is to have a new option in the settings to have Sumatra ask me (or do it automatically) to "switch" from the opened document to the recently saved copy of it at the new location to continue reading/further processing (meaning closing the first file, opening the "new" file in same state as old one).

I hope I was able to convey my point.

**Comment by GitHubRulesOK** [comment] 2020-02-04 18:30
When saving from the web  (or other location) use Rename <kbd>**F2**</kbd> that will by design allow you to navigate from the temporary directory to a preferred location to store the file with any name (with or without the [1]). When you complete the "_save as new name_" then the file is automatically replaced along with the new name in the tab and normal service history is resumed.

Closing as duplicate of #93

**Closed by GitHubRulesOK** 2020-02-04 18:30 UTC

**Comment by Pjotrrr** [comment] 2021-05-02 16:14
dank an vm für den link

https://www.youtube.com/watch?v=LuOu9y-Ilpk
