### ISSUE TITLE
Keeps crashing due to a mobi file (probably)

### ISSUE THREAD

**Issue by hrishikesh-deshpande** [sumatrapdfreader/sumatrapdf#2050] opened 2021-07-23 19:23 UTC
Crashed when I tried to open a couple of mobi files.
Now I cannot open the application as it crashes again as it tries to load the file.

logs :- https://gist.github.com/hrishikesh-deshpande/f0062d1881504f0a9e25f51a125c9cae

If you want the mobi files, let me know.

**Comment by kjk** [comment] 2021-07-23 20:21
Thanks, should be fixed in a build that will be ready in about an hour.

**Closed by kjk** 2021-07-23 20:21 UTC

**Comment by hrishikesh-deshpande** [comment] 2021-07-24 09:02
Thanks for quick reply.
But it still is not working as expected.

Now its not crashing but also not responding (on v3.4.13859 64-bit Pre-release).

I am pretty sure the mobi file is corrupt, but it still shouldn't mess up the application.
Is there any way to give option to abort loading of the file?

link to the mobi file :- https://1lib.in/book/15873647/86f407

**Comment by kjk** [comment] 2021-07-24 10:32
Could you provide more information about when / how often does this happen? How are you opening the file etc.

I tried the linked file with latest code and while there's an occasional memory corruption, I can't reproduce reliable crash / hang with the latest code (13863).

BTW: it's very easy to update to latest version with Help / Check for updates and press "Install and relaunch" button. It'll run the installer for the installed version and overwrite the .exe for portable.

**Comment by kjk** [comment] 2021-07-24 11:02
Please re-check with 13866 (when it's ready). I've fixed an issue and tested with a bunch of files and didn't get a crash or a hang yet.

**Comment by hrishikesh-deshpande** [comment] 2021-07-24 16:10
Sorry for the late reply.

It used to crash every time on my machine when I opened by double-clinking the file as well as browsed the file through the "Open a document" option.

Just installed 13866 and it did not crash. I thought the file was corrupt as it hung my calibre ebook viewer too.
I also rebooted my pc before installing, so if I encounter any problem later, I will let you know, Thanks.

**Comment by GitHubRulesOK** [comment] 2021-07-24 16:20
@hrishikesh-deshpande 
I got a crash with the file (still in 13866) when switching from mobi to fixed view (toggle ebook UI) is it possible you had done something similar ??

**Comment by hrishikesh-deshpande** [comment] 2021-07-24 16:35
Initially I didn't see any change with the UI when I toggled the option.
So, I switched to a pdf file and observed the same thing.
When I checked forum for expected behavior, I noticed that we are supposed to reload it.

So, when I checked the toggle option in the pdf and pressed R, it stopped responding.
I don't think it is related to mobi.
