### ISSUE TITLE
[feature request] Line spacing control for epub.

### ISSUE THREAD

**Issue by metacortexplus** [sumatrapdfreader/sumatrapdf#1785] opened 2020-10-17 17:54 UTC
Please add line spacing control for epub, or set default option to 140% of font size.

**Comment by GitHubRulesOK** [comment] 2020-10-18 21:32
Closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/476#

**Closed by GitHubRulesOK** 2020-10-18 21:32 UTC
