### ISSUE TITLE
Unable to change background color

### ISSUE THREAD

**Issue by shivamkumar13** [sumatrapdfreader/sumatrapdf#1610] opened 2020-06-06 10:10 UTC
on changing FixedPageUI in advanced settings to white, opening PDF shows background color white, but when open cbr file background color is black, how to change that color
on PDF file
![image](https://user-images.githubusercontent.com/52490694/83941783-d501e800-a80b-11ea-9407-757bcdb79a18.png)

on CBR file
![image](https://user-images.githubusercontent.com/52490694/83941798-efd45c80-a80b-11ea-83ea-eb8bec6ba865.png)

**Comment by GitHubRulesOK** [comment] 2020-06-06 10:22
Efectively duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/853 search GradientColors for examples

**Closed** 2020-06-06 12:42 UTC
