### ISSUE TITLE
Tab arrows block close tab element

### ISSUE THREAD

**Issue by Dyphen** [sumatrapdfreader/sumatrapdf#447] opened 2016-02-23 16:46 UTC
When multiple tabs are open and the tabs reach the end of the bar, the last tab's close 'x' dialog cannot be clicked, because the tab switch arrow buttons appear over it. The link below displays this behavior (note: mouse is invisible in gif). 

http://i.imgur.com/VE0HCU8.gifv

I'm using SumatraPDF v3.1.1 64-bit; Windows 10, 3200x1800 with 200% default scaling. 

I looked the advanced options but did not find any way to turn off the tab arrows.

**Comment by fbouchet** [comment] 2016-04-18 12:56
I'm having the very same issue, with the same combination of SumatraPDF (v3.1.1 64-bit on Windows 10) and resolution (3200x1800 with 200% default scaling).
As a temporary workaround, I'm now using CTRL-W to close the current tab, but only after having naturally tried to aim at the 'x' at first. It's not a big issue but it feels a bit frustrating every time as closing the current tab is such a basic action one does even without thinking.

**Comment by Wehrdo** [comment] 2017-12-15 02:52
Also happening here on v3.1.2, Windows 10 Version 1709, with 215% scaling. (Screen resolution 3840x2160)

I wonder if this issue only shows up when Windows scaling is turned on. I recently upgraded computers, to a high-DPI screen, and never encountered this issue before.

**Comment by GitHubRulesOK** [comment] 2019-11-22 21:55
@kjk just a link to report issue is still present in current pre-release on 250% scaling see https://forum.sumatrapdfreader.org/t/hard-to-close-the-tab-to-the-right/2456/4

**Comment by rcragun** [comment] 2021-10-05 18:57
Present on 

**Sumatra**: version 3.3.3 (64-bit)
**Scaling**: 250%
**Screen resolution**: 3840×2160
**Windows**: version 10 Home 21H1

**Comment by kjk** [comment] 2022-06-08 19:07
Can't reproduce at 200% scaling (or any scaling).

The arrows should no longer appear at all.

**Closed by kjk** 2022-06-08 19:07 UTC

**Comment by GitHubRulesOK** [comment] 2022-06-08 21:36
@rcragun current "for compare" would be [pre-release](https://www.sumatrapdfreader.org/prerelease)
