### ISSUE TITLE
printing

### ISSUE THREAD

**Issue by dddffgg** [sumatrapdfreader/sumatrapdf#1814] opened 2020-11-19 12:08 UTC
print lots of tabs
close tabs
open new tabs
print them
quicky

fails and prints same thing over and over again

great software though chaps, well done

**Comment by GitHubRulesOK** [comment] 2020-11-19 12:38
Unclear exact symptom needs to be simplified to minimum example 
e.g. if you print from two/three tabs how to close tabs is it all application closed or just those tabs one by one until zero?
How are you opening new tabs? is it drag and drop or file open ?
what do you mean by **quickly,** each one should take some time thus if getting repeats there is some work flow step that is missing or overlapping.

**Comment by GitHubRulesOK** [comment] 2020-12-13 17:36
@kjk 
I suspect it is possible there could be a windows spooling issue here, under some odd circumstances / settings.

However in general it should not be possible since in my attempts to print a second tab whilst first is still in progress SumatraPDF should invoke a warning such as
![image](https://user-images.githubusercontent.com/12754913/102018938-5e204b80-3d68-11eb-85c0-ddb2b173f073.png)

Without any further guide as to how unwanted duplicates  could occur. I suggest this is not a currently reproducible issue / bug and am closing for now as "insufficient information to duplicate / resolve"

**Closed by GitHubRulesOK** 2020-12-13 17:36 UTC
