### ISSUE TITLE
Changing color settings changes images

### ISSUE THREAD

**Issue by horusra** [sumatrapdfreader/sumatrapdf#1589] opened 2020-05-20 21:20 UTC
![23](https://user-images.githubusercontent.com/17074394/82498462-52c9b200-9af0-11ea-94e0-1cdc911f7868.jpg)
right are color settings
top is Edge
bottom is Sumatra
for some reason the image is now miscolored... 
did I do something wrong or is this a bug?

**Comment by horusra** [comment] 2020-05-20 21:42
As I understand it the software is just mapping all colors? can it not have an option to ignore images that are not in greyscale?

**Comment by GitHubRulesOK** [comment] 2020-05-20 21:55
You have inversed the color range
Text color must be **lower** than BackgroundColor
FixedPageUI [
	TextColor = #000000
	BackgroundColor = #ffffff

**Comment by horusra** [comment] 2020-05-20 22:08
![00](https://user-images.githubusercontent.com/17074394/82502004-8576a900-9af6-11ea-8ceb-7af9ffa0f385.jpg)
but even if text color is lower than background color, the colored images are still remapped.
I only want the page background and text to change colors, not the colored images. Is there no way to exclude them?

**Comment by GitHubRulesOK** [comment] 2020-05-20 22:18
Short answer No, so am closing as your request as primarily a duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1275
there is no black and white in a PDF just text, background and images with a bounded range of colors
see many open issues with setting blackground to same as text or setting fonts on whiteground to white there are just so many interconnected places they will go wrong if reversed

**Closed by GitHubRulesOK** 2020-05-20 22:18 UTC

**Comment by horusra** [comment] 2020-05-20 22:35
what if you do it on a page by page basis? only change the colors of pages where there is no color information other than greyscale/back&white

**Comment by horusra** [comment] 2020-05-20 23:09
![01](https://user-images.githubusercontent.com/17074394/82506271-a099e680-9aff-11ea-8873-76d2cddc05ed.jpg)
nevermind, Adobe reader seems the only software capable or changing text+background without ruining image colors.
