### ISSUE TITLE
annotation box of highlighted text keeps blinking

### ISSUE THREAD

**Issue by LqkUWp** [sumatrapdfreader/sumatrapdf#2772] opened 2022-07-01 13:46 UTC
reproducing procedure:
1. select some text and type `a` to highlight it. 
2. suppose my user name is 'xxx'. so the default annotation of highlighted text is 'xxx'. 
3. hover mouse clicker on the highlighted text. then the yellow annotation box with 'xxx' will keep blinking instead of fading in and out. 

Ver. pre-3.5.15210 64bit

**Comment by GitHubRulesOK** [comment] 2022-07-01 15:45
potentially duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/2728

The real time polling of appearance changes make the appearance change ?

**Closed** 2022-07-12 02:37 UTC
