### ISSUE TITLE
Failed to display Table in epub files

### ISSUE THREAD

**Issue by hikboy** [sumatrapdfreader/sumatrapdf#2112] opened 2021-08-09 12:30 UTC
Failed to display Table in epub files

For example:
![failes](https://user-images.githubusercontent.com/18178653/128706342-27aa04dc-ade8-4512-8c09-2d99348fa091.png)

![succ](https://user-images.githubusercontent.com/18178653/128706352-aff43c5e-133b-4f17-b73a-92cb14f49447.png)

**Comment by GitHubRulesOK** [comment] 2021-08-09 13:08
Epub rendering has changed so you need to report and show experience
against current pre-release with a sample file.

Closing as duplicate of #319 , #565 and #1441
covered by more general open issue #849

**Closed by GitHubRulesOK** 2021-08-09 13:08 UTC
