### ISSUE TITLE
need save(ctrl+s) not just save as

### ISSUE THREAD

**Issue by zhaoliang0302** [sumatrapdfreader/sumatrapdf#1137] opened 2019-02-23 04:43 UTC
After spotlighted in the PDF file, I want to save it but save as a new file is unnecessary, can you add an option just "save"? Thanks

**Comment by GitHubRulesOK** [comment] 2019-02-23 11:44
When you start a save action in many applications, it is save AS either text or pdf with highlight changes in the pdf or in the smx or as different name so as not to corrupt the original
Only editors tend to have unconditional "save", and Sumatra
PDF is not an editor
If you wish to overwrite a file as same name it would be unsafe without extra checks and controls.

**Comment by GitHubRulesOK** [comment] 2019-12-27 22:36
@kjk duplicate of closed https://github.com/sumatrapdfreader/sumatrapdf/issues/460#issuecomment-194212422

**Closed** 2019-12-27 22:45 UTC
