### ISSUE TITLE
can not specific color or monochrome

### ISSUE THREAD

**Issue by ziqiangxu** [sumatrapdfreader/sumatrapdf#1018] opened 2018-05-11 12:46 UTC
I have tried this command:
`   
 SumatraPDF.exe -print-to "HP00E810 (HP Officejet Pro 8100)" -print-settings "monochrome" test.pdf
`
And then the printer output a color printed document.(I have just one printer, so it's hard to test more printer)
Is it the matter of my printer(The driver do not support specific the dmColor of devMode)?
_I am so sorry, I am not good at English, I hope you can understand what I want express._

**Comment by GitHubRulesOK** [comment] 2018-05-11 21:43
Using current version 3.1.2 I tried
SumatraPDF.exe  -print-to "HP928555 (HP DeskJet 3630 series)" -print-settings "monochrome" cover.pdf
although my default is color ON it printed as Black & White as expected

It is possible some basic print drivers do not have monochrome setting (I tried print to PDF and it reproduced a color copy, but since there is no mono option that would be as expected for that driver)

If it is important to you, some companies **duplicate** the driver with the **default set to monochrome** and send all bulk prints to that copy of the driver

**Comment by ziqiangxu** [comment] 2018-05-11 23:33
I see, Thank you very much. It's must because of the printer driver. I found it's settings (in the control panel) have three options about color:
1. color
2.gray level
3. only black
I am tring to find a compatible method to fit more printer driver.
Thank you again!

**Comment by kjk** [comment] 2018-06-09 20:19
Closing as per suggestion.

**Closed by kjk** 2018-06-09 20:19 UTC
