### ISSUE TITLE
Add scroll bar in single page mode

### ISSUE THREAD

**Issue by msmolensky** [sumatrapdfreader/sumatrapdf#4654] opened 2024-11-23 06:51 UTC
Absence of a scroll bar in a single page mode is unexpected and confusing and makes navigation harder.

**Comment by GitHubRulesOK** [comment] 2024-11-23 11:39
MuPDF and Xpdf based viewers do not use scroll in a fit page into single frame.
Even Acrobat Light Web Viewer does not use one when a page fits the frame, it is removed.
![image](https://github.com/user-attachments/assets/16038304-628b-4146-8824-32906fd8f09d)


The problem is Acrobat did for historic web plug in and navigation in their enhanced desktop free editor reader.

Duplicate of #191

**Closed by GitHubRulesOK** 2024-11-23 11:39 UTC
