### ISSUE TITLE
When printing, how to realize the reduction function, such as 4-in-1, that is, four pages are printed on a piece of paper. Usually, there is this option in the printing function. Can we realize this through the command

### ISSUE THREAD

**Issue by wangpai1998** [sumatrapdfreader/sumatrapdf#1851] opened 2021-01-03 03:38 UTC
When printing, how to realize the reduction function, such as 4-in-1, that is, four pages are printed on a piece of paper. Usually, there is this option in the printing function. Can we realize this through the command

**Comment by GitHubRulesOK** [comment] 2021-01-03 04:17
The 4-up feature is not often available in simpler print drivers but if it is always available as a setting in your default printer then "possibly". However there are much better dedicated applications for controlling that task.

SumatraPDF depends on runtime windows DEFAULT print settings when command line printing.

For n-up printing I would be looking to save a new NAMED printer (duplicate of the default print driver) with that page layout as its fixed default layout. My previous HP manufacturers enhanced driver had that ability but none of my current windows supplied print drivers allow me to test that feature.

**Comment by GitHubRulesOK** [comment] 2021-01-03 11:16
Closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/39

**Closed by GitHubRulesOK** 2021-01-03 11:16 UTC

**Comment by wangpai1998** [comment] 2021-01-03 11:22
I want to know if there are any similar tools. Can you recommend them for me? Thank you very much!!! I haven't found it for a long time

**Comment by GitHubRulesOK** [comment] 2021-01-03 16:02
the better CLI tools like 2Printer may not show that (ask their tech support/forums) it may only be in their other products like https://www.fcoder.com/news/print-conductor-7-0 try looking especially for "n-up"
https://duckduckgo.com/?q=command+line+%2B%22n-up%22+print&ia=web

**Comment by wangpai1998** [comment] 2021-01-06 06:26
First of all, thank you very much for your reply! This function is indeed very complete, but this print out has a watermark, you must also buy software, a computer will cost a lot of money. Then do not know if there is similar open source software, or no watermark, not so many functions does not matter, it is too much trouble for you!

**Comment by GitHubRulesOK** [comment] 2021-01-06 15:28
If you need to repeat a task frequently and reliably there should be no problem with the watermark simply ignore it is either an extra page or only one corner NOT annoyingly a hyperlink across the page.
Otherwise consider much slower methods like open source Sejda I use the desktop version but try their n-up page first at https://www.sejda.com/n-up-pdf
