### ISSUE TITLE
I can not create a dark theme

### ISSUE THREAD

**Issue by u3712** [sumatrapdfreader/sumatrapdf#1023] opened 2018-05-19 22:43 UTC
The program does not have color settings through the GUI, but you can configure them through the text description file - FixedPageUI.
Changing the TextColor and BackgroundColor to # ffffff / # 303030 makes the program look very user-friendly, but what happens to the pictures? They become negative. It's creepy.

**Comment by SumatraPeter** [comment] 2018-05-21 13:56
As I understand it the whole page is rendered by the underlying MuPDF engine and then displayed by Sumatra, so inverting colors inverts everything since no distinction is made between the text and image portions of a page. You'll have to wait for the app itself to implements a dark theme.

Related/duplicate of #437

Also see #743, #898 etc.

**Comment by kjk** [comment] 2020-01-06 22:25
This falls under theming support i.e. #898

**Closed by kjk** 2020-01-06 22:25 UTC
