### ISSUE TITLE
Feature request: Fit to width & zoom working independently

### ISSUE THREAD

**Issue by SillyBirds** [sumatrapdfreader/sumatrapdf#1184] opened 2019-07-25 09:13 UTC
Currently, fit to width also forces the zoom for all images, which means that if you fit to with because you have double pages, the single pages will usually end quite small.

So what would be great, would be for “fit to width” to work as to not allow an image to go beyond the window size, regardless of the zoom level. That would allow for keeping the one page images big and the double ones from escaping the window.

Basically, “fit to width” just being for keeping the image within the window instead of being a zoom feature.

(You can check PicWalker if you want the perfect example of how that works)

Example:
Currently in sumatra:
![image](https://user-images.githubusercontent.com/22528910/61863712-6c9a6880-aed0-11e9-8f1b-5a6bb82e442f.png)

Wanted feature (PicWalker)
![image](https://user-images.githubusercontent.com/22528910/61863827-a7040580-aed0-11e9-9ee0-ef9030df5080.png)

Thanks in advance if it can be implemented.

**Comment by GitHubRulesOK** [comment] 2019-07-25 18:56
In part this is related to your other question, the viewer shown above is treating the two as separate images and SumatraPDF in this respect works exactly like Adobe reader 9 and practically all PDF readers.
![Adobe9](https://user-images.githubusercontent.com/12754913/61899466-6c6f8c80-af13-11e9-9747-86cd70190918.png)

 SumatraPDF can obviously fit both **even better** to full true width if the images are separated in a folder and rescaled to be displayed sequentially. I have done that here to show how the images can be saved using SumatraPDF into a PDF or CBZ comic just the way you asked. However note most other readers would complain the small pages are too big and the size of writing jumps from page to page. Geuess you will NEVER please all of the people all of the time.

@kjk this is effectively duplicate of #152 https://github.com/sumatrapdfreader/sumatrapdf/issues/152

**Comment by SillyBirds** [comment] 2019-07-25 19:41
I'm only asking for the option for images not escaping the width of the window when changing the zoom level (don't see the relation with #152 btw).

I don't use this to read pdfs, only for manga (cbr/cbz/zip), and because it supports both continuous reading and webp images.

Frankly, I wish I could still use PicWalker, but sadly it doesn’t support webp (the program hasn’t been updated in 15 years).

**Comment by SumatraPeter** [comment] 2019-07-25 22:51
@SillyBirds: So basically what you want is that if Fit Width is turned on, you should be able to keep zooming in a page till its width is equal to the current window width, but no more? Also you want to be able to do this for each page independently even in continuous page view mode, right?

Firstly, as kjk has [mentioned](https://github.com/sumatrapdfreader/sumatrapdf/issues/152#issuecomment-87956692) in #152, currently in continuous page view mode Sumatra assumes a common zoom level (zoomReal) for all pages. So to even begin to implement what you want, first of all there needs to be an independent zoomReal for each page.

Secondly, since the main problem is that in continuous page view mode with Fit Width, single pages end up way too small in case there are double-page spreads, if #152 is implemented properly that will no longer be an issue. In that case, how does this request further improve upon matters? Seems to me that #152 does indeed serve as an effective duplicate to fix the problem you've highlighted.

@kjk: While we're on the subject of #152, I see 3 small commits made 4 years ago... Do you happen to remember if you got stuck with implementation details, or was it just something that got abandoned due to lack of time?

**Comment by kjk** [comment] 2019-07-25 23:40
@SumatraPeter A bit of both. It turned out a bit more complicated than I thought and I ran out of steam.

**Comment by SumatraPeter** [comment] 2019-07-26 01:17
Ah, too bad. Maybe (some one?) some day... :)

**Comment by SillyBirds** [comment] 2019-07-26 06:54
@SumatraPeter I don't want to change the zoom factor for each image independently.

The feature I’m referring to is that when “fit to width” is enabled, for it to supersede the zoom factor, so that images have the window width as cap, while letting the smaller still be zoomed in.

**Comment by SumatraPeter** [comment] 2019-07-27 00:29
> I don't want to change the zoom factor for each image independently.

Huh?

> while further zoom changes continue to apply to the other images

_automatically implies that you **do**_

> want to change the zoom factor for each image independently

Given that there can obviously be many images of varying sizes (width/height), in such a case each will need to be zoomed to a different extent till each hits the window's width/height cap, right? So how does that _not_ require Sumatra to have the ability to store and manipulate each page's zoom factor independently?

Any way you look at it, your request is completely dependant on per-page zoomReal being implemented first (as mentioned in #152).

**Comment by SillyBirds** [comment] 2019-07-27 06:46
I don't know how the program works, so maybe I'm asking for that, sorry. Please feel free to check it out on the old reader I was mentioning it about, [PicWalker](https://github.com/sumatrapdfreader/sumatrapdf/files/3437916/pwalk41.zip):

![image](https://user-images.githubusercontent.com/22528910/61990981-5c0dfd80-b04a-11e9-8f5e-b3dc4217caac.png)

**Comment by GitHubRulesOK** [comment] 2019-12-15 03:26
Many users get caught up in terms of "fit width" and zoom together
They ARE independent settings but naturally have an affect on each other.

**Most users simply just want a page to fit the width of a widescreen** either as a part of a single or landscaped doublespread.
That is the simplest out of the dozens of combined layouts, it is the one on the far right
![mixed](https://user-images.githubusercontent.com/12754913/70857355-90dcfd00-1ee4-11ea-87fe-86f7bb07323c.png)

1) on the view menu UNCHECK `show pages continuously` mode, since doublewidth will automatically overide the single page setting (note in SumatraPDF **single page without continuous** is the way fit width works with different size pages)

You can use <kbd>**Ctrl**</kbd> & <kbd>**2**</kbd> to set fit width
The alternative is to toggle the **fit width icon** once or twice to set it OFF of **Fit width and show pages continuously** which only works with pages that are ALL same fixed width

Now ALL pages can fit width singly as required 

The next problem is users zoom in and out without noticing that SumatraPDF can only use the one current scale setting as they move from page to page so they should "UNZOOM" using <kbd>**Ctrl**</kbd> & <kbd>**2**</kbd> to **again** refit width, BEFORE CHANGING PAGE, if you try to use the fit width icon after scale has changed then it is likely too late and the simple layout has likely been disturbed.

**Comment by kjk** [comment] 2019-12-15 06:13
Fixed with https://github.com/sumatrapdfreader/sumatrapdf/commit/48ba64ef4cadc656905026fa274dfb73d19d49aa

**Closed by kjk** 2019-12-15 06:13 UTC
