### ISSUE TITLE
Crash when opening files

### ISSUE THREAD

**Issue by Dharmainiciativ** [sumatrapdfreader/sumatrapdf#729] opened 2017-02-27 19:57 UTC
The program is the only open files pdf, when you try to open any other types of files, the program crashes. In the case of the pdf is not displayed in the header tab.
Also, when you try to open e-book file, do not display the contents of the documents, in addition to the table of contents.
Crashdump https://yadi.sk/d/WviWcFel3Ejmhj
Used assembly SumatraPDF-prerelease-10593 or the same but x64. Windows 7 x64 system

**Comment by kjk** [comment] 2017-02-27 20:12
Which version of Sumatra is this?

How are you opening the files that cause the crash (drag&drop on the window, File/Open)?

Does the crash happen with every non-pdf file? Every non-supported file? Or to aks differently: what exactly were the files you tried to open that caused the crash (name of the file, what was in the file) ?

**Comment by Dharmainiciativ** [comment] 2017-02-27 20:23
Sumatra is the version that you have laid out at home, in this case SumatraPDF-prerelease-10593.
The fall does not depend on the method of opening the file that the menu because of drag & drop.
Sumatra falls on files fb2, epub, mobi, djvu, djv. Opened only files pdf, while there is the following http://i.imgur.com/lrFEAil.png
Crashdump I have created, but for whatever reason I can not attach it here. I filled just in case another zippyshare http://www27.zippyshare.com/v/H3LaLPUm/file.html

**Comment by Dharmainiciativ** [comment] 2017-02-27 20:27
Yet there appears http://i.imgur.com/k8qnjN1.png

**Comment by VictorVG** [comment] 2017-02-27 20:54
I build v3.2 Git-a9999f9dec use in source and can't crash, but last build have anover problems:

1) Tab title is cleaned and don't display document name or title - is navigation problem on MDI interface:

![multi-tab](https://cloud.githubusercontent.com/assets/906886/23379223/3048bcde-fd47-11e6-80c9-aa58adb04267.png)

2) (is cosmetic) - installer:

before open Installer options dialog:

![installer 1](https://cloud.githubusercontent.com/assets/906886/23379266/5cc40c50-fd47-11e6-985c-cd23c1a36014.png)

after: 

![instllaer 2](https://cloud.githubusercontent.com/assets/906886/23379267/5cc77d0e-fd47-11e6-91c5-b25804486193.png)
 
then I would prefer the smaller size of the main window installer times there is currently not an animated screensaver that conclusion, and so takes time, and a simple non-animated text banner announcing what was happening.

Personally, my assessment of what I see - a minor cosmetic flaw that would later be corrected.

**Comment by VictorVG** [comment] 2017-02-27 21:47
@kjk 

I see part crash report then send me @Dharmainiciativ - when you open a document in the program there is AV (Access Violation) because of the treatment to the address below 64k and trigger memory protection schemes CPU by generating an interrupt with 0h00000005 code. Interrupt handler that automatically calls to the failed task TerminateProcess().

**Comment by Dharmainiciativ** [comment] 2017-02-28 13:30
DJVU files were opened, but not the name of the tab header. In other types of files, except djvu pdf and still falls.

**Comment by VictorVG** [comment] 2017-02-28 16:16
I build new commit 3f025c62e1 and test it use PDF, DjVu, CBR, CHM, FB2 - open is w/o crash, but no tab's title:

![git-3f025c62e1](https://cloud.githubusercontent.com/assets/906886/23412840/fbf306d2-fde7-11e6-9d8b-724ade8bf8dc.png)

then test ePub - SumatraPDF is not respondig for OS and 100% used one logical CPU core on i7-2600 see Process Hacker v3.0(r402) miniWindow (pleased on tray) screenshot:

![git-3f025c62e1-epub-open](https://cloud.githubusercontent.com/assets/906886/23413059/a206650a-fde8-11e6-90d7-a2e1bbdcb487.png)

threaded list for SumatraPDF on this time is:

![threads-3f025c62e1](https://cloud.githubusercontent.com/assets/906886/23413448/bf89ac94-fde9-11e6-9801-a68587324d10.png)

stack for main thread:

![stack-3f025c62e1](https://cloud.githubusercontent.com/assets/906886/23413472/cf1a109a-fde9-11e6-8a8a-022e990d15c5.png)

I also check CPU, RAM, I/O activity other ten minutes after test starting:

![perfomance-3f025c62e1](https://cloud.githubusercontent.com/assets/906886/23413562/1a49ffe4-fdea-11e6-9673-f7081620ab91.png)

then send to freeze task signal _TerminateProcess()_  - test is finished failure. :)

**Comment by VictorVG** [comment] 2017-02-28 17:52
Version 3.2 Git-49c79e307d also crashed [SumatraPDF-v3.2-Git-49c79e307d_settings_and_dump.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/807629/SumatraPDF-v3.2-Git-49c79e307d_settings_and_dump.zip)  if _RestoreSession = true_ and any input file is encrypted and password not saved. My test kit is  [**SumatraPDF-v3.2-Git-49c79e307d_test.zip**](https://www.upload.ee/files/6728819/SumatraPDF-v3.2-Git-49c79e307d_test.zip.html) (upload.ee , HTTPS).

**Comment by VictorVG** [comment] 2017-02-28 19:15
Common logical crash formula is - `_(RestoreSession=True ^ Input_pasword_encrypted_file ^ Password_is_unknown) v RestoreSession=True_` then error located in Restore Session algorithm.

**Comment by kjk** [comment] 2017-03-01 05:38
I cant reproduce the invisible title nor other crashes, so closing this one.

I looked at the test kit  SumatraPDF-v3.2-Git-49c79e307d_test.zip and was able to load all the files inside Test directory with both 32 and 64-bit Sumatra version included in the .zip. This was on Win 10 64-bit.

There's nothing more I can investigate given the information I have.

**Closed by kjk** 2017-03-01 05:38 UTC

**Comment by Dharmainiciativ** [comment] 2017-03-01 13:01
We are talking about your assembly 10605, on it all of the above bugs are present.
![2017-03-01_15-58-31](https://cloud.githubusercontent.com/assets/10089507/23460782/1aa10ea2-fe98-11e6-9542-295f5f7bd238.gif)
