### ISSUE TITLE
Signature display issue

### ISSUE THREAD

**Issue by zyd306** [sumatrapdfreader/sumatrapdf#3460] opened 2023-04-23 13:57 UTC
The same signature file is displayed incomplete in SumatraPDF, while other readers display it as complete

other readers Preview
![2023-04-23_215327](https://user-images.githubusercontent.com/64816822/233843929-e0cf1429-a83a-43e8-ada6-b269741dad07.png)

SumatraPDF Preview
![2023-04-23_215336](https://user-images.githubusercontent.com/64816822/233843933-dead7137-341b-46c6-bbca-bbfa5352871d.png)

**Comment by GitHubRulesOK** [comment] 2023-04-23 14:48
1st try [pre-release](https://www.sumatrapdfreader.org/prerelease) and if that is still a problem then add a sample for reopening

**Comment by GitHubRulesOK** [comment] 2023-10-31 03:19
closing as duplicate of resolved issue

**Closed by GitHubRulesOK** 2023-10-31 03:19 UTC
