### ISSUE TITLE
Updated and sumatra will not open sesson

### ISSUE THREAD

**Issue by Aphexus** [sumatrapdfreader/sumatrapdf#1790] opened 2020-10-25 19:23 UTC
Updated from 3.1(or whatever, been several months) to the latest and the app will not restore opened documents. It seems to show them(some of them at least) in recents but it does not restore the session. All the correct options are set, I've tried to modify them and reset them and all that and nothing.

FileStates  is showing all the files but only 3 are showing up in recents and in the frequently read and none of them are being open.

Even if I delete the contents of SumatraPDF-settings it still does not do what it is suppose to do. This is almost surely a bug with sumatrapdf.

I had no problem with it before the update and changed no settings.

**Comment by GitHubRulesOK** [comment] 2020-10-25 20:07
"Latest" could be 
3.2 formal release (which does update File States but Session Data is a seperate set of files that are only stored when the session ends)
Pre-Release or Daily which after 3.2 store SessionData when tabs change.

Recents and frequentlly read are two different ways of showing past history from the settings.txt FileStates history 

Recents should be the last 10 files opened
Favoirites are the 10 most often opened

If you are only seeing the same 3 in each list it suggests the settings file is not being read beyond a rogue entry, and since session history is at the end of file then that would also explain sessions not restoring.

I would first rename the settings file (incase it is of value later) then let SumatraPDF build a fresh one where the default is to start building file history anew.
If you need to put back historic filenames into the fresh copy then very carefully cut and paste chunks from the saved copy with MSnotepad and watch out for any session failing after testing those that may have unusual filename characters.

**Comment by SumatraPeter** [comment] 2020-10-26 22:21
> Even if I delete the contents of SumatraPDF-settings it still does not do what it is suppose to do.

@Aphexus: Note that the default install location, settings file location etc. have all changed with Sumatra 3.2, so when you say that deleting SumatraPDF-settings.txt does nothing, it definitely sounds like you're deleting the file from the old location i.e. `%AppData%\SumatraPDF` (i.e. `C:\Users\<UserName>\AppData\Roaming\SumatraPDF`).

Try closing Sumatra and deleting the settings file located at `%LocalAppData%\SumatraPDF` (i.e. `C:\Users\<UserName>\AppData\Local\SumatraPDF`). Now if _that_ doesn't reset Sumatra completely back to default freshly-installed behavior, I'd say there's something seriously wrong with your system.

**Comment by Aphexus** [comment] 2020-11-03 00:38
So that is just f'ing great. 1. It must be my system just cause you say so huh? 2. You are god? All seeing? You make a significant change to how an app functions and automatically any failures must be someone else's problem? Great, I see, sounds like narcissism to me.

Of course it seems you were too stupid to realize that some people use multiple Sumatra apps simultaneously. Great, now I'm stuck with having to never use never versions again because you decided that in all your wisdom that if you make any significant changes to your app that it must mean that any issues that come up are impossible to be due to your ignorance and those changes that you know to be 100% factually proven safe.

Great, now that is settled I'll just go look for some alternative pdf reader to use...

**Closed** 2020-11-03 01:51 UTC

**Comment by GitHubRulesOK** [comment] 2020-11-03 01:58
@Aphexus 
You may not be aware that @SumatraPeter was against the changes that may have contributed to your setup having multiple settings files. I am presuming the issue is solved since your comments sugest that was your problem **although you are not happy with the cause** which is thus duplicate and covered by similar open issues

**Comment by SumatraPeter** [comment] 2020-11-10 21:55
@Aphexus: Well, clearly you are too stupid to realize that I'm just an end user and not the dev, and I really don't give a damn what you use. Don't let the door hit you on your way out.
