### ISSUE TITLE
Suggestions about line breaks

### ISSUE THREAD

**Issue by Foooool** [sumatrapdfreader/sumatrapdf#1869] opened 2021-01-27 06:44 UTC
When copy a paragraph from a paper, the content of different lines will have line breaks. I  wonder whether the line breaks can be deleted automatically. I believe that many people will also have the same needs :D

**Comment by GitHubRulesOK** [comment] 2021-01-27 10:08
I an sure this is a duplicate of several other requests, so expect closure when I later find those entries.
 Short answer is NO since that's the way text is stored and presented. Whilst it is possible to strip and restructure punctuation easily in one language, that will not work for another, thus altering text layout becomes a massive editing exercise. You want to only tip of the iceberg remove one of three types of line feed but what about hyphenation and non breaking spaces etc.. More important would be removing the white spaces often found between glyphs such that W o r d s B e c o m e L e s s R ea d a b l e. But that is down to the FreeType libraries.
Not impossible just a large task with variable rules.

**Comment by GitHubRulesOK** [comment] 2021-01-28 00:50
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1427

**Closed by GitHubRulesOK** 2021-01-28 00:50 UTC
