### ISSUE TITLE
Spaces are not treated as characters when searching

### ISSUE THREAD

**Issue by Peter-202122** [sumatrapdfreader/sumatrapdf#3948] opened 2023-12-10 15:20 UTC
Hello,

it's a small but (for my needs) important detail: 

When performing  a search within a PDF, a space between two characters is ignored. That means for example:

- I search for **:Paris**  [i.e. colon followed by the word Paris, **without** space between colon and Paris]

- As search result I also get every incidence of **: Paris** [i.e. colon - **space** - Paris]. And this is undesired (for my needs). It produces by far more results than I wish.

If necessary, I can elaborate why this difference is of importance for me. But I think my request is clear anyway:

It would be fine if spaces were considered as a character when performing a search.

As this is the standard in the search function of all other software I use, I think the way it works in Sumatra is an issue.

Thanks in advance for dealing with the matter.

**Comment by GitHubRulesOK** [comment] 2023-12-10 17:22
in effect duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/995

**Closed by GitHubRulesOK** 2023-12-10 17:22 UTC
