### ISSUE TITLE
Some tables/forms in EPUB don't display correctly

### ISSUE THREAD

**Issue by OXFEEA** [sumatrapdfreader/sumatrapdf#2272] opened 2021-12-26 13:03 UTC
Here's the Sumatra v3.4.14237 64bit:
![sumatra](https://user-images.githubusercontent.com/3413305/147408734-7c92bb6e-f1a4-474e-9f9f-7430c83ed7b3.png)

And the same table in my web-browser epub reader:
![epubreader](https://user-images.githubusercontent.com/3413305/147408718-71271911-8da3-4b13-bb42-80a17ecfb2ac.PNG)

I can provide the .epub file if you need, but it's over 40mb, maybe not in git-hub.

**Comment by GitHubRulesOK** [comment] 2021-12-26 13:22
This is a known issue that in general ebook tables with columns are not well defined/supported and is thus a duplicate of several historic issues.
The core issue is MuPDF rendering of epub.

**Comment by OXFEEE** [comment] 2021-12-26 13:49
Too sad to known about this. Hope it wound be fixed soon.

**Comment by OXFEEE** [comment] 2021-12-26 13:50
Thanks for the information.

**Comment by s-kocher** [comment] 2022-06-05 20:53
=> MuPDF issue : https://bugs.ghostscript.com/show_bug.cgi?id=700013
No activity since 2019-08-22, status is still in UNCONFIRMED 😔

**Comment by GitHubRulesOK** [comment] 2024-12-23 09:45
MuPDF have closed those older issues as "resolved" and the one known example shown here in SumatraPDF
![image](https://github.com/user-attachments/assets/ca4089a4-fe40-4bfd-986c-770cf73fbd6d)

HOWEVER although there may be other examples, without a live reference example am closing as now duplicated by latest issue
For a given problem publicly available attachments  must be uploaded for test, AFTER problem shown a present in current pre-release.

**Closed by GitHubRulesOK** 2024-12-23 09:45 UTC
Labels: mupdf, ebook
