### ISSUE TITLE
Please add the option to show scrollbars on non-contiguous pages

### ISSUE THREAD

**Issue by Krist1798** [sumatrapdfreader/sumatrapdf#3282] opened 2023-02-17 12:03 UTC
Scroll bar cannot be displayed on non-continuous pages now

**Comment by GitHubRulesOK** [comment] 2023-02-17 13:51
Press C key closing as not an issue but a duplicate of comments in https://github.com/sumatrapdfreader/sumatrapdf/issues/191

**Closed by GitHubRulesOK** 2023-02-17 13:51 UTC
