### ISSUE TITLE
Faulty display - and print -  of the PDF in attach

### ISSUE THREAD

**Issue by freneksi** [sumatrapdfreader/sumatrapdf#1708] opened 2020-07-22 07:04 UTC
[VERHELST GARAGEBEDRIJF - Factuur 202000152.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4958360/VERHELST.GARAGEBEDRIJF.-.Factuur.202000152.pdf)

In adobe reader and browser plugins it displays just fine. In SumatraPDF only numbers are displayed.

Thank you

**Comment by GitHubRulesOK** [comment] 2020-09-17 00:07
Bad font embedded file especially that first character F then downhill after that till the bad refs at the end
Opened and re-saved as an Archival Quality file in PDF studio 
[1708 VERHELST.GARAGEBEDRIJF.-.Factuur.202000152 resaved.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5235493/1708.VERHELST.GARAGEBEDRIJF.-.Factuur.202000152.resaved.pdf)
It then works exactly as it should with the correct font embedded
![image](https://user-images.githubusercontent.com/12754913/93404241-93a8bc00-f881-11ea-9b73-84ac8f9fc6dc.png)

**Comment by SumatraPeter** [comment] 2020-09-17 23:04
@GitHubRulesOK: So if it was a bad file then might as well close this?

**Comment by GitHubRulesOK** [comment] 2020-09-24 18:28
@kjk 
Seems to be a MuPDF font handling regression as 3.1.2 shows the file perfectly well but MuPDf 1.17 does not

**Comment by GitHubRulesOK** [comment] 2023-10-24 14:45
same basic source as #3239

**Comment by kjk** [comment] 2023-10-25 22:32
possibly fixed in https://github.com/sumatrapdfreader/sumatrapdf/commit/8024e4fe01c980332656b8880808520e671a5bc2

**Closed** 2023-10-25 22:37 UTC
Labels: mupdf

**Comment by GitHubRulesOK** [comment] 2023-10-26 02:04
agreed that fixed this one AND same source 3239
