### ISSUE TITLE
PDF files from "manager"

### ISSUE THREAD

**Issue by bluelayer** [sumatrapdfreader/sumatrapdf#3239] opened 2023-01-27 01:21 UTC
Hello,

today I found sumatra unable to "render"? the very simple PDF generated by manager.io accounting software, invoices basically...
[Inter Account Transfer.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/10514682/Inter.Account.Transfer.pdf)

thanks!

V3.5.15264 64

**Comment by GitHubRulesOK** [comment] 2023-01-27 02:28
Hmm the problem is there in MuPDF 1.21 but not in a couple of other viewers.
Interesting that the source is `/Author  (EXPIRED license detected, check EULA - Apitron PDF Kit \(www.apitron.com\))` 
but I would be surprised they intended other apps not to view the fonts

**Comment by bluelayer** [comment] 2023-01-27 11:40
Firefox/edge can read it flawless

**Comment by kjk** [comment] 2023-02-08 00:44
mupdf says:
```
no builtin cmap file: Adobe-Identity-UCS
couldn't find system font ''
```

**Comment by kjk** [comment] 2023-02-08 00:47
Reported to mupdf: https://bugs.ghostscript.com/show_bug.cgi?id=706395

**Comment by kjk** [comment] 2023-10-25 22:32
fixed in https://github.com/sumatrapdfreader/sumatrapdf/commit/8024e4fe01c980332656b8880808520e671a5bc2

**Closed by kjk** 2023-10-25 22:32 UTC
Labels: mupdf

**Comment by GitHubRulesOK** [comment] 2023-10-26 02:05
agreed that fixed this one AND same source 1708 2 for the price of one
