### ISSUE TITLE
SumatraPDF crashed

### ISSUE THREAD

**Issue by palex70** [sumatrapdfreader/sumatrapdf#1102] opened 2018-12-05 12:19 UTC
We have more errors with the SumatraPDF. The error message is:
"We're sorry, SumatraPDF crashed."
Unfortunately, we can not do much with it.
Can you tell us more when you look at the dump file?
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/2648752/sumatrapdfcrash.zip)

**Comment by LiMinggang** [comment] 2019-01-09 06:44
Not much can be found in the crash dump. If you can reproduce it easily, please provide steps to do it. Otherwise, the developer can do nothing.

**Comment by palex70** [comment] 2019-01-25 10:31
We also do not receive any more information from the Event Viewer.
After several attempts with different versions, we found the following:
Only the "SumatraPDF-prerelease-10638.exe" works without crashes.
When will there be a final version 3.2?

**Comment by joshisanonymous** [comment] 2019-04-26 18:49
I receive this crash message every single time I close SumatraPDF on two different Win10 computers. Is there anything I can provide here that would help determine what's going on?

**Comment by GitHubRulesOK** [comment] 2019-11-16 10:31
@palex70 is it a type of file that causes crash, if so please attach an example and any other information about actions before crash. also see next comment

**Comment by GitHubRulesOK** [comment] 2019-11-16 10:31
@joshisanonymous can you please test latest daily build at https://www.sumatrapdfreader.org/dailybuilds.html

**Comment by joshisanonymous** [comment] 2019-11-20 15:18
> 
> 
> @joshisanonymous can you please test latest daily build at https://www.sumatrapdfreader.org/dailybuilds.html

Actually, I stopped experiencing this issue some time ago, though it was persistent for quite a while. I didn't update the version of Sumatra that I was using, so I can only assume it was something about the version of Windows 10 at that time.

**Comment by GitHubRulesOK** [comment] 2019-11-20 15:30
@joshisanonymous thanks for describing your experience it helps to class your issue as perhaps a short term instability in windows (not uncommon)

**Comment by kjk** [comment] 2019-11-20 19:01
Symptoms like that are usually caused by programs that inject their own code into Sumatra process and then crash, bringing sumatra down as well.

I've seen crashes caused e.g. by Avast anti-virus.

Uninstalling such programs would fix the crash.

Closing as this particular issue is no longer experienced.

**Closed by kjk** 2019-11-20 19:01 UTC
