### ISSUE TITLE
UNC path link not being handled properly by sumatra

### ISSUE THREAD

**Issue by Minkward** [sumatrapdfreader/sumatrapdf#620] opened 2016-09-23 10:42 UTC
Links within PDF document images are not working. The unc path is missing a backslash.

e.g. \server instead of \\server   (even here the 2nd back slash is disappearing!!!)

Links work fine in Adobe reader.
![unc path link issue 23-09-2016](https://cloud.githubusercontent.com/assets/22392592/18783263/ccc52c32-8182-11e6-9c73-b8b8112ccabd.JPG)

**Comment by GitHubRulesOK** [comment] 2021-08-02 01:53
Test an example against current Pre-release where many relative links have been fixed over time.
\\\\ is notorious for misinterpretation since every second one escapes thus sometimes four are needed as at start of line !!

Without samples cannot progress, so closing as unknown/unconfirmed current behaviour

**Closed by GitHubRulesOK** 2021-08-02 01:53 UTC
