### ISSUE TITLE
I would be very grateful if authors add the shortcuts of save annotations

### ISSUE THREAD

**Issue by harleyxu-xhl** [sumatrapdfreader/sumatrapdf#2459] opened 2022-04-06 08:37 UTC
It will be more convinient if adding "undo" shortcut, e.g. ctrl+z , just like the photoshop.

**Comment by GitHubRulesOK** [comment] 2022-04-06 11:15
In photoshop undo removes contents but in Adobe PDF undo will not always remove annotations it simply sets them to invisible, so deleting a saved annotation is not undo, that is not a bug it is the way PDF incremental writing works by Adobe design.

Always decide what invisible objects you wish to save and thus only save annotations when you have to.

closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1755

**Closed by GitHubRulesOK** 2022-04-06 11:15 UTC
