### ISSUE TITLE
[Feature request] Add tooltip with full filename when hovering over tabs

### ISSUE THREAD

**Issue by vlakoff** [sumatrapdfreader/sumatrapdf#1884] opened 2021-02-12 08:53 UTC
Title says it all :)

Long filenames don't fit in the tabs, so they are cropped with trailing dots ("...").
As many softwares do, we could display a tooltip with the full filename when hovering over the tab.

**Comment by GitHubRulesOK** [comment] 2021-02-12 11:40
Long time request from when tabs were first added, earliest duplicated request https://github.com/sumatrapdfreader/sumatrapdf/issues/336 so closing as duplicate of currently open https://github.com/sumatrapdfreader/sumatrapdf/issues/1188

**Closed by GitHubRulesOK** 2021-02-12 11:40 UTC
