### ISSUE TITLE
Close with double click on upper left corner doesn't work

### ISSUE THREAD

**Issue by breaker27** [sumatrapdfreader/sumatrapdf#681] opened 2016-12-06 12:02 UTC
Windows default behavior of applications is that you can close an application with a double-click on the upper left corner.
This does not work currently with SumatraPDF. Even if there's a Menu placed there, the double click could be detected (menu showing, closing, then SumatraPDF closes).

**Comment by GitHubRulesOK** [comment] 2019-03-25 20:42
@kjk duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/162

**Comment by kjk** [comment] 2019-03-25 20:46
closing as dup of #162

**Closed by kjk** 2019-03-25 20:46 UTC
