### ISSUE TITLE
Add half-page scrolling with <C-d>/<C-u>

### ISSUE THREAD

**Issue by corneliusroemer** [sumatrapdfreader/sumatrapdf#1784] opened 2020-10-17 13:04 UTC
I went through the SumatraPDF shortcuts and noticed that there was no half-page scrolling shortcut available - instead there's only full-page advance. It'd be great if there was half-page scrolling - otherwise you lose context when you switch to the next page.

This was already proposed back in 2015 but for some reason the issue was closed by the person who opened it without comment #272

**Comment by amosbird** [comment] 2020-10-17 13:07
I'd like to close issues when it's evident that no one has interest. And I'm using llpp now.

**Comment by corneliusroemer** [comment] 2020-10-17 13:28
Ah I understand :) Well now you've found someone else who's interested. Let's see what happens next...

**Comment by GitHubRulesOK** [comment] 2020-10-17 14:24
If only half a page is showing in either fixed page or continuous mode then CTRL Down / Up arrow will start every second step at top of page (thus not exactly half but a roughly equivalent move)

**Comment by folofjc** [comment] 2021-01-14 10:41
Sorry, I posted in the other one (https://github.com/sumatrapdfreader/sumatrapdf/issues/272#issuecomment-760111935)

But `<C-Up>` does not do what this feature request is asking.

**Comment by GitHubRulesOK** [comment] 2021-01-14 12:24
Personally I am happy the way it is, so as it is always working for part page mode it is close

Technically the command is a bit off, it is supposed to be

Move the focus up or down a line without changing the selection | Ctrl +Up arrow or Ctrl +Down arrow | Command +Up arrow or Command +Down arrow
-- | -- | --

However if it was changed to lines rather than part page then a different control would be needed i.e.. NOT c-up or c-dn

**Comment by corneliusroemer** [comment] 2021-01-14 20:06
No it's not working for part page mode. For part page mode, it is also always moving full SCREEN (not page), I'm talking about screen here.

There is no way to move the middle of the current screen to the top.

Vimium for Chromium uses u/d for fast up and down scrolling. This keys are also still available for shortcuts. Might be even better than Ctrl+u/Ctrl+d.

Alternative could be Ctrl+Space for half screen down, and Ctrl+Shift+Space for half screen up.

Weirdly, Ctrl+Space currently goes down an entire screen, despite not being listed in official shortcuts. https://www.sumatrapdfreader.org/manual.html

**Comment by GitHubRulesOK** [comment] 2021-01-14 21:11
I depends on the mode

space | scroll by screen
-- | --
< Shift > + space | scroll back by screen

In continuous mode [shift] space is converted to goback/advance one whole screen with a small overlap to allow for a split line. Zoom in and its the same (roughly one whole screen either way) Thus if height = full page it will advance one whole page (same as MuPDF) and with Shift is go back one whole page (it is BackSpace in MuPDF). Control should be ignored in both cases but annoyingly blocks shift from working. Hence you see movement for Ctrl Space that should be the same as just space. I find that generally natural and acceptable.

Page up and Page down (with / without shift) should say they are both page and **screen** relative i.e. in whole page it is full Page up/down but for screen within a page it is part page up/down. It may seem erratic but again makes sense to me as its the expected actions from a PDF reader.
Result | Windows/UNIX Action | Mac OS Action
-- | -- | --
Previous screen | Page Up or Shift+Enter | Page Up or Shift+Return
Next screen | Page Down or Enter | Page Down or Return

Control Page up and Control Page down are different they are a **full** (accelerated) "page" up / down in both cases again the expected behaviour for a leading PDF reader.

Previous page | Left Arrow or Ctrl+Page Up | Left Arrow or Command+Page Up
-- | -- | --
Next page | Right Arrow or Ctrl+Page Down | Right Arrow or Command+Page Down

**Comment by corneliusroemer** [comment] 2021-01-14 22:04
Ok, that makes sense :)
But there's still no move half-screen, right, or did I miss that?

**Comment by GitHubRulesOK** [comment] 2021-01-14 22:12
@corneliusroemer 
Try shifted right/left but margins are never exceeded so you must be zoomed in.

**Comment by imspzero** [comment] 2021-08-10 14:04
I recently encounter the same problem. 
Scrolling line by line with j/k makes the eyes get tired easily, while scrolling by page let you lose context. 
By comparison, Zathura supports scrolling by half without any configuration. All you need is to update the key-binding. 
In Calibre ebook viewer, there is also no scrolling by half screen, but it provides an option to set up the scroll behavior. If I set the scroll speed to 40 or 50, it works well.
Hence, I think it would be nice if the program supports scroll by half screen , or configurable scrolling speed.

**Comment by imspzero** [comment] 2021-08-14 14:14
Thanks for your reply and I understand that we can't put everything in an application. 

Today I spent some time on AutoHotKey and finally made a workable one. I put it here because it might help those who has similar needs. 

The script is [here](https://gist.github.com/imspzero/6c78ce18e72ef49b1e5fea33c82ddadb)
### What need to do
* Install **AutoHotKey**
* Download and edit the script, pick a suitable `scrollAmount`
* Find the proper hotkeys. I override the `n` and `m` key functions because I seldom use them. `<C-d>` and `<C-u>` are appliable as well, please read [the tutorial](https://www.autohotkey.com/docs/Tutorial.htm#s21) to try and test it.
* Double click and run the script

### My environment
* SumatraPDF 3.3.3
* Windows 10

Hope that this would provide a workaround for someone.

**Comment by GitHubRulesOK** [comment] 2022-05-09 16:47
@astroHaoPeng 
It only works half page in some cases e.g. if full page is showing as screen then it is a full half page roll as per design.
![image](https://user-images.githubusercontent.com/12754913/167458123-e15dd95b-c4d1-4121-95b9-b0c73afde008.png)


If you are zoomed it is accelerated shift as roughly half of the screen page, which is not always what users desire, hence this issue is still open.

**Comment by astroHaoPeng** [comment] 2022-05-09 18:18
@GitHubRulesOK Sorry but I got completely confused by your reply.
To clarify, my need is precisely a **"half-window-height scroll"**, regardless of zoom status or page showing status. My test results are:
- In continuous mode, either zoom-in or zoom-out status, screen scrolls by half. (good)
- In single-page mode,
  - if height-fitted, pages are turned. (good)
  - if not height-fitted, i.e., zoomed-in to higher than the window, pages are scrolled by half, and not turned when reaching the top/bottom. (very good design)
- In facing/book mode, same as single-page mode. (very good design)

I would say the function is already perfect to me!

BTW, I didn't see the usage for **half-page** or **half-screen-height** in my case. I guess mostly they mean **half-window-height**.

**Comment by GitHubRulesOK** [comment] 2022-05-09 21:01
@astroHaoPeng 
 AFAIK your re-assigning Shift Up and Shift Down now exposed as re definable cmd (been there for 10 years or so)

Worked as designed but reading between the lines not what users expected 

If you are confident that reassigning as Ctrl+d with Ctrl+u matches all users expectations then we can close the issue, as fully addressed.

**Comment by astroHaoPeng** [comment] 2022-05-09 21:20
@GitHubRulesOK 
Wow, my bad. Didn't read carefully and missed the part you mention about the `Shift + Up/Down` shortcut. 

After a third reading, I guess @imspzero @corneliusroemer @folofjc were asking about the same function to be exposed to customizable keys. So, let's wait for their confirm and then close this hopefully.

**Comment by GitHubRulesOK** [comment] 2022-05-09 22:31
@kjk since in effect the OP to access inbuilt half page command (zenico added in 2012) via custom keys is now addressed, 
do you want to reset the counter and close the issue as met ?

**Comment by kjk** [comment] 2022-05-09 22:33
Makes sense, thanks

**Closed by kjk** 2022-05-09 22:33 UTC
