### ISSUE TITLE
"narrow non-break space" not displayed well in ePUB and PDF files

### ISSUE THREAD

**Issue by ViveLaRosierre** [sumatrapdfreader/sumatrapdf#1035] opened 2018-06-25 08:33 UTC
Hi, the ["narrow non-break space"](https://en.wikipedia.org/wiki/Non-breaking_space) character isn't read well in SumatraPDF reader.

In ePub files, it renders as a blank void square like here :
<a href="https://www.noelshack.com/2018-26-1-1529914845-epub-blank-square.png"><img src="https://image.noelshack.com/minis/2018/26/1/1529914845-epub-blank-square.png" border="0" alt="1529914845-epub-blank-square.png - envoi d'image avec NoelShack" title="1529914845-epub-blank-square.png"/></a>

And in pdf the nnbsp is simply omitted :
<a href="https://www.noelshack.com/2018-26-1-1529914846-pdf-nnbsp-omission.png"><img src="https://image.noelshack.com/minis/2018/26/1/1529914846-pdf-nnbsp-omission.png" border="0" alt="1529914846-pdf-nnbsp-omission.png - envoi d'image avec NoelShack" title="1529914846-pdf-nnbsp-omission.png"/></a>

I think the other "non-breaking space" type and others text files should be test.

It's particularly problematic for French language which have strict typographic rules concerning the use of non-breaking spaces. Thanks by advance to solve it.

(Here the link to the ePub use for the test :
[L’Anarchie passive et le comte Léon Tolstoï](https://tools.wmflabs.org/wsexport/tool/book.php?lang=fr&format=epub&page=L%E2%80%99Anarchie_passive_et_le_comte_L%C3%A9on_Tolsto%C3%AF) from Wikisource project
An there the pdf use for the test :
[L’Anarchie_passive_et_le_comte_Léon_Tolstoï_02.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/2132307/L.Anarchie_passive_et_le_comte_Leon_Tolstoi_02.pdf) )

**Comment by GitHubRulesOK** [comment] 2018-06-25 17:29
@ViveLaRosierre  
I do not have the same problem, see my ebook screen shot, the reason is that I am using use the default epub Georgia font where nbsp is defined whereas the font you are currently using has a glyph block for the epub character, you may need to change fonts to get the correct blank space.

EbookUI [
	FontName = Georgia
	FontSize = 11
	TextColor = #5f4b32
	BackgroundColor = #fbf0d9
	UseFixedPageUI = true
]

![untitled](https://user-images.githubusercontent.com/12754913/41865577-712ab93e-78a5-11e8-8510-5b407e7f2cfd.png)


In the pdf I can not tell yet if the space has been ommited or not during conversion
thus these may be two different however font related problems

**Comment by GitHubRulesOK** [comment] 2018-06-28 21:12
Since the file had been converted with Calibre I tried that to reverse the process, however calibre did not see any nbsp in its own PDF, it only gave back from the file "douloureuse pour la philosophie; les élèves de Kant".
Without wasting further time I have to assume the nbspaces were lost at the time of conversion to PDF thus they are NOT seen in Calibre or Acrobat and with the best will in the world SumatraPDF cannot be expected to insert something thats not there (even if it does sometimes :-)
@kjk I suggest these two inter-related issues are closed as expected behaviours

**Comment by ViveLaRosierre** [comment] 2018-07-14 12:05
Thanks for the answer. So if I understand your point the problem is not from SumatraPDF but either from the hoster site (which convert it somehow) ? or either my personal computer fonts problem ?
I'm asking to know if I have to warn them or not about this point. Sorry to had wrongly report to your project anyway. No problem to close this issue, if SumatraPDF can't solve that.

**Comment by fbprod** [comment] 2019-05-02 16:52
Additionnal informations

In this case, narrow non-break space doesn't appear correctly because the glyph (U+202F)
doesn't exist in Georgia font.

Two solutions :

- in Advanced settings, change UseFixedPageUI = false for true of EbookUI section.
However, this solution could break the "grey tone", the "typographic color" or doesn't work.

```
EbookUI [
FontName = Georgia
FontSize = 11
TextColor = #5f4b32
BackgroundColor = #fbf0d9
UseFixedPageUI = true
]
```

- better solution, change the FontName of EbookUI section for a font with special spaces glyphs like DejaVu Serif, or Liberation Serif for example.

```
EbookUI [
FontName = DejaVu Serif
FontSize = 11
TextColor = #5f4b32
BackgroundColor = #fbf0d9
UseFixedPageUI = false
]
```

**Comment by GitHubRulesOK** [comment] 2021-08-16 00:03
@kjk 
Historic issue ? as MuPDF shows spaces however part of this issue is justification may also have a bearing, generally for nbsp problems it is down to authorship/conversion/OCR.

![image](https://user-images.githubusercontent.com/12754913/129496636-39a9fbbf-1967-4308-a759-34933ae40bb2.png)

**Comment by kjk** [comment] 2021-08-16 00:08
Closing as fixed in pre-release https://www.sumatrapdfreader.org/prerelease

**Closed by kjk** 2021-08-16 00:08 UTC
Labels: ebook
