### ISSUE TITLE
Side by Side document viewing

### ISSUE THREAD

**Issue by ConradBerl** [sumatrapdfreader/sumatrapdf#413] opened 2016-01-17 20:39 UTC
I know the workarounds, but is it possible to drag-out a tab and have it launch a new instance/window of the file? The end goal would be to have two open instances, but still have the ability to maintain tabs on those instances, similar to Chrome or Firefox. 

This would especially convenient for viewing multiple files on multi-monitor displays.

**Comment by mchels** [comment] 2016-01-30 20:05
+1

**Comment by yaqwsx** [comment] 2016-04-13 14:52
+1
I really miss this featue (I would appreciate behavior like Firefox and other browsers - multiple windows and drag&drop of the tabs)

**Comment by SumatraPeter** [comment] 2016-10-06 17:34
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/18

**Closed** 2016-10-06 18:19 UTC
