### ISSUE TITLE
Document fonts list in 64 bits Sumatra PDF

### ISSUE THREAD

**Issue by Alfonsib** [sumatrapdfreader/sumatrapdf#489] opened 2016-04-05 20:53 UTC
It would be nice to display the document fonts list as in Zeniko's version/builds for the 64 bits version.
Thanks in advance,

Bernard

**Comment by SumatraPeter** [comment] 2019-08-24 23:20
@kjk: Duplicate of #23

**Comment by kjk** [comment] 2019-08-24 23:22
Closing as duplicate

**Closed by kjk** 2019-08-24 23:22 UTC
